import type { Metadata } from 'next'
import {
  ArrowRight,
  Car,
  Clock3,
  Gauge,
  Mail,
  MapPin,
  Phone,
  ShieldCheck,
  Wrench,
} from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro autoservis | SpustWeb.cz',
  description:
    'Ukázka webu pro autoservis: servisní úkony, diagnostika, pneuservis, orientační ceny, průběh zakázky, tým, lokalita a kontakt.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/autoservis/' },
  robots: { index: true, follow: true },
}

const services = [
  ['01', 'Pravidelný servis', 'Výměna oleje a filtrů, servisní prohlídky a běžná údržba podle nájezdu a stáří vozu.', 'olej · filtry · prohlídka'],
  ['02', 'Diagnostika a závady', 'Kontrolky, hluk, vibrace, ztráta výkonu a další závady. Zjistíme příčinu a navrhneme opravu.', 'diagnostika · hledání závady'],
  ['03', 'Brzdy a podvozek', 'Brzdy, tlumiče, čepy, ložiska a geometrie. Kontrola, výměna opotřebených dílů a seřízení.', 'brzdy · podvozek · geometrie'],
  ['04', 'Klimatizace', 'Kontrola funkce, servis, doplnění chladiva a dezinfekce klimatizace.', 'servis A/C · dezinfekce'],
  ['05', 'Pneuservis', 'Přezutí, vyvážení, kontrola stavu pneumatik a opravy běžných defektů.', 'přezutí · vyvážení · defekty'],
]

const prices = [
  ['Základní diagnostika', 'od 690 Kč'],
  ['Výměna motorového oleje', 'od 590 Kč + materiál'],
  ['Servis klimatizace', 'od 990 Kč'],
  ['Přezutí 16–18″', 'od 1 290 Kč'],
  ['Kontrola vozu před koupí', 'od 1 490 Kč'],
]

const rules = [
  ['Změnu ceny řešíme předem.', 'Pokud se během práce ukáže další závada nebo větší rozsah opravy, před pokračováním zavoláme.'],
  ['U nejasné závady začínáme diagnostikou.', 'Po zjištění příčiny sdělíme navrženou opravu, potřebné díly a cenu.'],
  ['Vyměněné díly můžeme nechat k nahlédnutí.', 'Na požádání ukážeme, co se na autě měnilo.'],
  ['Při převzetí dostanete přehled práce.', 'Uvedeme provedené úkony a použitý materiál.'],
]

const steps = [
  ['01', 'Domluva termínu', 'Ozvete se telefonicky, e-mailem nebo formulářem a domluvíme vhodný den.'],
  ['02', 'Příjem vozu', 'Při převzetí projdeme, co má servis řešit.'],
  ['03', 'Kontrola nebo diagnostika', 'Podle zakázky ověříme stav vozu a rozsah práce.'],
  ['04', 'Potvrzení opravy', 'U větších nebo nejasných oprav potvrdíme cenu předem.'],
  ['05', 'Převzetí auta', 'Předáme auto a přehled provedených prací.'],
]

const reviews = [
  ['„Domluvený termín seděl. Před výměnou brzd mi zavolali s cenou a auto bylo odpoledne hotové.“', 'Martin K.'],
  ['„Přijela jsem s kontrolkou motoru. Po diagnostice mi zavolali, co našli a kolik bude oprava stát.“', 'Petra S.'],
  ['„Na přezutí jsem byl domluvený na osmou a vzali mě hned. Za půl hodiny hotovo.“', 'Jakub M.'],
]

const brands = ['Škoda', 'Volkswagen', 'Seat', 'Ford', 'Toyota', 'Hyundai', 'Kia', 'Peugeot', 'Renault', 'BMW', 'Mercedes']

export default function AutoserviceShowcase() {
  return (
    <div className="asg3" id="top">
      <style>{`
        body:has(.asg3) > .verno-nav-shell,body:has(.asg3) > .footer{display:none!important}
        body:has(.asg3) main{padding:0!important;margin:0!important}
        body:has(.asg3){background:#f1f1ec!important}
        .asg3{--ink:#0e1110;--paper:#f1f1ec;--white:#fff;--muted:#666d69;--line:#d3d5cf;--blue:#2f55ff;--acid:#d9ff64;--dark:#101412;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--paper);font-size:16px}
        .asg3 *{box-sizing:border-box}.asg3 a{color:inherit;text-decoration:none}.asg3 svg{stroke-width:1.8}.asg3Wrap{width:min(1240px,calc(100% - 48px));margin:0 auto}.asg3Kicker{font-size:10px;font-weight:900;letter-spacing:.15em;text-transform:uppercase;color:var(--blue)}
        .asg3Demo{min-height:25px;padding:5px 14px;background:#090b0a;color:#d5d8d5;display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.asg3Demo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .asg3NavShell{position:sticky;top:0;z-index:100;background:rgba(14,17,16,.95);backdrop-filter:blur(14px);border-bottom:1px solid rgba(255,255,255,.12)}.asg3Nav{height:68px;display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:34px;color:#fff}.asg3Brand{display:flex;align-items:center;gap:10px;font-size:18px;font-weight:900;letter-spacing:-.045em}.asg3Mark{width:30px;height:30px;border:2px solid #fff;border-radius:50%;display:grid;place-items:center}.asg3Brand small{display:block;font-size:8px;letter-spacing:.16em;color:#aeb4b0;margin-top:2px}.asg3Links{display:flex;gap:26px;font-size:11px;font-weight:800}.asg3Links a{opacity:.78}.asg3NavRight{display:flex;align-items:center;gap:12px}.asg3Phone{font-size:11px;font-weight:900}.asg3NavCta{min-height:38px;padding:0 15px;background:var(--acid);color:var(--ink)!important;display:inline-flex;align-items:center;gap:7px;font-size:10px;font-weight:900}
        .asg3Hero{position:relative;min-height:690px;background:#131715;overflow:hidden;color:#fff}.asg3Hero img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 52%;filter:saturate(.72) contrast(1.07) brightness(.72)}.asg3Hero:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(8,11,10,.96) 0%,rgba(8,11,10,.88) 34%,rgba(8,11,10,.30) 68%,rgba(8,11,10,.12) 100%),linear-gradient(180deg,rgba(8,11,10,.18),rgba(8,11,10,.40))}.asg3HeroContent{position:relative;z-index:2;min-height:690px;display:grid;grid-template-columns:minmax(0,720px) 1fr;align-items:end;padding-bottom:58px}.asg3HeroCopy{padding-top:100px}.asg3Hero .asg3Kicker{color:var(--acid);margin-bottom:18px}.asg3Hero h1{font-size:clamp(58px,7vw,96px);line-height:.86;letter-spacing:-.065em;font-weight:500;max-width:760px;margin:0 0 24px}.asg3Lead{font-size:15px;line-height:1.6;color:#d6dbd7;max-width:580px;margin:0 0 24px}.asg3HeroActions{display:flex;gap:9px;flex-wrap:wrap}.asg3Btn{min-height:44px;padding:0 18px;display:inline-flex;align-items:center;justify-content:center;gap:8px;font-size:11px;font-weight:900;border:1px solid rgba(255,255,255,.5)}.asg3BtnPrimary{background:var(--acid);border-color:var(--acid);color:var(--ink)!important}.asg3BtnGhost{color:#fff!important}.asg3HeroSide{justify-self:end;align-self:end;width:270px;border-left:1px solid rgba(255,255,255,.28);padding-left:22px}.asg3HeroSide strong{display:block;font-size:12px;margin-bottom:12px}.asg3HeroSide div{display:grid;gap:8px;font-size:10px;color:#c6ccc8}.asg3HeroSide span,.asg3HeroSide a{display:flex;align-items:center;gap:7px}
        .asg3ServiceIntro{padding:66px 0 22px;background:#fff}.asg3ServiceIntroGrid{display:grid;grid-template-columns:.85fr 1.15fr;gap:80px;align-items:end}.asg3ServiceIntro h2{font-size:clamp(42px,5.3vw,70px);line-height:.9;letter-spacing:-.055em;font-weight:500;margin:0}.asg3ServiceIntro p{font-size:13px;line-height:1.65;color:var(--muted);max-width:520px;margin:0}
        .asg3Services{background:#fff;border-top:1px solid var(--line)}.asg3Service{display:grid;grid-template-columns:70px 1.15fr 1fr 170px 42px;align-items:center;gap:28px;min-height:112px;border-bottom:1px solid var(--line);padding:0 2px}.asg3ServiceNo{font-size:11px;color:var(--blue);font-weight:900}.asg3Service h3{font-size:28px;line-height:1;letter-spacing:-.035em;font-weight:500;margin:0}.asg3Service p{font-size:11.5px;line-height:1.55;color:var(--muted);margin:0}.asg3ServiceMeta{font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:#747b77}.asg3ServiceArrow{justify-self:end;width:42px;height:42px;border:1px solid #bec2bc;border-radius:50%;display:grid;place-items:center}
        .asg3PriceScene{display:grid;grid-template-columns:1.02fr .98fr;min-height:600px}.asg3PricePhoto{position:relative;overflow:hidden}.asg3PricePhoto img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.72) contrast(1.04)}.asg3PricePhoto:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 60%,rgba(0,0,0,.52))}.asg3PriceCaption{position:absolute;left:30px;bottom:26px;z-index:2;color:#fff}.asg3PriceCaption strong{display:block;font-size:18px}.asg3PriceCaption span{font-size:10px;color:#d8ddda}.asg3PricePanel{padding:64px clamp(34px,5vw,74px);display:flex;flex-direction:column;justify-content:center}.asg3PricePanel h2{font-size:clamp(40px,4.7vw,62px);line-height:.92;letter-spacing:-.052em;font-weight:500;margin:12px 0 24px}.asg3PriceList{border-top:1px solid #bfc3bc}.asg3PriceRow{display:grid;grid-template-columns:1fr auto;gap:20px;padding:15px 0;border-bottom:1px solid #c9ccc6;font-size:12px}.asg3PriceNote{margin-top:22px;background:var(--blue);color:#fff;padding:20px 22px;display:grid;grid-template-columns:34px 1fr;gap:14px}.asg3PriceNote strong{font-size:13px}.asg3PriceNote p{font-size:10.5px;line-height:1.5;color:#e5e8ff;margin:4px 0 0}.asg3Fine{font-size:8.5px;color:#7a817c;margin-top:10px}
        .asg3Workshop{position:relative;min-height:680px;background:#222;color:#fff;overflow:hidden}.asg3Workshop img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 55%;filter:saturate(.68) contrast(1.08) brightness(.64)}.asg3Workshop:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(8,10,9,.08),rgba(8,10,9,.72) 78%)}.asg3WorkshopInner{position:relative;z-index:2;min-height:680px;display:flex;flex-direction:column;justify-content:space-between;padding-top:56px;padding-bottom:44px}.asg3WorkshopTop{display:flex;justify-content:space-between;gap:40px}.asg3Workshop h2{font-size:clamp(52px,6.2vw,82px);line-height:.88;letter-spacing:-.06em;font-weight:500;margin:14px 0 0;max-width:650px}.asg3WorkshopLead{max-width:360px;font-size:12px;line-height:1.6;color:#d2d8d4;margin-top:34px}.asg3WorkshopStats{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid rgba(255,255,255,.35)}.asg3WorkshopStat{padding:18px 22px 0 0;border-right:1px solid rgba(255,255,255,.24)}.asg3WorkshopStat+.asg3WorkshopStat{padding-left:22px}.asg3WorkshopStat:last-child{border-right:0}.asg3WorkshopStat strong{display:block;font-size:13px}.asg3WorkshopStat span{display:block;font-size:9.5px;color:#bfc6c1;margin-top:4px}
        .asg3Manifesto{background:var(--acid);padding:46px 0}.asg3ManifestoHead{display:grid;grid-template-columns:220px 1fr;gap:30px;align-items:start;margin-bottom:28px}.asg3ManifestoHead h2{font-size:clamp(34px,4vw,52px);line-height:.95;letter-spacing:-.045em;font-weight:500;margin:0}.asg3Rules{display:grid;grid-template-columns:repeat(2,1fr);border-top:1px solid rgba(14,17,16,.25)}.asg3Rule{padding:22px 34px 22px 0;border-bottom:1px solid rgba(14,17,16,.25)}.asg3Rule:nth-child(even){padding-left:34px;border-left:1px solid rgba(14,17,16,.25)}.asg3Rule strong{display:block;font-size:17px;line-height:1.25;margin-bottom:6px}.asg3Rule p{font-size:10.5px;line-height:1.55;color:#3d453f;margin:0;max-width:450px}
        .asg3Brands{background:#fff;padding:24px 0;border-bottom:1px solid var(--line)}.asg3BrandsInner{display:flex;align-items:center;gap:28px;overflow:hidden}.asg3Brands strong{font-size:9px;text-transform:uppercase;letter-spacing:.13em;white-space:nowrap;color:#676e69}.asg3BrandList{display:flex;gap:28px;flex-wrap:wrap;font-size:12px;font-weight:900}
        .asg3Journey{background:#fff;padding:70px 0 74px}.asg3JourneyHead{display:grid;grid-template-columns:1fr .9fr;gap:70px;align-items:end;margin-bottom:40px}.asg3JourneyHead h2{font-size:clamp(44px,5vw,68px);line-height:.9;letter-spacing:-.055em;font-weight:500;margin:12px 0 0}.asg3JourneyHead p{font-size:12px;line-height:1.6;color:var(--muted);max-width:470px;margin:0}.asg3Timeline{position:relative;display:grid;grid-template-columns:repeat(5,1fr);gap:0;padding-top:30px}.asg3Timeline:before{content:'';position:absolute;left:8%;right:8%;top:41px;height:1px;background:#bdc1bb}.asg3Step{position:relative;padding:34px 22px 0 0}.asg3StepDot{position:absolute;top:4px;left:0;width:16px;height:16px;border-radius:50%;background:#fff;border:4px solid #aeb3ad;z-index:2}.asg3Step:nth-child(4) .asg3StepDot{border-color:var(--blue);background:var(--acid);box-shadow:0 0 0 8px rgba(47,85,255,.10)}.asg3StepNo{font-size:10px;color:#929993;font-weight:900}.asg3Step h3{font-size:15px;margin:10px 0 7px}.asg3Step p{font-size:10.5px;line-height:1.5;color:var(--muted);margin:0;max-width:180px}
        .asg3Reviews{background:var(--dark);color:#fff;padding:68px 0}.asg3ReviewsGrid{display:grid;grid-template-columns:.75fr 1.25fr;gap:70px}.asg3Rating strong{display:block;font-size:108px;line-height:.78;letter-spacing:-.07em;font-weight:500}.asg3Rating span{font-size:10px;color:#aeb6b0}.asg3ReviewsMain h2{font-size:46px;line-height:.95;letter-spacing:-.048em;font-weight:500;margin:0 0 26px}.asg3ReviewFeature{font-size:24px;line-height:1.35;letter-spacing:-.025em;margin:0 0 24px;max-width:720px}.asg3ReviewFeature small{display:block;font-size:9px;letter-spacing:.08em;color:#98a29b;margin-top:16px}.asg3ReviewMini{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid #343a36}.asg3ReviewMini article{padding:20px 24px 0 0}.asg3ReviewMini article+article{border-left:1px solid #343a36;padding-left:24px}.asg3ReviewMini p{font-size:12px;line-height:1.55;color:#d4d9d6;margin:0}.asg3ReviewMini small{display:block;font-size:8.5px;color:#8f9992;margin-top:12px}.asg3DemoLabel{display:inline-block;margin-top:24px;border:1px solid #3a413d;padding:6px 8px;font-size:8px;color:#7f8982}
        .asg3Team{position:relative;min-height:560px;background:#d9dbd5;overflow:hidden}.asg3Team img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 48%;filter:saturate(.58) contrast(1.08)}.asg3Team:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(241,241,236,.98) 0%,rgba(241,241,236,.94) 40%,rgba(241,241,236,.25) 68%,transparent 100%)}.asg3TeamInner{position:relative;z-index:2;min-height:560px;display:flex;align-items:center}.asg3TeamCard{max-width:610px;padding:52px 0}.asg3TeamCard h2{font-size:clamp(46px,5.2vw,70px);line-height:.9;letter-spacing:-.055em;font-weight:500;margin:14px 0 18px}.asg3TeamCard>p{font-size:13px;line-height:1.65;color:#4b534f;max-width:520px;margin:0}.asg3People{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:28px}.asg3Person{border-top:1px solid #bfc3bd;padding-top:10px}.asg3Person strong{display:block;font-size:11px}.asg3Person span{font-size:9px;color:#747b76}
        .asg3Location{padding:68px 0;background:#e6e9e4}.asg3LocationGrid{display:grid;grid-template-columns:.72fr 1.28fr;gap:14px}.asg3LocCopy{background:#fff;padding:34px}.asg3LocCopy h2{font-size:38px;line-height:.95;letter-spacing:-.045em;font-weight:500;margin:12px 0 20px}.asg3LocRows{display:grid;gap:15px}.asg3LocRow{display:grid;grid-template-columns:24px 1fr;gap:9px;font-size:11px;line-height:1.45}.asg3LocRow strong{display:block}.asg3LocRow span{color:var(--muted)}.asg3Map{position:relative;min-height:360px;background:#d6dbd4;overflow:hidden}.asg3Map:before{content:'';position:absolute;inset:-15%;background:repeating-linear-gradient(24deg,transparent 0 42px,#c3c9c2 43px 45px),repeating-linear-gradient(118deg,transparent 0 68px,#c1c7c0 69px 72px)}.asg3Map:after{content:'';position:absolute;width:24px;height:24px;border:8px solid var(--blue);border-radius:50% 50% 50% 0;transform:rotate(-45deg);left:57%;top:45%;background:#fff}.asg3MapTag{position:absolute;left:22px;bottom:20px;z-index:2;background:var(--dark);color:#fff;padding:10px 13px;font-size:10px;font-weight:900}.asg3Road{position:absolute;left:-4%;right:-3%;top:52%;height:13px;background:#f2f2ed;transform:rotate(-8deg);box-shadow:0 0 0 1px #b7bdb6}.asg3Road2{position:absolute;top:-12%;bottom:-7%;left:44%;width:12px;background:#f2f2ed;transform:rotate(15deg);box-shadow:0 0 0 1px #b7bdb6}
        .asg3Contact{background:var(--blue);color:#fff;padding:74px 0}.asg3ContactGrid{display:grid;grid-template-columns:.82fr 1.18fr;gap:76px;align-items:start}.asg3ContactCopy h2{font-size:clamp(50px,6vw,80px);line-height:.86;letter-spacing:-.06em;font-weight:500;margin:14px 0 20px}.asg3ContactCopy p{font-size:13px;line-height:1.6;color:#e3e7ff;max-width:460px}.asg3ContactAlt{display:grid;gap:10px;margin-top:24px;font-size:11px}.asg3ContactAlt a{display:flex;gap:9px;align-items:center}.asg3ContactAlt strong{font-size:14px}.asg3Form{background:#fff;color:var(--ink);padding:18px}.asg3Fields{display:grid;grid-template-columns:1fr 1fr}.asg3Field{padding:13px 15px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.asg3Field:nth-child(even){border-right:0}.asg3FieldWide{grid-column:1/-1;border-right:0}.asg3Field label{display:block;font-size:8px;text-transform:uppercase;letter-spacing:.09em;color:#7c837e;margin-bottom:8px}.asg3Field input,.asg3Field select,.asg3Field textarea{width:100%;border:0;background:transparent;font:inherit;font-size:12px;outline:none}.asg3Field textarea{min-height:90px;resize:vertical}.asg3Form button{width:100%;margin-top:14px;min-height:48px;background:var(--dark);color:#fff;border:0;font-size:11px;font-weight:900}.asg3FormNote{padding-top:10px;font-size:8.5px;color:#7c837e}
        .asg3Footer{background:#090b0a;color:#b9c0bb;border-top:3px solid var(--acid)}.asg3FooterInner{min-height:122px;padding:26px 0;display:grid;grid-template-columns:1fr auto;gap:30px;align-items:center;font-size:10px}.asg3Footer strong{font-size:14px;color:#fff}.asg3FooterRight{display:flex;align-items:center;gap:16px}.asg3Footer a{text-decoration:underline;text-underline-offset:3px}.asg3FooterCta{border:1px solid #414743;padding:10px 12px;color:#fff!important;text-decoration:none!important;font-weight:900}
        @media(max-width:980px){.asg3Wrap{width:min(100% - 34px,1240px)}.asg3Nav{grid-template-columns:1fr auto}.asg3Links{display:none}.asg3HeroContent{grid-template-columns:1fr}.asg3HeroSide{justify-self:start;margin-top:34px}.asg3Service{grid-template-columns:54px 1fr 1fr 42px}.asg3ServiceMeta{display:none}.asg3PriceScene{grid-template-columns:1fr 1fr}.asg3ReviewsGrid{gap:38px}.asg3ContactGrid{gap:38px}}
        @media(max-width:720px){.asg3Wrap{width:min(100% - 26px,1240px)}.asg3Demo{font-size:8px;text-align:center}.asg3Nav{height:62px}.asg3Phone{display:none}.asg3Hero,.asg3HeroContent{min-height:650px}.asg3HeroContent{padding-bottom:36px}.asg3HeroCopy{padding-top:90px}.asg3Hero h1{font-size:clamp(50px,15vw,72px)}.asg3HeroSide{display:none}.asg3ServiceIntroGrid{grid-template-columns:1fr;gap:18px}.asg3Service{grid-template-columns:42px 1fr 38px;gap:12px;padding:18px 0;min-height:0}.asg3Service p{grid-column:2/-1}.asg3ServiceMeta{display:none}.asg3ServiceArrow{grid-column:3;grid-row:1;width:34px;height:34px}.asg3PriceScene{grid-template-columns:1fr}.asg3PricePhoto{min-height:390px}.asg3WorkshopStats{grid-template-columns:1fr 1fr}.asg3Rules{grid-template-columns:1fr}.asg3Rule,.asg3Rule:nth-child(even){padding:18px 0;border-left:0}.asg3JourneyHead{grid-template-columns:1fr;gap:18px}.asg3Timeline{display:block;padding-top:0}.asg3Timeline:before{left:8px;right:auto;top:0;bottom:0;width:1px;height:auto}.asg3Step{padding:0 0 28px 42px}.asg3ReviewsGrid{grid-template-columns:1fr}.asg3ReviewMini{grid-template-columns:1fr}.asg3People{grid-template-columns:1fr}.asg3LocationGrid{grid-template-columns:1fr}.asg3ContactGrid{grid-template-columns:1fr}.asg3Fields{grid-template-columns:1fr}.asg3Field,.asg3Field:nth-child(even){border-right:0}.asg3FooterInner{grid-template-columns:1fr}.asg3FooterRight{flex-wrap:wrap}}
      `}</style>

      <div className="asg3Demo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <div className="asg3NavShell"><div className="asg3Wrap"><nav className="asg3Nav"><a className="asg3Brand" href="#top"><span className="asg3Mark"><Wrench size={15}/></span><span>GARÁŽ 17<small>AUTOSERVIS · BRNO</small></span></a><div className="asg3Links"><a href="#servis">Servis</a><a href="#cenik">Ceník</a><a href="#prubeh">Jak to funguje</a><a href="#tym">O nás</a><a href="#kontakt">Kontakt</a></div><div className="asg3NavRight"><a className="asg3Phone" href="tel:+420705911941">+420 705 911 941</a><a className="asg3NavCta" href="#poptavka">Poptat servis <ArrowRight size={12}/></a></div></nav></div></div>

      <header className="asg3Hero"><img src="https://images.pexels.com/photos/6870298/pexels-photo-6870298.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Mechanik kontroluje motor běžného osobního auta v servisní dílně"/><div className="asg3Wrap asg3HeroContent"><div className="asg3HeroCopy"><div className="asg3Kicker">AUTOSERVIS · BRNO SLATINA</div><h1>Servis a opravy osobních aut.</h1><p className="asg3Lead">Pravidelný servis, diagnostika, brzdy, podvozek, klimatizace a pneuservis pro většinu běžných značek. U větších oprav předem potvrdíme rozsah práce a cenu.</p><div className="asg3HeroActions"><a className="asg3Btn asg3BtnPrimary" href="#poptavka">Poptat servis</a><a className="asg3Btn asg3BtnGhost" href="#cenik">Služby a ceny <ArrowRight size={14}/></a></div></div><div className="asg3HeroSide"><strong>Kontakt</strong><div><a href="tel:+420705911941"><Phone size={13}/> +420 705 911 941</a><a href="mailto:kontakt@spustweb.cz"><Mail size={13}/> kontakt@spustweb.cz</a><span><Clock3 size={13}/> Po–Pá 7:30–17:00</span><span><MapPin size={13}/> Řípská 17, Brno</span></div></div></div></header>

      <section className="asg3ServiceIntro" id="servis"><div className="asg3Wrap asg3ServiceIntroGrid"><div><div className="asg3Kicker">SERVIS A OPRAVY</div><h2>S čím k nám můžete přijet.</h2></div><p>Od pravidelné údržby po hledání závady. Rozsah práce závisí na konkrétním vozu a jeho stavu.</p></div></section>
      <section className="asg3Services"><div className="asg3Wrap">{services.map(([no,title,text,meta])=><a className="asg3Service" href="#poptavka" key={no}><span className="asg3ServiceNo">{no}</span><h3>{title}</h3><p>{text}</p><span className="asg3ServiceMeta">{meta}</span><span className="asg3ServiceArrow"><ArrowRight size={15}/></span></a>)}</div></section>

      <section className="asg3PriceScene" id="cenik"><div className="asg3PricePhoto"><img src="https://images.pexels.com/photos/8470688/pexels-photo-8470688.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Mechanik při opravě motoru běžného osobního auta"/><div className="asg3PriceCaption"><strong>Rozsah práce potvrzujeme před opravou.</strong><span>U nejasné závady začínáme diagnostikou.</span></div></div><div className="asg3PricePanel"><div className="asg3Kicker">ORIENTAČNÍ CENY</div><h2>Běžné servisní úkony.</h2><div className="asg3PriceList">{prices.map(([service,price])=><div className="asg3PriceRow" key={service}><span>{service}</span><strong>{price}</strong></div>)}</div><div className="asg3PriceNote"><Gauge size={24}/><div><strong>U závady nejdřív určíme rozsah opravy.</strong><p>Po zjištění závady sdělíme cenu a další postup.</p></div></div><div className="asg3Fine">Ukázkové ceny fiktivního autoservisu. Nejde o skutečnou nabídku služby.</div></div></section>

      <section className="asg3Workshop"><img src="https://images.pexels.com/photos/8985667/pexels-photo-8985667.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Běžné osobní auto na zvedáku v nezávislé servisní dílně"/><div className="asg3Wrap asg3WorkshopInner"><div className="asg3WorkshopTop"><div><div className="asg3Kicker" style={{color:'#d9ff64'}}>DÍLNA</div><h2>Vybavení pro běžný servis i opravy.</h2></div><p className="asg3WorkshopLead">Čtyři servisní stání, diagnostika, zvedáky a pneuservis. Termín návštěvy se domlouvá předem.</p></div><div className="asg3WorkshopStats"><div className="asg3WorkshopStat"><strong>4 servisní stání</strong><span>běžný servis a opravy</span></div><div className="asg3WorkshopStat"><strong>Diagnostika vozů</strong><span>evropské a asijské značky</span></div><div className="asg3WorkshopStat"><strong>Pneuservis</strong><span>přezutí, vyvážení, defekty</span></div><div className="asg3WorkshopStat"><strong>Náhradní vůz</strong><span>u delších oprav po dohodě</span></div></div></div></section>

      <section className="asg3Manifesto"><div className="asg3Wrap"><div className="asg3ManifestoHead"><div className="asg3Kicker" style={{color:'#0e1110'}}>JAK PRACUJEME</div><h2>Co platí při každé zakázce.</h2></div><div className="asg3Rules">{rules.map(([title,text])=><article className="asg3Rule" key={title}><strong>{title}</strong><p>{text}</p></article>)}</div></div></section>
      <div className="asg3Brands"><div className="asg3Wrap asg3BrandsInner"><strong>Nejčastěji servisujeme</strong><div className="asg3BrandList">{brands.map(b=><span key={b}>{b}</span>)}</div></div></div>
      <section className="asg3Journey" id="prubeh"><div className="asg3Wrap"><div className="asg3JourneyHead"><div><div className="asg3Kicker">PRŮBĚH ZAKÁZKY</div><h2>Od domluvy po převzetí auta.</h2></div><p>U diagnostiky a větších oprav potvrzujeme rozsah práce předem.</p></div><div className="asg3Timeline">{steps.map(([no,title,text])=><article className="asg3Step" key={no}><span className="asg3StepDot"/><span className="asg3StepNo">{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="asg3Reviews"><div className="asg3Wrap asg3ReviewsGrid"><div className="asg3Rating"><strong>4,9</strong><span>/ 5 · 286 hodnocení</span></div><div className="asg3ReviewsMain"><div className="asg3Kicker" style={{color:'#d9ff64',marginBottom:12}}>HODNOCENÍ ZÁKAZNÍKŮ</div><h2>Zkušenosti se servisem.</h2><p className="asg3ReviewFeature">{reviews[0][0]}<small>{reviews[0][1]} · GOOGLE RECENZE / DEMO</small></p><div className="asg3ReviewMini">{reviews.slice(1).map(([quote,name])=><article key={name}><p>{quote}</p><small>{name} · GOOGLE RECENZE / DEMO</small></article>)}</div><span className="asg3DemoLabel">Ukázková data fiktivního autoservisu.</span></div></div></section>

      <section className="asg3Team" id="tym"><img src="https://images.pexels.com/photos/9112797/pexels-photo-9112797.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Mechanik při práci v menší české autodílně"/><div className="asg3Wrap asg3TeamInner"><div className="asg3TeamCard"><div className="asg3Kicker">TÝM AUTOSERVISU</div><h2>Lidé, kteří se starají o vaše auto.</h2><p>Servis vede David Horák. Marek se věnuje diagnostice a podvozku, Tomáš běžnému servisu a pneuservisu.</p><div className="asg3People"><div className="asg3Person"><strong>David Horák</strong><span>vedoucí servisu · 16 let praxe</span></div><div className="asg3Person"><strong>Marek Dvořák</strong><span>diagnostika · podvozek</span></div><div className="asg3Person"><strong>Tomáš Jelínek</strong><span>servis · pneuservis</span></div></div></div></div></section>

      <section className="asg3Location" id="kontakt"><div className="asg3Wrap asg3LocationGrid"><div className="asg3LocCopy"><div className="asg3Kicker">KDE NÁS NAJDETE</div><h2>Brno-Slatina.</h2><div className="asg3LocRows"><div className="asg3LocRow"><MapPin size={16}/><div><strong>Řípská 17, Brno</strong><span>vjezd z boční komunikace, parkování před dílnou</span></div></div><div className="asg3LocRow"><Clock3 size={16}/><div><strong>Po–Pá 7:30–17:00</strong><span>příjem vozů podle domluveného termínu</span></div></div><div className="asg3LocRow"><Phone size={16}/><div><strong>+420 705 911 941</strong><span>v pracovní době</span></div></div><div className="asg3LocRow"><Mail size={16}/><div><strong>kontakt@spustweb.cz</strong><span>e-mailový kontakt v ukázce směřuje na SpustWeb.cz</span></div></div></div></div><div className="asg3Map" aria-label="Ilustrační mapa příjezdu"><div className="asg3Road"/><div className="asg3Road2"/><span className="asg3MapTag">ŘÍPSKÁ 17 · VJEZD DO SERVISU</span></div></div></section>

      <section className="asg3Contact" id="poptavka"><div className="asg3Wrap asg3ContactGrid"><div className="asg3ContactCopy"><div className="asg3Kicker" style={{color:'#d9ff64'}}>KONTAKT</div><h2>Poptávka servisu.</h2><p>Napište, co potřebujete řešit, jaké máte auto a který den vám vyhovuje. Přidejte telefon i e-mail; servis následně potvrdí konkrétní termín.</p><div className="asg3ContactAlt"><a href="tel:+420705911941"><Phone size={16}/><strong>+420 705 911 941</strong></a><a href="mailto:kontakt@spustweb.cz"><Mail size={16}/><strong>kontakt@spustweb.cz</strong></a></div></div><form className="asg3Form"><div className="asg3Fields"><div className="asg3Field"><label htmlFor="asg3-name">Jméno</label><input id="asg3-name" type="text" placeholder="Vaše jméno"/></div><div className="asg3Field"><label htmlFor="asg3-phone">Telefon</label><input id="asg3-phone" type="tel" placeholder="Např. +420 777 123 456"/></div><div className="asg3Field"><label htmlFor="asg3-email">E-mail</label><input id="asg3-email" type="email" placeholder="vas@email.cz"/></div><div className="asg3Field"><label htmlFor="asg3-service">Služba</label><select id="asg3-service" defaultValue=""><option value="" disabled>Vyberte službu</option><option>Pravidelný servis</option><option>Diagnostika</option><option>Brzdy a podvozek</option><option>Klimatizace</option><option>Pneuservis</option></select></div><div className="asg3Field"><label htmlFor="asg3-day">Preferovaný den</label><input id="asg3-day" type="text" placeholder="Např. úterý nebo středa"/></div><div className="asg3Field"><label htmlFor="asg3-car">Vůz</label><input id="asg3-car" type="text" placeholder="Značka, model, rok"/></div><div className="asg3Field asg3FieldWide"><label htmlFor="asg3-message">Popis</label><textarea id="asg3-message" placeholder="Popis závady nebo požadované práce"/></div></div><button type="button">Odeslat poptávku</button><div className="asg3FormNote">Ukázkový formulář na této demonstrační stránce se neodesílá.</div></form></div></section>

      <footer className="asg3Footer"><div className="asg3Wrap asg3FooterInner"><div><strong>GARÁŽ 17 · AUTOSERVIS</strong><br/>Fiktivní firma vytvořená pouze jako ukázkový koncept.</div><div className="asg3FooterRight">Tento koncept vytvořil <a href="/">SpustWeb.cz</a><a className="asg3FooterCta" href="/#kontakt">Web pro moje podnikání</a></div></div></footer>
    </div>
  )
}