import type { Metadata } from 'next'
import {
  ArrowRight,
  CalendarDays,
  Car,
  Clock3,
  Gauge,
  MapPin,
  Phone,
  ShieldCheck,
  Wrench,
} from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro autoservis | SpustWeb.cz',
  description:
    'Ukázka webu pro autoservis: servisní úkony, diagnostika, pneuservis, orientační ceny, průběh zakázky, tým, lokalita a rezervace.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/autoservis/' },
  robots: { index: true, follow: true },
}

const services = [
  ['01', 'Pravidelný servis', 'Výměna oleje a filtrů, servisní prohlídky a běžná údržba podle nájezdu a stáří vozu.', 'olej · filtry · prohlídka'],
  ['02', 'Diagnostika a závady', 'Kontrolky, hluk, vibrace, ztráta výkonu a další závady. Zjistíme příčinu a navrhneme opravu.', 'diagnostika · hledání závady'],
  ['03', 'Brzdy a podvozek', 'Brzdy, tlumiče, čepy, ložiska a geometrie. Kontrola, výměna opotřebených dílů a seřízení.', 'brzdy · podvozek · geometrie'],
  ['04', 'Klimatizace', 'Kontrola funkce, servis, doplnění chladiva a dezinfekce klimatizace.', 'servis A/C · dezinfekce'],
  ['05', 'Pneuservis', 'Přezutí, vyvážení, kontrola stavu pneumatik a opravy běžných defektů.', 'přezutí · vyvážení · defekty'],
]

const prices = [
  ['Základní diagnostika', 'od 690 Kč'],
  ['Výměna motorového oleje', 'od 590 Kč + materiál'],
  ['Servis klimatizace', 'od 990 Kč'],
  ['Přezutí 16–18″', 'od 1 290 Kč'],
  ['Kontrola vozu před koupí', 'od 1 490 Kč'],
]

const rules = [
  ['Změnu ceny řešíme předem.', 'Pokud se během práce ukáže další závada nebo větší rozsah opravy, před pokračováním zavoláme.'],
  ['U nejasné závady začínáme diagnostikou.', 'Po zjištění příčiny sdělíme navrženou opravu, potřebné díly a cenu.'],
  ['Vyměněné díly můžeme nechat k nahlédnutí.', 'Na požádání ukážeme, co se na autě měnilo.'],
  ['Při převzetí dostanete přehled práce.', 'Uvedeme provedené úkony a použitý materiál.'],
]

const steps = [
  ['01', 'Objednání termínu', 'Vyberete službu a den, který vám vyhovuje.'],
  ['02', 'Příjem vozu', 'Při převzetí projdeme, co má servis řešit.'],
  ['03', 'Kontrola nebo diagnostika', 'Podle zakázky ověříme stav vozu a rozsah práce.'],
  ['04', 'Potvrzení opravy', 'U větších nebo nejasných oprav potvrdíme cenu předem.'],
  ['05', 'Převzetí auta', 'Předáme auto a přehled provedených prací.'],
]

const reviews = [
  ['„Objednaný termín seděl. Před výměnou brzd mi zavolali s cenou a auto bylo odpoledne hotové.“', 'Martin K.'],
  ['„Přijela jsem s kontrolkou motoru. Po diagnostice mi zavolali, co našli a kolik bude oprava stát.“', 'Petra S.'],
  ['„Na přezutí jsem byl objednaný na osmou a vzali mě hned. Za půl hodiny hotovo.“', 'Jakub M.'],
]

const brands = ['Škoda', 'Volkswagen', 'Seat', 'Ford', 'Toyota', 'Hyundai', 'Kia', 'Peugeot', 'Renault', 'BMW', 'Mercedes']

export default function AutoserviceShowcase() {
  return (
    <div className="asg2" id="top">
      <style>{`
        body:has(.asg2) > .verno-nav-shell,body:has(.asg2) > .footer{display:none!important}
        body:has(.asg2) main{padding:0!important;margin:0!important}
        body:has(.asg2){background:#f1f1ec!important}
        .asg2{--ink:#0e1110;--paper:#f1f1ec;--white:#fff;--muted:#666d69;--line:#d3d5cf;--blue:#2f55ff;--acid:#d9ff64;--dark:#101412;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--paper);font-size:16px}
        .asg2 *{box-sizing:border-box}.asg2 a{color:inherit;text-decoration:none}.asg2 svg{stroke-width:1.8}.asg2Wrap{width:min(1240px,calc(100% - 48px));margin:0 auto}.asg2Kicker{font-size:10px;font-weight:900;letter-spacing:.15em;text-transform:uppercase;color:var(--blue)}
        .asg2Demo{min-height:25px;padding:5px 14px;background:#090b0a;color:#d5d8d5;display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.asg2Demo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .asg2NavShell{position:sticky;top:0;z-index:100;background:rgba(14,17,16,.95);backdrop-filter:blur(14px);border-bottom:1px solid rgba(255,255,255,.12)}.asg2Nav{height:68px;display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:34px;color:#fff}.asg2Brand{display:flex;align-items:center;gap:10px;font-size:18px;font-weight:900;letter-spacing:-.045em}.asg2Mark{width:30px;height:30px;border:2px solid #fff;border-radius:50%;display:grid;place-items:center}.asg2Brand small{display:block;font-size:8px;letter-spacing:.16em;color:#aeb4b0;margin-top:2px}.asg2Links{display:flex;gap:26px;font-size:11px;font-weight:800}.asg2Links a{opacity:.78;transition:.2s}.asg2Links a:hover{opacity:1;color:var(--acid)}.asg2NavRight{display:flex;align-items:center;gap:12px}.asg2Phone{font-size:11px;font-weight:900}.asg2NavCta{min-height:38px;padding:0 15px;background:var(--acid);color:var(--ink)!important;display:inline-flex;align-items:center;gap:7px;font-size:10px;font-weight:900}

        .asg2Hero{position:relative;min-height:690px;background:#131715;overflow:hidden;color:#fff}.asg2Hero img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 52%;filter:saturate(.72) contrast(1.07) brightness(.72)}.asg2Hero:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(8,11,10,.96) 0%,rgba(8,11,10,.88) 34%,rgba(8,11,10,.30) 68%,rgba(8,11,10,.12) 100%),linear-gradient(180deg,rgba(8,11,10,.18),rgba(8,11,10,.40))}.asg2HeroContent{position:relative;z-index:2;min-height:690px;display:grid;grid-template-columns:minmax(0,720px) 1fr;align-items:end;padding-bottom:58px}.asg2HeroCopy{padding-top:100px}.asg2Hero .asg2Kicker{color:var(--acid);margin-bottom:18px}.asg2Hero h1{font-size:clamp(58px,7vw,96px);line-height:.86;letter-spacing:-.065em;font-weight:500;max-width:760px;margin:0 0 24px}.asg2Lead{font-size:15px;line-height:1.6;color:#d6dbd7;max-width:580px;margin:0 0 24px}.asg2HeroActions{display:flex;gap:9px;flex-wrap:wrap}.asg2Btn{min-height:44px;padding:0 18px;display:inline-flex;align-items:center;justify-content:center;gap:8px;font-size:11px;font-weight:900;border:1px solid rgba(255,255,255,.5)}.asg2BtnPrimary{background:var(--acid);border-color:var(--acid);color:var(--ink)!important}.asg2BtnGhost{color:#fff!important}.asg2HeroSide{justify-self:end;align-self:end;width:260px;border-left:1px solid rgba(255,255,255,.28);padding-left:22px;margin-bottom:4px}.asg2HeroSide strong{display:block;font-size:12px;margin-bottom:12px}.asg2HeroSide div{display:grid;gap:8px;font-size:10px;color:#c6ccc8}.asg2HeroSide span{display:flex;align-items:center;gap:7px}.asg2HeroIndex{position:absolute;right:28px;top:28px;z-index:2;font-size:10px;letter-spacing:.13em;color:#c8ceca}.asg2HeroBadge{position:absolute;right:34px;bottom:34px;z-index:2;width:82px;height:82px;border-radius:50%;background:var(--blue);display:grid;place-items:center;color:#fff;transform:rotate(-8deg)}

        .asg2ServiceIntro{padding:66px 0 22px;background:#fff}.asg2ServiceIntroGrid{display:grid;grid-template-columns:.85fr 1.15fr;gap:80px;align-items:end}.asg2ServiceIntro h2{font-size:clamp(42px,5.3vw,70px);line-height:.9;letter-spacing:-.055em;font-weight:500;margin:0}.asg2ServiceIntro p{font-size:13px;line-height:1.65;color:var(--muted);max-width:520px;margin:0 0 4px}
        .asg2Services{background:#fff;border-top:1px solid var(--line)}.asg2Service{display:grid;grid-template-columns:70px 1.15fr 1fr 170px;align-items:center;gap:28px;min-height:112px;border-bottom:1px solid var(--line);transition:background .2s,padding .2s;padding:0 2px}.asg2Service:hover{background:#f5f6f1;padding:0 14px}.asg2ServiceNo{font-size:11px;color:var(--blue);font-weight:900}.asg2Service h3{font-size:28px;line-height:1;letter-spacing:-.035em;font-weight:500;margin:0}.asg2Service p{font-size:11.5px;line-height:1.55;color:var(--muted);margin:0}.asg2ServiceMeta{font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:#747b77}.asg2ServiceArrow{justify-self:end;width:42px;height:42px;border:1px solid #bec2bc;border-radius:50%;display:grid;place-items:center}

        .asg2PriceScene{display:grid;grid-template-columns:1.02fr .98fr;min-height:600px;background:var(--paper)}.asg2PricePhoto{position:relative;overflow:hidden}.asg2PricePhoto img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.72) contrast(1.04)}.asg2PricePhoto:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 60%,rgba(0,0,0,.52))}.asg2PriceCaption{position:absolute;left:30px;bottom:26px;z-index:2;color:#fff}.asg2PriceCaption strong{display:block;font-size:18px}.asg2PriceCaption span{font-size:10px;color:#d8ddda}.asg2PricePanel{padding:64px clamp(34px,5vw,74px);display:flex;flex-direction:column;justify-content:center}.asg2PricePanel h2{font-size:clamp(40px,4.7vw,62px);line-height:.92;letter-spacing:-.052em;font-weight:500;margin:12px 0 24px}.asg2PriceList{border-top:1px solid #bfc3bc}.asg2PriceRow{display:grid;grid-template-columns:1fr auto;gap:20px;padding:15px 0;border-bottom:1px solid #c9ccc6;font-size:12px}.asg2PriceRow strong{font-size:12px}.asg2PriceNote{margin-top:22px;background:var(--blue);color:#fff;padding:20px 22px;display:grid;grid-template-columns:34px 1fr;gap:14px}.asg2PriceNote strong{font-size:13px}.asg2PriceNote p{font-size:10.5px;line-height:1.5;color:#e5e8ff;margin:4px 0 0}.asg2Fine{font-size:8.5px;color:#7a817c;margin-top:10px}

        .asg2Workshop{position:relative;min-height:680px;background:#222;color:#fff;overflow:hidden}.asg2Workshop img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 55%;filter:saturate(.68) contrast(1.08) brightness(.64)}.asg2Workshop:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(8,10,9,.08),rgba(8,10,9,.72) 78%)}.asg2WorkshopInner{position:relative;z-index:2;min-height:680px;display:flex;flex-direction:column;justify-content:space-between;padding-top:56px;padding-bottom:44px}.asg2WorkshopTop{display:flex;justify-content:space-between;gap:40px}.asg2Workshop h2{font-size:clamp(52px,6.2vw,82px);line-height:.88;letter-spacing:-.06em;font-weight:500;margin:14px 0 0;max-width:650px}.asg2WorkshopLead{max-width:360px;font-size:12px;line-height:1.6;color:#d2d8d4;margin-top:34px}.asg2WorkshopStats{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid rgba(255,255,255,.35)}.asg2WorkshopStat{padding:18px 22px 0 0;border-right:1px solid rgba(255,255,255,.24)}.asg2WorkshopStat+.asg2WorkshopStat{padding-left:22px}.asg2WorkshopStat:last-child{border-right:0}.asg2WorkshopStat strong{display:block;font-size:13px}.asg2WorkshopStat span{display:block;font-size:9.5px;color:#bfc6c1;margin-top:4px}

        .asg2Manifesto{background:var(--acid);padding:46px 0}.asg2ManifestoHead{display:grid;grid-template-columns:220px 1fr;gap:30px;align-items:start;margin-bottom:28px}.asg2ManifestoHead h2{font-size:clamp(34px,4vw,52px);line-height:.95;letter-spacing:-.045em;font-weight:500;margin:0}.asg2Rules{display:grid;grid-template-columns:repeat(2,1fr);border-top:1px solid rgba(14,17,16,.25)}.asg2Rule{padding:22px 34px 22px 0;border-bottom:1px solid rgba(14,17,16,.25)}.asg2Rule:nth-child(even){padding-left:34px;border-left:1px solid rgba(14,17,16,.25)}.asg2Rule strong{display:block;font-size:17px;line-height:1.25;margin-bottom:6px}.asg2Rule p{font-size:10.5px;line-height:1.55;color:#3d453f;margin:0;max-width:450px}

        .asg2Brands{background:#fff;padding:24px 0;border-bottom:1px solid var(--line)}.asg2BrandsInner{display:flex;align-items:center;gap:28px;overflow:hidden}.asg2Brands strong{font-size:9px;text-transform:uppercase;letter-spacing:.13em;white-space:nowrap;color:#676e69}.asg2BrandList{display:flex;gap:28px;flex-wrap:wrap;font-size:12px;font-weight:900}

        .asg2Journey{background:#fff;padding:70px 0 74px}.asg2JourneyHead{display:grid;grid-template-columns:1fr .9fr;gap:70px;align-items:end;margin-bottom:40px}.asg2JourneyHead h2{font-size:clamp(44px,5vw,68px);line-height:.9;letter-spacing:-.055em;font-weight:500;margin:12px 0 0}.asg2JourneyHead p{font-size:12px;line-height:1.6;color:var(--muted);max-width:470px;margin:0}.asg2Timeline{position:relative;display:grid;grid-template-columns:repeat(5,1fr);gap:0;padding-top:30px}.asg2Timeline:before{content:'';position:absolute;left:8%;right:8%;top:41px;height:1px;background:#bdc1bb}.asg2Step{position:relative;padding:34px 22px 0 0}.asg2StepDot{position:absolute;top:4px;left:0;width:16px;height:16px;border-radius:50%;background:#fff;border:4px solid #aeb3ad;z-index:2}.asg2Step:nth-child(4) .asg2StepDot{border-color:var(--blue);background:var(--acid);box-shadow:0 0 0 8px rgba(47,85,255,.10)}.asg2StepNo{font-size:10px;color:#929993;font-weight:900}.asg2Step h3{font-size:15px;margin:10px 0 7px}.asg2Step p{font-size:10.5px;line-height:1.5;color:var(--muted);margin:0;max-width:180px}.asg2Step:nth-child(4) h3{color:var(--blue)}

        .asg2Reviews{background:var(--dark);color:#fff;padding:68px 0}.asg2ReviewsGrid{display:grid;grid-template-columns:.75fr 1.25fr;gap:70px}.asg2Rating strong{display:block;font-size:108px;line-height:.78;letter-spacing:-.07em;font-weight:500}.asg2Rating span{font-size:10px;color:#aeb6b0}.asg2ReviewsMain h2{font-size:46px;line-height:.95;letter-spacing:-.048em;font-weight:500;margin:0 0 26px}.asg2ReviewFeature{font-size:24px;line-height:1.35;letter-spacing:-.025em;margin:0 0 24px;max-width:720px}.asg2ReviewFeature small{display:block;font-size:9px;letter-spacing:.08em;color:#98a29b;margin-top:16px}.asg2ReviewMini{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid #343a36}.asg2ReviewMini article{padding:20px 24px 0 0}.asg2ReviewMini article+article{border-left:1px solid #343a36;padding-left:24px}.asg2ReviewMini p{font-size:12px;line-height:1.55;color:#d4d9d6;margin:0}.asg2ReviewMini small{display:block;font-size:8.5px;color:#8f9992;margin-top:12px}.asg2DemoLabel{display:inline-block;margin-top:24px;border:1px solid #3a413d;padding:6px 8px;font-size:8px;color:#7f8982}

        .asg2Team{position:relative;min-height:560px;background:#d9dbd5;overflow:hidden}.asg2Team img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 48%;filter:saturate(.58) contrast(1.08)}.asg2Team:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(241,241,236,.98) 0%,rgba(241,241,236,.94) 40%,rgba(241,241,236,.25) 68%,transparent 100%)}.asg2TeamInner{position:relative;z-index:2;min-height:560px;display:flex;align-items:center}.asg2TeamCard{max-width:610px;padding:52px 0}.asg2TeamCard h2{font-size:clamp(46px,5.2vw,70px);line-height:.9;letter-spacing:-.055em;font-weight:500;margin:14px 0 18px}.asg2TeamCard>p{font-size:13px;line-height:1.65;color:#4b534f;max-width:520px;margin:0}.asg2People{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:28px}.asg2Person{border-top:1px solid #bfc3bd;padding-top:10px}.asg2Person strong{display:block;font-size:11px}.asg2Person span{font-size:9px;color:#747b76}

        .asg2Location{padding:68px 0;background:#e6e9e4}.asg2LocationGrid{display:grid;grid-template-columns:.72fr 1.28fr;gap:14px;align-items:stretch}.asg2LocCopy{background:#fff;padding:34px}.asg2LocCopy h2{font-size:38px;line-height:.95;letter-spacing:-.045em;font-weight:500;margin:12px 0 20px}.asg2LocRows{display:grid;gap:15px}.asg2LocRow{display:grid;grid-template-columns:24px 1fr;gap:9px;font-size:11px;line-height:1.45}.asg2LocRow strong{display:block}.asg2LocRow span{color:var(--muted)}.asg2Map{position:relative;min-height:360px;background:#d6dbd4;overflow:hidden}.asg2Map:before{content:'';position:absolute;inset:-15%;background:repeating-linear-gradient(24deg,transparent 0 42px,#c3c9c2 43px 45px),repeating-linear-gradient(118deg,transparent 0 68px,#c1c7c0 69px 72px)}.asg2Map:after{content:'';position:absolute;width:24px;height:24px;border:8px solid var(--blue);border-radius:50% 50% 50% 0;transform:rotate(-45deg);left:57%;top:45%;background:#fff}.asg2MapTag{position:absolute;left:22px;bottom:20px;z-index:2;background:var(--dark);color:#fff;padding:10px 13px;font-size:10px;font-weight:900}.asg2Road{position:absolute;left:-4%;right:-3%;top:52%;height:13px;background:#f2f2ed;transform:rotate(-8deg);box-shadow:0 0 0 1px #b7bdb6}.asg2Road2{position:absolute;top:-12%;bottom:-7%;left:44%;width:12px;background:#f2f2ed;transform:rotate(15deg);box-shadow:0 0 0 1px #b7bdb6}

        .asg2Booking{background:var(--blue);color:#fff;padding:74px 0}.asg2BookingGrid{display:grid;grid-template-columns:.82fr 1.18fr;gap:76px;align-items:start}.asg2BookingCopy h2{font-size:clamp(50px,6vw,80px);line-height:.86;letter-spacing:-.06em;font-weight:500;margin:14px 0 20px}.asg2BookingCopy p{font-size:13px;line-height:1.6;color:#e3e7ff;max-width:460px}.asg2BookingAlt{display:flex;gap:11px;align-items:center;margin-top:24px;font-size:11px}.asg2BookingAlt strong{font-size:14px}.asg2BookingPanel{background:#fff;color:var(--ink)}.asg2BookingTop{padding:20px 22px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:20px}.asg2BookingTop strong{font-size:17px}.asg2BookingTop span{font-size:9px;color:var(--muted);max-width:220px;text-align:right}.asg2Fields{display:grid;grid-template-columns:1fr 1fr}.asg2Field{min-height:70px;padding:13px 15px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.asg2Field:nth-child(even){border-right:0}.asg2FieldWide{grid-column:1/-1;border-right:0}.asg2Field label{display:block;font-size:8px;text-transform:uppercase;letter-spacing:.09em;color:#7c837e;margin-bottom:8px}.asg2Field span{font-size:12px}.asg2BookingBtn{margin:16px;width:calc(100% - 32px);min-height:48px;background:var(--dark);color:#fff;border:0;font-size:11px;font-weight:900;display:flex;align-items:center;justify-content:center;gap:8px}.asg2BookingNote{padding:0 16px 16px;font-size:8.5px;color:#7c837e}

        .asg2Footer{background:#090b0a;color:#b9c0bb;border-top:3px solid var(--acid)}.asg2FooterInner{min-height:122px;padding:26px 0;display:grid;grid-template-columns:1fr auto;gap:30px;align-items:center;font-size:10px}.asg2Footer strong{font-size:14px;color:#fff}.asg2FooterRight{display:flex;align-items:center;gap:16px}.asg2Footer a{text-decoration:underline;text-underline-offset:3px}.asg2FooterCta{border:1px solid #414743;padding:10px 12px;color:#fff!important;text-decoration:none!important;font-weight:900}

        @media(max-width:980px){.asg2Wrap{width:min(100% - 34px,1240px)}.asg2Nav{grid-template-columns:1fr auto}.asg2Links{display:none}.asg2HeroContent{grid-template-columns:1fr}.asg2HeroSide{justify-self:start;margin-top:34px}.asg2Service{grid-template-columns:54px 1fr 1fr 42px}.asg2ServiceMeta{display:none}.asg2PriceScene{grid-template-columns:1fr 1fr}.asg2ManifestoHead{grid-template-columns:160px 1fr}.asg2ReviewsGrid{gap:38px}.asg2BookingGrid{gap:38px}}
        @media(max-width:720px){.asg2Wrap{width:min(100% - 26px,1240px)}.asg2Demo{font-size:8px;text-align:center;line-height:1.35}.asg2Nav{height:62px}.asg2Phone{display:none}.asg2Hero,.asg2HeroContent{min-height:650px}.asg2Hero:after{background:linear-gradient(180deg,rgba(8,11,10,.54),rgba(8,11,10,.92) 70%)}.asg2HeroContent{align-items:end;padding-bottom:36px}.asg2HeroCopy{padding-top:90px}.asg2Hero h1{font-size:clamp(50px,15vw,72px)}.asg2HeroSide{display:none}.asg2HeroBadge{width:62px;height:62px;right:18px;bottom:20px}.asg2ServiceIntro{padding:50px 0 20px}.asg2ServiceIntroGrid{grid-template-columns:1fr;gap:18px}.asg2Service{grid-template-columns:42px 1fr 38px;gap:12px;padding:18px 0;min-height:0}.asg2Service p{grid-column:2/-1}.asg2ServiceMeta{display:none}.asg2ServiceArrow{grid-column:3;grid-row:1;width:34px;height:34px}.asg2Service h3{font-size:23px}.asg2PriceScene{grid-template-columns:1fr}.asg2PricePhoto{min-height:390px}.asg2PricePanel{padding:48px 26px}.asg2Workshop,.asg2WorkshopInner{min-height:620px}.asg2WorkshopTop{display:block}.asg2WorkshopLead{margin-top:20px}.asg2WorkshopStats{grid-template-columns:1fr 1fr}.asg2WorkshopStat{border-bottom:1px solid rgba(255,255,255,.24);padding:15px 12px 15px 0}.asg2WorkshopStat+.asg2WorkshopStat{padding-left:12px}.asg2ManifestoHead{grid-template-columns:1fr;gap:12px}.asg2Rules{grid-template-columns:1fr}.asg2Rule,.asg2Rule:nth-child(even){padding:18px 0;border-left:0}.asg2BrandsInner{align-items:flex-start;flex-direction:column}.asg2BrandList{gap:12px 18px}.asg2Journey{padding:52px 0}.asg2JourneyHead{grid-template-columns:1fr;gap:18px}.asg2Timeline{display:block;padding-top:0}.asg2Timeline:before{left:8px;right:auto;top:0;bottom:0;width:1px;height:auto}.asg2Step{padding:0 0 28px 42px}.asg2StepDot{left:0;top:3px}.asg2Step p{max-width:none}.asg2ReviewsGrid{grid-template-columns:1fr;gap:26px}.asg2Rating strong{font-size:84px}.asg2ReviewFeature{font-size:21px}.asg2ReviewMini{grid-template-columns:1fr}.asg2ReviewMini article,.asg2ReviewMini article+article{padding:18px 0;border-left:0;border-top:1px solid #343a36}.asg2Team,.asg2TeamInner{min-height:610px}.asg2Team:after{background:linear-gradient(180deg,rgba(241,241,236,.96) 0%,rgba(241,241,236,.88) 62%,rgba(241,241,236,.25) 100%)}.asg2TeamInner{align-items:flex-start}.asg2TeamCard{padding-top:48px}.asg2People{grid-template-columns:1fr}.asg2LocationGrid{grid-template-columns:1fr}.asg2Map{min-height:300px}.asg2BookingGrid{grid-template-columns:1fr}.asg2Fields{grid-template-columns:1fr}.asg2Field,.asg2Field:nth-child(even){border-right:0}.asg2FooterInner{grid-template-columns:1fr}.asg2FooterRight{flex-wrap:wrap}}
      `}</style>

      <div className="asg2Demo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>

      <div className="asg2NavShell">
        <div className="asg2Wrap">
          <nav className="asg2Nav" aria-label="Navigace ukázkového autoservisu">
            <a className="asg2Brand" href="#top"><span className="asg2Mark"><Wrench size={15}/></span><span>GARÁŽ 17<small>AUTOSERVIS · BRNO</small></span></a>
            <div className="asg2Links"><a href="#servis">Servis</a><a href="#cenik">Ceník</a><a href="#prubeh">Jak to funguje</a><a href="#tym">O nás</a><a href="#kontakt">Kontakt</a></div>
            <div className="asg2NavRight"><a className="asg2Phone" href="tel:+420777000000">777 000 000</a><a className="asg2NavCta" href="#rezervace">Objednat servis <ArrowRight size={12}/></a></div>
          </nav>
        </div>
      </div>

      <header className="asg2Hero">
        <img src="https://images.pexels.com/photos/6870298/pexels-photo-6870298.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Mechanik kontroluje motor běžného osobního auta v servisní dílně"/>
        <div className="asg2HeroIndex">GARÁŽ 17 / BRNO-SLATINA / PO–PÁ 7:30–17:00</div>
        <div className="asg2HeroBadge"><Wrench size={26}/></div>
        <div className="asg2Wrap asg2HeroContent">
          <div className="asg2HeroCopy">
            <div className="asg2Kicker">AUTOSERVIS · BRNO SLATINA</div>
            <h1>Servis a opravy osobních aut.</h1>
            <p className="asg2Lead">Pravidelný servis, diagnostika, brzdy, podvozek, klimatizace a pneuservis pro většinu běžných značek. U větších oprav předem potvrdíme rozsah práce a cenu.</p>
            <div className="asg2HeroActions"><a className="asg2Btn asg2BtnPrimary" href="#rezervace">Objednat termín <CalendarDays size={15}/></a><a className="asg2Btn asg2BtnGhost" href="#cenik">Služby a ceny <ArrowRight size={14}/></a></div>
          </div>
          <div className="asg2HeroSide"><strong>Objednání a kontakt</strong><div><span><Phone size={13}/> 777 000 000</span><span><Clock3 size={13}/> Po–Pá 7:30–17:00</span><span><MapPin size={13}/> Řípská 17, Brno</span><span><Car size={13}/> většina běžných značek</span></div></div>
        </div>
      </header>

      <section className="asg2ServiceIntro" id="servis"><div className="asg2Wrap asg2ServiceIntroGrid"><div><div className="asg2Kicker">SERVIS A OPRAVY</div><h2>S čím k nám můžete přijet.</h2></div><p>Od pravidelné údržby po hledání závady. Rozsah práce závisí na konkrétním vozu a jeho stavu.</p></div></section>
      <section className="asg2Services"><div className="asg2Wrap">{services.map(([no,title,text,meta])=><a className="asg2Service" href="#rezervace" key={no}><span className="asg2ServiceNo">{no}</span><h3>{title}</h3><p>{text}</p><span className="asg2ServiceMeta">{meta}</span><span className="asg2ServiceArrow"><ArrowRight size={15}/></span></a>)}</div></section>

      <section className="asg2PriceScene" id="cenik">
        <div className="asg2PricePhoto"><img src="https://images.pexels.com/photos/8470688/pexels-photo-8470688.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Mechanik při opravě motoru běžného osobního auta"/><div className="asg2PriceCaption"><strong>Rozsah práce potvrzujeme před opravou.</strong><span>U nejasné závady začínáme diagnostikou.</span></div></div>
        <div className="asg2PricePanel"><div className="asg2Kicker">ORIENTAČNÍ CENY</div><h2>Běžné servisní úkony.</h2><div className="asg2PriceList">{prices.map(([service,price])=><div className="asg2PriceRow" key={service}><span>{service}</span><strong>{price}</strong></div>)}</div><div className="asg2PriceNote"><Gauge size={24}/><div><strong>U závady nejdřív určíme rozsah opravy.</strong><p>Pokud není příčina zřejmá, začínáme diagnostikou. Po zjištění závady sdělíme cenu a další postup.</p></div></div><div className="asg2Fine">Ukázkové ceny fiktivního autoservisu. Nejde o skutečnou nabídku služby.</div></div>
      </section>

      <section className="asg2Workshop">
        <img src="https://images.pexels.com/photos/8985667/pexels-photo-8985667.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Běžné osobní auto na zvedáku v nezávislé servisní dílně"/>
        <div className="asg2Wrap asg2WorkshopInner"><div className="asg2WorkshopTop"><div><div className="asg2Kicker" style={{color:'#d9ff64'}}>DÍLNA</div><h2>Vybavení pro běžný servis i opravy.</h2></div><p className="asg2WorkshopLead">Čtyři servisní stání, diagnostika, zvedáky a pneuservis. Objednání na konkrétní termín.</p></div><div className="asg2WorkshopStats"><div className="asg2WorkshopStat"><strong>4 servisní stání</strong><span>běžný servis a opravy</span></div><div className="asg2WorkshopStat"><strong>Diagnostika vozů</strong><span>evropské a asijské značky</span></div><div className="asg2WorkshopStat"><strong>Pneuservis</strong><span>přezutí, vyvážení, defekty</span></div><div className="asg2WorkshopStat"><strong>Náhradní vůz</strong><span>u delších oprav po dohodě</span></div></div></div>
      </section>

      <section className="asg2Manifesto"><div className="asg2Wrap"><div className="asg2ManifestoHead"><div className="asg2Kicker" style={{color:'#0e1110'}}>JAK PRACUJEME</div><h2>Co platí při každé zakázce.</h2></div><div className="asg2Rules">{rules.map(([title,text])=><article className="asg2Rule" key={title}><strong>{title}</strong><p>{text}</p></article>)}</div></div></section>

      <div className="asg2Brands"><div className="asg2Wrap asg2BrandsInner"><strong>Nejčastěji servisujeme</strong><div className="asg2BrandList">{brands.map(b=><span key={b}>{b}</span>)}</div></div></div>

      <section className="asg2Journey" id="prubeh"><div className="asg2Wrap"><div className="asg2JourneyHead"><div><div className="asg2Kicker">PRŮBĚH ZAKÁZKY</div><h2>Od objednání po převzetí auta.</h2></div><p>U diagnostiky a větších oprav potvrzujeme rozsah práce předem. Zvýrazněný krok je moment, kdy se domlouvá samotná oprava.</p></div><div className="asg2Timeline">{steps.map(([no,title,text])=><article className="asg2Step" key={no}><span className="asg2StepDot"/><span className="asg2StepNo">{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="asg2Reviews"><div className="asg2Wrap asg2ReviewsGrid"><div className="asg2Rating"><strong>4,9</strong><span>/ 5 · 286 hodnocení</span></div><div className="asg2ReviewsMain"><div className="asg2Kicker" style={{color:'#d9ff64',marginBottom:12}}>HODNOCENÍ ZÁKAZNÍKŮ</div><h2>Zkušenosti se servisem.</h2><p className="asg2ReviewFeature">{reviews[0][0]}<small>{reviews[0][1]} · GOOGLE RECENZE / DEMO</small></p><div className="asg2ReviewMini">{reviews.slice(1).map(([quote,name])=><article key={name}><p>{quote}</p><small>{name} · GOOGLE RECENZE / DEMO</small></article>)}</div><span className="asg2DemoLabel">Ukázková data fiktivního autoservisu.</span></div></div></section>

      <section className="asg2Team" id="tym"><img src="https://images.pexels.com/photos/9112797/pexels-photo-9112797.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Mechanik při práci v menší české autodílně"/><div className="asg2Wrap asg2TeamInner"><div className="asg2TeamCard"><div className="asg2Kicker">TÝM AUTOSERVISU</div><h2>Lidé, kteří se starají o vaše auto.</h2><p>Servis vede David Horák. Marek se věnuje diagnostice a podvozku, Tomáš běžnému servisu a pneuservisu.</p><div className="asg2People"><div className="asg2Person"><strong>David Horák</strong><span>vedoucí servisu · 16 let praxe</span></div><div className="asg2Person"><strong>Marek Dvořák</strong><span>diagnostika · podvozek</span></div><div className="asg2Person"><strong>Tomáš Jelínek</strong><span>servis · pneuservis</span></div></div></div></div></section>

      <section className="asg2Location" id="kontakt"><div className="asg2Wrap asg2LocationGrid"><div className="asg2LocCopy"><div className="asg2Kicker">KDE NÁS NAJDETE</div><h2>Brno-Slatina.</h2><div className="asg2LocRows"><div className="asg2LocRow"><MapPin size={16}/><div><strong>Řípská 17, Brno</strong><span>vjezd z boční komunikace, parkování před dílnou</span></div></div><div className="asg2LocRow"><Clock3 size={16}/><div><strong>Po–Pá 7:30–17:00</strong><span>příjem vozů podle rezervovaného termínu</span></div></div><div className="asg2LocRow"><Phone size={16}/><div><strong>777 000 000</strong><span>v pracovní době</span></div></div><div className="asg2LocRow"><ShieldCheck size={16}/><div><strong>Pojištění odpovědnosti</strong><span>po dobu, kdy je vůz převzatý do servisu</span></div></div></div></div><div className="asg2Map" aria-label="Ilustrační mapa příjezdu"><div className="asg2Road"/><div className="asg2Road2"/><span className="asg2MapTag">ŘÍPSKÁ 17 · VJEZD DO SERVISU</span></div></div></section>

      <section className="asg2Booking" id="rezervace"><div className="asg2Wrap asg2BookingGrid"><div className="asg2BookingCopy"><div className="asg2Kicker" style={{color:'#d9ff64'}}>OBJEDNÁNÍ</div><h2>Objednání do servisu.</h2><p>Vyberte službu, vůz a požadovaný den. Termín potvrdíme podle kapacity dílny a rozsahu práce.</p><div className="asg2BookingAlt"><Phone size={16}/><div><span>nebo zavolejte</span><br/><strong>777 000 000</strong></div></div></div><div className="asg2BookingPanel"><div className="asg2BookingTop"><strong>Rezervace servisu</strong><span>Ukázka rezervačního rozhraní. Formulář není aktivní.</span></div><div className="asg2Fields"><div className="asg2Field"><label>Služba</label><span>Vyberte službu</span></div><div className="asg2Field"><label>Preferovaný den</label><span>Vyberte termín</span></div><div className="asg2Field"><label>Vůz</label><span>Značka a model</span></div><div className="asg2Field"><label>Telefon</label><span>+420 ...</span></div><div className="asg2Field asg2FieldWide"><label>Poznámka</label><span>Popis závady nebo požadované práce</span></div></div><button className="asg2BookingBtn" type="button">Odeslat rezervaci <ArrowRight size={13}/></button><div className="asg2BookingNote">Tlačítko je v ukázkovém konceptu záměrně neaktivní. Nejde o skutečný autoservis.</div></div></div></section>

      <footer className="asg2Footer"><div className="asg2Wrap asg2FooterInner"><div><strong>GARÁŽ 17 · AUTOSERVIS</strong><br/>Fiktivní firma vytvořená pouze jako ukázkový koncept.</div><div className="asg2FooterRight">Tento koncept vytvořil <a href="/">SpustWeb.cz</a><a className="asg2FooterCta" href="/#kontakt">Web pro moje podnikání</a></div></div></footer>
    </div>
  )
}
