import type { Metadata } from 'next'
import { Bike, Car, Coffee, Mail, MapPin, PawPrint, Phone, Wifi } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro penzion | SpustWeb.cz',
  description: 'Ukázka webu pro menší penzion: pokoje, vybavení, snídaně, okolí, praktické informace a poptávka pobytu.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/penzion/' },
  robots: { index: true, follow: true },
}

const rooms = [
  {
    no: '01',
    name: 'Pokoj U zahrady',
    meta: '2 hosté · 24 m²',
    price: 'od 2 190 Kč / noc',
    text: 'Pokoj v přízemí s okny do zahrady. Vlastní koupelna, malá lednice a místo k posezení.',
    image: 'https://images.pexels.com/photos/15699340/pexels-photo-13038494.jpeg?auto=compress&cs=tinysrgb&w=1800'.replace('13038494','15699340'),
    alt: 'Dvoulůžkový pokoj s dřevěnými trámy, kamennou stěnou a modrými detaily',
  },
  {
    no: '02',
    name: 'Pokoj Pod střechou',
    meta: '2 hosté · 28 m²',
    price: 'od 2 390 Kč / noc',
    text: 'Prostornější pokoj v podkroví. Dřevěné trámy, koupelna se sprchou a výhled do dvora.',
    image: 'https://images.pexels.com/photos/15692793/pexels-photo-15692793.jpeg?auto=compress&cs=tinysrgb&w=1800',
    alt: 'Pokoj se světlým povlečením, dřevěnými trámy a modrým čelem postele',
  },
  {
    no: '03',
    name: 'Rodinný pokoj',
    meta: '2–4 hosté · 36 m²',
    price: 'od 3 090 Kč / noc',
    text: 'Větší pokoj pro rodiče s dětmi. Vlastní koupelna, úložný prostor a dost místa i na delší pobyt.',
    image: 'https://images.pexels.com/photos/15692794/pexels-photo-15692794.jpeg?auto=compress&cs=tinysrgb&w=1800',
    alt: 'Světlý rustikální pokoj s dřevěnými trámy, modrými dveřmi a bílým povlečením',
  },
]

const practical = [
  ['Check-in', '15:00–19:00'],
  ['Check-out', 'do 10:30'],
  ['Snídaně', '8:00–10:00'],
  ['Parkování', 'zdarma u domu'],
  ['Kola', 'uzamykatelná kolárna'],
  ['Pes', 'po předchozí dohodě'],
]

const trebonTrail = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Okolo_T%C5%99ebon%C4%9B_%28educational_trail%29_between_Sv%C4%9Bt_and_Opatovick%C3%BD_rybn%C3%ADk_01.jpg?width=1500'
const trebonTown = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/T%C5%99ebo%C5%88%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg?width=1200'
const rozmberek = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rybn%C3%ADk_Ro%C5%BEmberk.jpg?width=1200'

export default function GuesthouseShowcase() {
  return (
    <div className="gh5" id="top">
      <style>{`
        body:has(.gh5) > .verno-nav-shell,body:has(.gh5) > .footer{display:none!important}
        body:has(.gh5) main{padding:0!important;margin:0!important}
        body:has(.gh5){background:#f7f7f4!important}
        .gh5{--ink:#17231f;--forest:#17372f;--white:#f7f7f4;--paper:#fff;--blue:#dfe9e8;--wine:#8a4351;--line:rgba(23,35,31,.16);font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--white)}
        .gh5 *{box-sizing:border-box}.gh5 a{color:inherit;text-decoration:none}.gh5 img{display:block;width:100%}.gh5Wrap{width:min(1280px,calc(100% - 54px));margin:0 auto}.gh5Meta{font-size:9px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.gh5Muted{color:#6d746f}
        .gh5Demo{min-height:24px;padding:5px 12px;background:#0f1a17;color:#cfd7d2;display:flex;justify-content:center;align-items:center;font-size:8.5px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.gh5Demo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .gh5NavShell{position:sticky;top:0;z-index:150;background:rgba(23,55,47,.95);backdrop-filter:blur(14px);color:#fff;border-bottom:1px solid rgba(255,255,255,.12)}.gh5Nav{height:64px;display:grid;grid-template-columns:1fr auto;align-items:center;gap:28px}.gh5Brand{display:flex;align-items:baseline;gap:14px}.gh5Brand strong{font-family:Georgia,'Times New Roman',serif;font-size:22px;font-weight:400;font-style:italic}.gh5Brand span{font-size:8px;letter-spacing:.13em;text-transform:uppercase;color:#b9c7c0}.gh5NavRight{display:flex;align-items:center;gap:26px}.gh5Links{display:flex;gap:24px;font-size:10px;font-weight:700}.gh5Links a{opacity:.82}.gh5ContactSmall{min-height:36px;padding:0 14px;background:#fff;color:var(--forest)!important;display:inline-flex;align-items:center;font-size:9.5px;font-weight:900}
        .gh5Hero{position:relative;height:calc(100svh - 88px);min-height:560px;max-height:820px;background:#243a34;color:#fff;overflow:hidden}.gh5Hero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 48%;filter:saturate(.68) contrast(1.03) brightness(.7)}.gh5Hero:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(10,19,16,.08),rgba(10,19,16,.15) 38%,rgba(10,19,16,.76) 100%),linear-gradient(90deg,rgba(10,19,16,.58),transparent 64%)}.gh5HeroInner{position:relative;z-index:2;height:100%;display:grid;grid-template-columns:1fr 330px;align-items:end;gap:70px;padding-bottom:48px}.gh5HeroTitle{max-width:790px}.gh5HeroTitle .gh5Meta{color:#d7e2dd;margin-bottom:16px}.gh5Hero h1{font-family:Georgia,'Times New Roman',serif;font-size:clamp(62px,7.5vw,104px);font-weight:400;line-height:.84;letter-spacing:-.055em;margin:0}.gh5HeroLead{font-size:13px;line-height:1.62;color:#eef1ee;max-width:540px;margin:20px 0 0}.gh5HeroContact{background:rgba(247,247,244,.96);color:var(--ink);padding:22px}.gh5HeroContact strong{display:block;font-family:Georgia,'Times New Roman',serif;font-size:22px;font-weight:400;margin-bottom:12px}.gh5HeroContact p{font-size:10.5px;line-height:1.55;color:#5f6863;margin:0 0 16px}.gh5HeroContact a{display:flex;align-items:center;gap:8px;padding:9px 0;border-top:1px solid var(--line);font-size:10.5px;font-weight:800}.gh5HeroContact .gh5HeroContactBtn{margin-top:12px;background:var(--wine);color:#fff!important;justify-content:center;border:0;padding:12px}
        .gh5Facts{background:#fff;border-bottom:1px solid var(--line)}.gh5FactsInner{min-height:76px;display:grid;grid-template-columns:repeat(5,1fr);align-items:center}.gh5Fact{padding:0 22px;border-right:1px solid var(--line);font-size:10px;line-height:1.4}.gh5Fact:first-child{padding-left:0}.gh5Fact:last-child{border-right:0}.gh5Fact strong{display:block;font-size:11px;margin-bottom:3px}.gh5Fact span{color:#737a75}
        .gh5Rooms{padding:78px 0 96px}.gh5RoomsHead{display:flex;justify-content:space-between;align-items:end;gap:50px;margin-bottom:50px}.gh5RoomsHead h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(50px,6vw,82px);line-height:.9;font-weight:400;letter-spacing:-.05em;margin:0}.gh5RoomsHead p{max-width:430px;font-size:12px;line-height:1.65;color:#606863;margin:0 0 7px}.gh5RoomGallery{display:grid;grid-template-columns:repeat(12,1fr);gap:28px 22px;align-items:start}.gh5RoomCard:nth-child(1){grid-column:1/8}.gh5RoomCard:nth-child(2){grid-column:8/13;margin-top:120px}.gh5RoomCard:nth-child(3){grid-column:3/10;margin-top:18px}.gh5RoomImage{overflow:hidden;background:#ddd}.gh5RoomCard:nth-child(1) .gh5RoomImage{aspect-ratio:1.42/1}.gh5RoomCard:nth-child(2) .gh5RoomImage{aspect-ratio:1.05/1}.gh5RoomCard:nth-child(3) .gh5RoomImage{aspect-ratio:1.48/1}.gh5RoomImage img{height:100%;object-fit:cover;filter:saturate(.76) contrast(1.02)}.gh5RoomText{padding:16px 2px 0;display:grid;grid-template-columns:1fr auto;gap:10px 30px}.gh5RoomText .gh5Meta{grid-column:1/-1;color:var(--wine)}.gh5RoomText h3{font-family:Georgia,'Times New Roman',serif;font-size:28px;font-weight:400;line-height:1;margin:0}.gh5RoomText p{grid-column:1;max-width:480px;font-size:10.5px;line-height:1.55;color:#5e6661;margin:0}.gh5RoomAside{grid-column:2;grid-row:2/4;text-align:right;min-width:140px}.gh5RoomAside strong{display:block;font-size:10.5px;margin-bottom:10px}.gh5RoomAside a{font-size:9.5px;font-weight:800;border-bottom:1px solid var(--ink);padding-bottom:3px}
        .gh5Included{background:var(--forest);color:#fff;padding:34px 0}.gh5IncludedInner{display:flex;align-items:center;gap:38px}.gh5IncludedTitle{font-family:Georgia,'Times New Roman',serif;font-size:27px;font-weight:400;white-space:nowrap}.gh5Amenities{display:flex;gap:26px;flex-wrap:wrap}.gh5Amenity{display:flex;align-items:center;gap:8px;font-size:10px;color:#d7e1dc}.gh5Amenity strong{color:#fff;font-size:10px}
        .gh5Place{padding:90px 0 96px;background:#fff}.gh5PlaceIntro{display:grid;grid-template-columns:.72fr 1.28fr;gap:90px}.gh5PlaceIntro h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(56px,6.7vw,92px);line-height:.86;font-weight:400;letter-spacing:-.055em;margin:0}.gh5PlaceIntro p{font-size:12.5px;line-height:1.65;color:#5e6762;max-width:500px;margin:17px 0 0}.gh5PlaceStory{margin-top:50px;display:grid;grid-template-columns:1.08fr .92fr;gap:16px}.gh5PlaceMain{margin:0}.gh5PlaceMain img{height:610px;object-fit:cover;filter:saturate(.82)}.gh5PlaceMain figcaption,.gh5PlaceSide figcaption{padding-top:9px;font-size:9px;color:#6a716d}.gh5PlaceSide{display:grid;grid-template-columns:1fr 1fr;gap:16px}.gh5PlaceSide figure{margin:0}.gh5PlaceSide img{height:280px;object-fit:cover;filter:saturate(.82)}.gh5PlaceSide figure:last-child{grid-column:1/-1}.gh5PlaceSide figure:last-child img{height:290px}.gh5PlaceSide figcaption{display:flex;justify-content:space-between;gap:14px}.gh5PlaceSide strong{font-family:Georgia,'Times New Roman',serif;font-size:16px;font-weight:400;color:var(--ink)}.gh5PlaceNote{margin:28px 0 0 16%;max-width:650px;border-left:1px solid var(--wine);padding-left:20px;font-size:12px;line-height:1.65;color:#4d5752}.gh5Credit{font-size:8px;color:#8a918c;margin-top:12px}
        .gh5Breakfast{padding:78px 0 82px;background:var(--blue)}.gh5BreakfastHead{display:grid;grid-template-columns:.72fr 1.28fr;gap:70px;align-items:end;margin-bottom:30px}.gh5BreakfastHead h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(48px,5.8vw,76px);line-height:.9;font-weight:400;letter-spacing:-.05em;margin:0}.gh5BreakfastHead p{font-size:12px;line-height:1.65;color:#53605c;max-width:480px;margin:0}.gh5BreakfastStrip{display:grid;grid-template-columns:1.18fr .82fr .82fr;gap:10px;align-items:end}.gh5BreakfastStrip img{width:100%;object-fit:cover;filter:saturate(.8)}.gh5BreakfastStrip img:nth-child(1){height:315px}.gh5BreakfastStrip img:nth-child(2),.gh5BreakfastStrip img:nth-child(3){height:240px}.gh5BreakfastBottom{display:flex;justify-content:space-between;gap:40px;margin-top:18px;border-top:1px solid rgba(23,35,31,.22);padding-top:13px;font-size:10px}
        .gh5Review{background:var(--wine);color:#fff;padding:70px 0}.gh5ReviewInner{display:grid;grid-template-columns:210px 1fr;gap:56px}.gh5Score strong{font-family:Georgia,'Times New Roman',serif;font-size:90px;font-weight:400;line-height:.8}.gh5Score span{display:block;font-size:9px;color:#f1dfe3;margin-top:10px}.gh5Quote{font-family:Georgia,'Times New Roman',serif;font-size:clamp(32px,3.8vw,50px);line-height:1.08;font-weight:400;margin:0;max-width:900px}.gh5QuoteBy{font-size:9px;letter-spacing:.09em;text-transform:uppercase;color:#efd8de;margin-top:18px}.gh5ReviewRow{display:grid;grid-template-columns:1fr 1fr;gap:38px;margin-top:26px;padding-top:20px;border-top:1px solid rgba(255,255,255,.3)}.gh5ReviewRow p{font-size:10.5px;line-height:1.55;color:#f5e9ec;margin:0}.gh5DemoLabel{display:inline-block;margin-top:18px;border:1px solid rgba(255,255,255,.35);padding:5px 7px;font-size:8px;color:#f0dfe3}
        .gh5Owners{padding:90px 0;background:#fff}.gh5OwnersGrid{display:grid;grid-template-columns:repeat(12,1fr);gap:22px;align-items:center}.gh5OwnersText{grid-column:1/6;padding-right:44px}.gh5OwnersText h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(48px,5.5vw,72px);font-weight:400;line-height:.9;margin:0 0 18px}.gh5OwnersText p{font-size:12px;line-height:1.65;color:#55605a;max-width:440px;margin:0}.gh5OwnersPhoto{grid-column:6/13;height:500px;overflow:hidden}.gh5OwnersPhoto img{height:100%;object-fit:cover;object-position:center 48%;filter:saturate(.75)}
        .gh5Practical{padding:82px 0}.gh5PracticalGrid{display:grid;grid-template-columns:.72fr 1.28fr;gap:80px}.gh5PracticalIntro h2{font-family:Georgia,'Times New Roman',serif;font-size:46px;font-weight:400;line-height:.94;margin:0}.gh5PracticalIntro p{font-size:11.5px;line-height:1.6;color:#626a65;max-width:360px;margin:16px 0 0}.gh5PracticalList{border-top:1px solid var(--line)}.gh5PracticalRow{display:grid;grid-template-columns:1fr auto;gap:25px;padding:15px 0;border-bottom:1px solid var(--line);font-size:11px}
        .gh5MapSection{background:var(--blue);padding:52px 0}.gh5MapGrid{display:grid;grid-template-columns:1.3fr .7fr;gap:18px}.gh5Map{position:relative;min-height:410px;background:#cbd7d6;overflow:hidden}.gh5Map:before{content:'';position:absolute;inset:-15%;background:repeating-linear-gradient(24deg,transparent 0 42px,#b7c6c5 43px 45px),repeating-linear-gradient(118deg,transparent 0 68px,#b9c8c6 69px 72px)}.gh5Map:after{content:'';position:absolute;width:24px;height:24px;border:8px solid var(--wine);border-radius:50% 50% 50% 0;transform:rotate(-45deg);left:56%;top:44%;background:#fff}.gh5Road{position:absolute;left:-5%;right:-5%;top:52%;height:13px;background:#f5f7f6;transform:rotate(-8deg);box-shadow:0 0 0 1px #aebdbc}.gh5Road2{position:absolute;top:-15%;bottom:-10%;left:44%;width:12px;background:#f5f7f6;transform:rotate(14deg);box-shadow:0 0 0 1px #aebdbc}.gh5MapCopy{background:#fff;padding:32px;display:flex;flex-direction:column;justify-content:space-between}.gh5MapCopy h2{font-family:Georgia,'Times New Roman',serif;font-size:37px;font-weight:400;line-height:.95;margin:0 0 16px}.gh5MapCopy p{font-size:11px;line-height:1.6;color:#5b645f;margin:0}.gh5MapDetails{display:grid;gap:10px;margin-top:26px;font-size:10px}.gh5MapDetails span,.gh5MapDetails a{display:flex;align-items:center;gap:8px}
        .gh5Enquiry{padding:78px 0;background:var(--forest);color:#fff}.gh5EnquiryHead{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:end;margin-bottom:28px}.gh5EnquiryHead h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(52px,6vw,80px);font-weight:400;line-height:.88;letter-spacing:-.05em;margin:0}.gh5EnquiryHead p{font-size:12px;line-height:1.6;color:#d5e0db;max-width:520px;margin:0}.gh5EnquiryGrid{display:grid;grid-template-columns:1.25fr .75fr;gap:54px}.gh5Form{background:#fff;color:var(--ink);padding:22px}.gh5Field{display:grid;grid-template-columns:160px 1fr;border-bottom:1px solid var(--line)}.gh5Field label{padding:16px 12px 16px 0;font-size:8.5px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.gh5Field input,.gh5Field select,.gh5Field textarea{border:0;background:transparent;padding:14px 0;font:inherit;font-size:11px;outline:none}.gh5Field textarea{min-height:96px;resize:vertical}.gh5Form button{width:100%;margin-top:12px;min-height:44px;border:0;background:var(--wine);color:#fff;font-size:10px;font-weight:900}.gh5FormNote{font-size:8.5px;color:#757d78;margin-top:9px}.gh5Direct{border-top:1px solid rgba(255,255,255,.5);padding-top:18px}.gh5Direct h3{font-family:Georgia,'Times New Roman',serif;font-size:28px;font-weight:400;margin:0 0 14px}.gh5Direct a{display:flex;align-items:center;gap:8px;padding:11px 0;border-bottom:1px solid rgba(255,255,255,.25);font-size:11px;font-weight:800}.gh5Direct p{font-size:10px;line-height:1.55;color:#cbd8d2;margin-top:16px}
        .gh5Footer{background:#0d1714;color:#aebbb5}.gh5FooterInner{min-height:108px;padding:23px 0;display:grid;grid-template-columns:1fr auto;gap:30px;align-items:center;font-size:9.5px}.gh5Footer strong{color:#fff;font-family:Georgia,'Times New Roman',serif;font-size:16px;font-weight:400}.gh5FooterRight{display:flex;gap:14px;align-items:center}.gh5Footer a{text-decoration:underline;text-underline-offset:3px}.gh5FooterCta{border:1px solid #46564f;padding:9px 11px;color:#fff!important;text-decoration:none!important;font-weight:800}
        @media(max-width:980px){.gh5Wrap{width:min(100% - 36px,1280px)}.gh5Links{display:none}.gh5HeroInner{grid-template-columns:1fr 310px;gap:30px}.gh5FactsInner{grid-template-columns:repeat(3,1fr)}.gh5Fact{padding:14px;border-bottom:1px solid var(--line)}.gh5RoomCard:nth-child(1){grid-column:1/9}.gh5RoomCard:nth-child(2){grid-column:8/13;margin-top:80px}.gh5RoomCard:nth-child(3){grid-column:2/10}.gh5PlaceIntro{grid-template-columns:1fr 1fr;gap:40px}.gh5PlaceStory{grid-template-columns:1fr}.gh5OwnersText{grid-column:1/6}.gh5OwnersPhoto{grid-column:6/13}.gh5EnquiryHead{grid-template-columns:1fr;gap:20px}.gh5EnquiryGrid{grid-template-columns:1fr 1fr}}
        @media(max-width:720px){.gh5Wrap{width:min(100% - 26px,1280px)}.gh5Demo{font-size:7.5px}.gh5Nav{height:58px}.gh5Brand span{display:none}.gh5Hero{height:auto;min-height:680px;max-height:none}.gh5HeroInner{min-height:680px;grid-template-columns:1fr;align-content:end;padding:100px 0 26px}.gh5Hero h1{font-size:clamp(56px,16vw,78px)}.gh5HeroContact{width:100%;max-width:430px}.gh5FactsInner{grid-template-columns:1fr 1fr}.gh5Rooms{padding:58px 0 70px}.gh5RoomsHead{display:block}.gh5RoomsHead p{margin-top:18px}.gh5RoomGallery{display:block}.gh5RoomCard:nth-child(n){margin:0 0 48px}.gh5RoomCard:nth-child(n) .gh5RoomImage{aspect-ratio:1.32/1}.gh5RoomText{grid-template-columns:1fr}.gh5RoomAside{grid-column:1;grid-row:auto;text-align:left}.gh5IncludedInner{align-items:flex-start;flex-direction:column}.gh5Place{padding:64px 0}.gh5PlaceIntro{grid-template-columns:1fr;gap:20px}.gh5PlaceMain img{height:430px}.gh5PlaceSide{grid-template-columns:1fr}.gh5PlaceSide figure:last-child{grid-column:auto}.gh5PlaceSide img,.gh5PlaceSide figure:last-child img{height:240px}.gh5PlaceNote{margin-left:0}.gh5Breakfast{padding:62px 0}.gh5BreakfastHead{grid-template-columns:1fr;gap:18px}.gh5BreakfastStrip{grid-template-columns:1fr 1fr}.gh5BreakfastStrip img:nth-child(1){grid-column:1/-1;height:280px}.gh5BreakfastStrip img:nth-child(2),.gh5BreakfastStrip img:nth-child(3){height:180px}.gh5ReviewInner{grid-template-columns:1fr;gap:28px}.gh5ReviewRow{grid-template-columns:1fr}.gh5Owners{padding:66px 0}.gh5OwnersGrid{display:flex;flex-direction:column}.gh5OwnersText{padding:0;order:2}.gh5OwnersPhoto{width:100%;height:390px;order:1}.gh5PracticalGrid{grid-template-columns:1fr;gap:32px}.gh5MapGrid{grid-template-columns:1fr}.gh5Map{min-height:320px}.gh5EnquiryGrid{grid-template-columns:1fr}.gh5Field{grid-template-columns:1fr}.gh5Field label{padding-bottom:0}.gh5FooterInner{grid-template-columns:1fr}.gh5FooterRight{flex-wrap:wrap}}
      `}</style>

      <div className="gh5Demo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <div className="gh5NavShell"><div className="gh5Wrap"><nav className="gh5Nav"><a className="gh5Brand" href="#top"><strong>U Tiché vody</strong><span>penzion · Třeboňsko</span></a><div className="gh5NavRight"><div className="gh5Links"><a href="#pokoje">Pokoje</a><a href="#okoli">Okolí</a><a href="#prakticke">Praktické</a></div><a className="gh5ContactSmall" href="#poptavka">Poptat pobyt</a></div></nav></div></div>

      <header className="gh5Hero"><img src="https://images.pexels.com/photos/15692771/pexels-photo-15692771.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Vstup do rustikálního pokoje s dřevěnými trámy a světlým povlečením"/><div className="gh5Wrap gh5HeroInner"><div className="gh5HeroTitle"><div className="gh5Meta">PENZION · TŘEBOŇSKO</div><h1>U Tiché<br/>vody.</h1><p className="gh5HeroLead">Osm pokojů v opraveném venkovském domě. Snídaně v ceně, zahrada, kolárna a Třeboň deset minut autem.</p></div><aside className="gh5HeroContact"><strong>Pobyt u Třeboně</strong><p>Termín a dostupnost pokoje ověříme po telefonu nebo e-mailem.</p><a href="tel:+420705911941"><Phone size={14}/> +420 705 911 941</a><a href="mailto:kontakt@spustweb.cz"><Mail size={14}/> kontakt@spustweb.cz</a><a className="gh5HeroContactBtn" href="#poptavka">Napsat kvůli pobytu</a></aside></div></header>

      <div className="gh5Facts"><div className="gh5Wrap gh5FactsInner"><div className="gh5Fact"><strong>8 pokojů</strong><span>dvoulůžkové i rodinné</span></div><div className="gh5Fact"><strong>Snídaně v ceně</strong><span>každé ráno 8:00–10:00</span></div><div className="gh5Fact"><strong>Parkování u domu</strong><span>bez příplatku</span></div><div className="gh5Fact"><strong>Kolárna</strong><span>uzamykatelná</span></div><div className="gh5Fact"><strong>Třeboň 8 km</strong><span>autem přibližně 10 minut</span></div></div></div>

      <section className="gh5Rooms" id="pokoje"><div className="gh5Wrap"><div className="gh5RoomsHead"><h2>Vyberte si pokoj.</h2><p>K dispozici jsou dvoulůžkové i rodinné pokoje. Každý má vlastní koupelnu, Wi-Fi a snídani v ceně.</p></div><div className="gh5RoomGallery">{rooms.map((room)=><article className="gh5RoomCard" key={room.no}><div className="gh5RoomImage"><img src={room.image} alt={room.alt}/></div><div className="gh5RoomText"><div className="gh5Meta">POKOJ {room.no} · {room.meta}</div><h3>{room.name}</h3><p>{room.text}</p><div className="gh5RoomAside"><strong>{room.price}</strong><a href="#poptavka">Poptat pokoj</a></div></div></article>)}</div></div></section>

      <section className="gh5Included"><div className="gh5Wrap gh5IncludedInner"><div className="gh5IncludedTitle">V ceně pobytu</div><div className="gh5Amenities"><div className="gh5Amenity"><Coffee size={14}/><span><strong>Snídaně</strong> 8:00–10:00</span></div><div className="gh5Amenity"><Car size={14}/><span><strong>Parkování</strong> u domu</span></div><div className="gh5Amenity"><Wifi size={14}/><span><strong>Wi-Fi</strong> pokoje i zahrada</span></div><div className="gh5Amenity"><Bike size={14}/><span><strong>Kolárna</strong> uzamykatelná</span></div><div className="gh5Amenity"><PawPrint size={14}/><span><strong>Pes</strong> po dohodě</span></div></div></div></section>

      <section className="gh5Place" id="okoli"><div className="gh5Wrap"><div className="gh5PlaceIntro"><h2>Třeboňsko<br/>v okolí.</h2><p>Rybníky, rovné cyklotrasy a Třeboň v krátké dojezdové vzdálenosti. Kolo lze uložit v uzamykatelné kolárně přímo u penzionu.</p></div><div className="gh5PlaceStory"><figure className="gh5PlaceMain"><img src={trebonTrail} alt="Stezka mezi rybníky Svět a Opatovický na Třeboňsku"/><figcaption>Stezka Okolo Třeboně mezi rybníky Svět a Opatovický.</figcaption></figure><div className="gh5PlaceSide"><figure><img src={trebonTown} alt="Náměstí v Třeboni"/><figcaption><strong>Třeboň</strong><span>8 km · centrum, zámek, restaurace</span></figcaption></figure><figure><img src={rozmberek} alt="Rybník Rožmberk u Třeboně"/><figcaption><strong>Rožmberk</strong><span>12 km · rybník a cyklotrasy</span></figcaption></figure><figure><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Hrani%C4%8Dn%C3%AD_rybn%C3%ADk%2C_T%C5%99ebo%C5%88sko.JPG?width=1200" alt="Rybník v krajině Třeboňska"/><figcaption><strong>Třeboňsko</strong><span>rybníky, hráze a rovná krajina</span></figcaption></figure></div></div><p className="gh5PlaceNote">Cyklostezka vede přibližně 600 metrů od domu. Třeboň je osm kilometrů, Rožmberk dvanáct.</p><div className="gh5Credit">Ilustrační fotografie okolí: Wikimedia Commons · skutečné Třeboňsko, Třeboň a Rožmberk.</div></div></section>

      <section className="gh5Breakfast"><div className="gh5Wrap"><div className="gh5BreakfastHead"><h2>Snídaně je v ceně pokoje.</h2><p>Pečivo, vejce, sýry, šunka, jogurt, ovoce, něco sladkého, káva a čaj. Podává se každé ráno mezi osmou a desátou.</p></div><div className="gh5BreakfastStrip"><img src="https://images.pexels.com/photos/5591699/pexels-photo-5591699.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Snídaně pro dva s vejci, pečivem a kávou na dřevěném stole"/><img src="https://images.pexels.com/photos/5720777/pexels-photo-5720777.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Rustikální snídaně s vejci, chlebem a kávou"/><img src="https://images.pexels.com/photos/5720783/pexels-photo-5720783.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Jednoduchá snídaně na dřevěném stole"/></div><div className="gh5BreakfastBottom"><strong>Snídaně 8:00–10:00</strong><span>V případě časného odjezdu lze předem domluvit balíček s sebou.</span></div></div></section>

      <section className="gh5Review"><div className="gh5Wrap gh5ReviewInner"><div className="gh5Score"><strong>9,4</strong><span>/ 10 · UKÁZKOVÉ HODNOCENÍ</span></div><div><p className="gh5Quote">„Klidné místo, výborná snídaně a dobrá poloha na výlety na kole.“</p><div className="gh5QuoteBy">MARTINA K. · DEMO RECENZE</div><div className="gh5ReviewRow"><p>„Pokoj byl čistý, postel pohodlná a večer byl na zahradě opravdu klid.“</p><p>„Do Třeboně jsme dojeli za pár minut a kola jsme mohli nechat zamčená přímo u domu.“</p></div><span className="gh5DemoLabel">Hodnocení je součástí fiktivního konceptu.</span></div></div></section>

      <section className="gh5Owners"><div className="gh5Wrap gh5OwnersGrid"><div className="gh5OwnersText"><h2>Jana a Petr.</h2><p>O penzion se starají od roku 2018. Jana řeší pobyty a snídaně, Petr dům, zahradu a kola.</p></div><div className="gh5OwnersPhoto"><img src="https://images.pexels.com/photos/6848255/pexels-photo-6848255.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Starší pár při přípravě jídla v útulné domácí kuchyni"/></div></div></section>

      <section className="gh5Practical" id="prakticke"><div className="gh5Wrap gh5PracticalGrid"><div className="gh5PracticalIntro"><h2>Praktické informace.</h2><p>Věci, které je dobré vědět před pobytem nebo příjezdem.</p></div><div className="gh5PracticalList">{practical.map(([label,value])=><div className="gh5PracticalRow" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section>

      <section className="gh5MapSection"><div className="gh5Wrap gh5MapGrid"><div className="gh5Map" aria-label="Ilustrační mapa příjezdu"><div className="gh5Road"/><div className="gh5Road2"/></div><div className="gh5MapCopy"><div><div className="gh5Meta gh5Muted">PŘÍJEZD</div><h2>U Tiché vody · Třeboňsko</h2><p>Penzion leží v klidné obci osm kilometrů od Třeboně. Parkování je přímo u domu, příjezd je možný autem i na kole.</p></div><div className="gh5MapDetails"><span><MapPin size={14}/> Třeboňsko · 8 km od Třeboně</span><span><Car size={14}/> parkování u domu</span><a href="tel:+420705911941"><Phone size={14}/> +420 705 911 941</a><a href="mailto:kontakt@spustweb.cz"><Mail size={14}/> kontakt@spustweb.cz</a></div></div></div></section>

      <section className="gh5Enquiry" id="poptavka"><div className="gh5Wrap"><div className="gh5EnquiryHead"><h2>Poptávka pobytu.</h2><p>Napište předběžný termín, počet hostů a kontakt. Provozovatel následně potvrdí, zda je vhodný pokoj volný a jaká bude cena pobytu.</p></div><div className="gh5EnquiryGrid"><form className="gh5Form"><div className="gh5Field"><label htmlFor="gh5-name">Jméno</label><input id="gh5-name" type="text" placeholder="Vaše jméno"/></div><div className="gh5Field"><label htmlFor="gh5-contact">Telefon nebo e-mail</label><input id="gh5-contact" type="text" placeholder="Jak vás můžeme kontaktovat"/></div><div className="gh5Field"><label htmlFor="gh5-arrival">Příjezd</label><input id="gh5-arrival" type="text" placeholder="Např. 12. 9. 2026"/></div><div className="gh5Field"><label htmlFor="gh5-departure">Odjezd</label><input id="gh5-departure" type="text" placeholder="Např. 15. 9. 2026"/></div><div className="gh5Field"><label htmlFor="gh5-guests">Hosté</label><select id="gh5-guests" defaultValue="2 osoby"><option>1 osoba</option><option>2 osoby</option><option>3 osoby</option><option>4 osoby</option></select></div><div className="gh5Field"><label htmlFor="gh5-message">Poznámka</label><textarea id="gh5-message" placeholder="Pokoj, pes, dětská postýlka nebo další informace"/></div><button type="button">Odeslat poptávku</button><div className="gh5FormNote">Ukázkový formulář na této demonstrační stránce se neodesílá.</div></form><div className="gh5Direct"><h3>Nebo přímo.</h3><a href="tel:+420705911941"><Phone size={15}/> +420 705 911 941</a><a href="mailto:kontakt@spustweb.cz"><Mail size={15}/> kontakt@spustweb.cz</a><p>Kontaktní údaje v této ukázce vedou na SpustWeb.cz. Penzion U Tiché vody je fiktivní koncept.</p></div></div></div></section>

      <footer className="gh5Footer"><div className="gh5Wrap gh5FooterInner"><div><strong>U Tiché vody</strong><br/>Fiktivní penzion vytvořený pouze jako ukázkový koncept.</div><div className="gh5FooterRight">Tento koncept vytvořil <a href="/">SpustWeb.cz</a><a className="gh5FooterCta" href="/#kontakt">Web pro moje podnikání</a></div></div></footer>
    </div>
  )
}
