import type { Metadata } from 'next'
import { ArrowRight, Bike, CalendarDays, Car, Clock3, Coffee, MapPin, PawPrint, Phone, Wifi } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro penzion | SpustWeb.cz',
  description: 'Ukázka webu pro menší penzion: pokoje, vybavení, snídaně, okolí, praktické informace a rezervace pobytu.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/penzion/' },
  robots: { index: true, follow: true },
}

const rooms = [
  {
    name: 'Pokoj U zahrady',
    meta: '2 hosté · 24 m² · manželská postel',
    price: 'od 2 190 Kč / noc',
    text: 'Pokoj v přízemí s okny do zahrady. Vlastní koupelna, malá lednice a místo k posezení.',
    image: 'https://images.pexels.com/photos/15699340/pexels-photo-15699340.jpeg?auto=compress&cs=tinysrgb&w=1800',
    alt: 'Útulný dvoulůžkový pokoj s dřevěnými trámy a světlým povlečením',
  },
  {
    name: 'Pokoj Pod střechou',
    meta: '2 hosté · 28 m² · manželská postel',
    price: 'od 2 390 Kč / noc',
    text: 'Prostornější pokoj v podkroví. Dřevěné trámy, koupelna se sprchou a výhled do dvora.',
    image: 'https://images.pexels.com/photos/11933083/pexels-photo-11933083.jpeg?auto=compress&cs=tinysrgb&w=1800',
    alt: 'Světlý pokoj v podkroví s dřevěnými trámy a bílou postelí',
  },
  {
    name: 'Rodinný pokoj',
    meta: '2–4 hosté · 36 m² · dvě lůžkové části',
    price: 'od 3 090 Kč / noc',
    text: 'Dvě navazující části pro rodiče a děti. Vlastní koupelna, úložný prostor a dost místa i na delší pobyt.',
    image: 'https://images.pexels.com/photos/28297757/pexels-photo-28297757.jpeg?auto=compress&cs=tinysrgb&w=1800',
    alt: 'Rodinný pokoj s dřevěnými trámy a dvěma lůžky',
  },
]

const practical = [
  ['Check-in', '15:00–19:00'],
  ['Check-out', 'do 10:30'],
  ['Snídaně', '8:00–10:00'],
  ['Parkování', 'zdarma u domu'],
  ['Kola', 'uzamykatelná kolárna'],
  ['Pes', 'po předchozí dohodě'],
]

export default function GuesthouseShowcase() {
  return (
    <div className="penPage" id="top">
      <style>{`
        body:has(.penPage) > .verno-nav-shell,body:has(.penPage) > .footer{display:none!important}
        body:has(.penPage) main{padding:0!important;margin:0!important}
        body:has(.penPage){background:#f3f0e8!important}
        .penPage{--ink:#24251f;--paper:#f3f0e8;--paper2:#e8e4d8;--sage:#7b8468;--sageD:#4c5440;--rust:#a65d3f;--line:rgba(36,37,31,.18);font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--paper)}
        .penPage *{box-sizing:border-box}.penPage a{color:inherit;text-decoration:none}.penPage img{display:block;width:100%}.penWrap{width:min(1240px,calc(100% - 52px));margin:0 auto}.penSerif{font-family:Georgia,'Times New Roman',serif}.penKicker{font-size:10px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;color:var(--sageD)}
        .penDemo{min-height:25px;padding:5px 12px;background:#22251f;color:#d9d9d2;display:flex;justify-content:center;align-items:center;font-size:9px;font-weight:700;letter-spacing:.09em;text-transform:uppercase}.penDemo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .penNavShell{position:sticky;top:0;z-index:120;background:rgba(243,240,232,.94);backdrop-filter:blur(14px);border-bottom:1px solid rgba(36,37,31,.12)}.penNav{height:72px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:24px}.penBrand{font-family:Georgia,'Times New Roman',serif;font-size:22px;font-style:italic}.penLinks{display:flex;gap:28px;font-size:11px;font-weight:700}.penLinks a{position:relative}.penLinks a:after{content:'';position:absolute;height:1px;left:0;right:100%;bottom:-7px;background:var(--rust);transition:right .2s}.penLinks a:hover:after{right:0}.penNavRight{justify-self:end;display:flex;align-items:center;gap:12px}.penPhone{font-size:11px;font-weight:700}.penReserve{min-height:38px;padding:0 15px;display:inline-flex;align-items:center;gap:7px;background:var(--ink);color:#fff!important;font-size:10px;font-weight:800}

        .penHero{position:relative;height:min(820px,calc(100svh - 97px));min-height:650px;overflow:hidden;background:#6f7569;color:#fff}.penHero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 52%;filter:saturate(.78) contrast(1.02) brightness(.76)}.penHero:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(20,24,19,.18) 0%,rgba(20,24,19,.12) 45%,rgba(20,24,19,.68) 100%),linear-gradient(90deg,rgba(20,24,19,.32),transparent 60%)}.penHeroInner{position:relative;z-index:2;height:100%;display:flex;flex-direction:column;justify-content:flex-end;padding-bottom:94px}.penHeroCopy{max-width:780px}.penHero .penKicker{color:#f3efe2;margin-bottom:17px}.penHero h1{font-family:Georgia,'Times New Roman',serif;font-size:clamp(56px,7vw,94px);font-weight:400;line-height:.91;letter-spacing:-.045em;margin:0 0 20px;max-width:780px}.penHeroLead{font-size:14px;line-height:1.6;max-width:590px;color:#f0eee6;margin:0}.penHeroMark{position:absolute;right:26px;top:26px;font-family:Georgia,'Times New Roman',serif;font-style:italic;font-size:16px;color:#f3efe8}
        .penBookingFloat{position:absolute;z-index:3;left:50%;bottom:0;transform:translate(-50%,50%);width:min(1050px,calc(100% - 52px));display:grid;grid-template-columns:1fr 1fr .8fr auto;background:#fff;color:var(--ink);box-shadow:0 18px 45px rgba(31,34,28,.14)}.penBookField{min-height:86px;padding:19px 22px;border-right:1px solid var(--line);display:flex;flex-direction:column;justify-content:center}.penBookField small{font-size:8.5px;text-transform:uppercase;letter-spacing:.12em;color:#777a70;margin-bottom:7px}.penBookField strong{font-family:Georgia,'Times New Roman',serif;font-size:18px;font-weight:400}.penBookBtn{border:0;background:var(--sageD);color:#fff;min-width:180px;padding:0 20px;font-size:10px;font-weight:800;display:flex;align-items:center;justify-content:center;gap:8px}

        .penFacts{padding:92px 0 42px}.penFactsInner{display:flex;justify-content:center;gap:42px;flex-wrap:wrap;font-size:11px}.penFactsInner span{display:flex;align-items:center;gap:8px}.penFactsInner svg{color:var(--sageD)}

        .penRooms{padding:54px 0 84px}.penRoomsIntro{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:end;margin-bottom:50px}.penRoomsIntro h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(48px,6vw,78px);font-weight:400;line-height:.93;letter-spacing:-.045em;margin:10px 0 0}.penRoomsIntro p{max-width:510px;font-size:13px;line-height:1.65;color:#5e6259;margin:0 0 8px}
        .penRoom{display:grid;grid-template-columns:1.24fr .76fr;gap:54px;align-items:center;margin:0 0 86px}.penRoom:nth-child(even){grid-template-columns:.76fr 1.24fr}.penRoom:nth-child(even) .penRoomImage{order:2}.penRoomImage{position:relative;aspect-ratio:1.48/1;overflow:hidden;background:#ddd}.penRoomImage img{width:100%;height:100%;object-fit:cover;filter:saturate(.78)}.penRoomIndex{position:absolute;left:16px;top:14px;width:42px;height:42px;border-radius:50%;background:rgba(243,240,232,.92);display:grid;place-items:center;font-size:10px;font-weight:800}.penRoomCopy{max-width:430px}.penRoomCopy h3{font-family:Georgia,'Times New Roman',serif;font-size:38px;font-weight:400;line-height:1;margin:8px 0 12px;letter-spacing:-.025em}.penRoomMeta{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#75796f;margin-bottom:18px}.penRoomCopy p{font-size:12px;line-height:1.65;color:#555b52;margin:0 0 20px}.penRoomBottom{border-top:1px solid var(--line);padding-top:14px;display:flex;justify-content:space-between;align-items:center;gap:20px}.penRoomBottom strong{font-size:12px}.penTextLink{font-size:10px;font-weight:800;display:inline-flex;align-items:center;gap:6px;border-bottom:1px solid var(--ink);padding-bottom:3px}

        .penIncluded{background:var(--sageD);color:#fff;padding:42px 0}.penIncludedInner{display:grid;grid-template-columns:220px repeat(5,1fr);align-items:start;gap:22px}.penIncludedTitle{font-family:Georgia,'Times New Roman',serif;font-size:30px;line-height:1.05}.penAmenity{border-left:1px solid rgba(255,255,255,.28);padding-left:18px}.penAmenity strong{display:block;font-size:11px;margin-bottom:5px}.penAmenity span{font-size:9.5px;line-height:1.45;color:#d8ddd3}

        .penPlace{padding:92px 0 88px;overflow:hidden}.penPlaceTop{display:grid;grid-template-columns:1fr .72fr;gap:80px;align-items:end;margin-bottom:46px}.penPlaceTop h2{font-family:Georgia,'Times New Roman',serif;font-weight:400;font-size:clamp(54px,6.5vw,88px);line-height:.9;letter-spacing:-.045em;margin:10px 0 0}.penPlaceTop p{font-size:13px;line-height:1.65;color:#5f645b;max-width:450px;margin:0 0 8px}.penPlaceCollage{display:grid;grid-template-columns:1.25fr .75fr;grid-template-rows:280px 280px;gap:12px}.penPlaceMain{grid-row:1/3;position:relative;overflow:hidden}.penPlaceMain img,.penPlaceSmall img{width:100%;height:100%;object-fit:cover;filter:saturate(.8)}.penPlaceSmall{overflow:hidden}.penPlaceCaption{position:absolute;left:22px;bottom:20px;background:rgba(243,240,232,.94);padding:12px 15px;font-size:10px;max-width:280px}.penTrips{margin-top:38px;display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line)}.penTrip{padding:20px 28px 0 0}.penTrip+.penTrip{border-left:1px solid var(--line);padding-left:28px}.penTrip strong{font-family:Georgia,'Times New Roman',serif;font-size:20px;font-weight:400;display:block;margin-bottom:6px}.penTrip span{font-size:10px;color:#666c62;line-height:1.5}

        .penBreakfast{position:relative;min-height:650px;overflow:hidden;color:#fff;background:#73695a}.penBreakfast img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.82) brightness(.72)}.penBreakfast:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(35,29,23,.72),rgba(35,29,23,.12) 70%)}.penBreakfastInner{position:relative;z-index:2;min-height:650px;display:flex;align-items:center}.penBreakfastCopy{max-width:530px}.penBreakfast .penKicker{color:#efe8da}.penBreakfast h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(54px,6vw,82px);font-weight:400;line-height:.9;letter-spacing:-.045em;margin:13px 0 18px}.penBreakfast p{font-size:13px;line-height:1.65;color:#f1ece3;max-width:500px}.penBreakfastTime{display:inline-block;margin-top:17px;border-top:1px solid rgba(255,255,255,.5);padding-top:10px;font-size:10px;font-weight:800}

        .penReview{padding:88px 0;background:#ded8c9}.penReviewGrid{display:grid;grid-template-columns:.65fr 1.35fr;gap:70px}.penScore strong{font-family:Georgia,'Times New Roman',serif;font-size:102px;font-weight:400;line-height:.8;letter-spacing:-.06em}.penScore span{display:block;font-size:9.5px;color:#6d7067;margin-top:10px}.penQuote{font-family:Georgia,'Times New Roman',serif;font-size:clamp(30px,3.7vw,48px);line-height:1.12;letter-spacing:-.025em;margin:0}.penQuoteBy{margin-top:20px;font-size:9px;text-transform:uppercase;letter-spacing:.09em;color:#6a6d65}.penMiniReviews{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin-top:36px;padding-top:24px;border-top:1px solid var(--line)}.penMiniReviews p{font-size:11px;line-height:1.6;color:#555a52;margin:0}.penDemoLabel{display:inline-block;margin-top:22px;font-size:8.5px;border:1px solid rgba(36,37,31,.3);padding:5px 7px;color:#696d64}

        .penOwners{padding:92px 0}.penOwnersGrid{display:grid;grid-template-columns:.78fr 1.22fr;gap:78px;align-items:center}.penOwnersText h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(46px,5vw,68px);font-weight:400;line-height:.92;letter-spacing:-.04em;margin:12px 0 18px}.penOwnersText p{font-size:13px;line-height:1.7;color:#555b52;max-width:500px;margin:0}.penOwnersPhoto{position:relative;aspect-ratio:1.25/1;overflow:hidden}.penOwnersPhoto img{width:100%;height:100%;object-fit:cover;filter:saturate(.72)}.penOwnersNote{position:absolute;right:18px;bottom:18px;background:var(--paper);padding:11px 13px;font-size:9px}

        .penPractical{padding:70px 0;background:#fff}.penPracticalHead{display:flex;justify-content:space-between;gap:40px;align-items:end;margin-bottom:34px}.penPracticalHead h2{font-family:Georgia,'Times New Roman',serif;font-size:48px;font-weight:400;line-height:.95;margin:8px 0 0}.penPracticalHead p{font-size:11px;color:#62675e;max-width:450px;line-height:1.55}.penPracticalRows{border-top:1px solid var(--line)}.penPracticalRow{display:grid;grid-template-columns:1fr 1fr;min-height:64px;align-items:center;border-bottom:1px solid var(--line)}.penPracticalRow strong{font-size:11px}.penPracticalRow span{font-family:Georgia,'Times New Roman',serif;font-size:18px}

        .penArrival{padding:82px 0;background:#e8e5dc}.penArrivalGrid{display:grid;grid-template-columns:.68fr 1.32fr;gap:14px}.penArrivalCopy{background:var(--paper);padding:36px}.penArrivalCopy h2{font-family:Georgia,'Times New Roman',serif;font-size:40px;line-height:.95;font-weight:400;margin:10px 0 20px}.penArrivalRows{display:grid;gap:14px}.penArrivalRow{display:flex;gap:10px;align-items:flex-start}.penArrivalRow svg{margin-top:2px;flex-shrink:0}.penArrivalRow strong{display:block;font-size:10px}.penArrivalRow span{font-size:9.5px;line-height:1.45;color:#6c7068}.penMap{position:relative;min-height:390px;background:#d7ddd2;overflow:hidden}.penMap:before{content:'';position:absolute;inset:-10%;background:repeating-linear-gradient(28deg,transparent 0 54px,#c3cbbf 55px 57px),repeating-linear-gradient(115deg,transparent 0 84px,#c7cec2 85px 87px)}.penMap:after{content:'';position:absolute;width:22px;height:22px;border:7px solid var(--rust);border-radius:50% 50% 50% 0;transform:rotate(-45deg);left:56%;top:45%;background:var(--paper)}.penMapTag{position:absolute;left:22px;bottom:20px;background:var(--ink);color:#fff;padding:10px 12px;font-size:9px;font-weight:800}

        .penFinal{position:relative;min-height:700px;color:#fff;overflow:hidden;background:#554f45}.penFinal img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.75) brightness(.64)}.penFinal:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(28,29,23,.12),rgba(28,29,23,.64))}.penFinalInner{position:relative;z-index:2;min-height:700px;display:flex;flex-direction:column;justify-content:space-between;padding-top:58px;padding-bottom:54px}.penFinal h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(58px,7vw,94px);font-weight:400;line-height:.9;letter-spacing:-.05em;max-width:760px;margin:12px 0 0}.penFinalBooking{align-self:flex-end;width:min(760px,100%);background:rgba(243,240,232,.96);color:var(--ink);display:grid;grid-template-columns:1fr 1fr .8fr auto}.penFinalField{padding:18px 20px;border-right:1px solid var(--line)}.penFinalField small{display:block;font-size:8px;text-transform:uppercase;letter-spacing:.1em;color:#75786f;margin-bottom:6px}.penFinalField strong{font-family:Georgia,'Times New Roman',serif;font-size:16px;font-weight:400}.penFinalBtn{border:0;background:var(--rust);color:#fff;min-width:160px;font-size:10px;font-weight:800}.penFinalNote{align-self:flex-end;margin-top:12px;font-size:9.5px;color:#ece9e1}.penFinalNote a{text-decoration:underline;text-underline-offset:3px}
        .penFooter{background:#22251f;color:#c7cbc3}.penFooterInner{min-height:118px;padding:26px 0;display:grid;grid-template-columns:1fr auto;gap:30px;align-items:center;font-size:9.5px}.penFooter strong{font-family:Georgia,'Times New Roman',serif;font-size:17px;font-weight:400;color:#fff}.penFooterRight{display:flex;align-items:center;gap:16px}.penFooterRight a{text-decoration:underline;text-underline-offset:3px}.penFooterCta{border:1px solid #5b6056;padding:10px 12px;text-decoration:none!important;color:#fff!important;font-weight:800}

        @media(max-width:980px){.penWrap{width:min(100% - 34px,1240px)}.penNav{grid-template-columns:1fr auto}.penLinks{display:none}.penBookingFloat{width:min(900px,calc(100% - 34px))}.penRoomsIntro,.penPlaceTop,.penOwnersGrid{gap:40px}.penIncludedInner{grid-template-columns:180px repeat(3,1fr)}.penIncludedInner .penAmenity:nth-child(n+5){margin-top:20px}.penPlaceCollage{grid-template-rows:240px 240px}.penReviewGrid{gap:40px}.penFinalBooking{width:100%}}
        @media(max-width:720px){.penWrap{width:min(100% - 26px,1240px)}.penDemo{font-size:8px;text-align:center;line-height:1.35}.penNav{height:62px}.penPhone{display:none}.penHero{height:690px;min-height:0}.penHeroInner{padding-bottom:142px}.penHero h1{font-size:clamp(50px,15vw,70px)}.penBookingFloat{grid-template-columns:1fr 1fr;bottom:0;transform:translate(-50%,58%)}.penBookField{min-height:68px;padding:13px}.penBookBtn{min-height:52px;grid-column:1/-1}.penFacts{padding-top:150px}.penFactsInner{justify-content:flex-start;gap:16px 26px}.penRoomsIntro,.penPlaceTop,.penReviewGrid,.penOwnersGrid{grid-template-columns:1fr;gap:20px}.penRoom,.penRoom:nth-child(even){grid-template-columns:1fr;gap:22px;margin-bottom:58px}.penRoom:nth-child(even) .penRoomImage{order:0}.penRoomImage{aspect-ratio:1.25/1}.penIncludedInner{grid-template-columns:1fr 1fr;gap:26px 14px}.penIncludedTitle{grid-column:1/-1;margin-bottom:8px}.penAmenity{padding-left:12px}.penPlaceCollage{grid-template-columns:1fr;grid-template-rows:360px 220px 220px}.penPlaceMain{grid-row:auto}.penTrips{grid-template-columns:1fr}.penTrip,.penTrip+.penTrip{border-left:0;border-bottom:1px solid var(--line);padding:18px 0}.penBreakfast,.penBreakfastInner{min-height:590px}.penScore strong{font-size:84px}.penMiniReviews{grid-template-columns:1fr}.penOwnersPhoto{order:-1}.penPracticalHead{display:block}.penPracticalRow{grid-template-columns:.8fr 1.2fr}.penArrivalGrid{grid-template-columns:1fr}.penMap{min-height:330px}.penFinal,.penFinalInner{min-height:650px}.penFinalBooking{grid-template-columns:1fr 1fr}.penFinalBtn{grid-column:1/-1;min-height:50px}.penFooterInner{grid-template-columns:1fr}.penFooterRight{flex-wrap:wrap}}
      `}</style>

      <div className="penDemo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNÝ PENZION <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>

      <div className="penNavShell"><div className="penWrap"><nav className="penNav" aria-label="Navigace ukázkového penzionu"><a className="penBrand" href="#top">U Tiché vody</a><div className="penLinks"><a href="#pokoje">Pokoje</a><a href="#okoli">Okolí</a><a href="#snidane">Snídaně</a><a href="#informace">Informace</a><a href="#kontakt">Kontakt</a></div><div className="penNavRight"><a className="penPhone" href="tel:+420777000000">777 000 000</a><a className="penReserve" href="#rezervace">Rezervace <ArrowRight size={12}/></a></div></nav></div></div>

      <header className="penHero">
        <img src="https://images.pexels.com/photos/15699340/pexels-photo-15699340.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Pokoj venkovského penzionu s dřevěnými trámy"/>
        <div className="penHeroMark">U Tiché vody · Třeboňsko</div>
        <div className="penWrap penHeroInner"><div className="penHeroCopy"><div className="penKicker">PENZION · TŘEBOŇSKO</div><h1>Pár dní v klidu mezi rybníky.</h1><p className="penHeroLead">Osm pokojů v opraveném venkovském domě. Snídaně v ceně, zahrada, kolárna a Třeboň deset minut autem.</p></div></div>
        <div className="penBookingFloat" id="rezervace"><div className="penBookField"><small>Příjezd</small><strong>Vybrat datum</strong></div><div className="penBookField"><small>Odjezd</small><strong>Vybrat datum</strong></div><div className="penBookField"><small>Hosté</small><strong>2 osoby</strong></div><button className="penBookBtn" type="button">Zjistit dostupnost <CalendarDays size={14}/></button></div>
      </header>

      <section className="penFacts"><div className="penWrap penFactsInner"><span><Coffee size={14}/> snídaně v ceně</span><span><Car size={14}/> parkování u domu</span><span><Bike size={14}/> uzamykatelná kolárna</span><span><Wifi size={14}/> Wi-Fi v pokojích i zahradě</span><span><MapPin size={14}/> Třeboň 8 km</span></div></section>

      <section className="penRooms" id="pokoje"><div className="penWrap"><div className="penRoomsIntro"><div><div className="penKicker">POKOJE</div><h2>Vyberte si pokoj.</h2></div><p>Každý pokoj má vlastní koupelnu. Cena zahrnuje snídani, parkování a využití kolárny. Níže jsou tři ukázkové typy z celkem osmi pokojů.</p></div>{rooms.map((room,index)=><article className="penRoom" key={room.name}><div className="penRoomImage"><img src={room.image} alt={room.alt}/><span className="penRoomIndex">0{index+1}</span></div><div className="penRoomCopy"><div className="penKicker">{room.meta}</div><h3>{room.name}</h3><div className="penRoomMeta">vlastní koupelna · snídaně v ceně</div><p>{room.text}</p><div className="penRoomBottom"><strong>{room.price}</strong><a className="penTextLink" href="#rezervace">Dostupnost <ArrowRight size={12}/></a></div></div></article>)}</div></section>

      <section className="penIncluded"><div className="penWrap penIncludedInner"><div className="penIncludedTitle">V ceně pobytu</div><div className="penAmenity"><strong>Snídaně</strong><span>každé ráno 8:00–10:00</span></div><div className="penAmenity"><strong>Parkování</strong><span>zdarma přímo u domu</span></div><div className="penAmenity"><strong>Wi-Fi</strong><span>v pokojích i na zahradě</span></div><div className="penAmenity"><strong>Kolárna</strong><span>uzamykatelná místnost pro kola</span></div><div className="penAmenity"><strong>Zahrada</strong><span>posezení pro hosty za domem</span></div></div></section>

      <section className="penPlace" id="okoli"><div className="penWrap"><div className="penPlaceTop"><div><div className="penKicker">TŘEBOŇSKO</div><h2>Za domem začínají rybníky a cyklostezky.</h2></div><p>Penzion stojí v malé obci osm kilometrů od Třeboně. Na kolo můžete vyjet rovnou od domu, autem jste v centru přibližně za deset minut.</p></div><div className="penPlaceCollage"><div className="penPlaceMain"><img src="https://images.pexels.com/photos/32177623/pexels-photo-32177623.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Venkovská zahrada u menšího domu"/><div className="penPlaceCaption">Zahrada je za domem a je k dispozici pouze ubytovaným hostům.</div></div><div className="penPlaceSmall"><img src="https://images.pexels.com/photos/6768765/pexels-photo-6768765.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Venkovský dům obklopený zelení"/></div><div className="penPlaceSmall"><img src="https://images.pexels.com/photos/36922140/pexels-photo-36922140.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Venkovská krajina a dům mezi poli"/></div></div><div className="penTrips"><div className="penTrip"><strong>Třeboň · 8 km</strong><span>historické centrum, zámek, restaurace a lázně</span></div><div className="penTrip"><strong>Rožmberk · 12 km</strong><span>cyklotrasa kolem největšího českého rybníka</span></div><div className="penTrip"><strong>Chlum u Třeboně · 14 km</strong><span>koupání, lesy a další trasy směrem k rakouské hranici</span></div></div></div></section>

      <section className="penBreakfast" id="snidane"><img src="https://images.pexels.com/photos/16471875/pexels-photo-16471875.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Snídaně s čerstvým chlebem na dřevěném stole"/><div className="penWrap penBreakfastInner"><div className="penBreakfastCopy"><div className="penKicker">SNÍDANĚ</div><h2>Ráno začíná u jednoho stolu.</h2><p>Pečivo z místní pekárny, vejce, sýry, šunka, jogurt, ovoce, něco sladkého, káva a čaj. Snídaně je součástí ceny pokoje.</p><span className="penBreakfastTime">8:00–10:00 · každý den</span></div></div></section>

      <section className="penReview"><div className="penWrap penReviewGrid"><div className="penScore"><strong>9,4</strong><span>/ 10 · ukázkové hodnocení</span></div><div><blockquote className="penQuote">„Klidné místo, výborná snídaně a perfektní poloha na výlety na kole.“</blockquote><div className="penQuoteBy">Jana P. · Booking / demo</div><div className="penMiniReviews"><p>„Pokoj byl čistý, večer byl na zahradě úplný klid a do Třeboně jsme dojeli za pár minut.“</p><p>„Kola jsme nechali přes noc v kolárně. Majitelé nám doporučili trasu, kterou jsme vůbec neznali.“</p></div><span className="penDemoLabel">Hodnocení je součástí fiktivního konceptu. Nejde o skutečná zákaznická data.</span></div></div></section>

      <section className="penOwners"><div className="penWrap penOwnersGrid"><div className="penOwnersText"><div className="penKicker">KDO SE O PENZION STARÁ</div><h2>Jana a Petr.</h2><p>Dům opravili v roce 2018. Jana připravuje snídaně a stará se o rezervace, Petr o dům, zahradu a kola hostů. Bydlí ve vedlejší části domu.</p></div><div className="penOwnersPhoto"><img src="https://images.pexels.com/photos/7911382/pexels-photo-7911382.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Dva lidé připravují stůl v domácí kuchyni"/><span className="penOwnersNote">Jana & Petr · majitelé penzionu / demo</span></div></div></section>

      <section className="penPractical" id="informace"><div className="penWrap"><div className="penPracticalHead"><div><div className="penKicker">PŘED PŘÍJEZDEM</div><h2>Praktické informace.</h2></div><p>Při zrušení pobytu více než 7 dní před příjezdem se storno neúčtuje. U pozdějšího zrušení se účtuje první noc.</p></div><div className="penPracticalRows">{practical.map(([label,value])=><div className="penPracticalRow" key={label}><strong>{label}</strong><span>{value}</span></div>)}</div></div></section>

      <section className="penArrival" id="kontakt"><div className="penWrap penArrivalGrid"><div className="penArrivalCopy"><div className="penKicker">PŘÍJEZD</div><h2>U Tiché vody · Třeboňsko</h2><div className="penArrivalRows"><div className="penArrivalRow"><MapPin size={15}/><div><strong>Nová Ves 28, Třeboňsko</strong><span>ukázková adresa fiktivního penzionu</span></div></div><div className="penArrivalRow"><Car size={15}/><div><strong>Parkování u domu</strong><span>bez rezervace a bez příplatku</span></div></div><div className="penArrivalRow"><Phone size={15}/><div><strong>777 000 000</strong><span>denně 8:00–19:00</span></div></div><div className="penArrivalRow"><Clock3 size={15}/><div><strong>Příjezd 15:00–19:00</strong><span>pozdější příjezd po předchozí domluvě</span></div></div></div></div><div className="penMap" aria-label="Ilustrační mapa příjezdu"><span className="penMapTag">PENZION U TICHÉ VODY · DEMO MAPA</span></div></div></section>

      <section className="penFinal"><img src="https://images.pexels.com/photos/37250181/pexels-photo-37250181.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Pokoj venkovského ubytování v měkkém večerním světle"/><div className="penWrap penFinalInner"><div><div className="penKicker" style={{color:'#fff'}}>REZERVACE</div><h2>Vyberte termín pobytu.</h2></div><div><div className="penFinalBooking"><div className="penFinalField"><small>Příjezd</small><strong>Vybrat datum</strong></div><div className="penFinalField"><small>Odjezd</small><strong>Vybrat datum</strong></div><div className="penFinalField"><small>Hosté</small><strong>2 osoby</strong></div><button className="penFinalBtn" type="button">Zjistit dostupnost</button></div><div className="penFinalNote">Nemáte pevný termín? <a href="tel:+420777000000">Zavolejte 777 000 000</a></div></div></div></section>

      <footer className="penFooter"><div className="penWrap penFooterInner"><div><strong>U Tiché vody</strong><br/>Fiktivní penzion vytvořený pouze jako ukázkový koncept.</div><div className="penFooterRight">Tento koncept vytvořil <a href="/">SpustWeb.cz</a><a className="penFooterCta" href="/#kontakt">Web pro moje podnikání</a></div></div></footer>
    </div>
  )
}
