import type { Metadata } from 'next'
import { ArrowRight, Bike, CalendarDays, Car, Coffee, MapPin, PawPrint, Phone, Wifi } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro penzion | SpustWeb.cz',
  description: 'Ukázka webu pro menší penzion: pokoje, vybavení, snídaně, okolí, praktické informace a rezervace pobytu.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/penzion/' },
  robots: { index: true, follow: true },
}

const rooms = [
  {
    no: '01',
    name: 'Pokoj U zahrady',
    meta: '2 hosté · 24 m²',
    price: 'od 2 190 Kč / noc',
    text: 'Pokoj v přízemí s okny do zahrady. Vlastní koupelna, malá lednice a místo k posezení.',
    image: 'https://images.pexels.com/photos/15699340/pexels-photo-15699340.jpeg?auto=compress&cs=tinysrgb&w=1800',
    alt: 'Dvoulůžkový pokoj s dřevěnými trámy, kamennou stěnou a modrými detaily',
  },
  {
    no: '02',
    name: 'Pokoj Pod střechou',
    meta: '2 hosté · 28 m²',
    price: 'od 2 390 Kč / noc',
    text: 'Prostornější pokoj v podkroví. Dřevěné trámy, koupelna se sprchou a výhled do dvora.',
    image: 'https://images.pexels.com/photos/15692793/pexels-photo-15692793.jpeg?auto=compress&cs=tinysrgb&w=1800',
    alt: 'Pokoj se světlým povlečením, dřevěnými trámy a modrým čelem postele',
  },
  {
    no: '03',
    name: 'Rodinný pokoj',
    meta: '2–4 hosté · 36 m²',
    price: 'od 3 090 Kč / noc',
    text: 'Větší pokoj pro rodiče s dětmi. Vlastní koupelna, úložný prostor a dost místa i na delší pobyt.',
    image: 'https://images.pexels.com/photos/15692794/pexels-photo-15692794.jpeg?auto=compress&cs=tinysrgb&w=1800',
    alt: 'Světlý rustikální pokoj s dřevěnými trámy, modrými dveřmi a bílým povlečením',
  },
]

const practical = [
  ['Check-in', '15:00–19:00'],
  ['Check-out', 'do 10:30'],
  ['Snídaně', '8:00–10:00'],
  ['Parkování', 'zdarma u domu'],
  ['Kola', 'uzamykatelná kolárna'],
  ['Pes', 'po předchozí dohodě'],
]

const trebonTrail = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Okolo_T%C5%99ebon%C4%9B_%28educational_trail%29_between_Sv%C4%9Bt_and_Opatovick%C3%BD_rybn%C3%ADk_01.jpg?width=1500'
const trebonTown = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/T%C5%99ebo%C5%88%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg?width=1200'
const rozmberek = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rybn%C3%ADk_Ro%C5%BEmberk.jpg?width=1200'

export default function GuesthouseShowcase() {
  return (
    <div className="gh4" id="top">
      <style>{`
        body:has(.gh4) > .verno-nav-shell,body:has(.gh4) > .footer{display:none!important}
        body:has(.gh4) main{padding:0!important;margin:0!important}
        body:has(.gh4){background:#f7f7f4!important}
        .gh4{--ink:#17231f;--forest:#17372f;--forest2:#21483d;--white:#f7f7f4;--paper:#fff;--blue:#dfe9e8;--wine:#8a4351;--line:rgba(23,35,31,.16);font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--white)}
        .gh4 *{box-sizing:border-box}.gh4 a{color:inherit;text-decoration:none}.gh4 img{display:block;width:100%}.gh4Wrap{width:min(1280px,calc(100% - 54px));margin:0 auto}.gh4Meta{font-size:9px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.gh4Muted{color:#6d746f}
        .gh4Demo{min-height:24px;padding:5px 12px;background:#0f1a17;color:#cfd7d2;display:flex;justify-content:center;align-items:center;font-size:8.5px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.gh4Demo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .gh4NavShell{position:sticky;top:0;z-index:150;background:rgba(23,55,47,.95);backdrop-filter:blur(14px);color:#fff;border-bottom:1px solid rgba(255,255,255,.12)}.gh4Nav{height:64px;display:grid;grid-template-columns:1fr auto;align-items:center;gap:28px}.gh4Brand{display:flex;align-items:baseline;gap:14px}.gh4Brand strong{font-family:Georgia,'Times New Roman',serif;font-size:22px;font-weight:400;font-style:italic}.gh4Brand span{font-size:8px;letter-spacing:.13em;text-transform:uppercase;color:#b9c7c0}.gh4NavRight{display:flex;align-items:center;gap:26px}.gh4Links{display:flex;gap:24px;font-size:10px;font-weight:700}.gh4Links a{opacity:.82}.gh4Links a:hover{opacity:1}.gh4BookSmall{min-height:36px;padding:0 14px;background:#fff;color:var(--forest)!important;display:inline-flex;align-items:center;gap:7px;font-size:9.5px;font-weight:900}
        .gh4Hero{position:relative;height:calc(100svh - 88px);min-height:560px;max-height:820px;background:#243a34;color:#fff;overflow:hidden}.gh4Hero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 48%;filter:saturate(.68) contrast(1.03) brightness(.7)}.gh4Hero:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(10,19,16,.08),rgba(10,19,16,.15) 38%,rgba(10,19,16,.76) 100%),linear-gradient(90deg,rgba(10,19,16,.58),transparent 64%)}.gh4HeroInner{position:relative;z-index:2;height:100%;display:grid;grid-template-columns:1fr 350px;align-items:end;gap:70px;padding-bottom:48px}.gh4HeroTitle{max-width:790px}.gh4HeroTitle .gh4Meta{color:#d7e2dd;margin-bottom:16px}.gh4Hero h1{font-family:Georgia,'Times New Roman',serif;font-size:clamp(62px,7.5vw,104px);font-weight:400;line-height:.84;letter-spacing:-.055em;margin:0}.gh4HeroLead{font-size:13px;line-height:1.62;color:#eef1ee;max-width:540px;margin:20px 0 0}.gh4HeroBook{background:rgba(247,247,244,.96);color:var(--ink);padding:20px}.gh4HeroBookTop{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:14px}.gh4HeroBookTop strong{font-family:Georgia,'Times New Roman',serif;font-weight:400;font-size:21px}.gh4HeroBookTop span{font-size:8px;color:#69716c}.gh4HeroFields{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid var(--line);border-left:1px solid var(--line)}.gh4HeroField{padding:11px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);min-height:58px}.gh4HeroField small{display:block;font-size:7.5px;text-transform:uppercase;letter-spacing:.11em;color:#7b817d;margin-bottom:5px}.gh4HeroField strong{font-size:10.5px}.gh4HeroBookBtn{margin-top:11px;width:100%;min-height:42px;border:0;background:var(--wine);color:#fff;font-size:10px;font-weight:900;display:flex;align-items:center;justify-content:center;gap:7px}
        .gh4Facts{background:#fff;border-bottom:1px solid var(--line)}.gh4FactsInner{min-height:76px;display:grid;grid-template-columns:repeat(5,1fr);align-items:center}.gh4Fact{padding:0 22px;border-right:1px solid var(--line);font-size:10px;line-height:1.4}.gh4Fact:first-child{padding-left:0}.gh4Fact:last-child{border-right:0}.gh4Fact strong{display:block;font-size:11px;margin-bottom:3px}.gh4Fact span{color:#737a75}
        .gh4Rooms{padding:78px 0 96px;background:#f7f7f4}.gh4RoomsHead{display:flex;justify-content:space-between;align-items:end;gap:50px;margin-bottom:50px}.gh4RoomsHead h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(50px,6vw,82px);line-height:.9;font-weight:400;letter-spacing:-.05em;margin:0}.gh4RoomsHead p{max-width:430px;font-size:12px;line-height:1.65;color:#606863;margin:0 0 7px}.gh4RoomGallery{display:grid;grid-template-columns:repeat(12,1fr);gap:28px 22px;align-items:start}.gh4RoomCard{min-width:0}.gh4RoomCard:nth-child(1){grid-column:1/8}.gh4RoomCard:nth-child(2){grid-column:8/13;margin-top:120px}.gh4RoomCard:nth-child(3){grid-column:3/10;margin-top:18px}.gh4RoomImage{overflow:hidden;background:#ddd}.gh4RoomCard:nth-child(1) .gh4RoomImage{aspect-ratio:1.42/1}.gh4RoomCard:nth-child(2) .gh4RoomImage{aspect-ratio:1.05/1}.gh4RoomCard:nth-child(3) .gh4RoomImage{aspect-ratio:1.48/1}.gh4RoomImage img{height:100%;object-fit:cover;filter:saturate(.76) contrast(1.02)}.gh4RoomText{padding:16px 2px 0;display:grid;grid-template-columns:1fr auto;gap:10px 30px;align-items:start}.gh4RoomText .gh4Meta{grid-column:1/-1;color:var(--wine)}.gh4RoomText h3{font-family:Georgia,'Times New Roman',serif;font-size:28px;font-weight:400;line-height:1;margin:0}.gh4RoomText p{grid-column:1;max-width:480px;font-size:10.5px;line-height:1.55;color:#5e6661;margin:0}.gh4RoomAside{grid-column:2;grid-row:2/4;text-align:right;min-width:140px}.gh4RoomAside strong{display:block;font-size:10.5px;margin-bottom:10px}.gh4RoomAside a{font-size:9.5px;font-weight:800;border-bottom:1px solid var(--ink);padding-bottom:3px}
        .gh4Included{background:var(--forest);color:#fff;padding:34px 0}.gh4IncludedInner{display:flex;align-items:center;gap:38px}.gh4IncludedTitle{font-family:Georgia,'Times New Roman',serif;font-size:27px;font-weight:400;white-space:nowrap}.gh4Amenities{display:flex;gap:26px;flex-wrap:wrap}.gh4Amenity{display:flex;align-items:center;gap:8px;font-size:10px;color:#d7e1dc}.gh4Amenity strong{color:#fff;font-size:10px}
        .gh4Place{padding:90px 0 96px;background:#fff}.gh4PlaceIntro{display:grid;grid-template-columns:.72fr 1.28fr;gap:90px;align-items:start}.gh4PlaceIntro h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(56px,6.7vw,92px);line-height:.86;font-weight:400;letter-spacing:-.055em;margin:0}.gh4PlaceIntro p{font-size:12.5px;line-height:1.65;color:#5e6762;max-width:500px;margin:17px 0 0}.gh4PlaceStory{margin-top:50px;display:grid;grid-template-columns:1.08fr .92fr;gap:16px;align-items:start}.gh4PlaceMain{margin:0}.gh4PlaceMain img{height:610px;object-fit:cover;object-position:center;filter:saturate(.82)}.gh4PlaceMain figcaption,.gh4PlaceSide figcaption{padding-top:9px;font-size:9px;color:#6a716d}.gh4PlaceSide{display:grid;grid-template-columns:1fr 1fr;gap:16px}.gh4PlaceSide figure{margin:0}.gh4PlaceSide img{height:280px;object-fit:cover;filter:saturate(.82)}.gh4PlaceSide figure:last-child{grid-column:1/-1}.gh4PlaceSide figure:last-child img{height:290px}.gh4PlaceSide figcaption{display:flex;justify-content:space-between;gap:14px}.gh4PlaceSide strong{font-family:Georgia,'Times New Roman',serif;font-size:16px;font-weight:400;color:var(--ink)}.gh4PlaceNote{margin:28px 0 0 16%;max-width:650px;border-left:1px solid var(--wine);padding-left:20px;font-size:12px;line-height:1.65;color:#4d5752}.gh4Credit{font-size:8px;color:#8a918c;margin-top:12px}
        .gh4Breakfast{padding:78px 0 82px;background:var(--blue)}.gh4BreakfastHead{display:grid;grid-template-columns:.72fr 1.28fr;gap:70px;align-items:end;margin-bottom:30px}.gh4BreakfastHead h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(48px,5.8vw,76px);line-height:.9;font-weight:400;letter-spacing:-.05em;margin:0}.gh4BreakfastHead p{font-size:12px;line-height:1.65;color:#53605c;max-width:480px;margin:0 0 4px}.gh4BreakfastStrip{display:grid;grid-template-columns:1.18fr .82fr .82fr;gap:10px;align-items:end}.gh4BreakfastStrip img{width:100%;object-fit:cover;filter:saturate(.8)}.gh4BreakfastStrip img:nth-child(1){height:315px}.gh4BreakfastStrip img:nth-child(2),.gh4BreakfastStrip img:nth-child(3){height:240px}.gh4BreakfastBottom{display:flex;justify-content:space-between;gap:40px;margin-top:18px;border-top:1px solid rgba(23,35,31,.22);padding-top:13px;font-size:10px}.gh4BreakfastBottom strong{font-size:11px}
        .gh4Review{background:var(--wine);color:#fff;padding:70px 0}.gh4ReviewInner{display:grid;grid-template-columns:210px 1fr;gap:56px}.gh4Score strong{font-family:Georgia,'Times New Roman',serif;font-size:90px;font-weight:400;line-height:.8}.gh4Score span{display:block;font-size:9px;color:#f1dfe3;margin-top:10px}.gh4Quote{font-family:Georgia,'Times New Roman',serif;font-size:clamp(32px,3.8vw,50px);line-height:1.08;font-weight:400;margin:0;max-width:900px}.gh4QuoteBy{font-size:9px;letter-spacing:.09em;text-transform:uppercase;color:#efd8de;margin-top:18px}.gh4ReviewRow{display:grid;grid-template-columns:1fr 1fr;gap:38px;margin-top:26px;padding-top:20px;border-top:1px solid rgba(255,255,255,.3)}.gh4ReviewRow p{font-size:10.5px;line-height:1.55;color:#f5e9ec;margin:0}.gh4DemoLabel{display:inline-block;margin-top:18px;border:1px solid rgba(255,255,255,.35);padding:5px 7px;font-size:8px;color:#f0dfe3}
        .gh4Owners{padding:90px 0;background:#fff}.gh4OwnersGrid{display:grid;grid-template-columns:repeat(12,1fr);gap:22px;align-items:center}.gh4OwnersText{grid-column:1/6;padding-right:44px}.gh4OwnersText h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(48px,5.5vw,72px);font-weight:400;line-height:.9;margin:0 0 18px}.gh4OwnersText p{font-size:12px;line-height:1.65;color:#55605a;max-width:440px;margin:0}.gh4OwnersPhoto{grid-column:6/13;height:500px;overflow:hidden}.gh4OwnersPhoto img{height:100%;object-fit:cover;object-position:center 48%;filter:saturate(.75) contrast(1.02)}
        .gh4Practical{padding:82px 0;background:#f7f7f4}.gh4PracticalGrid{display:grid;grid-template-columns:.72fr 1.28fr;gap:80px}.gh4PracticalIntro h2{font-family:Georgia,'Times New Roman',serif;font-size:46px;font-weight:400;line-height:.94;margin:0}.gh4PracticalIntro p{font-size:11.5px;line-height:1.6;color:#626a65;max-width:360px;margin:16px 0 0}.gh4PracticalList{border-top:1px solid var(--line)}.gh4PracticalRow{display:grid;grid-template-columns:1fr auto;gap:25px;padding:15px 0;border-bottom:1px solid var(--line);font-size:11px}.gh4PracticalRow strong{font-weight:800}
        .gh4MapSection{background:var(--blue);padding:52px 0}.gh4MapGrid{display:grid;grid-template-columns:1.3fr .7fr;gap:18px}.gh4Map{position:relative;min-height:410px;background:#cbd7d6;overflow:hidden}.gh4Map:before{content:'';position:absolute;inset:-15%;background:repeating-linear-gradient(24deg,transparent 0 42px,#b7c6c5 43px 45px),repeating-linear-gradient(118deg,transparent 0 68px,#b9c8c6 69px 72px)}.gh4Map:after{content:'';position:absolute;width:24px;height:24px;border:8px solid var(--wine);border-radius:50% 50% 50% 0;transform:rotate(-45deg);left:56%;top:44%;background:#fff}.gh4Road{position:absolute;left:-5%;right:-5%;top:52%;height:13px;background:#f5f7f6;transform:rotate(-8deg);box-shadow:0 0 0 1px #aebdbc}.gh4Road2{position:absolute;top:-15%;bottom:-10%;left:44%;width:12px;background:#f5f7f6;transform:rotate(14deg);box-shadow:0 0 0 1px #aebdbc}.gh4MapCopy{background:#fff;padding:32px;display:flex;flex-direction:column;justify-content:space-between}.gh4MapCopy h2{font-family:Georgia,'Times New Roman',serif;font-size:37px;font-weight:400;line-height:.95;margin:0 0 16px}.gh4MapCopy p{font-size:11px;line-height:1.6;color:#5b645f;margin:0}.gh4MapDetails{display:grid;gap:10px;margin-top:26px;font-size:10px}.gh4MapDetails span{display:flex;align-items:center;gap:8px}
        .gh4ReserveEnd{padding:82px 0 72px;background:var(--forest);color:#fff}.gh4ReserveGrid{display:grid;grid-template-columns:.8fr 1.2fr;gap:76px;align-items:start}.gh4ReserveCopy h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(54px,6.2vw,84px);font-weight:400;line-height:.86;letter-spacing:-.055em;margin:0 0 18px}.gh4ReserveCopy p{font-size:12px;line-height:1.6;color:#d5e0db;max-width:430px}.gh4ReservePanel{background:#fff;color:var(--ink);padding:22px}.gh4ReserveFields{display:grid;grid-template-columns:1fr 1fr 1fr;border-top:1px solid var(--line);border-left:1px solid var(--line)}.gh4ReserveField{padding:13px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);min-height:66px}.gh4ReserveField small{display:block;font-size:7.5px;text-transform:uppercase;letter-spacing:.1em;color:#7a827d;margin-bottom:7px}.gh4ReserveField strong{font-size:10.5px}.gh4ReserveBtn{width:100%;margin-top:11px;min-height:44px;background:var(--wine);border:0;color:#fff;font-size:10px;font-weight:900;display:flex;justify-content:center;align-items:center;gap:7px}.gh4ReserveNote{margin-top:9px;font-size:8.5px;color:#757d78}
        .gh4Footer{background:#0d1714;color:#aebbb5}.gh4FooterInner{min-height:108px;padding:23px 0;display:grid;grid-template-columns:1fr auto;gap:30px;align-items:center;font-size:9.5px}.gh4Footer strong{color:#fff;font-family:Georgia,'Times New Roman',serif;font-size:16px;font-weight:400}.gh4FooterRight{display:flex;gap:14px;align-items:center}.gh4Footer a{text-decoration:underline;text-underline-offset:3px}.gh4FooterCta{border:1px solid #46564f;padding:9px 11px;color:#fff!important;text-decoration:none!important;font-weight:800}
        @media(max-width:980px){.gh4Wrap{width:min(100% - 36px,1280px)}.gh4Links{display:none}.gh4HeroInner{grid-template-columns:1fr 330px;gap:30px}.gh4FactsInner{grid-template-columns:repeat(3,1fr)}.gh4Fact{padding:14px;border-bottom:1px solid var(--line)}.gh4RoomCard:nth-child(1){grid-column:1/9}.gh4RoomCard:nth-child(2){grid-column:8/13;margin-top:80px}.gh4RoomCard:nth-child(3){grid-column:2/10}.gh4RoomText{grid-template-columns:1fr}.gh4RoomAside{grid-column:1;grid-row:auto;text-align:left}.gh4PlaceIntro{grid-template-columns:1fr 1fr;gap:40px}.gh4PlaceStory{grid-template-columns:1fr}.gh4PlaceMain img{height:500px}.gh4PlaceSide{grid-template-columns:1fr 1fr}.gh4OwnersText{grid-column:1/6}.gh4OwnersPhoto{grid-column:6/13}.gh4ReserveGrid{gap:40px}}
        @media(max-width:720px){.gh4Wrap{width:min(100% - 26px,1280px)}.gh4Demo{font-size:7.5px;text-align:center;line-height:1.3}.gh4Nav{height:58px}.gh4Brand span{display:none}.gh4Hero{height:auto;min-height:680px;max-height:none}.gh4HeroInner{height:auto;min-height:680px;grid-template-columns:1fr;align-content:end;padding:100px 0 26px}.gh4Hero h1{font-size:clamp(56px,16vw,78px)}.gh4HeroBook{width:100%;max-width:430px}.gh4FactsInner{grid-template-columns:1fr 1fr}.gh4Rooms{padding:58px 0 70px}.gh4RoomsHead{display:block}.gh4RoomsHead p{margin-top:18px}.gh4RoomGallery{display:block}.gh4RoomCard:nth-child(n){margin:0 0 48px}.gh4RoomCard:nth-child(n) .gh4RoomImage{aspect-ratio:1.32/1}.gh4RoomText{padding-top:14px}.gh4IncludedInner{align-items:flex-start;flex-direction:column}.gh4Amenities{gap:16px 22px}.gh4Place{padding:64px 0}.gh4PlaceIntro{grid-template-columns:1fr;gap:20px}.gh4PlaceStory{margin-top:34px}.gh4PlaceMain img{height:430px}.gh4PlaceSide{grid-template-columns:1fr}.gh4PlaceSide figure:last-child{grid-column:auto}.gh4PlaceSide img,.gh4PlaceSide figure:last-child img{height:240px}.gh4PlaceNote{margin-left:0}.gh4Breakfast{padding:62px 0}.gh4BreakfastHead{grid-template-columns:1fr;gap:18px}.gh4BreakfastStrip{grid-template-columns:1fr 1fr}.gh4BreakfastStrip img:nth-child(1){grid-column:1/-1;height:280px}.gh4BreakfastStrip img:nth-child(2),.gh4BreakfastStrip img:nth-child(3){height:180px}.gh4ReviewInner{grid-template-columns:1fr;gap:28px}.gh4ReviewRow{grid-template-columns:1fr;gap:18px}.gh4Owners{padding:66px 0}.gh4OwnersGrid{display:flex;flex-direction:column}.gh4OwnersText{padding:0;order:2}.gh4OwnersPhoto{width:100%;height:390px;order:1}.gh4PracticalGrid{grid-template-columns:1fr;gap:32px}.gh4MapGrid{grid-template-columns:1fr}.gh4Map{min-height:320px}.gh4ReserveGrid{grid-template-columns:1fr;gap:28px}.gh4ReserveFields{grid-template-columns:1fr}.gh4FooterInner{grid-template-columns:1fr}.gh4FooterRight{flex-wrap:wrap}}
      `}</style>

      <div className="gh4Demo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <div className="gh4NavShell"><div className="gh4Wrap"><nav className="gh4Nav" aria-label="Navigace ukázkového penzionu"><a className="gh4Brand" href="#top"><strong>U Tiché vody</strong><span>penzion · Třeboňsko</span></a><div className="gh4NavRight"><div className="gh4Links"><a href="#pokoje">Pokoje</a><a href="#okoli">Okolí</a><a href="#prakticke">Praktické</a></div><a className="gh4BookSmall" href="#rezervace">Rezervace <CalendarDays size={12}/></a></div></nav></div></div>

      <header className="gh4Hero">
        <img src="https://images.pexels.com/photos/15692771/pexels-photo-15692771.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Vstup do rustikálního pokoje s dřevěnými trámy a světlým povlečením"/>
        <div className="gh4Wrap gh4HeroInner"><div className="gh4HeroTitle"><div className="gh4Meta">PENZION · TŘEBOŇSKO</div><h1>U Tiché<br/>vody.</h1><p className="gh4HeroLead">Osm pokojů v opraveném venkovském domě. Snídaně v ceně, zahrada, kolárna a Třeboň deset minut autem.</p></div><div className="gh4HeroBook"><div className="gh4HeroBookTop"><strong>Termín pobytu</strong><span>ukázková rezervace</span></div><div className="gh4HeroFields"><div className="gh4HeroField"><small>Příjezd</small><strong>Vyberte datum</strong></div><div className="gh4HeroField"><small>Odjezd</small><strong>Vyberte datum</strong></div><div className="gh4HeroField"><small>Hosté</small><strong>2 osoby</strong></div><div className="gh4HeroField"><small>Pokoje</small><strong>1 pokoj</strong></div></div><button className="gh4HeroBookBtn" type="button">Zjistit dostupnost <ArrowRight size={12}/></button></div></div>
      </header>

      <div className="gh4Facts"><div className="gh4Wrap gh4FactsInner"><div className="gh4Fact"><strong>8 pokojů</strong><span>dvoulůžkové i rodinné</span></div><div className="gh4Fact"><strong>Snídaně v ceně</strong><span>každé ráno 8:00–10:00</span></div><div className="gh4Fact"><strong>Parkování u domu</strong><span>bez příplatku</span></div><div className="gh4Fact"><strong>Kolárna</strong><span>uzamykatelná</span></div><div className="gh4Fact"><strong>Třeboň 8 km</strong><span>autem přibližně 10 minut</span></div></div></div>

      <section className="gh4Rooms" id="pokoje"><div className="gh4Wrap"><div className="gh4RoomsHead"><h2>Vyberte si pokoj.</h2><p>K dispozici jsou dvoulůžkové i rodinné pokoje. Každý má vlastní koupelnu, Wi-Fi a snídani v ceně.</p></div><div className="gh4RoomGallery">{rooms.map((room)=><article className="gh4RoomCard" key={room.no}><div className="gh4RoomImage"><img src={room.image} alt={room.alt}/></div><div className="gh4RoomText"><div className="gh4Meta">POKOJ {room.no} · {room.meta}</div><h3>{room.name}</h3><p>{room.text}</p><div className="gh4RoomAside"><strong>{room.price}</strong><a href="#rezervace">Rezervovat</a></div></div></article>)}</div></div></section>

      <section className="gh4Included"><div className="gh4Wrap gh4IncludedInner"><div className="gh4IncludedTitle">V ceně pobytu</div><div className="gh4Amenities"><div className="gh4Amenity"><Coffee size={14}/><span><strong>Snídaně</strong> 8:00–10:00</span></div><div className="gh4Amenity"><Car size={14}/><span><strong>Parkování</strong> u domu</span></div><div className="gh4Amenity"><Wifi size={14}/><span><strong>Wi-Fi</strong> pokoje i zahrada</span></div><div className="gh4Amenity"><Bike size={14}/><span><strong>Kolárna</strong> uzamykatelná</span></div><div className="gh4Amenity"><PawPrint size={14}/><span><strong>Pes</strong> po dohodě</span></div></div></div></section>

      <section className="gh4Place" id="okoli"><div className="gh4Wrap"><div className="gh4PlaceIntro"><h2>Třeboňsko<br/>v okolí.</h2><p>Rybníky, rovné cyklotrasy a Třeboň v krátké dojezdové vzdálenosti. Kolo lze uložit v uzamykatelné kolárně přímo u penzionu.</p></div><div className="gh4PlaceStory"><figure className="gh4PlaceMain"><img src={trebonTrail} alt="Stezka mezi rybníky Svět a Opatovický na Třeboňsku"/><figcaption>Stezka Okolo Třeboně mezi rybníky Svět a Opatovický.</figcaption></figure><div className="gh4PlaceSide"><figure><img src={trebonTown} alt="Náměstí v Třeboni"/><figcaption><strong>Třeboň</strong><span>8 km · centrum, zámek, restaurace</span></figcaption></figure><figure><img src={rozmberek} alt="Rybník Rožmberk u Třeboně"/><figcaption><strong>Rožmberk</strong><span>12 km · rybník a cyklotrasy</span></figcaption></figure><figure><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Hrani%C4%8Dn%C3%AD_rybn%C3%ADk%2C_T%C5%99ebo%C5%88sko.JPG?width=1200" alt="Rybník v krajině Třeboňska"/><figcaption><strong>Třeboňsko</strong><span>rybníky, hráze a rovná krajina</span></figcaption></figure></div></div><p className="gh4PlaceNote">Cyklostezka vede přibližně 600 metrů od domu. Třeboň je osm kilometrů, Rožmberk dvanáct.</p><div className="gh4Credit">Ilustrační fotografie okolí: Wikimedia Commons · skutečné Třeboňsko, Třeboň a Rožmberk.</div></div></section>

      <section className="gh4Breakfast"><div className="gh4Wrap"><div className="gh4BreakfastHead"><h2>Snídaně je v ceně pokoje.</h2><p>Pečivo, vejce, sýry, šunka, jogurt, ovoce, něco sladkého, káva a čaj. Podává se každé ráno mezi osmou a desátou.</p></div><div className="gh4BreakfastStrip"><img src="https://images.pexels.com/photos/5591699/pexels-photo-5591699.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Snídaně pro dva s vejci, pečivem a kávou na dřevěném stole"/><img src="https://images.pexels.com/photos/5720777/pexels-photo-5720777.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Rustikální snídaně s vejci, chlebem a kávou"/><img src="https://images.pexels.com/photos/5720783/pexels-photo-5720783.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Jednoduchá snídaně na dřevěném stole"/></div><div className="gh4BreakfastBottom"><strong>Snídaně 8:00–10:00</strong><span>V případě časného odjezdu lze předem domluvit balíček s sebou.</span></div></div></section>

      <section className="gh4Review"><div className="gh4Wrap gh4ReviewInner"><div className="gh4Score"><strong>9,4</strong><span>/ 10 · UKÁZKOVÉ HODNOCENÍ</span></div><div><p className="gh4Quote">„Klidné místo, výborná snídaně a dobrá poloha na výlety na kole.“</p><div className="gh4QuoteBy">MARTINA K. · DEMO RECENZE</div><div className="gh4ReviewRow"><p>„Pokoj byl čistý, postel pohodlná a večer byl na zahradě opravdu klid.“</p><p>„Do Třeboně jsme dojeli za pár minut a kola jsme mohli nechat zamčená přímo u domu.“</p></div><span className="gh4DemoLabel">Hodnocení je součástí fiktivního konceptu.</span></div></div></section>

      <section className="gh4Owners"><div className="gh4Wrap gh4OwnersGrid"><div className="gh4OwnersText"><h2>Jana a Petr.</h2><p>O penzion se starají od roku 2018. Jana řeší rezervace a snídaně, Petr dům, zahradu a kola.</p></div><div className="gh4OwnersPhoto"><img src="https://images.pexels.com/photos/6848255/pexels-photo-6848255.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Starší pár při přípravě jídla v útulné domácí kuchyni"/></div></div></section>

      <section className="gh4Practical" id="prakticke"><div className="gh4Wrap gh4PracticalGrid"><div className="gh4PracticalIntro"><h2>Praktické informace.</h2><p>Věci, které je dobré vědět ještě před rezervací nebo příjezdem.</p></div><div className="gh4PracticalList">{practical.map(([label,value])=><div className="gh4PracticalRow" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section>

      <section className="gh4MapSection"><div className="gh4Wrap gh4MapGrid"><div className="gh4Map" aria-label="Ilustrační mapa příjezdu"><div className="gh4Road"/><div className="gh4Road2"/></div><div className="gh4MapCopy"><div><div className="gh4Meta gh4Muted">PŘÍJEZD</div><h2>U Tiché vody · Třeboňsko</h2><p>Penzion leží v klidné obci osm kilometrů od Třeboně. Parkování je přímo u domu, příjezd je možný autem i na kole.</p></div><div className="gh4MapDetails"><span><MapPin size={14}/> Třeboňsko · 8 km od Třeboně</span><span><Car size={14}/> parkování u domu</span><span><Phone size={14}/> 777 000 000</span></div></div></div></section>

      <section className="gh4ReserveEnd" id="rezervace"><div className="gh4Wrap gh4ReserveGrid"><div className="gh4ReserveCopy"><h2>Vyberte termín pobytu.</h2><p>Zvolte datum příjezdu, odjezdu a počet hostů. Volný pokoj a cenu uvidíte před dokončením rezervace.</p></div><div className="gh4ReservePanel"><div className="gh4ReserveFields"><div className="gh4ReserveField"><small>Příjezd</small><strong>Vyberte datum</strong></div><div className="gh4ReserveField"><small>Odjezd</small><strong>Vyberte datum</strong></div><div className="gh4ReserveField"><small>Hosté</small><strong>2 osoby</strong></div></div><button className="gh4ReserveBtn" type="button">Zjistit dostupnost <ArrowRight size={12}/></button><div className="gh4ReserveNote">Ukázkové rezervační rozhraní není aktivní.</div></div></div></section>

      <footer className="gh4Footer"><div className="gh4Wrap gh4FooterInner"><div><strong>U Tiché vody</strong><br/>Fiktivní penzion vytvořený pouze jako ukázkový koncept.</div><div className="gh4FooterRight">Tento koncept vytvořil <a href="/">SpustWeb.cz</a><a className="gh4FooterCta" href="/#kontakt">Web pro moje podnikání</a></div></div></footer>
    </div>
  )
}
