import type { Metadata } from 'next'
import { ArrowRight, CalendarDays, Clock3, MapPin, Phone } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro fitness trenérku | SpustWeb.cz',
  description: 'Ukázka webu pro fitness trenérku: kruhový trénink, cardio dance, rozvrh lekcí, ceník, trenérka a přihlášení.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/fitness-trenerka/' },
  robots: { index: true, follow: true },
}

const schedule = [
  ['PO', '17:30', 'Kruhový trénink', '55 min', '4 místa'],
  ['ÚT', '18:30', 'Cardio Dance', '50 min', '6 míst'],
  ['ČT', '17:30', 'Kruhový trénink', '55 min', '3 místa'],
  ['SO', '09:30', 'Cardio Dance', '50 min', '8 míst'],
]

export default function FitnessTrainerShowcase() {
  return (
    <div className="ft" id="top">
      <style>{`
        body:has(.ft) > .verno-nav-shell,body:has(.ft) > .footer{display:none!important}
        body:has(.ft) main{padding:0!important;margin:0!important}
        body:has(.ft){background:#fff7ea!important}
        .ft{--ink:#171717;--cream:#fff7ea;--coral:#ff6a57;--lav:#b9a7ff;--mint:#45cdb7;--white:#fff;--line:rgba(23,23,23,.2);font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--cream)}
        .ft *{box-sizing:border-box}.ft a{color:inherit;text-decoration:none}.ft img{display:block;width:100%}.ftWrap{width:min(1320px,calc(100% - 56px));margin:0 auto}
        .ftDemo{min-height:24px;background:#171717;color:#ddd;padding:5px 12px;text-align:center;font-size:8.5px;font-weight:800;letter-spacing:.09em;text-transform:uppercase}.ftDemo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .ftNav{background:var(--cream);border-bottom:1px solid #171717}.ftNavIn{height:54px;display:flex;align-items:center;justify-content:space-between;gap:24px}.ftBrand{font-size:18px;font-weight:900;letter-spacing:-.05em}.ftLinks{display:flex;align-items:center;gap:24px;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.ftJoin{background:var(--ink);color:#fff!important;padding:9px 12px}

        .ftHero{position:relative;min-height:730px;height:calc(100svh - 78px);max-height:900px;overflow:hidden;background:var(--coral)}
        .ftHeroWord{position:absolute;left:2.5vw;top:50%;transform:translateY(-52%);z-index:5;font-size:clamp(92px,14vw,210px);line-height:.68;letter-spacing:-.105em;font-weight:900}.ftHeroWord span{display:block}.ftHeroWord .lav{color:var(--lav)}
        .ftHeroCircle{position:absolute;right:7vw;top:8%;width:min(39vw,560px);aspect-ratio:1;border-radius:50%;overflow:hidden;border:14px solid var(--cream);z-index:3}.ftHeroCircle img{height:100%;object-fit:cover;object-position:center 45%}
        .ftHeroSmall{position:absolute;right:2.7vw;bottom:8%;width:min(25vw,340px);height:240px;overflow:hidden;transform:rotate(4deg);border:10px solid var(--lav);z-index:6}.ftHeroSmall img{height:100%;object-fit:cover}
        .ftHeroMeta{position:absolute;left:3vw;top:30px;font-size:10px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;z-index:6}
        .ftHeroCopy{position:absolute;left:3vw;bottom:34px;width:390px;z-index:7;font-size:14px;line-height:1.55}.ftHeroCopy p{margin:0 0 13px}.ftHeroCopy a{font-size:10.5px;font-weight:900;border-bottom:1px solid #171717;padding-bottom:3px}
        .ftTicker{background:var(--lav);border-top:1px solid #171717;border-bottom:1px solid #171717;overflow:hidden;white-space:nowrap;padding:13px 0;font-size:16px;font-weight:900;letter-spacing:.02em}.ftTicker span{display:inline-block;margin-right:48px}

        .ftSchedule{padding:72px 0 84px;background:var(--cream)}.ftScheduleHead{display:flex;align-items:end;justify-content:space-between;gap:50px;margin-bottom:28px}.ftScheduleHead h2{font-size:clamp(54px,6.5vw,90px);line-height:.82;letter-spacing:-.085em;margin:0}.ftScheduleHead p{max-width:440px;font-size:13px;line-height:1.55;margin:0;color:#5f5f5f}.ftRows{border-top:3px solid #171717}.ftRow{display:grid;grid-template-columns:72px 110px 1fr 120px 110px auto;gap:22px;align-items:center;padding:18px 0;border-bottom:1px solid var(--line)}.ftDay{font-size:28px;font-weight:900}.ftTime{font-size:17px;font-weight:800}.ftClass{font-size:24px;font-weight:900;letter-spacing:-.035em}.ftMeta{font-size:11px;color:#666}.ftSpot{font-size:10px;font-weight:900;background:var(--mint);padding:7px 9px;justify-self:start}.ftRow a{font-size:10px;font-weight:900;border-bottom:1px solid #171717;padding-bottom:3px}

        .ftClasses{background:#171717;color:#fff;padding:0}.ftClassBand{min-height:560px;position:relative;overflow:hidden;border-bottom:1px solid #444}.ftClassBand img{position:absolute;inset:0;height:100%;object-fit:cover;filter:saturate(.9) contrast(1.04);opacity:.74}.ftClassBand:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(0,0,0,.72),rgba(0,0,0,.18) 64%,rgba(0,0,0,.08))}.ftClassBand:nth-child(2):after{background:linear-gradient(90deg,rgba(75,47,0,.1),rgba(0,0,0,.15) 45%,rgba(0,0,0,.7))}.ftClassBandInner{position:relative;z-index:3;min-height:560px;display:flex;flex-direction:column;justify-content:flex-end;padding:56px 0}.ftClassBand h2{font-size:clamp(70px,9vw,126px);font-weight:900;line-height:.76;letter-spacing:-.09em;margin:0 0 18px;max-width:880px}.ftClassBand p{max-width:560px;font-size:14px;line-height:1.6;margin:0}.ftClassBand:nth-child(2) .ftClassBandInner{align-items:flex-end;text-align:right}.ftClassBand:nth-child(2) p{margin-left:auto}.ftClassLabel{position:absolute;top:32px;left:0;background:var(--coral);color:#171717;padding:8px 10px;font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.ftClassBand:nth-child(2) .ftClassLabel{left:auto;right:0;background:var(--lav)}

        .ftBring{background:var(--mint);border-top:1px solid #171717;border-bottom:1px solid #171717}.ftBringIn{min-height:88px;display:grid;grid-template-columns:170px repeat(4,1fr);gap:28px;align-items:center;font-size:11px}.ftBringIn strong{font-size:15px}.ftBringIn span{border-left:1px solid rgba(23,23,23,.28);padding-left:22px}

        .ftPrice{padding:86px 0 94px;background:var(--cream)}.ftPriceHead{font-size:clamp(56px,7vw,96px);font-weight:900;letter-spacing:-.085em;line-height:.8;margin:0 0 42px}.ftTickets{display:grid;grid-template-columns:1fr 1fr 1fr;border-top:3px solid #171717;border-bottom:3px solid #171717}.ftTicket{padding:26px 26px 28px;border-right:1px solid #171717;min-height:230px;display:flex;flex-direction:column;justify-content:space-between}.ftTicket:last-child{border-right:0}.ftTicket small{font-size:9px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.ftTicket b{font-size:clamp(52px,5vw,74px);letter-spacing:-.07em}.ftTicket p{font-size:11px;line-height:1.5;color:#666;margin:0}.ftTicket:nth-child(2){background:var(--lav)}.ftTicket:nth-child(3){background:var(--coral)}

        .ftTrainer{padding:88px 0 96px;background:#fff}.ftTrainerCanvas{position:relative;min-height:720px}.ftTrainerTitle{font-size:clamp(72px,10vw,144px);font-weight:900;letter-spacing:-.095em;line-height:.72;margin:0;position:relative;z-index:4;max-width:850px}.ftTrainerPhoto{position:absolute;right:4%;top:0;width:42%;height:650px;overflow:hidden;border-radius:50% 50% 8px 8px}.ftTrainerPhoto img{height:100%;object-fit:cover;object-position:center 30%}.ftTrainerCopy{position:absolute;left:0;bottom:0;max-width:510px;font-size:14px;line-height:1.65}.ftTrainerCopy p{margin:0 0 22px}.ftCreds{display:flex;flex-wrap:wrap;gap:8px}.ftCreds span{border:1px solid #171717;padding:7px 9px;font-size:9px;font-weight:800}

        .ftFirst{background:var(--lav);padding:68px 0}.ftFirst h2{font-size:clamp(52px,6.5vw,88px);letter-spacing:-.08em;line-height:.82;margin:0 0 30px}.ftFirstGrid{display:grid;grid-template-columns:repeat(3,1fr);border-top:2px solid #171717}.ftFirstItem{padding:22px 24px 0 0;border-right:1px solid rgba(23,23,23,.35)}.ftFirstItem:last-child{border-right:0;padding-left:24px}.ftFirstItem:nth-child(2){padding-left:24px}.ftFirstItem strong{display:block;font-size:17px;margin-bottom:8px}.ftFirstItem p{font-size:12px;line-height:1.55;margin:0;color:#3f3658}

        .ftPlace{background:#171717;color:#fff;padding:74px 0}.ftPlaceIn{display:grid;grid-template-columns:1.15fr .85fr;gap:80px;align-items:end}.ftPlace h2{font-size:clamp(58px,7.5vw,104px);line-height:.78;letter-spacing:-.09em;margin:0}.ftPlaceData{display:grid;gap:12px;font-size:12px;color:#bbb}.ftPlaceData span{display:flex;align-items:center;gap:8px}.ftPlaceData strong{color:#fff}.ftSignup{margin-top:26px;display:flex;gap:10px;flex-wrap:wrap}.ftSignup a{background:var(--coral);color:#171717!important;padding:12px 14px;font-size:10px;font-weight:900}.ftSignup a:last-child{background:transparent;color:#fff!important;border:1px solid #fff}

        .ftFooter{background:var(--coral);padding:34px 0}.ftFooterIn{display:flex;align-items:center;justify-content:space-between;gap:30px}.ftFooterName{font-size:28px;font-weight:900;letter-spacing:-.06em}.ftFooterText{font-size:9.5px}.ftFooterCta{background:#171717;color:#fff!important;padding:11px 13px;font-size:10px;font-weight:900}

        @media(max-width:980px){.ftHeroCircle{width:48vw;right:4vw}.ftHeroWord{font-size:clamp(84px,16vw,150px)}.ftRow{grid-template-columns:64px 95px 1fr auto}.ftMeta{display:none}.ftSpot{justify-self:end}.ftBringIn{grid-template-columns:1fr 1fr}.ftBringIn strong{grid-column:1/-1}.ftBringIn span{border-left:0;padding-left:0}.ftTrainerPhoto{width:48%}.ftTrainerCopy{max-width:430px}.ftPlaceIn{grid-template-columns:1fr;gap:35px}}
        @media(max-width:680px){.ftWrap{width:min(100% - 28px,1320px)}.ftDemo{font-size:7.5px}.ftLinks a:not(.ftJoin){display:none}.ftHero{min-height:700px;height:auto}.ftHeroWord{top:28%;font-size:clamp(72px,24vw,104px)}.ftHeroCircle{width:76vw;right:-12vw;top:18%;border-width:9px}.ftHeroSmall{width:46vw;height:180px;right:2vw;bottom:15%;border-width:7px}.ftHeroCopy{left:14px;bottom:24px;width:78%;font-size:13px}.ftSchedule{padding:56px 0}.ftScheduleHead{display:block}.ftScheduleHead p{margin-top:16px}.ftRow{grid-template-columns:54px 78px 1fr;gap:10px;padding:16px 0}.ftSpot{grid-column:2;justify-self:start}.ftRow a{grid-column:3;justify-self:start}.ftClass{font-size:18px}.ftClassBand,.ftClassBandInner{min-height:500px}.ftClassBand h2{font-size:56px}.ftBringIn{grid-template-columns:1fr;padding:18px 0;gap:10px}.ftTickets{grid-template-columns:1fr}.ftTicket{border-right:0;border-bottom:1px solid #171717}.ftTrainerCanvas{min-height:920px}.ftTrainerTitle{font-size:72px}.ftTrainerPhoto{position:relative;right:auto;top:auto;width:100%;height:520px;margin-top:26px}.ftTrainerCopy{position:relative;bottom:auto;margin-top:24px}.ftFirstGrid{grid-template-columns:1fr}.ftFirstItem,.ftFirstItem:nth-child(2),.ftFirstItem:last-child{padding:18px 0;border-right:0;border-bottom:1px solid rgba(23,23,23,.3)}.ftFooterIn{display:grid}.ftFooterCta{justify-self:start}}
      `}</style>

      <div className="ftDemo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <nav className="ftNav"><div className="ftWrap ftNavIn"><a className="ftBrand" href="#top">TEREZA NOVÁKOVÁ</a><div className="ftLinks"><a href="#rozvrh">Rozvrh</a><a href="#lekce">Lekce</a><a href="#cenik">Vstupné</a><a href="#trenerka">Trenérka</a><a className="ftJoin" href="#prihlaseni">Přihlásit se</a></div></div></nav>

      <header className="ftHero"><div className="ftHeroMeta">KRUHOVÝ TRÉNINK · CARDIO DANCE · ČESKÉ BUDĚJOVICE</div><div className="ftHeroWord"><span>TEREZA</span><span className="lav">MOVE</span></div><div className="ftHeroCircle"><img src="https://images.pexels.com/photos/3768695/pexels-photo-3768695.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Skupina žen při skupinovém fitness tréninku"/></div><div className="ftHeroSmall"><img src="https://images.pexels.com/photos/8957646/pexels-photo-8957646.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Skupinová cardio dance lekce"/></div><div className="ftHeroCopy"><p>Skupinové lekce vedené v menším sále. Kruhový trénink pro sílu a kondici, cardio dance pro tempo a pohyb.</p><a href="#rozvrh">Zobrazit rozvrh →</a></div></header>

      <div className="ftTicker"><span>KRUHOVÝ TRÉNINK</span><span>CARDIO DANCE</span><span>MAX. 12 LIDÍ</span><span>ČESKÉ BUDĚJOVICE</span><span>KRUHOVÝ TRÉNINK</span><span>CARDIO DANCE</span></div>

      <section className="ftSchedule" id="rozvrh"><div className="ftWrap"><div className="ftScheduleHead"><h2>Tento týden.</h2><p>Na skupinovou lekci je potřeba se předem přihlásit. Kapacita sálu je 12 lidí.</p></div><div className="ftRows">{schedule.map(([day,time,name,duration,spots])=><div className="ftRow" key={`${day}-${time}`}><div className="ftDay">{day}</div><div className="ftTime">{time}</div><div className="ftClass">{name}</div><div className="ftMeta">{duration}</div><div className="ftSpot">{spots}</div><a href="#prihlaseni">Přihlásit se</a></div>)}</div></div></section>

      <section className="ftClasses" id="lekce"><article className="ftClassBand"><img src="https://images.pexels.com/photos/3775524/pexels-photo-3775524.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="Skupina žen při kruhovém tréninku s činkami"/><div className="ftWrap ftClassBandInner"><div className="ftClassLabel">SÍLA + KONDICE</div><h2>Kruhový trénink.</h2><p>Stanoviště se střídají v krátkých intervalech. Vlastní váha, činky, gumy a jednoduché kondiční prvky. Intenzitu lze upravit podle zkušeností.</p></div></article><article className="ftClassBand"><img src="https://images.pexels.com/photos/8957646/pexels-photo-8957646.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="Ženy při cardio dance lekci ve světlém sále"/><div className="ftWrap ftClassBandInner"><div className="ftClassLabel">KARDIO + TANEC</div><h2>Cardio Dance.</h2><p>Jednoduché taneční kombinace v tempu hudby. Lekce je zaměřená na kondici a pohyb, ne na zvládnutí složité choreografie.</p></div></article></section>

      <section className="ftBring"><div className="ftWrap ftBringIn"><strong>Na lekci</strong><span>čisté sportovní boty</span><span>pití</span><span>ručník</span><span>dorazit 10 minut před začátkem</span></div></section>

      <section className="ftPrice" id="cenik"><div className="ftWrap"><h2 className="ftPriceHead">Vstupné.</h2><div className="ftTickets"><div className="ftTicket"><small>Jednorázový vstup</small><b>190 Kč</b><p>Jedna vybraná skupinová lekce.</p></div><div className="ftTicket"><small>5 vstupů</small><b>850 Kč</b><p>Platnost 8 týdnů od prvního vstupu.</p></div><div className="ftTicket"><small>10 vstupů</small><b>1 550 Kč</b><p>Platnost 12 týdnů od prvního vstupu.</p></div></div></div></section>

      <section className="ftTrainer" id="trenerka"><div className="ftWrap ftTrainerCanvas"><h2 className="ftTrainerTitle">Tereza<br/>Nováková.</h2><div className="ftTrainerPhoto"><img src="https://images.pexels.com/photos/6739930/pexels-photo-6739930.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Fitness trenérka Tereza v tělocvičně"/></div><div className="ftTrainerCopy"><p>Tereza vede skupinové kondiční a dance fitness lekce. Kruhový trénink staví na jednoduchých stanovištích a práci v malé skupině, cardio dance na pohybu v tempu hudby.</p><div className="ftCreds"><span>fitness instruktor</span><span>skupinové lekce</span><span>kruhový trénink</span><span>dance fitness</span></div></div></div></section>

      <section className="ftFirst"><div className="ftWrap"><h2>Jdete poprvé?</h2><div className="ftFirstGrid"><div className="ftFirstItem"><strong>Není potřeba zkušenost</strong><p>U kruhového tréninku lze upravit obtížnost. U cardio dance se jede podle jednoduchých opakujících se kombinací.</p></div><div className="ftFirstItem"><strong>Stačí běžné sportovní oblečení</strong><p>Není potřeba vlastní vybavení. Pomůcky jsou připravené v sále.</p></div><div className="ftFirstItem"><strong>Přihlášení předem</strong><p>Skupina je omezená na 12 lidí, proto se místo vybírá z aktuálního rozvrhu.</p></div></div></div></section>

      <section className="ftPlace" id="prihlaseni"><div className="ftWrap ftPlaceIn"><h2>Lekce v Českých Budějovicích.</h2><div><div className="ftPlaceData"><span><MapPin size={15}/><strong>centrum Českých Budějovic</strong></span><span><Clock3 size={15}/>Po, Út, Čt a So podle rozvrhu</span><span><Phone size={15}/>777 000 000</span><span><CalendarDays size={15}/>přihlášení na konkrétní lekci předem</span></div><div className="ftSignup"><a href="#rozvrh">Vybrat lekci <ArrowRight size={13}/></a><a href="tel:777000000">Zavolat</a></div></div></div></section>

      <footer className="ftFooter"><div className="ftWrap ftFooterIn"><div className="ftFooterName">TEREZA MOVE</div><div className="ftFooterText">Fiktivní fitness trenérka · ukázkový koncept SpustWeb.cz</div><a className="ftFooterCta" href="/#kontakt">Podobný web pro moje podnikání</a></div></footer>
    </div>
  )
}
