import type { Metadata } from 'next'
import { Mail, MapPin, Phone } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro fitness trenérku | SpustWeb.cz',
  description: 'Ukázka webu pro fitness trenérku: kruhový trénink, cardio dance, rozvrh lekcí, ceník, trenérka a kontakt.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/fitness-trenerka/' },
  robots: { index: true, follow: true },
}

const schedule = [
  ['PO', '17:30', 'Kruhový trénink', '55 min'],
  ['ÚT', '18:30', 'Cardio Dance', '50 min'],
  ['ČT', '17:30', 'Kruhový trénink', '55 min'],
  ['SO', '09:30', 'Cardio Dance', '50 min'],
]

export default function FitnessTrainerShowcase() {
  return (
    <div className="ft2" id="top">
      <style>{`
        body:has(.ft2) > .verno-nav-shell,body:has(.ft2) > .footer{display:none!important}
        body:has(.ft2) main{padding:0!important;margin:0!important}
        body:has(.ft2){background:#fff7ea!important}
        .ft2{--ink:#171717;--cream:#fff7ea;--coral:#ff6a57;--lav:#b9a7ff;--mint:#45cdb7;--line:rgba(23,23,23,.2);font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--cream)}
        .ft2 *{box-sizing:border-box}.ft2 a{color:inherit;text-decoration:none}.ft2 img{display:block;width:100%}.ft2Wrap{width:min(1320px,calc(100% - 56px));margin:0 auto}
        .ft2Demo{min-height:24px;background:#171717;color:#ddd;padding:5px 12px;text-align:center;font-size:8.5px;font-weight:800;letter-spacing:.09em;text-transform:uppercase}.ft2Demo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .ft2Nav{background:var(--cream);border-bottom:1px solid #171717}.ft2NavIn{height:54px;display:flex;align-items:center;justify-content:space-between;gap:24px}.ft2Brand{font-size:18px;font-weight:900;letter-spacing:-.05em}.ft2Links{display:flex;align-items:center;gap:24px;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.ft2ContactTop{background:var(--ink);color:#fff!important;padding:9px 12px}
        .ft2Hero{position:relative;min-height:680px;height:calc(100svh - 78px);max-height:820px;overflow:hidden;background:var(--coral)}.ft2HeroWord{position:absolute;left:2.5vw;top:47%;transform:translateY(-52%);z-index:5;font-size:clamp(82px,12.8vw,184px);line-height:.7;letter-spacing:-.1em;font-weight:900}.ft2HeroWord span{display:block}.ft2HeroWord .lav{color:var(--lav)}.ft2HeroCircle{position:absolute;right:7vw;top:9%;width:min(37vw,520px);aspect-ratio:1;border-radius:50%;overflow:hidden;border:12px solid var(--cream);z-index:3}.ft2HeroCircle img{height:100%;object-fit:cover;object-position:center 45%}.ft2HeroSmall{position:absolute;right:3vw;bottom:9%;width:min(23vw,320px);height:220px;overflow:hidden;transform:rotate(3deg);border:9px solid var(--lav);z-index:6}.ft2HeroSmall img{height:100%;object-fit:cover}.ft2HeroMeta{position:absolute;left:3vw;top:30px;font-size:10px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;z-index:6}.ft2HeroCopy{position:absolute;left:3vw;bottom:32px;width:390px;z-index:7;font-size:14px;line-height:1.55}.ft2HeroCopy p{margin:0 0 13px}.ft2HeroCopy a{font-size:10.5px;font-weight:900;border-bottom:1px solid #171717;padding-bottom:3px}
        .ft2PlaceStrip{background:#171717;color:#fff}.ft2PlaceStripIn{min-height:64px;display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap;font-size:11px}.ft2PlaceStripIn span,.ft2PlaceStripIn a{display:flex;align-items:center;gap:8px}
        .ft2Ticker{background:var(--lav);border-bottom:1px solid #171717;overflow:hidden;white-space:nowrap;padding:12px 0;font-size:15px;font-weight:900}.ft2Ticker span{display:inline-block;margin-right:48px}
        .ft2Schedule{padding:68px 0 78px}.ft2ScheduleHead{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:end;margin-bottom:26px}.ft2ScheduleHead h2{font-size:clamp(50px,6vw,82px);line-height:.84;letter-spacing:-.08em;margin:0}.ft2ScheduleHead p{max-width:520px;font-size:13px;line-height:1.55;margin:0;color:#5f5f5f}.ft2ScheduleHead strong{color:#171717}.ft2Rows{border-top:3px solid #171717}.ft2Row{display:grid;grid-template-columns:72px 110px 1fr 120px;gap:22px;align-items:center;padding:18px 0;border-bottom:1px solid var(--line)}.ft2Day{font-size:28px;font-weight:900}.ft2Time{font-size:17px;font-weight:800}.ft2Class{font-size:23px;font-weight:900;letter-spacing:-.035em}.ft2Meta{font-size:11px;color:#666;text-align:right}
        .ft2Classes{background:#171717;color:#fff}.ft2ClassBand{min-height:520px;position:relative;overflow:hidden;border-bottom:1px solid #444}.ft2ClassBand img{position:absolute;inset:0;height:100%;object-fit:cover;filter:saturate(.9) contrast(1.04);opacity:.74}.ft2ClassBand:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(0,0,0,.72),rgba(0,0,0,.18) 64%,rgba(0,0,0,.08))}.ft2ClassBand:nth-child(2):after{background:linear-gradient(90deg,rgba(0,0,0,.08),rgba(0,0,0,.15) 45%,rgba(0,0,0,.72))}.ft2ClassBandInner{position:relative;z-index:3;min-height:520px;display:flex;flex-direction:column;justify-content:flex-end;padding:50px 0}.ft2ClassBand h2{font-size:clamp(62px,8vw,108px);font-weight:900;line-height:.78;letter-spacing:-.085em;margin:0 0 16px;max-width:820px}.ft2ClassBand p{max-width:560px;font-size:14px;line-height:1.6;margin:0}.ft2ClassBand:nth-child(2) .ft2ClassBandInner{align-items:flex-end;text-align:right}.ft2ClassBand:nth-child(2) p{margin-left:auto}.ft2ClassLabel{position:absolute;top:30px;left:0;background:var(--coral);color:#171717;padding:8px 10px;font-size:9px;font-weight:900;letter-spacing:.08em}.ft2ClassBand:nth-child(2) .ft2ClassLabel{left:auto;right:0;background:var(--lav)}
        .ft2Bring{background:var(--mint);border-top:1px solid #171717;border-bottom:1px solid #171717}.ft2BringIn{min-height:84px;display:grid;grid-template-columns:170px repeat(4,1fr);gap:28px;align-items:center;font-size:11px}.ft2BringIn strong{font-size:15px}.ft2BringIn span{border-left:1px solid rgba(23,23,23,.28);padding-left:22px}
        .ft2Price{padding:78px 0 88px}.ft2PriceHead{font-size:clamp(52px,6.5vw,88px);font-weight:900;letter-spacing:-.08em;line-height:.82;margin:0 0 36px}.ft2Tickets{display:grid;grid-template-columns:1fr 1fr 1fr;border-top:3px solid #171717;border-bottom:3px solid #171717}.ft2Ticket{padding:25px;border-right:1px solid #171717;min-height:220px;display:flex;flex-direction:column;justify-content:space-between}.ft2Ticket:last-child{border-right:0}.ft2Ticket small{font-size:9px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.ft2Ticket b{font-size:clamp(48px,4.7vw,68px);letter-spacing:-.07em}.ft2Ticket p{font-size:11px;line-height:1.5;color:#666;margin:0}.ft2Ticket:nth-child(2){background:var(--lav)}.ft2Ticket:nth-child(3){background:var(--coral)}
        .ft2Trainer{padding:80px 0 90px;background:#fff}.ft2TrainerGrid{display:grid;grid-template-columns:1fr .8fr;gap:80px;align-items:end}.ft2TrainerTitle{font-size:clamp(62px,8vw,112px);font-weight:900;letter-spacing:-.09em;line-height:.74;margin:0 0 36px}.ft2TrainerCopy{max-width:540px;font-size:14px;line-height:1.65}.ft2Creds{display:flex;flex-wrap:wrap;gap:8px;margin-top:22px}.ft2Creds span{border:1px solid #171717;padding:7px 9px;font-size:9px;font-weight:800}.ft2TrainerPhoto{height:610px;overflow:hidden;border-radius:48% 48% 8px 8px}.ft2TrainerPhoto img{height:100%;object-fit:cover;object-position:center 30%}
        .ft2First{background:var(--lav);padding:60px 0}.ft2First h2{font-size:clamp(48px,5.8vw,78px);letter-spacing:-.075em;line-height:.84;margin:0 0 28px}.ft2FirstGrid{display:grid;grid-template-columns:repeat(3,1fr);border-top:2px solid #171717}.ft2FirstItem{padding:20px 24px 0 0;border-right:1px solid rgba(23,23,23,.35)}.ft2FirstItem:nth-child(2),.ft2FirstItem:last-child{padding-left:24px}.ft2FirstItem:last-child{border-right:0}.ft2FirstItem strong{display:block;font-size:16px;margin-bottom:8px}.ft2FirstItem p{font-size:12px;line-height:1.55;margin:0;color:#3f3658}
        .ft2Contact{background:#171717;color:#fff;padding:64px 0 68px}.ft2ContactHead{display:grid;grid-template-columns:.72fr 1.28fr;gap:70px;align-items:end;margin-bottom:34px}.ft2ContactHead h2{font-size:clamp(50px,6vw,82px);line-height:.82;letter-spacing:-.075em;margin:0}.ft2ContactHead p{max-width:560px;font-size:13px;line-height:1.6;color:#bbb;margin:0}.ft2ContactGrid{display:grid;grid-template-columns:1.2fr .8fr;gap:72px;align-items:start}.ft2Form{border-top:2px solid #fff}.ft2Field{display:grid;grid-template-columns:180px 1fr;border-bottom:1px solid #5c5c5c;align-items:start}.ft2Field label{padding:17px 14px 17px 0;font-size:9px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.ft2Field input,.ft2Field textarea{width:100%;border:0;background:transparent;color:#fff;padding:15px 0;font:inherit;font-size:13px;outline:none}.ft2Field input::placeholder,.ft2Field textarea::placeholder{color:#9d9d9d}.ft2Field textarea{min-height:92px;resize:vertical}.ft2ChoiceField{padding:13px 0 15px}.ft2ChoiceField>span{display:block;font-size:11px;color:#aaa;margin-bottom:10px}.ft2Choices{display:grid;grid-template-columns:1fr 1fr;gap:7px}.ft2Choice{position:relative;display:block}.ft2Choice input{position:absolute;opacity:0;pointer-events:none}.ft2Choice span{display:block;border:1px solid #616161;padding:10px 11px;font-size:10.5px;line-height:1.3;color:#ddd;cursor:pointer;transition:.15s}.ft2Choice input:checked+span{background:var(--lav);border-color:var(--lav);color:#171717}.ft2Choice span:hover{border-color:#fff}.ft2Form button{width:100%;min-height:48px;margin-top:14px;border:0;background:var(--coral);color:#171717;font-size:10px;font-weight:900;text-transform:uppercase;cursor:pointer}.ft2FormNote{font-size:9px;color:#999;margin-top:10px;line-height:1.45}.ft2Direct{border-top:2px solid #fff;padding-top:20px}.ft2Direct h3{font-size:26px;margin:0 0 14px}.ft2Direct>p:first-of-type{font-size:11.5px;line-height:1.55;color:#bbb;margin:0 0 10px}.ft2Direct a{display:flex;align-items:center;gap:9px;font-size:14px;font-weight:800;padding:13px 0;border-bottom:1px solid #555}.ft2Direct>p:last-child{font-size:10.5px;line-height:1.55;color:#8f8f8f;margin-top:18px}
        .ft2Footer{background:var(--coral);padding:34px 0}.ft2FooterIn{display:flex;align-items:center;justify-content:space-between;gap:30px}.ft2FooterName{font-size:28px;font-weight:900;letter-spacing:-.06em}.ft2FooterText{font-size:9.5px}.ft2FooterCta{background:#171717;color:#fff!important;padding:11px 13px;font-size:10px;font-weight:900}
        @media(max-width:980px){.ft2HeroCircle{width:46vw;right:4vw}.ft2HeroWord{font-size:clamp(80px,15vw,140px)}.ft2ScheduleHead,.ft2TrainerGrid,.ft2ContactHead,.ft2ContactGrid{grid-template-columns:1fr;gap:28px}.ft2Row{grid-template-columns:64px 95px 1fr auto}.ft2BringIn{grid-template-columns:1fr 1fr}.ft2BringIn strong{grid-column:1/-1}.ft2BringIn span{border-left:0;padding-left:0}.ft2TrainerPhoto{height:520px}.ft2TrainerGrid{align-items:start}.ft2Direct{margin-top:12px}}
        @media(max-width:680px){.ft2Wrap{width:min(100% - 28px,1320px)}.ft2Demo{font-size:7.5px}.ft2Links a:not(.ft2ContactTop){display:none}.ft2Hero{min-height:680px;height:auto}.ft2HeroWord{top:28%;font-size:clamp(70px,23vw,100px)}.ft2HeroCircle{width:74vw;right:-11vw;top:18%;border-width:8px}.ft2HeroSmall{width:45vw;height:170px;right:2vw;bottom:15%;border-width:7px}.ft2HeroCopy{left:14px;bottom:22px;width:80%;font-size:13px}.ft2PlaceStripIn{padding:12px 0;justify-content:flex-start}.ft2Schedule{padding:54px 0}.ft2Row{grid-template-columns:52px 74px 1fr;gap:10px}.ft2Meta{grid-column:3;text-align:left}.ft2Class{font-size:18px}.ft2ClassBand,.ft2ClassBandInner{min-height:480px}.ft2ClassBand h2{font-size:54px}.ft2BringIn{grid-template-columns:1fr;padding:18px 0;gap:10px}.ft2Tickets{grid-template-columns:1fr}.ft2Ticket{border-right:0;border-bottom:1px solid #171717}.ft2TrainerPhoto{height:500px}.ft2FirstGrid{grid-template-columns:1fr}.ft2FirstItem,.ft2FirstItem:nth-child(2),.ft2FirstItem:last-child{padding:18px 0;border-right:0;border-bottom:1px solid rgba(23,23,23,.3)}.ft2Field{grid-template-columns:1fr}.ft2Field label{padding-bottom:0}.ft2Choices{grid-template-columns:1fr}.ft2FooterIn{display:grid}.ft2FooterCta{justify-self:start}}
      `}</style>

      <div className="ft2Demo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <nav className="ft2Nav"><div className="ft2Wrap ft2NavIn"><a className="ft2Brand" href="#top">TEREZA NOVÁKOVÁ</a><div className="ft2Links"><a href="#rozvrh">Rozvrh</a><a href="#lekce">Lekce</a><a href="#cenik">Vstupné</a><a href="#trenerka">Trenérka</a><a className="ft2ContactTop" href="#kontakt">Kontakt</a></div></div></nav>

      <header className="ft2Hero"><div className="ft2HeroMeta">KRUHOVÝ TRÉNINK · CARDIO DANCE · ČESKÉ BUDĚJOVICE</div><div className="ft2HeroWord"><span>TEREZA</span><span className="lav">MOVE</span></div><div className="ft2HeroCircle"><img src="https://images.pexels.com/photos/3768695/pexels-photo-3768695.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Skupina žen při skupinovém fitness tréninku"/></div><div className="ft2HeroSmall"><img src="https://images.pexels.com/photos/8957646/pexels-photo-8957646.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Skupinová cardio dance lekce"/></div><div className="ft2HeroCopy"><p>Skupinové lekce v menším sále. Kruhový trénink pro sílu a kondici, cardio dance pro tempo a pohyb.</p><a href="#rozvrh">Zobrazit rozvrh →</a></div></header>

      <div className="ft2PlaceStrip"><div className="ft2Wrap ft2PlaceStripIn"><span><MapPin size={14}/> Studio MOVE · Lannova 12 · České Budějovice · 1. patro</span><a href="tel:+420705911941"><Phone size={14}/> +420 705 911 941</a><a href="mailto:kontakt@spustweb.cz"><Mail size={14}/> kontakt@spustweb.cz</a></div></div>
      <div className="ft2Ticker"><span>KRUHOVÝ TRÉNINK</span><span>CARDIO DANCE</span><span>MAX. 12 LIDÍ</span><span>ČESKÉ BUDĚJOVICE</span><span>KRUHOVÝ TRÉNINK</span></div>

      <section className="ft2Schedule" id="rozvrh"><div className="ft2Wrap"><div className="ft2ScheduleHead"><h2>Tento týden.</h2><p>Lekce probíhají ve <strong>Studiu MOVE, Lannova 12, České Budějovice, 1. patro.</strong> Kapacita jedné skupiny je maximálně 12 lidí.</p></div><div className="ft2Rows">{schedule.map(([day,time,name,duration])=><div className="ft2Row" key={`${day}-${time}`}><div className="ft2Day">{day}</div><div className="ft2Time">{time}</div><div className="ft2Class">{name}</div><div className="ft2Meta">{duration}</div></div>)}</div></div></section>

      <section className="ft2Classes" id="lekce"><article className="ft2ClassBand"><img src="https://images.pexels.com/photos/3775524/pexels-photo-3775524.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="Skupina žen při kruhovém tréninku s činkami"/><div className="ft2Wrap ft2ClassBandInner"><div className="ft2ClassLabel">SÍLA + KONDICE</div><h2>Kruhový trénink.</h2><p>Stanoviště se střídají v krátkých intervalech. Vlastní váha, činky, gumy a jednoduché kondiční prvky. Intenzitu lze upravit podle zkušeností.</p></div></article><article className="ft2ClassBand"><img src="https://images.pexels.com/photos/8957646/pexels-photo-8957646.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="Ženy při cardio dance lekci ve světlém sále"/><div className="ft2Wrap ft2ClassBandInner"><div className="ft2ClassLabel">KARDIO + TANEC</div><h2>Cardio Dance.</h2><p>Jednoduché taneční kombinace v tempu hudby. Lekce je zaměřená na kondici a pohyb, ne na zvládnutí složité choreografie.</p></div></article></section>

      <section className="ft2Bring"><div className="ft2Wrap ft2BringIn"><strong>Na lekci</strong><span>čisté sportovní boty</span><span>pití</span><span>ručník</span><span>dorazit 10 minut před začátkem</span></div></section>

      <section className="ft2Price" id="cenik"><div className="ft2Wrap"><h2 className="ft2PriceHead">Vstupné.</h2><div className="ft2Tickets"><div className="ft2Ticket"><small>Jednorázový vstup</small><b>190 Kč</b><p>Jedna vybraná skupinová lekce.</p></div><div className="ft2Ticket"><small>5 vstupů</small><b>850 Kč</b><p>Platnost 8 týdnů od prvního vstupu.</p></div><div className="ft2Ticket"><small>10 vstupů</small><b>1 550 Kč</b><p>Platnost 12 týdnů od prvního vstupu.</p></div></div></div></section>

      <section className="ft2Trainer" id="trenerka"><div className="ft2Wrap ft2TrainerGrid"><div><h2 className="ft2TrainerTitle">Tereza<br/>Nováková.</h2><div className="ft2TrainerCopy">Tereza vede skupinové kondiční a dance fitness lekce. Kruhový trénink staví na jednoduchých stanovištích a práci v malé skupině, cardio dance na pohybu v tempu hudby.<div className="ft2Creds"><span>fitness instruktor</span><span>skupinové lekce</span><span>kruhový trénink</span><span>dance fitness</span></div></div></div><div className="ft2TrainerPhoto"><img src="https://images.pexels.com/photos/6739930/pexels-photo-6739930.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Fitness trenérka Tereza v tělocvičně"/></div></div></section>

      <section className="ft2First"><div className="ft2Wrap"><h2>Jdete poprvé?</h2><div className="ft2FirstGrid"><div className="ft2FirstItem"><strong>Není potřeba zkušenost</strong><p>U kruhového tréninku lze upravit obtížnost. U cardio dance se jede podle jednoduchých opakujících se kombinací.</p></div><div className="ft2FirstItem"><strong>Stačí běžné sportovní oblečení</strong><p>Není potřeba vlastní vybavení. Pomůcky jsou připravené v sále.</p></div><div className="ft2FirstItem"><strong>Ozvěte se předem</strong><p>Do zprávy stačí napsat vybranou lekci a kontakt. Potvrzení účasti se domluví následně.</p></div></div></div></section>

      <section className="ft2Contact" id="kontakt"><div className="ft2Wrap"><div className="ft2ContactHead"><h2>Kontakt.</h2><p>Chcete přijít na konkrétní lekci? Napište den a typ lekce. Odpověď potvrdí, zda je pro vás místo.</p></div><div className="ft2ContactGrid"><form className="ft2Form"><div className="ft2Field"><label htmlFor="ft2-name">Jméno</label><input id="ft2-name" type="text" placeholder="Vaše jméno"/></div><div className="ft2Field"><label htmlFor="ft2-phone">Telefon</label><input id="ft2-phone" type="tel" placeholder="Např. +420 777 123 456"/></div><div className="ft2Field"><label htmlFor="ft2-email">E-mail</label><input id="ft2-email" type="email" placeholder="vas@email.cz"/></div><div className="ft2Field"><label>Lekce</label><div className="ft2ChoiceField"><span>Vyberte lekci</span><div className="ft2Choices"><label className="ft2Choice"><input type="radio" name="lesson"/><span>Po 17:30 · Kruhový trénink</span></label><label className="ft2Choice"><input type="radio" name="lesson"/><span>Út 18:30 · Cardio Dance</span></label><label className="ft2Choice"><input type="radio" name="lesson"/><span>Čt 17:30 · Kruhový trénink</span></label><label className="ft2Choice"><input type="radio" name="lesson"/><span>So 09:30 · Cardio Dance</span></label></div></div></div><div className="ft2Field"><label htmlFor="ft2-message">Zpráva</label><textarea id="ft2-message" placeholder="Doplňující informace"/></div><button type="button">Odeslat zprávu</button><div className="ft2FormNote">Ukázkový formulář na této demonstrační stránce se neodesílá.</div></form><div className="ft2Direct"><h3>Studio MOVE</h3><p>Lannova 12 · České Budějovice · 1. patro<br/>Vchod z Lannovy třídy. V zázemí je šatna.</p><a href="tel:+420705911941"><Phone size={17}/> +420 705 911 941</a><a href="mailto:kontakt@spustweb.cz"><Mail size={17}/> kontakt@spustweb.cz</a><p>Kontaktní údaje v této ukázce vedou na SpustWeb.cz. Tereza MOVE je fiktivní koncept.</p></div></div></div></section>

      <footer className="ft2Footer"><div className="ft2Wrap ft2FooterIn"><div className="ft2FooterName">TEREZA MOVE</div><div className="ft2FooterText">Fiktivní fitness trenérka · ukázkový koncept SpustWeb.cz</div><a className="ft2FooterCta" href="/#kontakt">Podobný web pro moje podnikání</a></div></footer>
    </div>
  )
}
