import type { Metadata } from 'next'
import { ArrowRight, CalendarDays, Clock3, MapPin, Phone } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro fitness trenérku | SpustWeb.cz',
  description: 'Ukázka webu pro fitness trenérku: kruhový trénink, cardio dance, rozvrh lekcí, ceník, trenérka a přihlášení.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/fitness-trenerka/' },
  robots: { index: true, follow: true },
}

const schedule = [
  ['PO', '17:30', 'Kruhový trénink', '55 min', '4 místa'],
  ['ÚT', '18:30', 'Cardio Dance', '50 min', '6 míst'],
  ['ČT', '17:30', 'Kruhový trénink', '55 min', '3 místa'],
  ['SO', '09:30', 'Cardio Dance', '50 min', '8 míst'],
]

export default function FitnessTrainerShowcase() {
  return (
    <div className="ft2" id="top">
      <style>{`
        body:has(.ft2) > .verno-nav-shell,body:has(.ft2) > .footer{display:none!important}
        body:has(.ft2) main{padding:0!important;margin:0!important}
        body:has(.ft2){background:#fff7ea!important}
        .ft2{--ink:#171717;--cream:#fff7ea;--coral:#ff6a57;--lav:#b9a7ff;--mint:#45cdb7;--white:#fff;--line:rgba(23,23,23,.2);font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--cream)}
        .ft2 *{box-sizing:border-box}.ft2 a{color:inherit;text-decoration:none}.ft2 img{display:block;width:100%}.ftWrap{width:min(1240px,calc(100% - 56px));margin:0 auto}
        .ftDemo{min-height:24px;background:#171717;color:#ddd;padding:5px 12px;text-align:center;font-size:8.5px;font-weight:800;letter-spacing:.09em;text-transform:uppercase}.ftDemo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .ftNav{background:var(--cream);border-bottom:1px solid #171717}.ftNavIn{height:52px;display:flex;align-items:center;justify-content:space-between;gap:24px}.ftBrand{font-size:17px;font-weight:900;letter-spacing:-.04em}.ftLinks{display:flex;align-items:center;gap:22px;font-size:9.5px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.ftJoin{background:var(--ink);color:#fff!important;padding:9px 12px}

        .ftHero{background:var(--coral);padding:38px 0 30px;overflow:hidden}.ftHeroGrid{min-height:610px;display:grid;grid-template-columns:1.04fr .96fr;gap:42px;align-items:center}.ftHeroLeft{align-self:stretch;display:flex;flex-direction:column;justify-content:space-between;padding:12px 0}.ftHeroMeta{font-size:9.5px;font-weight:900;letter-spacing:.13em;text-transform:uppercase}.ftHero h1{font-size:clamp(84px,10vw,154px);line-height:.73;letter-spacing:-.095em;font-weight:900;margin:28px 0 30px}.ftHero h1 span{display:block;color:var(--lav)}.ftHeroCopy{max-width:430px;font-size:14px;line-height:1.58}.ftHeroCopy p{margin:0 0 14px}.ftHeroCopy a{font-size:10.5px;font-weight:900;border-bottom:1px solid #171717;padding-bottom:3px}.ftHeroVisual{position:relative;min-height:560px}.ftHeroCircle{position:absolute;right:0;top:0;width:86%;aspect-ratio:1;border-radius:50%;overflow:hidden;border:12px solid var(--cream)}.ftHeroCircle img{height:100%;object-fit:cover;object-position:center 45%}.ftHeroSmall{position:absolute;left:0;bottom:8px;width:48%;height:220px;overflow:hidden;transform:rotate(-3deg);border:8px solid var(--lav);background:#ddd}.ftHeroSmall img{height:100%;object-fit:cover}

        .ftVenue{background:var(--ink);color:#fff}.ftVenueIn{min-height:68px;display:grid;grid-template-columns:170px 1.5fr 1fr auto;gap:26px;align-items:center;font-size:11px}.ftVenue strong{font-size:13px}.ftVenue span{display:flex;align-items:center;gap:8px;color:#d8d8d8}.ftVenue a{font-size:10px;font-weight:900;border-bottom:1px solid #fff;padding-bottom:3px}
        .ftTicker{background:var(--lav);border-bottom:1px solid #171717;overflow:hidden;white-space:nowrap;padding:11px 0;font-size:14px;font-weight:900}.ftTicker span{display:inline-block;margin-right:42px}

        .ftSchedule{padding:68px 0 78px;background:var(--cream)}.ftScheduleHead{display:grid;grid-template-columns:.9fr 1.1fr;gap:70px;align-items:end;margin-bottom:28px}.ftScheduleHead h2{font-size:clamp(52px,5.8vw,80px);line-height:.84;letter-spacing:-.075em;margin:0;font-weight:500}.ftScheduleInfo{display:grid;gap:8px;font-size:12px;line-height:1.5;color:#5d5d5d}.ftScheduleInfo strong{color:#171717}.ftRows{border-top:3px solid #171717}.ftRow{display:grid;grid-template-columns:64px 100px 1fr 90px 92px auto;gap:20px;align-items:center;padding:18px 0;border-bottom:1px solid var(--line)}.ftDay{font-size:25px;font-weight:900}.ftTime{font-size:16px;font-weight:800}.ftClass{font-size:21px;font-weight:900;letter-spacing:-.03em}.ftMeta{font-size:10.5px;color:#666}.ftSpot{font-size:9.5px;font-weight:900;background:var(--mint);padding:7px 9px;justify-self:start}.ftRow a{font-size:9.5px;font-weight:900;border-bottom:1px solid #171717;padding-bottom:3px}

        .ftClasses{background:#171717;color:#fff}.ftClassBand{min-height:500px;position:relative;overflow:hidden;border-bottom:1px solid #444}.ftClassBand img{position:absolute;inset:0;height:100%;object-fit:cover;filter:saturate(.9) contrast(1.04);opacity:.72}.ftClassBand:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(0,0,0,.7),rgba(0,0,0,.2) 62%,rgba(0,0,0,.05))}.ftClassBand:nth-child(2):after{background:linear-gradient(90deg,rgba(0,0,0,.08),rgba(0,0,0,.18) 45%,rgba(0,0,0,.72))}.ftClassBandInner{position:relative;z-index:3;min-height:500px;display:flex;flex-direction:column;justify-content:flex-end;padding:46px 0}.ftClassBand h2{font-size:clamp(62px,7.8vw,104px);font-weight:900;line-height:.78;letter-spacing:-.08em;margin:0 0 16px;max-width:760px}.ftClassBand p{max-width:540px;font-size:13.5px;line-height:1.6;margin:0}.ftClassBand:nth-child(2) .ftClassBandInner{align-items:flex-end;text-align:right}.ftClassBand:nth-child(2) p{margin-left:auto}.ftClassLabel{position:absolute;top:28px;left:0;background:var(--coral);color:#171717;padding:8px 10px;font-size:8.5px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.ftClassBand:nth-child(2) .ftClassLabel{left:auto;right:0;background:var(--lav)}

        .ftBring{background:var(--mint);border-bottom:1px solid #171717}.ftBringIn{min-height:74px;display:grid;grid-template-columns:150px repeat(4,1fr);gap:24px;align-items:center;font-size:10.5px}.ftBringIn strong{font-size:14px}.ftBringIn span{border-left:1px solid rgba(23,23,23,.28);padding-left:20px}

        .ftPrice{padding:74px 0 82px;background:var(--cream)}.ftPriceHead{font-size:clamp(50px,6vw,80px);font-weight:900;letter-spacing:-.075em;line-height:.82;margin:0 0 34px}.ftTickets{display:grid;grid-template-columns:1fr 1fr 1fr;border-top:3px solid #171717;border-bottom:3px solid #171717}.ftTicket{padding:24px;min-height:200px;display:flex;flex-direction:column;justify-content:space-between;border-right:1px solid #171717}.ftTicket:last-child{border-right:0}.ftTicket small{font-size:8.5px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.ftTicket b{font-size:clamp(46px,4.7vw,66px);letter-spacing:-.06em}.ftTicket p{font-size:10.5px;line-height:1.5;color:#666;margin:0}.ftTicket:nth-child(2){background:var(--lav)}.ftTicket:nth-child(3){background:var(--coral)}

        .ftTrainer{padding:84px 0 88px;background:#fff}.ftTrainerGrid{display:grid;grid-template-columns:.92fr 1.08fr;gap:70px;align-items:center}.ftTrainerText h2{font-size:clamp(58px,7.2vw,98px);font-weight:900;letter-spacing:-.085em;line-height:.78;margin:0 0 30px}.ftTrainerText p{max-width:520px;font-size:13.5px;line-height:1.65;margin:0 0 22px}.ftTrainerPhoto{height:590px;overflow:hidden;border-radius:48% 48% 10px 10px}.ftTrainerPhoto img{height:100%;object-fit:cover;object-position:center 30%}.ftCreds{display:flex;flex-wrap:wrap;gap:8px}.ftCreds span{border:1px solid #171717;padding:7px 9px;font-size:8.5px;font-weight:800}

        .ftFirst{background:var(--lav);padding:58px 0 64px}.ftFirst h2{font-size:clamp(46px,5.8vw,76px);letter-spacing:-.07em;line-height:.84;margin:0 0 26px;font-weight:500}.ftFirstGrid{display:grid;grid-template-columns:repeat(3,1fr);border-top:2px solid #171717}.ftFirstItem{padding:20px 22px 0 0;border-right:1px solid rgba(23,23,23,.35)}.ftFirstItem:nth-child(2),.ftFirstItem:last-child{padding-left:22px}.ftFirstItem:last-child{border-right:0}.ftFirstItem strong{display:block;font-size:15px;margin-bottom:7px}.ftFirstItem p{font-size:11.5px;line-height:1.55;margin:0;color:#3f3658}

        .ftPlace{background:#171717;color:#fff;padding:62px 0}.ftPlaceIn{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:start}.ftPlace h2{font-size:clamp(48px,6vw,78px);line-height:.83;letter-spacing:-.075em;margin:0}.ftPlaceRight{display:grid;grid-template-columns:1fr 1fr;gap:28px}.ftPlaceData{display:grid;gap:11px;font-size:11.5px;color:#bbb}.ftPlaceData span{display:flex;align-items:flex-start;gap:8px}.ftPlaceData strong{color:#fff}.ftPlaceNote{font-size:11.5px;line-height:1.6;color:#bbb}.ftPlaceNote strong{color:#fff}.ftSignup{margin-top:20px;display:flex;gap:10px;flex-wrap:wrap}.ftSignup a{background:var(--coral);color:#171717!important;padding:11px 13px;font-size:9.5px;font-weight:900}.ftSignup a:last-child{background:transparent;color:#fff!important;border:1px solid #fff}

        .ftFooter{background:var(--coral);padding:30px 0}.ftFooterIn{display:flex;align-items:center;justify-content:space-between;gap:30px}.ftFooterName{font-size:25px;font-weight:900;letter-spacing:-.05em}.ftFooterText{font-size:9px}.ftFooterCta{background:#171717;color:#fff!important;padding:10px 12px;font-size:9.5px;font-weight:900}

        @media(max-width:980px){.ftHeroGrid{grid-template-columns:1fr;min-height:0}.ftHeroVisual{min-height:500px}.ftHeroCircle{width:64%;right:4%}.ftHeroSmall{width:34%}.ftVenueIn{grid-template-columns:1fr 1fr}.ftScheduleHead,.ftTrainerGrid,.ftPlaceIn{grid-template-columns:1fr;gap:28px}.ftRow{grid-template-columns:56px 90px 1fr auto}.ftMeta{display:none}.ftSpot{justify-self:end}.ftBringIn{grid-template-columns:1fr 1fr}.ftBringIn strong{grid-column:1/-1}.ftBringIn span{border-left:0;padding-left:0}.ftPlaceRight{grid-template-columns:1fr 1fr}}
        @media(max-width:680px){.ftWrap{width:min(100% - 28px,1240px)}.ftDemo{font-size:7.5px}.ftLinks a:not(.ftJoin){display:none}.ftHero{padding:26px 0}.ftHero h1{font-size:72px;margin:20px 0}.ftHeroVisual{min-height:420px}.ftHeroCircle{width:82%;right:-8%;border-width:8px}.ftHeroSmall{width:46%;height:160px;border-width:6px}.ftVenueIn{grid-template-columns:1fr;padding:15px 0;gap:8px}.ftTicker{font-size:12px}.ftSchedule{padding:52px 0}.ftRow{grid-template-columns:48px 70px 1fr;gap:9px}.ftSpot{grid-column:2;justify-self:start}.ftRow a{grid-column:3;justify-self:start}.ftClass{font-size:17px}.ftClassBand,.ftClassBandInner{min-height:470px}.ftClassBand h2{font-size:52px}.ftBringIn{grid-template-columns:1fr;padding:16px 0;gap:8px}.ftTickets{grid-template-columns:1fr}.ftTicket{border-right:0;border-bottom:1px solid #171717}.ftTrainerPhoto{height:480px}.ftFirstGrid{grid-template-columns:1fr}.ftFirstItem,.ftFirstItem:nth-child(2),.ftFirstItem:last-child{padding:16px 0;border-right:0;border-bottom:1px solid rgba(23,23,23,.3)}.ftPlaceRight{grid-template-columns:1fr}.ftFooterIn{display:grid}.ftFooterCta{justify-self:start}}
      `}</style>

      <div className="ftDemo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <nav className="ftNav"><div className="ftWrap ftNavIn"><a className="ftBrand" href="#top">TEREZA NOVÁKOVÁ</a><div className="ftLinks"><a href="#rozvrh">Rozvrh</a><a href="#lekce">Lekce</a><a href="#cenik">Vstupné</a><a href="#trenerka">Trenérka</a><a className="ftJoin" href="#prihlaseni">Přihlásit se</a></div></div></nav>

      <header className="ftHero"><div className="ftWrap ftHeroGrid"><div className="ftHeroLeft"><div className="ftHeroMeta">KRUHOVÝ TRÉNINK · CARDIO DANCE · ČESKÉ BUDĚJOVICE</div><div><h1>TEREZA<span>MOVE</span></h1><div className="ftHeroCopy"><p>Skupinové lekce v malé skupině. Kruhový trénink pro sílu a kondici, cardio dance pro tempo a pohyb.</p><a href="#rozvrh">Zobrazit rozvrh →</a></div></div></div><div className="ftHeroVisual"><div className="ftHeroCircle"><img src="https://images.pexels.com/photos/3768695/pexels-photo-3768695.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Skupina žen při skupinovém fitness tréninku"/></div><div className="ftHeroSmall"><img src="https://images.pexels.com/photos/8957646/pexels-photo-8957646.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Skupinová cardio dance lekce"/></div></div></div></header>

      <section className="ftVenue"><div className="ftWrap ftVenueIn"><strong>Kde cvičíme</strong><span><MapPin size={14}/>Studio MOVE · Lannova 12 · České Budějovice</span><span>1. patro · šatna v zázemí</span><a href="#prihlaseni">Praktické informace ↓</a></div></section>
      <div className="ftTicker"><span>KRUHOVÝ TRÉNINK</span><span>CARDIO DANCE</span><span>MAX. 12 LIDÍ</span><span>STUDIO MOVE · LANNOVA 12</span><span>KRUHOVÝ TRÉNINK</span><span>CARDIO DANCE</span></div>

      <section className="ftSchedule" id="rozvrh"><div className="ftWrap"><div className="ftScheduleHead"><h2>Tento týden.</h2><div className="ftScheduleInfo"><strong>Studio MOVE · Lannova 12 · České Budějovice</strong><span>Kapacita každé lekce je 12 lidí. Na lekci je potřeba se předem přihlásit.</span></div></div><div className="ftRows">{schedule.map(([day,time,name,duration,spots])=><div className="ftRow" key={`${day}-${time}`}><div className="ftDay">{day}</div><div className="ftTime">{time}</div><div className="ftClass">{name}</div><div className="ftMeta">{duration}</div><div className="ftSpot">{spots}</div><a href="#prihlaseni">Přihlásit se</a></div>)}</div></div></section>

      <section className="ftClasses" id="lekce"><article className="ftClassBand"><img src="https://images.pexels.com/photos/3775524/pexels-photo-3775524.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="Skupina žen při kruhovém tréninku s činkami"/><div className="ftWrap ftClassBandInner"><div className="ftClassLabel">SÍLA + KONDICE</div><h2>Kruhový trénink.</h2><p>Stanoviště se střídají v krátkých intervalech. Vlastní váha, činky, gumy a jednoduché kondiční prvky. Intenzitu lze upravit podle zkušeností.</p></div></article><article className="ftClassBand"><img src="https://images.pexels.com/photos/8957646/pexels-photo-8957646.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="Ženy při cardio dance lekci ve světlém sále"/><div className="ftWrap ftClassBandInner"><div className="ftClassLabel">KARDIO + TANEC</div><h2>Cardio Dance.</h2><p>Jednoduché taneční kombinace v tempu hudby. Lekce je zaměřená na kondici a pohyb, ne na zvládnutí složité choreografie.</p></div></article></section>

      <section className="ftBring"><div className="ftWrap ftBringIn"><strong>Na lekci</strong><span>čisté sportovní boty</span><span>pití</span><span>ručník</span><span>dorazit 10 minut před začátkem</span></div></section>

      <section className="ftPrice" id="cenik"><div className="ftWrap"><h2 className="ftPriceHead">Vstupné.</h2><div className="ftTickets"><div className="ftTicket"><small>Jednorázový vstup</small><b>190 Kč</b><p>Jedna vybraná skupinová lekce.</p></div><div className="ftTicket"><small>5 vstupů</small><b>850 Kč</b><p>Platnost 8 týdnů od prvního vstupu.</p></div><div className="ftTicket"><small>10 vstupů</small><b>1 550 Kč</b><p>Platnost 12 týdnů od prvního vstupu.</p></div></div></div></section>

      <section className="ftTrainer" id="trenerka"><div className="ftWrap ftTrainerGrid"><div className="ftTrainerText"><h2>Tereza<br/>Nováková.</h2><p>Vede skupinové kondiční a dance fitness lekce. Kruhový trénink staví na jednoduchých stanovištích a práci v malé skupině, cardio dance na pohybu v tempu hudby.</p><div className="ftCreds"><span>fitness instruktor</span><span>skupinové lekce</span><span>kruhový trénink</span><span>dance fitness</span></div></div><div className="ftTrainerPhoto"><img src="https://images.pexels.com/photos/6739930/pexels-photo-6739930.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Fitness trenérka Tereza v tělocvičně"/></div></div></section>

      <section className="ftFirst"><div className="ftWrap"><h2>Jdete poprvé?</h2><div className="ftFirstGrid"><div className="ftFirstItem"><strong>Není potřeba zkušenost</strong><p>U kruhového tréninku lze upravit obtížnost. U cardio dance se jede podle jednoduchých opakujících se kombinací.</p></div><div className="ftFirstItem"><strong>Stačí běžné sportovní oblečení</strong><p>Není potřeba vlastní vybavení. Pomůcky jsou připravené v sále.</p></div><div className="ftFirstItem"><strong>Přihlášení předem</strong><p>Skupina je omezená na 12 lidí, proto se místo vybírá z aktuálního rozvrhu.</p></div></div></div></section>

      <section className="ftPlace" id="prihlaseni"><div className="ftWrap ftPlaceIn"><h2>Studio MOVE.<br/>Lannova 12.</h2><div className="ftPlaceRight"><div><div className="ftPlaceData"><span><MapPin size={15}/><strong>Lannova 12 · České Budějovice</strong></span><span><Clock3 size={15}/>Po, Út, Čt a So podle rozvrhu</span><span><Phone size={15}/>777 000 000</span><span><CalendarDays size={15}/>přihlášení na konkrétní lekci předem</span></div><div className="ftSignup"><a href="#rozvrh">Vybrat lekci <ArrowRight size={13}/></a><a href="tel:777000000">Zavolat</a></div></div><div className="ftPlaceNote"><strong>Po příchodu:</strong><br/>vchod z Lannovy třídy, studio je v 1. patře. V zázemí je šatna a místo na odložení věcí. Na první návštěvu stačí přijít přibližně 10 minut před začátkem.</div></div></div></section>

      <footer className="ftFooter"><div className="ftWrap ftFooterIn"><div className="ftFooterName">TEREZA MOVE</div><div className="ftFooterText">Fiktivní fitness trenérka · ukázkový koncept SpustWeb.cz</div><a className="ftFooterCta" href="/#kontakt">Podobný web pro moje podnikání</a></div></footer>
    </div>
  )
}
