import type { Metadata } from 'next'
import { Mail, MapPin, Phone } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro barber shop | SpustWeb.cz',
  description: 'Ukázka webu pro barber shop: střihy, vousy, ceník, barbeři, práce, provozovna a kontakt.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/barber/' },
  robots: { index: true, follow: true },
}

const services = [
  ['Pánský střih', '650 Kč', 'Střih nůžkami a strojkem, mytí a styling.'],
  ['Střih strojkem', '450 Kč', 'Krátký střih bez práce nůžkami.'],
  ['Střih + vousy', '950 Kč', 'Kompletní střih vlasů a úprava vousů při jedné návštěvě.'],
  ['Úprava vousů', '450 Kč', 'Zastřižení, tvar, kontury a závěrečná péče.'],
  ['Holení břitvou', '550 Kč', 'Napaření, holení břitvou a ošetření pokožky.'],
  ['Dětský střih do 12 let', '490 Kč', 'Klasický pánský střih pro mladší klienty.'],
]

const work = [
  ['https://images.pexels.com/photos/7781848/pexels-photo-7781848.jpeg?auto=compress&cs=tinysrgb&w=1600', 'Hotový krátký pánský střih s čistou konturou'],
  ['https://images.pexels.com/photos/4625632/pexels-photo-4625632.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Detail strojkového střihu při práci'],
  ['https://images.pexels.com/photos/2035310/pexels-photo-2035310.jpeg?auto=compress&cs=tinysrgb&w=1500', 'Úprava vousů v barbershopu'],
  ['https://images.pexels.com/photos/10003357/pexels-photo-10003357.jpeg?auto=compress&cs=tinysrgb&w=1500', 'Hotový střih a upravené vousy'],
]

const barbers = [
  ['Marek', 'fade · delší vlasy', 'https://images.pexels.com/photos/4625614/pexels-photo-4625614.jpeg?auto=compress&cs=tinysrgb&w=1500'],
  ['David', 'vousy · břitva · klasika', 'https://images.pexels.com/photos/7518735/pexels-photo-7518735.jpeg?auto=compress&cs=tinysrgb&w=1500'],
  ['Tomáš', 'krátké střihy · crop · styling', 'https://images.pexels.com/photos/9992818/pexels-photo-9992818.jpeg?auto=compress&cs=tinysrgb&w=1500'],
]

export default function BarberShowcase() {
  return (
    <div className="br6" id="top">
      <style>{`
        body:has(.br6) > .verno-nav-shell,body:has(.br6) > .footer{display:none!important}
        body:has(.br6) main{padding:0!important;margin:0!important}
        body:has(.br6){background:#f1ede4!important}
        .br6{--ink:#111;--paper:#f1ede4;--blue:#1844c7;--rust:#bd5d34;--acid:#d8f64c;--line:rgba(17,17,17,.22);font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--paper)}
        .br6 *{box-sizing:border-box}.br6 a{color:inherit;text-decoration:none}.br6 img{display:block;width:100%}.br6Wrap{width:min(1320px,calc(100% - 56px));margin:0 auto}
        .br6Demo{min-height:24px;padding:5px 12px;background:#111;color:#d8d8d8;text-align:center;font-size:8.5px;font-weight:800;letter-spacing:.09em;text-transform:uppercase}.br6Demo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .br6Nav{background:var(--paper);border-bottom:1px solid #111}.br6NavIn{height:54px;display:flex;align-items:center;justify-content:space-between;gap:24px}.br6Brand{font-size:19px;font-weight:900;letter-spacing:-.05em}.br6Links{display:flex;align-items:center;gap:24px;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.br6ContactTop{background:#111;color:#fff!important;padding:9px 12px}
        .br6Hero{overflow:hidden;background:var(--paper)}.br6HeroGrid{height:calc(100svh - 78px);min-height:650px;max-height:850px;display:grid;grid-template-columns:repeat(12,1fr);grid-template-rows:1fr 1fr;gap:12px;position:relative;padding:24px 0 28px}.br6HeroMeta{position:absolute;left:0;top:26px;font-size:9.5px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;z-index:5}.br6HeroWord{position:absolute;left:0;top:46%;transform:translateY(-50%);z-index:6;font-size:clamp(86px,12.5vw,182px);font-weight:900;line-height:.69;letter-spacing:-.1em;max-width:920px;pointer-events:none}.br6HeroWord span{display:block}.br6HeroWord .br6Num{color:var(--blue)}.br6HeroMain{grid-column:7/13;grid-row:1/3;margin:0;overflow:hidden;background:#ccc}.br6HeroMain img{height:100%;object-fit:cover;object-position:center 42%;filter:saturate(.8) contrast(1.02)}.br6HeroDetail{grid-column:5/8;grid-row:2;margin:0 0 12px;height:230px;align-self:end;overflow:hidden;border:9px solid var(--paper);z-index:7}.br6HeroDetail img{height:100%;object-fit:cover}.br6HeroCopy{position:absolute;left:0;bottom:34px;width:390px;z-index:8;font-size:14px;line-height:1.58}.br6HeroCopy p{margin:0 0 14px}.br6HeroCopy a{font-size:10.5px;font-weight:900;border-bottom:1px solid #111;padding-bottom:3px}.br6HeroTag{position:absolute;right:20px;bottom:20px;background:var(--rust);color:#fff;z-index:8;padding:14px 17px;font-size:9px;font-weight:900;line-height:1.25;transform:rotate(2deg)}
        .br6Facts{background:var(--blue);color:#fff}.br6FactsIn{min-height:58px;display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap;font-size:10.5px}.br6FactsIn a,.br6FactsIn span{display:flex;align-items:center;gap:7px}
        .br6Menu{padding:82px 0 96px}.br6MenuTop{display:flex;justify-content:space-between;align-items:end;gap:50px;margin-bottom:38px}.br6MenuTop h2{font-size:clamp(58px,6.8vw,94px);font-weight:900;letter-spacing:-.085em;line-height:.78;margin:0}.br6MenuTop p{max-width:470px;font-size:13.5px;line-height:1.6;color:#555;margin:0}.br6MenuList{border-top:4px solid #111}.br6Service{display:grid;grid-template-columns:1fr auto;gap:7px 30px;padding:22px 0 20px;border-bottom:1px solid var(--line)}.br6Service strong{font-size:clamp(24px,2.4vw,34px);letter-spacing:-.045em}.br6Service b{font-size:15px;align-self:center}.br6Service p{grid-column:1/-1;margin:0;font-size:12px;line-height:1.5;color:#626262;max-width:620px}
        .br6Work{background:#fff;padding:80px 0 96px}.br6WorkTop{display:grid;grid-template-columns:.78fr 1.22fr;gap:70px;align-items:end;margin-bottom:30px}.br6Work h2{font-size:clamp(62px,8vw,110px);font-weight:900;line-height:.77;letter-spacing:-.09em;margin:0}.br6WorkTop p{max-width:480px;font-size:13px;line-height:1.6;color:#666;margin:0}.br6WorkGrid{display:grid;grid-template-columns:1.28fr .72fr 1fr;grid-template-rows:310px 245px;gap:10px}.br6WorkGrid figure{margin:0;position:relative;overflow:hidden;background:#ddd}.br6WorkGrid figure:nth-child(1){grid-column:1;grid-row:1/3}.br6WorkGrid figure:nth-child(2){grid-column:2;grid-row:1}.br6WorkGrid figure:nth-child(3){grid-column:3;grid-row:1/3}.br6WorkGrid figure:nth-child(4){grid-column:2;grid-row:2}.br6WorkGrid img{height:100%;object-fit:cover;filter:saturate(.82)}.br6WorkGrid figcaption{position:absolute;left:10px;bottom:10px;background:var(--acid);padding:6px 8px;font-size:8px;font-weight:900}.br6WorkFoot{margin-top:14px;display:flex;justify-content:space-between;gap:30px;font-size:10px;color:#777}
        .br6People{padding:90px 0 100px;background:var(--paper);overflow:hidden}.br6PeopleIntro{display:flex;align-items:end;justify-content:space-between;gap:50px;margin-bottom:34px}.br6PeopleIntro h2{font-size:clamp(58px,7vw,96px);font-weight:900;letter-spacing:-.085em;line-height:.78;margin:0}.br6PeopleIntro p{max-width:460px;font-size:13px;line-height:1.6;color:#555;margin:0}.br6PeopleCanvas{display:grid;grid-template-columns:1.12fr .78fr .92fr;gap:18px;align-items:start}.br6Person:nth-child(2){margin-top:120px}.br6Person:nth-child(3){margin-top:42px}.br6PersonPhoto{overflow:hidden;background:#ccc}.br6Person:nth-child(1) .br6PersonPhoto{height:600px}.br6Person:nth-child(2) .br6PersonPhoto{height:420px}.br6Person:nth-child(3) .br6PersonPhoto{height:510px}.br6PersonPhoto img{height:100%;object-fit:cover;filter:saturate(.68) contrast(1.03)}.br6PersonName{font-size:30px;font-weight:900;letter-spacing:-.05em;margin-top:11px}.br6PersonRole{font-size:10px;color:#666;margin-top:3px}
        .br6Shop{background:#111;color:#fff;padding:0 0 54px}.br6ShopPhoto{height:650px;overflow:hidden}.br6ShopPhoto img{height:100%;object-fit:cover;filter:saturate(.72) contrast(1.03)}.br6ShopInfo{display:grid;grid-template-columns:1.1fr .9fr .9fr .9fr;gap:28px;padding-top:22px;border-top:1px solid #555;margin-top:22px}.br6ShopName{font-size:44px;font-weight:900;letter-spacing:-.065em;line-height:.88}.br6ShopInfo div:not(.br6ShopName){font-size:10.5px;line-height:1.55;color:#aaa}.br6ShopInfo strong{color:#fff}
        .br6Contact{padding:72px 0 80px;background:var(--paper)}.br6ContactHead{display:grid;grid-template-columns:.7fr 1.3fr;gap:70px;align-items:end;margin-bottom:30px}.br6ContactHead h2{font-size:clamp(56px,7vw,96px);font-weight:900;letter-spacing:-.085em;line-height:.78;margin:0}.br6ContactHead p{max-width:520px;font-size:13px;line-height:1.6;color:#555;margin:0}.br6ContactGrid{display:grid;grid-template-columns:1.3fr .7fr;gap:60px}.br6Form{border-top:3px solid #111}.br6Field{display:grid;grid-template-columns:170px 1fr;border-bottom:1px solid #111}.br6Field label{padding:18px 14px 18px 0;font-size:9px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.br6Field input,.br6Field select,.br6Field textarea{border:0;background:transparent;padding:16px 0;font:inherit;font-size:13px;outline:none}.br6Field textarea{min-height:110px;resize:vertical}.br6Form button{width:100%;min-height:50px;border:0;background:var(--acid);font-size:10px;font-weight:900;text-transform:uppercase}.br6FormNote{font-size:9px;color:#777;margin-top:9px}.br6Direct{border-top:3px solid #111;padding-top:18px}.br6Direct h3{font-size:24px;margin:0 0 16px}.br6Direct a{display:flex;align-items:center;gap:9px;font-size:14px;font-weight:800;padding:13px 0;border-bottom:1px solid var(--line)}.br6Direct p{font-size:11px;color:#666;line-height:1.55;margin-top:18px}
        .br6Footer{background:#111;color:#fff;padding:38px 0}.br6FooterIn{display:grid;grid-template-columns:1.2fr 1fr auto;gap:45px;align-items:center}.br6FooterName{font-size:30px;font-weight:900;letter-spacing:-.06em}.br6FooterText{font-size:10px;line-height:1.6;color:#aaa}.br6FooterText strong{color:#fff}.br6FooterCta{background:var(--acid);color:#111!important;padding:11px 13px;font-size:10px;font-weight:900;white-space:nowrap}
        @media(max-width:980px){.br6HeroGrid{height:auto;min-height:720px}.br6HeroWord{font-size:clamp(82px,15vw,140px)}.br6HeroMain{grid-column:6/13}.br6HeroDetail{grid-column:4/8}.br6MenuTop,.br6PeopleIntro{display:block}.br6MenuTop p,.br6PeopleIntro p{margin-top:20px}.br6WorkTop,.br6ContactHead{grid-template-columns:1fr;gap:22px}.br6PeopleCanvas{grid-template-columns:1fr 1fr}.br6Person:nth-child(1){grid-column:1/-1}.br6Person:nth-child(2),.br6Person:nth-child(3){margin-top:0}.br6Person:nth-child(n) .br6PersonPhoto{height:460px}.br6ShopInfo,.br6ContactGrid{grid-template-columns:1fr 1fr}.br6ShopName{grid-column:1/-1}.br6FooterIn{grid-template-columns:1fr 1fr}.br6FooterCta{grid-column:1/-1;justify-self:start}}
        @media(max-width:680px){.br6Wrap{width:min(100% - 28px,1320px)}.br6Demo{font-size:7.5px}.br6Links a:not(.br6ContactTop){display:none}.br6HeroGrid{min-height:660px}.br6HeroWord{top:37%;font-size:clamp(74px,23vw,102px)}.br6HeroMain{grid-column:3/13}.br6HeroDetail{grid-column:1/6;height:180px}.br6HeroCopy{width:84%;bottom:20px;font-size:13px}.br6FactsIn{padding:12px 0;justify-content:flex-start}.br6Menu{padding:60px 0 68px}.br6Work{padding:60px 0 68px}.br6WorkGrid{grid-template-columns:1fr 1fr;grid-template-rows:auto}.br6WorkGrid figure:nth-child(n){grid-column:auto;grid-row:auto;height:240px}.br6WorkGrid figure:nth-child(1){grid-column:1/-1;height:380px}.br6People{padding:62px 0 70px}.br6PeopleCanvas{grid-template-columns:1fr}.br6Person:nth-child(1){grid-column:auto}.br6Person:nth-child(n) .br6PersonPhoto{height:420px}.br6ShopPhoto{height:460px}.br6ShopInfo,.br6ContactGrid{grid-template-columns:1fr}.br6ShopName{grid-column:auto}.br6Contact{padding:56px 0}.br6Field{grid-template-columns:1fr}.br6Field label{padding-bottom:0}.br6FooterIn{grid-template-columns:1fr;gap:18px}}
      `}</style>

      <div className="br6Demo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <nav className="br6Nav"><div className="br6Wrap br6NavIn"><a className="br6Brand" href="#top">KŘESLO 39</a><div className="br6Links"><a href="#cenik">Ceník</a><a href="#prace">Práce</a><a href="#barberi">Barbeři</a><a href="#provozovna">Provozovna</a><a className="br6ContactTop" href="#kontakt">Kontakt</a></div></div></nav>

      <header className="br6Hero"><div className="br6Wrap br6HeroGrid"><div className="br6HeroMeta">BARBERSHOP · BRNO · 2 KŘESLA</div><div className="br6HeroWord"><span>KŘESLO</span><span className="br6Num">39</span></div><figure className="br6HeroMain"><img src="https://images.pexels.com/photos/4625614/pexels-photo-4625614.jpeg?auto=compress&cs=tinysrgb&w=1900" alt="Barber při pánském střihu v menším barbershopu"/></figure><figure className="br6HeroDetail"><img src="https://images.pexels.com/photos/7781848/pexels-photo-7781848.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Hotový pánský střih"/></figure><div className="br6HeroCopy"><p>Pánské střihy, vousy a holení břitvou. Objednání telefonicky, e-mailem nebo přes kontaktní formulář.</p><a href="#cenik">Ceník a služby →</a></div><div className="br6HeroTag">STŘIHY<br/>VOUSY</div></div></header>

      <div className="br6Facts"><div className="br6Wrap br6FactsIn"><span><MapPin size={14}/> Brno–Žabovřesky</span><a href="tel:+420705911941"><Phone size={14}/> +420 705 911 941</a><a href="mailto:kontakt@spustweb.cz"><Mail size={14}/> kontakt@spustweb.cz</a></div></div>

      <section className="br6Menu" id="cenik"><div className="br6Wrap"><div className="br6MenuTop"><h2>Ceník.</h2><p>Všechny ceny jsou za kompletní službu. Cena je známá před návštěvou.</p></div><div className="br6MenuList">{services.map(([name,price,text])=><div className="br6Service" key={name}><strong>{name}</strong><b>{price}</b><p>{text}</p></div>)}</div></div></section>

      <section className="br6Work" id="prace"><div className="br6Wrap"><div className="br6WorkTop"><h2>Střihy a vousy.</h2><p>Ukázky výsledků i detailů práce. Fotografie jsou ilustrační.</p></div><div className="br6WorkGrid">{work.map(([src,alt],i)=><figure key={src}><img src={src} alt={alt}/><figcaption>0{i+1}</figcaption></figure>)}</div><div className="br6WorkFoot"><span>Krátké střihy · fade · delší vlasy · vousy · břitva</span><span>Ilustrační fotografie z Pexels</span></div></div></section>

      <section className="br6People" id="barberi"><div className="br6Wrap"><div className="br6PeopleIntro"><h2>Barbeři.</h2><p>Při objednání stačí uvést, zda chcete konkrétního barbera, nebo je vám výběr jedno.</p></div><div className="br6PeopleCanvas">{barbers.map(([name,role,image])=><article className="br6Person" key={name}><div className="br6PersonPhoto"><img src={image} alt={`Barber ${name} při práci`}/></div><div className="br6PersonName">{name}</div><div className="br6PersonRole">{role}</div></article>)}</div></div></section>

      <section className="br6Shop" id="provozovna"><div className="br6ShopPhoto"><img src="https://images.pexels.com/photos/4625614/pexels-photo-4625614.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Interiér menšího barbershopu s pracovním křeslem"/></div><div className="br6Wrap br6ShopInfo"><div className="br6ShopName">Křeslo 39.</div><div><strong>Adresa</strong><br/>Tábor 39 · Brno–Žabovřesky</div><div><strong>Otevírací doba</strong><br/>Po–Pá 10:00–20:00<br/>So 9:00–15:00</div><div><strong>Kontakt</strong><br/>+420 705 911 941<br/>kontakt@spustweb.cz</div></div></section>

      <section className="br6Contact" id="kontakt"><div className="br6Wrap"><div className="br6ContactHead"><h2>Objednání.</h2><p>Napište službu, kontakt a případně preferovaný den. Konkrétní termín se domluví následně.</p></div><div className="br6ContactGrid"><form className="br6Form"><div className="br6Field"><label htmlFor="br6-name">Jméno</label><input id="br6-name" type="text" placeholder="Vaše jméno"/></div><div className="br6Field"><label htmlFor="br6-contact">Telefon nebo e-mail</label><input id="br6-contact" type="text" placeholder="Jak vás můžeme kontaktovat"/></div><div className="br6Field"><label htmlFor="br6-service">Služba</label><select id="br6-service" defaultValue=""><option value="" disabled>Vyberte službu</option><option>Pánský střih</option><option>Střih + vousy</option><option>Úprava vousů</option><option>Holení břitvou</option></select></div><div className="br6Field"><label htmlFor="br6-message">Poznámka</label><textarea id="br6-message" placeholder="Například preferovaný den nebo barber"/></div><button type="button">Odeslat poptávku</button><div className="br6FormNote">Ukázkový formulář na této demonstrační stránce se neodesílá.</div></form><div className="br6Direct"><h3>Nebo přímo.</h3><a href="tel:+420705911941"><Phone size={17}/> +420 705 911 941</a><a href="mailto:kontakt@spustweb.cz"><Mail size={17}/> kontakt@spustweb.cz</a><p>Kontaktní údaje v této ukázce vedou na SpustWeb.cz. Křeslo 39 je fiktivní koncept.</p></div></div></div></section>

      <footer className="br6Footer"><div className="br6Wrap br6FooterIn"><div className="br6FooterName">KŘESLO 39</div><div className="br6FooterText"><strong>Barbershop · Brno</strong><br/>Fiktivní ukázkový koncept.</div><a className="br6FooterCta" href="/#kontakt">Podobný web pro moje podnikání</a></div></footer>
    </div>
  )
}
