import type { Metadata } from 'next'
import { ArrowRight, CalendarDays, Clock3, MapPin, Phone, Scissors } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro barber shop | SpustWeb.cz',
  description: 'Ukázka webu pro barber shop: střihy, vousy, ceník, barbeři, práce, provozovna a online rezervace.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/barber/' },
  robots: { index: true, follow: true },
}

const services = [
  ['Pánský střih', '650 Kč', 'Konzultace, střih nůžkami a strojkem, mytí a styling.'],
  ['Střih strojkem', '450 Kč', 'Krátký střih strojkem bez práce nůžkami.'],
  ['Úprava vousů', '450 Kč', 'Zastřižení, tvar, kontury a závěrečná péče.'],
  ['Střih + vousy', '950 Kč', 'Kompletní střih vlasů a úprava vousů při jedné návštěvě.'],
  ['Holení břitvou', '550 Kč', 'Napaření, holení břitvou a ošetření pokožky.'],
  ['Dětský střih do 12 let', '490 Kč', 'Pánský střih pro mladší klienty.'],
]

const work = [
  ['https://images.pexels.com/photos/7781848/pexels-photo-7781848.jpeg?auto=compress&cs=tinysrgb&w=1500', 'Hotový krátký pánský střih s čistou konturou'],
  ['https://images.pexels.com/photos/4625632/pexels-photo-4625632.jpeg?auto=compress&cs=tinysrgb&w=1500', 'Detail strojkového střihu v průběhu práce'],
  ['https://images.pexels.com/photos/2035310/pexels-photo-2035310.jpeg?auto=compress&cs=tinysrgb&w=1500', 'Úprava vousů v barbershopu'],
  ['https://images.pexels.com/photos/10003357/pexels-photo-10003357.jpeg?auto=compress&cs=tinysrgb&w=1500', 'Detail hotového střihu a vousů'],
]

const barbers = [
  {
    name: 'Marek',
    role: 'střihy · fade · delší vlasy',
    image: 'https://images.pexels.com/photos/4625614/pexels-photo-4625614.jpeg?auto=compress&cs=tinysrgb&w=1300',
    alt: 'Barber při práci v moderním menším barbershopu',
  },
  {
    name: 'David',
    role: 'vousy · břitva · klasické střihy',
    image: 'https://images.pexels.com/photos/7518735/pexels-photo-7518735.jpeg?auto=compress&cs=tinysrgb&w=1300',
    alt: 'Barber při přesném pánském střihu',
  },
  {
    name: 'Tomáš',
    role: 'krátké střihy · crop · styling',
    image: 'https://images.pexels.com/photos/9992818/pexels-photo-9992818.jpeg?auto=compress&cs=tinysrgb&w=1300',
    alt: 'Barber pracuje na pánském střihu v salonu',
  },
]

export default function BarberShowcase() {
  return (
    <div className="bb" id="top">
      <style>{`
        body:has(.bb) > .verno-nav-shell,body:has(.bb) > .footer{display:none!important}
        body:has(.bb) main{padding:0!important;margin:0!important}
        body:has(.bb){background:#f3efe7!important}
        .bb{--ink:#111;--paper:#f3efe7;--blue:#1947d1;--rust:#b85d35;--acid:#d7f64c;--white:#fff;--line:rgba(17,17,17,.22);font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--paper)}
        .bb *{box-sizing:border-box}.bb a{color:inherit;text-decoration:none}.bb img{display:block;width:100%}.bbWrap{width:min(1320px,calc(100% - 56px));margin:0 auto}
        .bbDemo{min-height:24px;background:#111;color:#d7d7d7;padding:5px 12px;text-align:center;font-size:8.5px;font-weight:800;letter-spacing:.09em;text-transform:uppercase}.bbDemo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .bbNav{position:absolute;left:0;right:0;top:24px;z-index:30;color:#fff}.bbNavInner{height:72px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.45)}.bbBrand{font-size:20px;font-weight:900;letter-spacing:-.045em}.bbNavLinks{display:flex;align-items:center;gap:26px;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.05em}.bbBookTop{background:var(--acid);color:#111!important;padding:11px 13px;display:inline-flex;align-items:center;gap:7px}
        .bbHero{position:relative;height:calc(100svh - 24px);min-height:680px;max-height:900px;background:#1b1b1b;color:#fff;overflow:hidden}.bbHeroBg{position:absolute;inset:0}.bbHeroBg img{height:100%;object-fit:cover;object-position:center 45%;filter:saturate(.55) contrast(1.08) brightness(.62)}.bbHeroBg:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.18),rgba(0,0,0,.12) 40%,rgba(0,0,0,.74) 100%),linear-gradient(90deg,rgba(0,0,0,.56),transparent 58%)}.bbHeroInner{position:relative;z-index:3;height:100%;display:flex;flex-direction:column;justify-content:flex-end;padding-bottom:42px}.bbHeroKicker{font-size:10px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;margin-bottom:16px}.bbHero h1{font-size:clamp(90px,13vw,188px);font-weight:900;line-height:.72;letter-spacing:-.09em;margin:0;max-width:1000px}.bbHero h1 span{display:block}.bbHero h1 .bbOutline{-webkit-text-stroke:2px #fff;color:transparent}.bbHeroBottom{display:grid;grid-template-columns:1.2fr .8fr;gap:70px;align-items:end;margin-top:34px}.bbHeroLead{max-width:580px;font-size:15px;line-height:1.6;margin:0;color:#ededed}.bbHeroActions{display:flex;gap:10px;justify-content:flex-end;flex-wrap:wrap}.bbBtn{min-height:46px;padding:0 16px;border:1px solid #fff;color:#fff!important;display:inline-flex;align-items:center;justify-content:center;gap:8px;font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.bbBtnAcid{background:var(--acid);border-color:var(--acid);color:#111!important}.bbHeroBadge{position:absolute;right:3vw;top:24%;z-index:4;background:var(--rust);width:124px;height:124px;border-radius:50%;display:grid;place-items:center;text-align:center;font-size:9px;font-weight:900;line-height:1.35;transform:rotate(8deg)}
        .bbFacts{background:var(--blue);color:#fff}.bbFactsInner{min-height:62px;display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap;font-size:10.5px}.bbFacts span{display:flex;align-items:center;gap:7px}
        .bbMenu{padding:88px 0 98px;background:var(--paper)}.bbMenuTop{display:grid;grid-template-columns:.78fr 1.22fr;gap:80px;align-items:end;margin-bottom:46px}.bbMenu h2{font-size:clamp(60px,7vw,98px);font-weight:900;letter-spacing:-.08em;line-height:.78;margin:0}.bbMenuTop p{max-width:520px;font-size:14px;line-height:1.65;color:#555;margin:0}.bbPriceBoard{border-top:4px solid #111}.bbPrice{display:grid;grid-template-columns:1fr 130px 1.1fr;gap:36px;align-items:center;padding:20px 0;border-bottom:1px solid var(--line)}.bbPrice strong{font-size:20px}.bbPrice b{font-size:15px}.bbPrice p{font-size:12.5px;line-height:1.5;color:#5c5c5c;margin:0}.bbPrice:hover strong{color:var(--blue)}
        .bbWork{background:#fff;padding:84px 0 96px;overflow:hidden}.bbWorkHead{display:flex;justify-content:space-between;align-items:end;gap:40px;margin-bottom:34px}.bbWorkHead h2{font-size:clamp(62px,8vw,110px);font-weight:900;letter-spacing:-.085em;line-height:.78;margin:0}.bbWorkHead p{max-width:440px;font-size:13px;line-height:1.6;color:#666;margin:0}.bbWorkGrid{display:grid;grid-template-columns:1.25fr .75fr 1fr;grid-template-rows:300px 250px;gap:10px}.bbWorkGrid figure{margin:0;overflow:hidden;position:relative;background:#ddd}.bbWorkGrid figure:nth-child(1){grid-column:1;grid-row:1/3}.bbWorkGrid figure:nth-child(2){grid-column:2;grid-row:1}.bbWorkGrid figure:nth-child(3){grid-column:3;grid-row:1/3}.bbWorkGrid figure:nth-child(4){grid-column:2;grid-row:2}.bbWorkGrid img{height:100%;object-fit:cover;filter:saturate(.82)}.bbWorkGrid figcaption{position:absolute;left:10px;bottom:10px;background:var(--acid);padding:6px 8px;font-size:8px;font-weight:900}.bbWorkNote{display:flex;justify-content:space-between;gap:30px;margin-top:15px;font-size:10px;color:#777}
        .bbBarbers{background:var(--blue);color:#fff;padding:88px 0 100px}.bbBarbersHead{display:grid;grid-template-columns:.85fr 1.15fr;gap:70px;align-items:end;margin-bottom:36px}.bbBarbers h2{font-size:clamp(62px,7.8vw,106px);line-height:.78;letter-spacing:-.085em;font-weight:900;margin:0}.bbBarbersHead p{max-width:500px;margin:0;font-size:13px;line-height:1.6;color:#dce4ff}.bbRoster{display:grid;grid-template-columns:1.25fr .9fr .9fr;gap:12px;align-items:end}.bbBarber{margin:0}.bbBarberPhoto{overflow:hidden;background:#0f2c88}.bbBarber:nth-child(1) .bbBarberPhoto{height:560px}.bbBarber:nth-child(2) .bbBarberPhoto{height:430px}.bbBarber:nth-child(3) .bbBarberPhoto{height:470px}.bbBarberPhoto img{height:100%;object-fit:cover;filter:saturate(.55) contrast(1.08)}.bbBarberMeta{display:flex;justify-content:space-between;gap:20px;align-items:baseline;padding-top:12px;border-top:1px solid rgba(255,255,255,.55);margin-top:10px}.bbBarberMeta strong{font-size:24px}.bbBarberMeta span{font-size:10px;color:#dbe3ff;text-align:right}
        .bbShop{background:var(--rust);color:#fff;padding:0}.bbShopGrid{display:grid;grid-template-columns:1.35fr .65fr;min-height:650px}.bbShopPhoto{overflow:hidden}.bbShopPhoto img{height:100%;object-fit:cover;filter:saturate(.72) contrast(1.04)}.bbShopCopy{padding:68px 54px;display:flex;flex-direction:column;justify-content:space-between}.bbShopCopy h2{font-size:clamp(58px,6.5vw,90px);font-weight:900;line-height:.8;letter-spacing:-.08em;margin:0 0 24px}.bbShopCopy p{font-size:14px;line-height:1.65;max-width:460px;margin:0}.bbShopData{border-top:1px solid rgba(255,255,255,.6);margin-top:36px}.bbShopRow{display:grid;grid-template-columns:120px 1fr;gap:20px;padding:13px 0;border-bottom:1px solid rgba(255,255,255,.35);font-size:11px}.bbShopRow strong{font-size:11px}
        .bbBooking{background:var(--paper);padding:82px 0}.bbBookingHead{display:grid;grid-template-columns:.72fr 1.28fr;gap:80px;align-items:end;margin-bottom:30px}.bbBooking h2{font-size:clamp(62px,7.6vw,106px);font-weight:900;letter-spacing:-.085em;line-height:.78;margin:0}.bbBookingHead p{font-size:13px;line-height:1.6;max-width:500px;margin:0}.bbBookSheet{border:2px solid #111;background:#fff}.bbBookRow{display:grid;grid-template-columns:180px 1fr auto;gap:24px;align-items:center;padding:17px 20px;border-bottom:1px solid #111}.bbBookRow:last-of-type{border-bottom:0}.bbBookRow small{font-size:9px;text-transform:uppercase;letter-spacing:.1em;color:#666}.bbBookRow strong{font-size:14px}.bbBookRow span{font-size:11px;color:#555}.bbBookButton{width:100%;min-height:52px;border:0;border-top:2px solid #111;background:var(--acid);color:#111;font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.05em;display:flex;align-items:center;justify-content:center;gap:8px}.bbBookHint{margin-top:10px;font-size:9px;color:#777}
        .bbFooter{background:#111;color:#fff;padding:44px 0}.bbFooterGrid{display:grid;grid-template-columns:1.2fr 1fr auto;gap:44px;align-items:center}.bbFooterName{font-size:34px;font-weight:900;letter-spacing:-.06em}.bbFooterText{font-size:10px;line-height:1.65;color:#aaa}.bbFooterText strong{color:#fff}.bbFooterCta{background:var(--acid);color:#111!important;padding:12px 14px;font-size:10px;font-weight:900;white-space:nowrap}
        @media(max-width:980px){.bbNavLinks a:not(.bbBookTop){display:none}.bbHero h1{font-size:clamp(86px,15vw,140px)}.bbHeroBottom{grid-template-columns:1fr}.bbHeroActions{justify-content:flex-start}.bbMenuTop,.bbBarbersHead,.bbBookingHead{grid-template-columns:1fr;gap:24px}.bbPrice{grid-template-columns:1fr auto}.bbPrice p{grid-column:1/-1}.bbRoster{grid-template-columns:1fr 1fr}.bbBarber:first-child{grid-column:1/-1}.bbBarber:nth-child(n) .bbBarberPhoto{height:460px}.bbShopGrid{grid-template-columns:1fr}.bbShopPhoto{height:520px}.bbFooterGrid{grid-template-columns:1fr 1fr}.bbFooterCta{grid-column:1/-1;justify-self:start}}
        @media(max-width:680px){.bbWrap{width:min(100% - 28px,1320px)}.bbDemo{font-size:7.5px}.bbNavInner{height:58px}.bbHero{min-height:700px;height:calc(100svh - 24px)}.bbHero h1{font-size:clamp(76px,24vw,112px)}.bbHeroBadge{width:92px;height:92px;top:24%;right:10px;font-size:7.5px}.bbHeroLead{font-size:13px}.bbFactsInner{padding:12px 0;justify-content:flex-start}.bbMenu,.bbWork,.bbBarbers,.bbBooking{padding:60px 0}.bbMenuTop,.bbWorkHead{display:block}.bbMenuTop p,.bbWorkHead p{margin-top:18px}.bbPrice{gap:8px 16px}.bbWorkGrid{grid-template-columns:1fr 1fr;grid-template-rows:auto}.bbWorkGrid figure:nth-child(n){grid-column:auto;grid-row:auto;height:240px}.bbWorkGrid figure:nth-child(1){grid-column:1/-1;height:360px}.bbWorkNote{display:block}.bbWorkNote span{display:block;margin-top:6px}.bbRoster{grid-template-columns:1fr}.bbBarber:first-child{grid-column:auto}.bbBarber:nth-child(n) .bbBarberPhoto{height:420px}.bbShopPhoto{height:420px}.bbShopCopy{padding:42px 24px}.bbBookRow{grid-template-columns:1fr auto}.bbBookRow small{grid-column:1/-1}.bbFooterGrid{grid-template-columns:1fr;gap:20px}}
      `}</style>

      <div className="bbDemo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <nav className="bbNav" aria-label="Navigace ukázkového barbershopu"><div className="bbWrap bbNavInner"><a className="bbBrand" href="#top">KŘESLO 39</a><div className="bbNavLinks"><a href="#cenik">Ceník</a><a href="#prace">Práce</a><a href="#barberi">Barbeři</a><a href="#shop">Provozovna</a><a className="bbBookTop" href="#rezervace">Rezervace <CalendarDays size={12}/></a></div></div></nav>
      <header className="bbHero"><div className="bbHeroBg"><img src="https://images.pexels.com/photos/9992820/pexels-photo-9992820.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Barber při pánském střihu v moderním barbershopu"/></div><div className="bbWrap bbHeroInner"><div className="bbHeroKicker">BARBERSHOP · BRNO · ŽIDENICE</div><h1><span>KŘESLO</span><span className="bbOutline">39</span></h1><div className="bbHeroBottom"><p className="bbHeroLead">Pánské střihy, vousy a holení břitvou. Tři barbeři, jedno místo a termíny přes online rezervaci.</p><div className="bbHeroActions"><a className="bbBtn bbBtnAcid" href="#rezervace">Vybrat termín <ArrowRight size={13}/></a><a className="bbBtn" href="#cenik">Ceník</a></div></div></div><div className="bbHeroBadge">STŘIHY<br/>VOUSY<br/>BŘITVA</div></header>
      <div className="bbFacts"><div className="bbWrap bbFactsInner"><span><MapPin size={14}/> Brno-Židenice</span><span><Clock3 size={14}/> Po–Pá 10:00–20:00 · So 9:00–15:00</span><span><Scissors size={14}/> 3 barbeři</span><span><Phone size={14}/> 777 000 000</span></div></div>
      <section className="bbMenu" id="cenik"><div className="bbWrap"><div className="bbMenuTop"><h2>Ceník.</h2><p>Střih, vousy nebo obojí při jedné návštěvě. U služby je vždy uvedeno, co cena zahrnuje.</p></div><div className="bbPriceBoard">{services.map(([name,price,text])=><div className="bbPrice" key={name}><strong>{name}</strong><b>{price}</b><p>{text}</p></div>)}</div></div></section>
      <section className="bbWork" id="prace"><div className="bbWrap"><div className="bbWorkHead"><h2>Střihy a vousy.</h2><p>Ukázky výsledků a práce při střihu.</p></div><div className="bbWorkGrid">{work.map(([src,alt],i)=><figure key={src}><img src={src} alt={alt}/><figcaption>0{i+1}</figcaption></figure>)}</div><div className="bbWorkNote"><strong>Krátké střihy · delší vlasy · vousy · břitva</strong><span>Ilustrační fotografie z Pexels · nejde o realizace skutečného barbershopu.</span></div></div></section>
      <section className="bbBarbers" id="barberi"><div className="bbWrap"><div className="bbBarbersHead"><h2>Barbeři.</h2><p>Při rezervaci si můžete vybrat konkrétního barbera nebo první volný termín.</p></div><div className="bbRoster">{barbers.map((barber)=><figure className="bbBarber" key={barber.name}><div className="bbBarberPhoto"><img src={barber.image} alt={barber.alt}/></div><figcaption className="bbBarberMeta"><strong>{barber.name}</strong><span>{barber.role}</span></figcaption></figure>)}</div></div></section>
      <section className="bbShop" id="shop"><div className="bbShopGrid"><div className="bbShopPhoto"><img src="https://images.pexels.com/photos/4625624/pexels-photo-4625624.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="Interiér menšího moderního barbershopu"/></div><div className="bbShopCopy"><div><h2>Křeslo 39.</h2><p>Menší barbershop se třemi pracovními místy. Rezervace mají přednost, volný termín lze vybrat online.</p></div><div className="bbShopData"><div className="bbShopRow"><strong>Adresa</strong><span>Táborská 39 · Brno-Židenice</span></div><div className="bbShopRow"><strong>Po–Pá</strong><span>10:00–20:00</span></div><div className="bbShopRow"><strong>Sobota</strong><span>9:00–15:00</span></div><div className="bbShopRow"><strong>Telefon</strong><span>777 000 000</span></div></div></div></div></section>
      <section className="bbBooking" id="rezervace"><div className="bbWrap"><div className="bbBookingHead"><h2>Rezervace.</h2><p>Vyberte službu, barbera a volný termín. Ukázkové rezervační rozhraní není aktivní.</p></div><div className="bbBookSheet"><div className="bbBookRow"><small>Služba</small><strong>Pánský střih</strong><span>650 Kč</span></div><div className="bbBookRow"><small>Barber</small><strong>Marek</strong><span>změnit</span></div><div className="bbBookRow"><small>Termín</small><strong>Úterý 25. 8. · 16:30</strong><span>volný</span></div><button className="bbBookButton" type="button">Pokračovat k rezervaci <ArrowRight size={13}/></button></div><div className="bbBookHint">Fiktivní barbershop · rezervaci nelze skutečně odeslat.</div></div></section>
      <footer className="bbFooter"><div className="bbWrap bbFooterGrid"><div className="bbFooterName">KŘESLO 39</div><div className="bbFooterText"><strong>Barbershop · Brno-Židenice</strong><br/>Po–Pá 10:00–20:00 · So 9:00–15:00<br/>Fiktivní ukázkový koncept.</div><a className="bbFooterCta" href="/#kontakt">Podobný web pro moje podnikání</a></div></footer>
    </div>
  )
}
