import type { Metadata } from 'next'
import { ArrowRight, Bath, Camera, Droplets, Flame, MapPin, Phone, Pipette, ShieldCheck, Wrench } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro instalatéra a topenáře',
  description: 'Ukázka webu pro instalatéra a topenáře: akutní opravy, plánované zakázky, voda, topení, koupelny, realizace a lokální působnost.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/instalater/' },
  robots: { index: true, follow: true },
}

const services = [
  { icon: Droplets, title: 'Voda', text: 'Opravy a nové rozvody vody, výměny baterií, WC, bojlerů a napojení spotřebičů.' },
  { icon: Flame, title: 'Topení', text: 'Radiátory, rozvody topení, podlahové vytápění a úpravy topných soustav.' },
  { icon: Bath, title: 'Koupelny', text: 'Příprava vody a odpadů, montáž sanity a instalatérské práce při rekonstrukci.' },
  { icon: Pipette, title: 'Odpady', text: 'Opravy a výměny odpadního potrubí, nové napojení a řešení běžných závad.' },
  { icon: Wrench, title: 'Technické místnosti', text: 'Rozvody, kotle, zásobníky a související technologie podle konkrétního systému.' },
]

const faqs = [
  ['Kolik stojí příjezd instalatéra?', 'Cenu výjezdu a způsob účtování potvrdíme předem. U větších prací připravíme cenovou nabídku.'],
  ['Děláte i malé opravy?', 'Ano. Od výměny baterie nebo ventilu po nové rozvody při rekonstrukci.'],
  ['Jak rychle přijedete při havárii?', 'Zavolejte. Podle aktuální vytíženosti rovnou řekneme nejbližší možný termín výjezdu.'],
  ['Mohu poslat fotografie závady?', 'Ano. Fotografie často pomohou určit potřebný materiál a rozsah práce ještě před výjezdem.'],
  ['Dostanu cenu předem?', 'U běžné opravy domluvíme cenu nebo způsob účtování. U větší realizace dostanete nabídku před zahájením.'],
  ['Do jakých obcí vyjíždíte?', 'Běžně do Českých Budějovic a přibližně 30 km od města. Větší realizace řešíme po dohodě i dál.'],
]

export default function PlumberShowcase() {
  return (
    <div className="demoPage">
      <style>{`
        body:has(.demoPage) > .verno-nav-shell,body:has(.demoPage) > .footer{display:none!important}
        body:has(.demoPage) main{padding:0!important;margin:0!important}
        body:has(.demoPage){background:#fff!important}
        .demoPage{--ink:#111312;--muted:#666a67;--line:#deded9;--paper:#fff;--soft:#f4f3ef;--signal:#d64d33;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:#fff}
        .demoPage *{box-sizing:border-box}.demoPage a{color:inherit;text-decoration:none}.demoPage svg{stroke-width:1.8}
        .wrap{width:min(1160px,calc(100% - 40px));margin:0 auto}
        .demoBar{background:#111312;color:#d9d9d6;font-size:9px;letter-spacing:.06em;text-transform:uppercase;text-align:center;padding:7px 16px}.demoBar a{color:#fff;text-decoration:underline;text-underline-offset:3px}
        .navShell{position:sticky;top:0;z-index:80;background:rgba(255,255,255,.96);backdrop-filter:blur(12px);border-bottom:1px solid var(--line)}
        .nav{height:66px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center}
        .brand{display:flex;align-items:center;gap:10px;font-size:19px;font-weight:900;letter-spacing:-.045em}.brandDrop{width:16px;height:23px;border:2px solid var(--ink);border-radius:55% 55% 60% 60%;transform:rotate(8deg)}.brand small{display:block;font-size:8px;letter-spacing:.13em;color:var(--muted);margin-top:1px}
        .navLinks{display:flex;gap:25px;font-size:11px;font-weight:700}.navLinks a:hover{opacity:.55}.navRight{justify-self:end;display:flex;align-items:center;gap:12px}.navPhone{font-size:11px;font-weight:800}.navCta{background:var(--ink);color:#fff;padding:11px 15px;font-size:10px;font-weight:800}
        .hero{border-bottom:1px solid var(--line)}.heroGrid{display:grid;grid-template-columns:1.01fr .99fr;height:min(680px,calc(100svh - 94px));min-height:535px}
        .heroCopy{padding:42px 48px 34px 0;display:flex;flex-direction:column;justify-content:center}.eyebrow{font-size:10px;font-weight:800;letter-spacing:.09em;text-transform:uppercase;color:var(--muted);margin-bottom:18px}
        .hero h1{font-size:clamp(44px,5.15vw,70px);line-height:.94;letter-spacing:-.058em;margin:0 0 20px;max-width:620px}.heroLead{font-size:15px;line-height:1.5;color:#3f4340;max-width:580px;margin:0 0 23px}.heroActions{display:flex;gap:8px;flex-wrap:wrap}.btn{min-height:42px;padding:0 16px;display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid var(--ink);font-size:10px;font-weight:900;letter-spacing:.01em}.btnDark{background:var(--ink);color:#fff}.btnSignal{background:var(--signal);border-color:var(--signal);color:#fff}.btnLight{background:#fff}
        .heroHint{margin-top:25px;padding-top:15px;border-top:1px solid var(--line);display:flex;gap:8px;align-items:center;font-size:10px;color:var(--muted)}.heroHint strong{color:var(--ink)}
        .heroPhoto{position:relative;height:100%;overflow:hidden;background:#d9d9d4}.heroPhoto img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;filter:saturate(.76) contrast(1.03)}.heroPhoto:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 65%,rgba(0,0,0,.42))}.heroPhotoText{position:absolute;z-index:2;left:24px;right:24px;bottom:21px;color:#fff;display:flex;justify-content:space-between;align-items:end}.heroPhotoText strong{font-size:14px}.heroPhotoText span{display:block;font-size:9px;color:#e1e1df;margin-top:3px}.heroPhotoIcon{width:38px;height:38px;border:1px solid rgba(255,255,255,.8);display:grid;place-items:center}
        .proofBar{display:grid;grid-template-columns:1.2fr repeat(4,1fr);border-top:1px solid var(--line)}.proofIntro,.proof{min-height:68px;display:flex;flex-direction:column;justify-content:center;padding:12px 16px}.proofIntro{font-size:10px;font-weight:800;padding-left:0}.proof{border-left:1px solid var(--line);font-size:10px;font-weight:800}.proof span{font-weight:500;color:var(--muted);margin-top:3px;line-height:1.3}
        .section{padding:58px 0}.sectionHead{display:grid;grid-template-columns:180px 1fr;gap:28px;align-items:start;margin-bottom:26px}.kicker{font-size:9px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);padding-top:5px}.sectionHead h2{font-size:clamp(31px,3.8vw,48px);line-height:.98;letter-spacing:-.047em;margin:0;max-width:720px}.sectionHead p{font-size:12px;line-height:1.5;color:var(--muted);max-width:620px;margin:10px 0 0}
        .situations{display:grid;grid-template-columns:1fr 1fr;gap:12px}.situation{padding:24px 26px;border:1px solid var(--line);display:grid;grid-template-columns:1fr auto;grid-template-rows:auto auto auto;column-gap:20px;align-items:start}.situation.hot{background:#fff4f1}.situation.plan{background:#f2f2ef}.situationLabel{font-size:9px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.situationIcon{width:40px;height:40px;border:1px solid var(--ink);display:grid;place-items:center;grid-column:2;grid-row:1/3}.hot .situationIcon{border-color:var(--signal);color:var(--signal)}.situation h3{grid-column:1;font-size:27px;letter-spacing:-.035em;margin:13px 0 12px}.tags{grid-column:1/-1;display:flex;gap:5px;flex-wrap:wrap;margin-bottom:16px}.tags span{font-size:9px;padding:6px 8px;border:1px solid #c5c5c0}.situation .btn{grid-column:1/-1;justify-self:start}
        .serviceGrid{display:grid;grid-template-columns:repeat(5,1fr);border-left:1px solid var(--line);border-top:1px solid var(--line)}.service{padding:20px 18px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.serviceIcon{width:38px;height:38px;display:grid;place-items:center;border:1px solid var(--ink);margin-bottom:28px}.service h3{font-size:18px;letter-spacing:-.025em;margin:0 0 7px}.service p{font-size:10px;line-height:1.5;color:var(--muted);margin:0}
        .work{background:var(--ink);color:#fff}.work .kicker,.work .sectionHead p{color:#aaa}.projects{display:grid;grid-template-columns:1.08fr .96fr .96fr;gap:10px}.project{aspect-ratio:1.18/1;position:relative;overflow:hidden;background:#333}.project img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.72) contrast(1.04)}.project:after{content:'';position:absolute;inset:45% 0 0;background:linear-gradient(transparent,rgba(0,0,0,.8))}.projectText{position:absolute;z-index:2;left:17px;right:17px;bottom:15px}.projectText small{font-size:8px;text-transform:uppercase;letter-spacing:.08em;color:#ddd}.projectText h3{font-size:17px;margin:4px 0 0;letter-spacing:-.025em}.project:first-child .projectText h3{font-size:21px}.demoNote{margin-top:13px;padding-top:12px;border-top:1px solid #454545;font-size:9px;color:#aaa;display:flex;justify-content:space-between;gap:30px}.demoNote strong{color:#fff}
        .promiseGrid{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line)}.promise{padding:20px 18px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.promiseNum{font-size:9px;font-weight:900;color:var(--signal)}.promise strong{display:block;font-size:15px;letter-spacing:-.015em;margin:24px 0 7px}.promise p{font-size:10px;line-height:1.5;color:var(--muted);margin:0}
        .about{display:grid;grid-template-columns:.82fr 1.18fr;border:1px solid var(--line)}.aboutPhoto{position:relative;min-height:370px;overflow:hidden;background:#ddd}.aboutPhoto img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.74)}.aboutCopy{padding:38px 42px;display:flex;flex-direction:column;justify-content:center}.aboutCopy h2{font-size:38px;line-height:.96;letter-spacing:-.045em;margin:12px 0}.aboutCopy p{font-size:12px;line-height:1.55;color:#444;max-width:560px}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:20px}.fact{padding-top:10px;border-top:1px solid var(--line);font-size:10px;font-weight:800}.fact span{display:block;font-size:9px;font-weight:500;color:var(--muted);margin-top:3px}
        .steps{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line)}.step{border-right:1px solid var(--line);border-bottom:1px solid var(--line);padding:18px 20px;display:grid;grid-template-columns:44px 1fr;gap:13px;align-items:start}.stepNo{font-size:34px;font-weight:900;line-height:1;letter-spacing:-.05em;color:#b7b7b2}.step h3{font-size:15px;margin:1px 0 6px}.step p{font-size:10px;line-height:1.5;color:var(--muted);margin:0}
        .areaFaq{display:grid;grid-template-columns:.82fr 1.18fr;gap:30px}.areaBox{background:var(--soft);padding:27px}.areaBox h3{font-size:26px;letter-spacing:-.035em;margin:0 0 10px}.areaBox p{font-size:10px;line-height:1.5;color:var(--muted)}.towns{display:flex;gap:5px;flex-wrap:wrap;margin:17px 0}.towns span{font-size:9px;border:1px solid #bbb;padding:6px 7px}.areaRule{height:1px;background:#cfcfca;margin:20px 0}.areaDistance{font-size:10px;font-weight:800;display:flex;gap:7px;align-items:center}.faq{border-top:1px solid var(--line)}.faqItem{padding:12px 0;border-bottom:1px solid var(--line)}.faqItem h3{font-size:11px;margin:0 0 4px}.faqItem p{font-size:10px;line-height:1.45;color:var(--muted);margin:0}
        .contact{background:#111312;color:#fff;padding:48px 0}.contactGrid{display:grid;grid-template-columns:1fr .86fr;gap:56px}.contact h2{font-size:clamp(36px,4.3vw,54px);line-height:.95;letter-spacing:-.05em;margin:0 0 15px}.contact p{font-size:11px;line-height:1.55;color:#bcbfbc;max-width:500px}.contactActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.contact .btnLight{background:#fff;color:#111}.form{background:#fff;color:#111;padding:18px;display:grid;grid-template-columns:1fr 1fr;gap:7px}.field{border:1px solid #d5d5d0;min-height:39px;padding:0 10px;display:flex;align-items:center;font-size:9px;color:#777}.field.wide{grid-column:1/-1}.field.big{min-height:65px;align-items:flex-start;padding-top:10px}.form .btn{grid-column:1/-1}.formNote{grid-column:1/-1;font-size:8px;color:#777;line-height:1.4}
        .demoFooter{background:#090a09;color:#aaa;border-top:1px solid #2d2d2d}.footerInner{padding:18px 0;display:flex;justify-content:space-between;gap:30px;font-size:9px;line-height:1.45}.demoFooter strong{color:#fff}.demoFooter a{color:#fff;text-decoration:underline;text-underline-offset:3px}
        @media(max-width:980px){.nav{grid-template-columns:1fr auto}.navLinks{display:none}.heroGrid{grid-template-columns:1fr;height:auto}.heroCopy{padding:42px 0 34px}.heroPhoto{height:470px}.proofBar{grid-template-columns:repeat(2,1fr)}.proofIntro{grid-column:1/-1}.proof:nth-child(even){border-left:0}.sectionHead{grid-template-columns:1fr;gap:8px}.serviceGrid{grid-template-columns:repeat(2,1fr)}.projects{grid-template-columns:1fr 1fr}.project:first-child{grid-column:1/-1;aspect-ratio:2/1}.promiseGrid{grid-template-columns:repeat(2,1fr)}.about,.contactGrid,.areaFaq{grid-template-columns:1fr}}
        @media(max-width:650px){.wrap{width:min(100% - 28px,1160px)}.nav{height:60px}.navPhone{display:none}.navCta{padding:9px 11px}.heroCopy{padding:38px 0 30px}.hero h1{font-size:43px}.heroLead{font-size:14px}.heroPhoto{height:390px}.proofBar{grid-template-columns:1fr 1fr}.proofIntro{grid-column:1/-1;padding-left:0}.section{padding:46px 0}.sectionHead h2{font-size:33px}.situations{grid-template-columns:1fr}.serviceGrid,.promiseGrid{grid-template-columns:1fr}.projects{grid-template-columns:1fr}.project,.project:first-child{grid-column:1;aspect-ratio:1.3/1}.demoNote{flex-direction:column;gap:6px}.aboutPhoto{min-height:330px}.aboutCopy{padding:28px 22px}.facts{grid-template-columns:1fr}.steps{grid-template-columns:1fr;border-top:1px solid var(--line)}.step{grid-template-columns:40px 1fr}.form{grid-template-columns:1fr}.field,.field.wide,.form .btn,.formNote{grid-column:1}.footerInner{flex-direction:column}}
      `}</style>
      <div className="demoBar">Ukázkový koncept SpustWeb.cz · nejde o skutečnou firmu · <a href="/">zpět na SpustWeb.cz</a></div>
      <div className="navShell"><div className="wrap"><nav className="nav"><a className="brand" href="#top"><span className="brandDrop"/><span>NOVÁK<small>VODA & TOPENÍ</small></span></a><div className="navLinks"><a href="#sluzby">Služby</a><a href="#realizace">Realizace</a><a href="#o-nas">O nás</a><a href="#faq">Časté dotazy</a></div><div className="navRight"><a className="navPhone" href="tel:+420777000000">777 000 000</a><a className="navCta" href="#kontakt">Poslat poptávku</a></div></nav></div></div>
      <header className="hero" id="top"><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow">Instalatér a topenář · České Budějovice a okolí</div><h1>Voda a topení pro domy a byty v Českých Budějovicích a okolí.</h1><p className="heroLead">Opravy, nové rozvody, koupelny a topné systémy. Akutní závady řešíme telefonicky, plánované práce můžete poptat online.</p><div className="heroActions"><a className="btn btnSignal" href="tel:+420777000000"><Phone size={15}/> Akutní závada: zavolat</a><a className="btn btnLight" href="#kontakt">Plánovaná práce <ArrowRight size={15}/></a></div><div className="heroHint"><Camera size={15}/><span><strong>Pošlete fotografii závady.</strong> Často podle ní připravíme správný materiál už před výjezdem.</span></div></div><div className="heroPhoto"><img src="https://www.shk-profi.de/imgs/2/3/0/4/2/7/8/Baumgart_Bild1-0546af6053abd05d.jpg" alt="Topenář pracující na potrubí v technické místnosti"/><div className="heroPhotoText"><div><strong>Voda · topení · koupelny · odpady</strong><span>Opravy, rekonstrukce a nové instalace</span></div><div className="heroPhotoIcon"><Wrench size={17}/></div></div></div></div><div className="wrap proofBar"><div className="proofIntro">Základní informace bez hledání:</div><div className="proof">15 let praxe<span>voda a topení</span></div><div className="proof">Cena předem<span>ne až po dokončení</span></div><div className="proof">Pojištění<span>odpovědnosti za škodu</span></div><div className="proof">Do 30 km<span>běžná oblast výjezdu</span></div></div></header>
      <section className="section"><div className="wrap"><div className="sectionHead"><div className="kicker">Co právě řešíte</div><div><h2>Potřebujete opravu, nebo plánujete větší práci?</h2><p>Každá situace má jiný další krok. U závady je nejrychlejší telefon. U plánované zakázky pošlete popis a fotografie.</p></div></div><div className="situations"><article className="situation hot"><span className="situationLabel">Akutní závada</span><div className="situationIcon"><Phone size={18}/></div><h3>Teče voda, netopí topení nebo nefunguje bojler?</h3><div className="tags"><span>prasklá voda</span><span>únik vody</span><span>radiátor</span><span>bojler</span><span>ucpaný odpad</span></div><a className="btn btnSignal" href="tel:+420777000000">Zavolat 777 000 000</a></article><article className="situation plan"><span className="situationLabel">Plánovaná práce</span><div className="situationIcon"><Camera size={18}/></div><h3>Nové rozvody, koupelna nebo topení?</h3><div className="tags"><span>nové rozvody</span><span>koupelna</span><span>podlahové topení</span><span>technická místnost</span></div><a className="btn btnDark" href="#kontakt">Poslat poptávku a fotografie <ArrowRight size={14}/></a></article></div></div></section>
      <section className="section" id="sluzby"><div className="wrap"><div className="sectionHead"><div className="kicker">Služby</div><div><h2>Voda, topení, odpady a instalace při rekonstrukcích.</h2><p>Přehled nejčastějších prací, které řešíme v bytech, rodinných domech a menších provozech.</p></div></div><div className="serviceGrid">{services.map(({icon:Icon,title,text})=><article className="service" key={title}><div className="serviceIcon"><Icon size={19}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="section work" id="realizace"><div className="wrap"><div className="sectionHead"><div className="kicker">Realizace</div><div><h2>Ukázky typických zakázek.</h2><p>Na skutečném webu by zde byly fotografie přímo z hotových realizací a stručný popis provedené práce.</p></div></div><div className="projects"><article className="project"><img src="https://www.isecursos.com/multimedia/estudios/img_78913_instalaciones_sanitarias.jpg" alt="Instalatér při opravě rozvodu pod umyvadlem"/><div className="projectText"><small>České Budějovice · rekonstrukce</small><h3>Nové rozvody vody v rodinném domě</h3></div></article><article className="project"><img src="https://www.shk-profi.de/imgs/2/3/0/4/2/7/8/Baumgart_Bild1-0546af6053abd05d.jpg" alt="Práce v technické místnosti"/><div className="projectText"><small>Rudolfov · voda + topení</small><h3>Technická místnost rodinného domu</h3></div></article><article className="project"><img src="https://vytapeni.tzb-info.cz/docu/clanky/0150/015069o7.jpg" alt="Servis topného systému v technické místnosti"/><div className="projectText"><small>Hluboká nad Vltavou · topení</small><h3>Úprava topného systému</h3></div></article></div><div className="demoNote"><span><strong>Ukázkový obsah.</strong> Firma ani uvedené realizace nejsou skutečné.</span><span>Na ostrém webu patří na toto místo vlastní fotografie firmy.</span></div></div></section>
      <section className="section"><div className="wrap"><div className="sectionHead"><div className="kicker">Podmínky práce</div><div><h2>Co je dobré vědět před objednáním.</h2></div></div><div className="promiseGrid"><article className="promise"><span className="promiseNum">01</span><strong>Cenu řešíme předem</strong><p>U běžné opravy domluvíme cenu nebo hodinovou sazbu. U větší zakázky připravíme nabídku.</p></article><article className="promise"><span className="promiseNum">02</span><strong>Termín potvrzujeme</strong><p>Domluvíme konkrétní den nebo časové okno. Pokud se něco změní, ozveme se.</p></article><article className="promise"><span className="promiseNum">03</span><strong>Materiál můžeme zajistit</strong><p>Podle typu práce přivezeme potřebný materiál, nebo předem řekneme, co je vhodné připravit.</p></article><article className="promise"><span className="promiseNum">04</span><strong>Oprávnění a pojištění</strong><p>Na ostrém webu zde patří konkrétní oprávnění, výše pojištění a podmínky záruky.</p></article></div></div></section>
      <section className="section" id="o-nas"><div className="wrap about"><div className="aboutPhoto"><img src="https://www.shk-profi.de/imgs/2/3/0/4/2/7/8/Baumgart_Bild1-0546af6053abd05d.jpg" alt="Topenář při práci v technické místnosti"/></div><div className="aboutCopy"><div className="kicker">Kdo přijede</div><h2>Jan Novák</h2><p>Instalatér a topenář z Českých Budějovic. V oboru pracuje 15 let. Dělá běžné opravy v domácnostech, nové rozvody vody a topení i instalatérské práce při rekonstrukcích. Menší zakázky řeší osobně, na rozsáhlejší práce přijíždí ve dvou.</p><div className="facts"><div className="fact">15 let<span>praxe v oboru</span></div><div className="fact"><ShieldCheck size={14}/> Pojištění<span>odpovědnosti</span></div><div className="fact"><MapPin size={14}/> České Budějovice<span>a okolí</span></div></div></div></div></section>
      <section className="section"><div className="wrap"><div className="sectionHead"><div className="kicker">Postup</div><div><h2>Od prvního kontaktu k hotové práci.</h2></div></div><div className="steps"><article className="step"><div className="stepNo">1</div><div><h3>Ozvete se</h3><p>Telefonicky nebo formulářem. U plánované práce můžete rovnou přiložit fotografie.</p></div></article><article className="step"><div className="stepNo">2</div><div><h3>Upřesníme práci a cenu</h3><p>U větší zakázky proběhne obhlídka. U malé opravy domluvíme postup a účtování rovnou.</p></div></article><article className="step"><div className="stepNo">3</div><div><h3>Provedeme zakázku</h3><p>Přijedeme v domluveném termínu, provedeme práci a předáme hotový výsledek.</p></div></article></div></div></section>
      <section className="section" id="faq"><div className="wrap areaFaq"><div className="areaBox"><h3>Kde vyjíždíme</h3><p>Běžně České Budějovice a okolí přibližně do 30 km. U větších realizací lze dojezd domluvit individuálně.</p><div className="towns"><span>České Budějovice</span><span>Rudolfov</span><span>Hluboká nad Vltavou</span><span>Lišov</span><span>Borovany</span><span>Třeboň</span></div><div className="areaRule"/><div className="areaDistance"><MapPin size={15}/> běžný výjezd přibližně do 30 km</div></div><div><div className="kicker" style={{marginBottom:14}}>Časté dotazy</div><div className="faq">{faqs.map(([q,a])=><article className="faqItem" key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></div></div></section>
      <section className="contact" id="kontakt"><div className="wrap contactGrid"><div><div className="kicker" style={{color:'#aaa',marginBottom:15}}>Kontakt</div><h2>Potřebujete instalatéra?</h2><p>Akutní závadu řešte telefonicky. U plánované práce pošlete obec, stručný popis a případně fotografie. Podle toho se domluví další postup.</p><div className="contactActions"><a className="btn btnSignal" href="tel:+420777000000"><Phone size={14}/> 777 000 000</a><a className="btn btnLight" href="mailto:ukazka@spustweb.cz">ukazka@spustweb.cz</a></div></div><div className="form"><div className="field">Jméno</div><div className="field">Telefon</div><div className="field wide">Obec</div><div className="field wide big">Co potřebujete?</div><div className="field wide"><Camera size={12}/> &nbsp; Přiložit fotografie</div><div className="btn btnDark">Odeslat poptávku <ArrowRight size={13}/></div><div className="formNote">Ukázkový formulář není aktivní. Stránka představuje možnou podobu webu pro instalatéra.</div></div></div></section>
      <footer className="demoFooter"><div className="wrap footerInner"><div><strong>NOVÁK VODA & TOPENÍ</strong><br/>Fiktivní firma vytvořená pouze jako ukázkový koncept.</div><div>Tento koncept vytvořil <a href="/">SpustWeb.cz</a> · <a href="/#kontakt">Chci web pro své podnikání</a></div></div></footer>
    </div>
  )
}
