import type { Metadata } from 'next'
import { ArrowRight, Bath, Camera, Droplets, Flame, MapPin, Phone, Pipette, ShieldCheck, Wrench } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro instalatéra a topenáře',
  description: 'Ukázka webu pro instalatéra a topenáře: akutní opravy, plánované zakázky, voda, topení, koupelny, realizace a lokální působnost.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/instalater/' },
  robots: { index: true, follow: true },
}

const services = [
  { icon: Droplets, title: 'Voda', text: 'Opravy a nové rozvody vody, baterie, WC, bojlery a napojení spotřebičů.' },
  { icon: Flame, title: 'Topení', text: 'Radiátory, rozvody topení, podlahové vytápění a úpravy topných soustav.' },
  { icon: Bath, title: 'Koupelny', text: 'Příprava vody a odpadů, montáž sanity a instalatérské práce při rekonstrukci.' },
  { icon: Pipette, title: 'Odpady', text: 'Opravy a výměny odpadního potrubí, nové napojení a běžné závady.' },
  { icon: Wrench, title: 'Technické místnosti', text: 'Rozvody, kotle, zásobníky a související technologie.' },
]

const faqs = [
  ['Kolik stojí příjezd instalatéra?', 'Cenu výjezdu a způsob účtování potvrdíme předem. U větších prací připravíme cenovou nabídku.'],
  ['Děláte i malé opravy?', 'Ano. Od výměny baterie nebo ventilu po nové rozvody při rekonstrukci.'],
  ['Jak rychle přijedete při havárii?', 'Zavolejte. Podle aktuální vytíženosti rovnou řekneme nejbližší možný termín výjezdu.'],
  ['Mohu poslat fotografie závady?', 'Ano. Fotografie často pomohou určit potřebný materiál a rozsah práce ještě před výjezdem.'],
  ['Dostanu cenu předem?', 'U běžné opravy domluvíme cenu nebo způsob účtování. U větší realizace dostanete nabídku před zahájením.'],
  ['Do jakých obcí vyjíždíte?', 'Běžně do Českých Budějovic a přibližně 30 km od města. Větší realizace řešíme po dohodě i dál.'],
]

export default function PlumberShowcase() {
  return (
    <div className="plbPage">
      <style>{`
        body:has(.plbPage) > .verno-nav-shell,body:has(.plbPage) > .footer{display:none!important}
        body:has(.plbPage) main{padding:0!important;margin:0!important}
        body:has(.plbPage){background:#fff!important}
        .plbPage{--ink:#111312;--muted:#686b68;--line:#deded9;--soft:#f4f3ef;--signal:#d64d33;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:#fff}
        .plbPage *{box-sizing:border-box}.plbPage a{color:inherit;text-decoration:none}.plbPage svg{stroke-width:1.8}
        .plbWrap{width:min(1180px,calc(100% - 40px));margin:0 auto}
        .plbDemo{height:24px;background:#111312;color:#d8d8d5;display:flex;align-items:center;justify-content:center;font-size:10px;letter-spacing:.07em;text-transform:uppercase}.plbDemo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:6px}
        .plbNavShell{position:sticky;top:0;z-index:100;background:rgba(255,255,255,.98);backdrop-filter:blur(12px);border-bottom:1px solid #d4d5d0;box-shadow:0 8px 26px rgba(17,19,18,.045)}
        .plbNav{height:72px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center}.plbBrand{display:flex;align-items:center;gap:10px;font-size:19px;font-weight:900;letter-spacing:-.04em}.plbDrop{width:15px;height:22px;border:2px solid var(--ink);border-radius:55% 55% 62% 62%;transform:rotate(8deg)}.plbBrand small{display:block;font-size:9px;letter-spacing:.13em;color:var(--muted);margin-top:1px}.plbLinks{display:flex;gap:30px;font-size:12px;font-weight:700}.plbLinks a{position:relative;padding:27px 0}.plbLinks a:after{content:'';position:absolute;left:0;right:100%;bottom:18px;height:2px;background:var(--signal);transition:right .2s ease}.plbLinks a:hover:after{right:0}.plbNavRight{justify-self:end;display:flex;align-items:center;gap:12px}.plbPhone{font-size:12px;font-weight:800}.plbNavCta{background:var(--ink);color:#fff!important;padding:12px 16px;font-size:11px;font-weight:800}.plbNavCta:hover{background:var(--signal)}
        .plbHero{border-bottom:1px solid var(--line)}.plbHeroFrame{height:min(720px,calc(100svh - 96px));min-height:560px;display:grid;grid-template-rows:minmax(0,1fr) 64px}.plbHeroMain{display:grid;grid-template-columns:1.02fr .98fr;min-height:0}.plbHeroCopy{padding:30px 52px 26px 0;display:flex;flex-direction:column;justify-content:center}.plbEyebrow{display:flex;align-items:center;gap:9px;font-size:10px;font-weight:900;letter-spacing:.11em;text-transform:uppercase;color:var(--muted);margin-bottom:15px}.plbEyebrow:before{content:'';width:22px;height:2px;background:var(--signal)}.plbHero h1{font-size:clamp(43px,4.25vw,58px);line-height:.95;letter-spacing:-.052em;margin:0 0 17px;max-width:570px;font-weight:500}.plbLead{font-size:14px;line-height:1.5;color:#414441;max-width:560px;margin:0 0 20px}.plbHeroActions{display:flex;gap:8px;flex-wrap:wrap}.plbBtn{min-height:40px;padding:0 15px;display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid var(--ink);font-size:10.5px;font-weight:900}.plbBtnDark{background:var(--ink);color:#fff!important}.plbBtnSignal{background:var(--signal);border-color:var(--signal);color:#fff!important}.plbBtnLight{background:#fff;color:var(--ink)!important}.plbHeroHint{margin-top:19px;padding-top:13px;border-top:1px solid var(--line);display:flex;gap:8px;align-items:center;font-size:11px;line-height:1.45;color:var(--muted);max-width:560px}.plbHeroHint strong{color:var(--ink)}
        .plbHeroPhoto{position:relative;min-height:0;overflow:hidden;background:#d9d9d4}.plbHeroPhoto img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;filter:saturate(.78) contrast(1.03)}.plbHeroPhoto:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 68%,rgba(0,0,0,.46))}.plbPhotoText{position:absolute;z-index:2;left:22px;right:22px;bottom:18px;color:#fff;display:flex;justify-content:space-between;align-items:end}.plbPhotoText strong{font-size:13px}.plbPhotoText span{display:block;font-size:10.5px;color:#e0e0dc;margin-top:3px}.plbPhotoIcon{width:36px;height:36px;border:1px solid rgba(255,255,255,.8);display:grid;place-items:center}
        .plbProof{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--line)}.plbProofItem{display:flex;flex-direction:column;justify-content:center;padding:10px 20px;border-left:1px solid var(--line);font-size:11.5px;font-weight:800}.plbProofItem:first-child{border-left:0;padding-left:0}.plbProofItem span{font-weight:500;color:var(--muted);margin-top:3px;font-size:10px}
        .plbSection{padding:50px 0}.plbSectionAlt{background:#fafaf8}.plbHead{display:grid;grid-template-columns:165px 1fr;gap:26px;align-items:start;margin-bottom:24px}.plbKicker{font-size:9.5px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;color:var(--muted);padding-top:5px}.plbHead h2{font-size:clamp(30px,3.3vw,43px);line-height:1;letter-spacing:-.043em;margin:0;max-width:740px;font-weight:500}.plbHead p{font-size:12.5px;line-height:1.55;color:var(--muted);max-width:610px;margin:8px 0 0}
        .plbSituations{display:grid;grid-template-columns:1fr 1fr;gap:10px}.plbSituation{padding:20px 22px;border:1px solid var(--line);display:grid;grid-template-columns:1fr auto;gap:0 18px}.plbSituationHot{background:#fff3ef}.plbSituationPlan{background:#f2f2ef}.plbSituationLabel{font-size:9.5px;font-weight:900;letter-spacing:.11em;text-transform:uppercase}.plbSituationIcon{grid-column:2;grid-row:1/3;width:38px;height:38px;border:1px solid var(--ink);display:grid;place-items:center}.plbSituationHot .plbSituationIcon{border-color:var(--signal);color:var(--signal)}.plbSituation h3{grid-column:1;font-size:24px;line-height:1.06;letter-spacing:-.03em;margin:10px 0 11px;font-weight:500}.plbTags{grid-column:1/-1;display:flex;gap:5px;flex-wrap:wrap;margin-bottom:13px}.plbTags span{font-size:9.5px;padding:5px 7px;border:1px solid #c6c6c1}.plbSituation .plbBtn{grid-column:1/-1;justify-self:start;min-height:36px}
        .plbServices{display:grid;grid-template-columns:repeat(5,1fr);border-left:1px solid var(--line);border-top:1px solid var(--line)}.plbService{padding:18px 16px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.plbServiceIcon{width:34px;height:34px;border:1px solid var(--ink);display:grid;place-items:center;margin-bottom:18px}.plbService h3{font-size:16px;letter-spacing:-.02em;margin:0 0 6px}.plbService p{font-size:11px;line-height:1.5;color:var(--muted);margin:0}
        .plbWork{background:var(--ink);color:#fff}.plbWork .plbKicker,.plbWork .plbHead p{color:#aaa}.plbProjects{display:grid;grid-template-columns:1.05fr .975fr .975fr;gap:9px}.plbProject{aspect-ratio:1.55/1;position:relative;overflow:hidden;background:#333}.plbProject img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.72) contrast(1.04)}.plbProject:after{content:'';position:absolute;inset:43% 0 0;background:linear-gradient(transparent,rgba(0,0,0,.82))}.plbProjectText{position:absolute;z-index:2;left:15px;right:15px;bottom:13px}.plbProjectText small{font-size:8.5px;text-transform:uppercase;letter-spacing:.09em;color:#ddd}.plbProjectText h3{font-size:15px;margin:3px 0 0;letter-spacing:-.02em}.plbProject:first-child .plbProjectText h3{font-size:18px}.plbDemoNote{margin-top:11px;padding-top:10px;border-top:1px solid #444;font-size:9.5px;color:#aaa}.plbDemoNote strong{color:#fff}
        .plbConditions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));column-gap:54px;border:0}.plbCondition{padding:24px 0 28px;border:0;border-top:1px solid var(--line);display:grid;grid-template-columns:44px 1fr;align-content:start}.plbConditionNum{grid-column:1;grid-row:1/3;font-size:10px;font-weight:900;color:var(--signal);padding-top:2px}.plbCondition strong{grid-column:2;display:block;font-size:15px;margin:0 0 8px}.plbCondition p{grid-column:2;font-size:11px;line-height:1.55;color:var(--muted);margin:0;max-width:430px}
        .plbAbout{display:grid;grid-template-columns:.72fr 1.28fr;border:1px solid var(--line)}.plbAboutPhoto{position:relative;min-height:310px;overflow:hidden;background:#ddd}.plbAboutPhoto img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.76)}.plbAboutCopy{padding:30px 34px;display:flex;flex-direction:column;justify-content:center}.plbAboutCopy h2{font-size:34px;line-height:.98;letter-spacing:-.04em;margin:10px 0;font-weight:500}.plbAboutCopy p{font-size:12.5px;line-height:1.6;color:#444;max-width:590px;margin:0}.plbFacts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:17px}.plbFact{padding-top:9px;border-top:1px solid var(--line);font-size:10.5px;font-weight:800}.plbFact span{display:block;font-size:9.5px;font-weight:500;color:var(--muted);margin-top:3px}
        .plbSteps{display:grid;grid-template-columns:repeat(3,1fr);border:0}.plbStep{border:0;padding:10px 34px 8px 0;display:grid;grid-template-columns:42px 1fr;gap:14px;min-height:112px}.plbStep + .plbStep{border-left:1px solid var(--line);padding-left:34px}.plbStepNo{font-size:34px;font-weight:500;line-height:1;color:#b9b9b4}.plbStep h3{font-size:14px;margin:1px 0 7px}.plbStep p{font-size:11px;line-height:1.52;color:var(--muted);margin:0}
        .plbAreaFaq{display:grid;grid-template-columns:.78fr 1.22fr;gap:28px}.plbArea{background:var(--soft);padding:23px}.plbArea h3{font-size:22px;letter-spacing:-.03em;margin:0 0 8px}.plbArea p{font-size:11.5px;line-height:1.55;color:var(--muted);margin:0}.plbTowns{display:flex;gap:5px;flex-wrap:wrap;margin:14px 0}.plbTowns span{font-size:9.5px;border:1px solid #bbb;padding:5px 6px}.plbDistance{padding-top:14px;border-top:1px solid #cfcfca;font-size:10.5px;font-weight:800;display:flex;gap:6px;align-items:center}.plbFaq{border-top:1px solid var(--line)}.plbFaqItem{padding:12px 0;border-bottom:1px solid var(--line)}.plbFaqItem h3{font-size:11.5px;margin:0 0 4px}.plbFaqItem p{font-size:10.75px;line-height:1.5;color:var(--muted);margin:0}
        .plbContact{background:#111312;color:#fff;padding:46px 0}.plbContactGrid{display:grid;grid-template-columns:1fr .9fr;gap:50px}.plbContact h2{font-size:clamp(34px,3.8vw,48px);line-height:.96;letter-spacing:-.045em;margin:0 0 12px;font-weight:500}.plbContact p{font-size:12px;line-height:1.6;color:#bcbfbc;max-width:500px}.plbContactActions{display:flex;gap:7px;flex-wrap:wrap;margin-top:17px}.plbForm{background:#fff;color:#111;padding:15px;display:grid;grid-template-columns:1fr 1fr;gap:6px}.plbField{border:1px solid #d5d5d0;min-height:35px;padding:0 9px;display:flex;align-items:center;font-size:10px;color:#777}.plbFieldWide{grid-column:1/-1}.plbFieldBig{min-height:54px;align-items:flex-start;padding-top:9px}.plbForm .plbBtn{grid-column:1/-1;min-height:36px}.plbFormNote{grid-column:1/-1;font-size:9px;color:#777;line-height:1.35}.plbFooter{background:#080908;color:#aaa;border-top:3px solid var(--signal)}.plbFooterInner{min-height:132px;padding:30px 0;display:grid;grid-template-columns:1fr auto;align-items:center;gap:46px;font-size:10.5px;line-height:1.6}.plbFooter strong,.plbFooter a{color:#fff!important}.plbFooter strong{display:inline-block;font-size:15px;margin-bottom:4px}.plbFooterInner>div:last-child{display:flex;align-items:center;gap:16px}.plbFooterInner>div:last-child a:last-child{display:inline-flex;min-height:39px;align-items:center;padding:0 14px;border:1px solid #555a56;background:#151715;font-weight:800}.plbFooterInner>div:last-child a:last-child:hover{background:var(--signal);border-color:var(--signal)}
        @media(max-width:980px){.plbNav{grid-template-columns:1fr auto;height:66px}.plbLinks{display:none}.plbHeroFrame{height:auto;max-height:none;min-height:0;grid-template-rows:auto auto}.plbHeroMain{grid-template-columns:1fr}.plbHeroCopy{padding:38px 0 30px}.plbHeroPhoto{height:430px}.plbProof{grid-template-columns:repeat(2,1fr)}.plbProofItem:nth-child(odd){border-left:0}.plbHead{grid-template-columns:1fr;gap:7px}.plbServices{grid-template-columns:repeat(2,1fr)}.plbProjects{grid-template-columns:1fr 1fr}.plbProject:first-child{grid-column:1/-1}.plbConditions{grid-template-columns:repeat(2,1fr);column-gap:34px}.plbAbout,.plbContactGrid,.plbAreaFaq{grid-template-columns:1fr}.plbFooterInner{grid-template-columns:1fr;gap:18px}.plbFooterInner>div:last-child{justify-content:space-between}}
        @media(max-width:650px){.plbWrap{width:min(100% - 28px,1180px)}.plbDemo{height:auto;min-height:24px;padding:5px 10px;text-align:center;line-height:1.3;font-size:8.5px}.plbNav{height:60px}.plbPhone{display:none}.plbNavCta{padding:9px 10px}.plbHeroCopy{padding:31px 0 26px}.plbHero h1{font-size:40px}.plbLead{font-size:13px}.plbHeroPhoto{height:360px}.plbProof{grid-template-columns:1fr 1fr}.plbProofItem{padding:10px}.plbSection{padding:40px 0}.plbHead h2{font-size:31px}.plbSituations,.plbServices,.plbProjects{grid-template-columns:1fr}.plbProject:first-child{grid-column:1}.plbProject{aspect-ratio:1.4/1}.plbConditions{grid-template-columns:1fr}.plbCondition{grid-template-columns:38px 1fr;padding:20px 0 22px}.plbAboutPhoto{min-height:300px}.plbAboutCopy{padding:25px 20px}.plbFacts{grid-template-columns:1fr}.plbSteps{grid-template-columns:1fr}.plbStep,.plbStep + .plbStep{border-left:0;border-top:1px solid var(--line);padding:20px 0;min-height:0}.plbForm{grid-template-columns:1fr}.plbField{grid-column:1/-1}.plbContact{padding:38px 0}.plbFooterInner{min-height:0;padding:26px 0}.plbFooterInner>div:last-child{display:grid;justify-content:start;gap:12px}}
      `}</style>

      <div className="plbDemo">Ukázkový koncept SpustWeb.cz · nejde o skutečnou firmu · <a href="/">zpět na SpustWeb.cz</a></div>
      <div className="plbNavShell"><div className="plbWrap"><nav className="plbNav"><a className="plbBrand" href="#top"><span className="plbDrop"/><span>NOVÁK<small>VODA & TOPENÍ</small></span></a><div className="plbLinks"><a href="#sluzby">Služby</a><a href="#realizace">Realizace</a><a href="#o-nas">O nás</a><a href="#faq">Časté dotazy</a></div><div className="plbNavRight"><a className="plbPhone" href="tel:+420777000000">777 000 000</a><a className="plbNavCta" href="#kontakt">Poslat poptávku</a></div></nav></div></div>
      <header className="plbHero" id="top"><div className="plbWrap plbHeroFrame"><div className="plbHeroMain"><div className="plbHeroCopy"><div className="plbEyebrow">Instalatér a topenář · České Budějovice a okolí</div><h1>Voda a topení pro domy a byty v Českých Budějovicích a okolí.</h1><p className="plbLead">Opravy, nové rozvody, koupelny a topné systémy. Akutní závady řešíme telefonicky, plánované práce můžete poptat online.</p><div className="plbHeroActions"><a className="plbBtn plbBtnSignal" href="tel:+420777000000"><Phone size={14}/> Akutní závada: zavolat</a><a className="plbBtn plbBtnLight" href="#kontakt">Plánovaná práce <ArrowRight size={14}/></a></div><div className="plbHeroHint"><Camera size={14}/><span><strong>Pošlete fotografii závady.</strong> Často podle ní připravíme správný materiál už před výjezdem.</span></div></div><div className="plbHeroPhoto"><img src="https://www.shk-profi.de/imgs/2/3/0/4/2/7/8/Baumgart_Bild1-0546af6053abd05d.jpg" alt="Topenář pracující na potrubí v technické místnosti"/><div className="plbPhotoText"><div><strong>Voda · topení · koupelny · odpady</strong><span>Opravy, rekonstrukce a nové instalace</span></div><div className="plbPhotoIcon"><Wrench size={16}/></div></div></div></div><div className="plbProof"><div className="plbProofItem">15 let praxe<span>voda a topení</span></div><div className="plbProofItem">Cena předem<span>ne až po dokončení</span></div><div className="plbProofItem">Pojištění<span>odpovědnosti za škodu</span></div><div className="plbProofItem">Do 30 km<span>běžná oblast výjezdu</span></div></div></div></header>

      <section className="plbSection"><div className="plbWrap"><div className="plbHead"><div className="plbKicker">Co právě řešíte</div><div><h2>Potřebujete opravu, nebo plánujete větší práci?</h2><p>U závady je nejrychlejší telefon. U plánované zakázky pošlete stručný popis a fotografie.</p></div></div><div className="plbSituations"><article className="plbSituation plbSituationHot"><span className="plbSituationLabel">Akutní závada</span><div className="plbSituationIcon"><Phone size={17}/></div><h3>Teče voda, netopí topení nebo nefunguje bojler?</h3><div className="plbTags"><span>prasklá voda</span><span>únik vody</span><span>radiátor</span><span>bojler</span><span>ucpaný odpad</span></div><a className="plbBtn plbBtnSignal" href="tel:+420777000000">Zavolat 777 000 000</a></article><article className="plbSituation plbSituationPlan"><span className="plbSituationLabel">Plánovaná práce</span><div className="plbSituationIcon"><Camera size={17}/></div><h3>Nové rozvody, koupelna nebo topení?</h3><div className="plbTags"><span>nové rozvody</span><span>koupelna</span><span>podlahové topení</span><span>technická místnost</span></div><a className="plbBtn plbBtnDark" href="#kontakt">Poslat poptávku a fotografie <ArrowRight size={13}/></a></article></div></div></section>

      <section className="plbSection plbSectionAlt" id="sluzby"><div className="plbWrap"><div className="plbHead"><div className="plbKicker">Služby</div><div><h2>Voda, topení, odpady a instalace při rekonstrukcích.</h2><p>Nejčastější práce v bytech, rodinných domech a menších provozech.</p></div></div><div className="plbServices">{services.map(({icon:Icon,title,text})=><article className="plbService" key={title}><div className="plbServiceIcon"><Icon size={17}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="plbSection plbWork" id="realizace"><div className="plbWrap"><div className="plbHead"><div className="plbKicker">Realizace</div><div><h2>Ukázky typických zakázek.</h2></div></div><div className="plbProjects"><article className="plbProject"><img src="https://www.isecursos.com/multimedia/estudios/img_78913_instalaciones_sanitarias.jpg" alt="Instalatér při opravě rozvodu pod umyvadlem"/><div className="plbProjectText"><small>České Budějovice · rekonstrukce</small><h3>Nové rozvody vody v rodinném domě</h3></div></article><article className="plbProject"><img src="https://www.shk-profi.de/imgs/2/3/0/4/2/7/8/Baumgart_Bild1-0546af6053abd05d.jpg" alt="Práce v technické místnosti"/><div className="plbProjectText"><small>Rudolfov · voda + topení</small><h3>Technická místnost rodinného domu</h3></div></article><article className="plbProject"><img src="https://vytapeni.tzb-info.cz/docu/clanky/0150/015069o7.jpg" alt="Servis topného systému v technické místnosti"/><div className="plbProjectText"><small>Hluboká nad Vltavou · topení</small><h3>Úprava topného systému</h3></div></article></div><div className="plbDemoNote"><strong>Ukázkový obsah:</strong> firma ani uvedené realizace nejsou skutečné.</div></div></section>

      <section className="plbSection"><div className="plbWrap"><div className="plbHead"><div className="plbKicker">Podmínky práce</div><div><h2>Co je dobré vědět před objednáním.</h2></div></div><div className="plbConditions"><article className="plbCondition"><span className="plbConditionNum">01</span><strong>Cenu řešíme předem</strong><p>U běžné opravy domluvíme cenu nebo hodinovou sazbu. U větší zakázky připravíme nabídku.</p></article><article className="plbCondition"><span className="plbConditionNum">02</span><strong>Termín potvrzujeme</strong><p>Domluvíme konkrétní den nebo časové okno. Pokud se něco změní, ozveme se.</p></article><article className="plbCondition"><span className="plbConditionNum">03</span><strong>Materiál můžeme zajistit</strong><p>Podle typu práce přivezeme potřebný materiál, případně předem upřesníme vhodné řešení.</p></article><article className="plbCondition"><span className="plbConditionNum">04</span><strong>Oprávnění a pojištění</strong><p>Odborné práce provádíme v rozsahu příslušných oprávnění a s pojištěním odpovědnosti.</p></article></div></div></section>

      <section className="plbSection plbSectionAlt" id="o-nas"><div className="plbWrap plbAbout"><div className="plbAboutPhoto"><img src="https://www.shk-profi.de/imgs/2/3/0/4/2/7/8/Baumgart_Bild1-0546af6053abd05d.jpg" alt="Topenář při práci v technické místnosti"/></div><div className="plbAboutCopy"><div className="plbKicker">Kdo přijede</div><h2>Jan Novák</h2><p>Instalatér a topenář z Českých Budějovic. V oboru pracuje 15 let. Dělá běžné opravy v domácnostech, nové rozvody vody a topení i instalatérské práce při rekonstrukcích. Menší zakázky řeší osobně, na rozsáhlejší práce přijíždí ve dvou.</p><div className="plbFacts"><div className="plbFact">15 let<span>praxe v oboru</span></div><div className="plbFact"><ShieldCheck size={13}/> Pojištění<span>odpovědnosti</span></div><div className="plbFact"><MapPin size={13}/> České Budějovice<span>a okolí</span></div></div></div></div></section>

      <section className="plbSection"><div className="plbWrap"><div className="plbHead"><div className="plbKicker">Postup</div><div><h2>Od prvního kontaktu k hotové práci.</h2></div></div><div className="plbSteps"><article className="plbStep"><div className="plbStepNo">1</div><div><h3>Ozvete se</h3><p>Telefonicky nebo formulářem. U plánované práce můžete rovnou přiložit fotografie.</p></div></article><article className="plbStep"><div className="plbStepNo">2</div><div><h3>Upřesníme práci a cenu</h3><p>U větší zakázky proběhne obhlídka. U malé opravy domluvíme postup a účtování rovnou.</p></div></article><article className="plbStep"><div className="plbStepNo">3</div><div><h3>Provedeme zakázku</h3><p>Přijedeme v domluveném termínu, provedeme práci a předáme hotový výsledek.</p></div></article></div></div></section>

      <section className="plbSection plbSectionAlt" id="faq"><div className="plbWrap plbAreaFaq"><div className="plbArea"><h3>Kde vyjíždíme</h3><p>Běžně České Budějovice a okolí přibližně do 30 km. U větších realizací lze dojezd domluvit individuálně.</p><div className="plbTowns"><span>České Budějovice</span><span>Rudolfov</span><span>Hluboká nad Vltavou</span><span>Lišov</span><span>Borovany</span><span>Třeboň</span></div><div className="plbDistance"><MapPin size={14}/> běžný výjezd přibližně do 30 km</div></div><div><div className="plbKicker" style={{marginBottom:12}}>Časté dotazy</div><div className="plbFaq">{faqs.map(([q,a])=><article className="plbFaqItem" key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></div></div></section>

      <section className="plbContact" id="kontakt"><div className="plbWrap plbContactGrid"><div><div className="plbKicker" style={{color:'#aaa',marginBottom:13}}>Kontakt</div><h2>Potřebujete instalatéra?</h2><p>Akutní závadu řešte telefonicky. U plánované práce pošlete obec, stručný popis a případně fotografie. Podle toho se domluví další postup.</p><div className="plbContactActions"><a className="plbBtn plbBtnSignal" href="tel:+420777000000"><Phone size={13}/> 777 000 000</a><a className="plbBtn plbBtnLight" href="mailto:kontakt@spustweb.cz">kontakt@spustweb.cz</a></div></div><div className="plbForm"><div className="plbField">Jméno</div><div className="plbField">Telefon</div><div className="plbField plbFieldWide">Obec</div><div className="plbField plbFieldWide plbFieldBig">Co potřebujete?</div><div className="plbField plbFieldWide"><Camera size={11}/> &nbsp; Přiložit fotografie</div><div className="plbBtn plbBtnDark">Odeslat poptávku <ArrowRight size={12}/></div><div className="plbFormNote">Ukázkový formulář není aktivní.</div></div></div></section>

      <footer className="plbFooter"><div className="plbWrap plbFooterInner"><div><strong>NOVÁK VODA & TOPENÍ</strong><br/>Fiktivní firma vytvořená pouze jako ukázkový koncept.</div><div>Tento koncept vytvořil <a href="/">SpustWeb.cz</a> · <a href="/#kontakt">Chci web pro své podnikání</a></div></div></footer>
    </div>
  )
}