import type { Metadata } from 'next'
import { ArrowRight, Bath, Camera, Droplets, Flame, MapPin, Phone, Pipette, ShieldCheck, Wrench } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro instalatéra a topenáře',
  description: 'Ukázka webu pro instalatéra a topenáře: akutní opravy, plánované zakázky, voda, topení, koupelny, realizace a lokální působnost.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/instalater/' },
  robots: { index: true, follow: true },
}

const services = [
  { icon: Droplets, title: 'Voda', text: 'Opravy a nové rozvody vody, baterie, WC, bojlery a napojení spotřebičů.' },
  { icon: Flame, title: 'Topení', text: 'Radiátory, rozvody, podlahové vytápění a úpravy topných soustav.' },
  { icon: Bath, title: 'Koupelny', text: 'Příprava vody a odpadů, montáž sanity a instalace při rekonstrukcích.' },
  { icon: Pipette, title: 'Odpady', text: 'Opravy a výměny odpadního potrubí, napojení a běžné závady.' },
  { icon: Wrench, title: 'Technické místnosti', text: 'Rozvody, kotle, zásobníky a související technologie podle konkrétního systému.' },
]

const faqs = [
  ['Kolik stojí příjezd instalatéra?', 'Cenu výjezdu a způsob účtování si potvrdíme předem. U plánovaných prací připravíme nabídku podle rozsahu.'],
  ['Děláte i malé opravy?', 'Ano. Běžné opravy v domácnostech i větší plánované instalace.'],
  ['Jak rychle přijedete při havárii?', 'Akutní závady řešíme telefonicky. Rovnou řekneme nejbližší možný termín výjezdu.'],
  ['Mohu poslat fotografie závady?', 'Ano. Fotografie často pomohou předem určit rozsah práce a potřebný materiál.'],
  ['Dostanu cenu předem?', 'U běžné opravy domluvíme cenu nebo způsob účtování. U větší realizace dostanete nabídku.'],
  ['Do jakých obcí vyjíždíte?', 'Běžně do Českých Budějovic a přibližně 30 km od města. Větší realizace po dohodě i dál.'],
]

export default function PlumberShowcase() {
  return (
    <div className="demoPage">
      <style>{`
        body:has(.demoPage) > .verno-nav-shell,body:has(.demoPage) > .footer{display:none!important}
        body:has(.demoPage) main{padding:0!important;margin:0!important}
        body:has(.demoPage){background:#fff!important}
        .demoPage{--ink:#111312;--muted:#666a67;--line:#deded9;--paper:#fff;--soft:#f4f3ef;--signal:#d64d33;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:#fff}
        .demoPage *{box-sizing:border-box}.demoPage a{color:inherit;text-decoration:none}.demoPage svg{stroke-width:1.8}
        .wrap{width:min(1180px,calc(100% - 40px));margin:0 auto}
        .demoBar{background:#111312;color:#d9d9d6;font-size:10px;letter-spacing:.06em;text-transform:uppercase;text-align:center;padding:8px 16px}.demoBar a{color:#fff;text-decoration:underline;text-underline-offset:3px}
        .nav{height:72px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;border-bottom:1px solid var(--line)}
        .brand{display:flex;align-items:center;gap:10px;font-size:20px;font-weight:900;letter-spacing:-.045em}.brandDrop{width:17px;height:24px;border:2px solid var(--ink);border-radius:55% 55% 60% 60%;transform:rotate(8deg)}.brand small{display:block;font-size:9px;letter-spacing:.13em;color:var(--muted);margin-top:1px}
        .navLinks{display:flex;gap:28px;font-size:12px;font-weight:700}.navRight{justify-self:end;display:flex;align-items:center;gap:14px}.navPhone{font-size:12px;font-weight:800}.navCta{background:var(--ink);color:#fff;padding:12px 16px;font-size:11px;font-weight:800}
        .hero{border-bottom:1px solid var(--line)}.heroGrid{display:grid;grid-template-columns:1.02fr .98fr;min-height:610px}
        .heroCopy{padding:66px 54px 44px 0;display:flex;flex-direction:column;justify-content:center}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.09em;text-transform:uppercase;color:var(--muted);margin-bottom:25px}
        .hero h1{font-size:clamp(50px,5.7vw,78px);line-height:.94;letter-spacing:-.06em;margin:0 0 25px;max-width:660px}.heroLead{font-size:17px;line-height:1.55;color:#3f4340;max-width:610px;margin:0 0 28px}.heroActions{display:flex;gap:9px;flex-wrap:wrap}.btn{min-height:46px;padding:0 18px;display:inline-flex;align-items:center;justify-content:center;gap:8px;border:1px solid var(--ink);font-size:11px;font-weight:900;letter-spacing:.01em}.btnDark{background:var(--ink);color:#fff}.btnSignal{background:var(--signal);border-color:var(--signal);color:#fff}.btnLight{background:#fff}
        .heroHint{margin-top:34px;padding-top:20px;border-top:1px solid var(--line);display:flex;gap:9px;align-items:center;font-size:11px;color:var(--muted)}.heroHint strong{color:var(--ink)}
        .heroPhoto{position:relative;min-height:610px;overflow:hidden;background:#d9d9d4}.heroPhoto img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;filter:saturate(.72) contrast(1.03)}.heroPhoto:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 62%,rgba(0,0,0,.48))}.heroPhotoText{position:absolute;z-index:2;left:28px;right:28px;bottom:25px;color:#fff;display:flex;justify-content:space-between;align-items:end}.heroPhotoText strong{font-size:16px}.heroPhotoText span{display:block;font-size:10px;color:#ddd;margin-top:4px}.heroPhotoIcon{width:42px;height:42px;border:1px solid rgba(255,255,255,.8);display:grid;place-items:center}
        .proofBar{display:grid;grid-template-columns:1.35fr repeat(4,1fr);border-top:1px solid var(--line)}.proofIntro,.proof{min-height:88px;display:flex;flex-direction:column;justify-content:center;padding:16px 20px}.proofIntro{font-size:12px;font-weight:800;padding-left:0}.proof{border-left:1px solid var(--line);font-size:11px;font-weight:800}.proof span{font-weight:500;color:var(--muted);margin-top:4px;line-height:1.35}
        .section{padding:84px 0}.sectionHead{display:grid;grid-template-columns:230px 1fr;gap:40px;align-items:start;margin-bottom:36px}.kicker{font-size:10px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);padding-top:7px}.sectionHead h2{font-size:clamp(36px,4.5vw,58px);line-height:.98;letter-spacing:-.05em;margin:0;max-width:760px}.sectionHead p{font-size:14px;line-height:1.6;color:var(--muted);max-width:640px;margin:15px 0 0}
        .situations{display:grid;grid-template-columns:1fr 1fr;gap:14px}.situation{min-height:330px;padding:30px;border:1px solid var(--line);display:flex;flex-direction:column}.situation.hot{background:#fff4f1}.situation.plan{background:#f1f2ef}.situationTop{display:flex;justify-content:space-between;align-items:start}.situationLabel{font-size:10px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.situationIcon{width:46px;height:46px;border:1px solid var(--ink);display:grid;place-items:center}.hot .situationIcon{border-color:var(--signal);color:var(--signal)}.situation h3{font-size:34px;letter-spacing:-.04em;margin:45px 0 18px}.tags{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:25px}.tags span{font-size:10px;padding:7px 9px;border:1px solid #bdbdb8}.situation .btn{align-self:flex-start;margin-top:auto}
        .serviceGrid{display:grid;grid-template-columns:repeat(5,1fr);border-left:1px solid var(--line);border-top:1px solid var(--line)}.service{min-height:285px;padding:23px 21px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);display:flex;flex-direction:column}.serviceIcon{width:44px;height:44px;display:grid;place-items:center;border:1px solid var(--ink);margin-bottom:auto}.service h3{font-size:20px;letter-spacing:-.03em;margin:0 0 9px}.service p{font-size:11px;line-height:1.55;color:var(--muted);margin:0}
        .work{background:var(--ink);color:#fff}.work .kicker,.work .sectionHead p{color:#aaa}.projects{display:grid;grid-template-columns:1.15fr .85fr .85fr;gap:12px}.project{min-height:340px;position:relative;overflow:hidden;background:#333}.project img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.68) contrast(1.04)}.project:after{content:'';position:absolute;inset:45% 0 0;background:linear-gradient(transparent,rgba(0,0,0,.8))}.projectText{position:absolute;z-index:2;left:20px;right:20px;bottom:18px}.projectText small{font-size:9px;text-transform:uppercase;letter-spacing:.09em;color:#ddd}.projectText h3{font-size:20px;margin:5px 0 0;letter-spacing:-.03em}.project:first-child .projectText h3{font-size:26px}.demoNote{margin-top:17px;padding-top:16px;border-top:1px solid #454545;font-size:10px;color:#aaa;display:flex;justify-content:space-between;gap:30px}.demoNote strong{color:#fff}
        .promiseGrid{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line)}.promise{min-height:210px;padding:25px 22px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.promiseNum{font-size:11px;font-weight:900;color:var(--signal)}.promise strong{display:block;font-size:17px;letter-spacing:-.02em;margin:54px 0 9px}.promise p{font-size:11px;line-height:1.55;color:var(--muted);margin:0}
        .about{display:grid;grid-template-columns:.88fr 1.12fr;border:1px solid var(--line)}.aboutPhoto{position:relative;min-height:500px;overflow:hidden;background:#ddd}.aboutPhoto img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.7)}.aboutCopy{padding:54px;display:flex;flex-direction:column;justify-content:center}.aboutCopy h2{font-size:50px;line-height:.95;letter-spacing:-.05em;margin:18px 0}.aboutCopy p{font-size:14px;line-height:1.65;color:#444;max-width:580px}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:28px}.fact{padding-top:12px;border-top:1px solid var(--line);font-size:11px;font-weight:800}.fact span{display:block;font-size:10px;font-weight:500;color:var(--muted);margin-top:4px}
        .steps{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.step{min-height:250px;border:1px solid var(--line);padding:25px;display:flex;flex-direction:column}.stepNo{font-size:46px;font-weight:900;letter-spacing:-.06em;color:#b7b7b2}.step h3{font-size:19px;margin:auto 0 8px}.step p{font-size:11px;line-height:1.55;color:var(--muted);margin:0}
        .areaFaq{display:grid;grid-template-columns:.9fr 1.1fr;gap:34px}.areaBox{background:var(--soft);padding:34px}.areaBox h3{font-size:31px;letter-spacing:-.04em;margin:0 0 14px}.areaBox p{font-size:12px;line-height:1.55;color:var(--muted)}.towns{display:flex;gap:6px;flex-wrap:wrap;margin:22px 0}.towns span{font-size:10px;border:1px solid #bbb;padding:7px 8px}.areaRule{height:1px;background:#cfcfca;margin:28px 0}.areaDistance{font-size:12px;font-weight:800;display:flex;gap:8px;align-items:center}.faq{border-top:1px solid var(--line)}.faqItem{padding:17px 0;border-bottom:1px solid var(--line)}.faqItem h3{font-size:13px;margin:0 0 6px}.faqItem p{font-size:11px;line-height:1.55;color:var(--muted);margin:0}
        .contact{background:#111312;color:#fff;padding:64px 0}.contactGrid{display:grid;grid-template-columns:1fr .86fr;gap:70px}.contact h2{font-size:clamp(43px,5vw,64px);line-height:.94;letter-spacing:-.055em;margin:0 0 20px}.contact p{font-size:13px;line-height:1.6;color:#bcbfbc;max-width:530px}.contactActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:24px}.contact .btnLight{background:#fff;color:#111}.form{background:#fff;color:#111;padding:22px;display:grid;grid-template-columns:1fr 1fr;gap:8px}.field{border:1px solid #d5d5d0;min-height:45px;padding:0 11px;display:flex;align-items:center;font-size:10px;color:#777}.field.wide{grid-column:1/-1}.field.big{min-height:78px;align-items:flex-start;padding-top:12px}.form .btn{grid-column:1/-1}.formNote{grid-column:1/-1;font-size:9px;color:#777;line-height:1.4}
        .demoFooter{background:#090a09;color:#aaa;border-top:1px solid #2d2d2d}.footerInner{padding:23px 0;display:flex;justify-content:space-between;gap:30px;font-size:10px;line-height:1.5}.demoFooter strong{color:#fff}.demoFooter a{color:#fff;text-decoration:underline;text-underline-offset:3px}
        @media(max-width:980px){.nav{grid-template-columns:1fr auto}.navLinks{display:none}.heroGrid{grid-template-columns:1fr}.heroCopy{padding-right:0}.proofBar{grid-template-columns:repeat(2,1fr)}.proofIntro{grid-column:1/-1}.proof:nth-child(even){border-left:0}.sectionHead{grid-template-columns:1fr;gap:10px}.serviceGrid{grid-template-columns:repeat(2,1fr)}.projects{grid-template-columns:1fr 1fr}.project:first-child{grid-column:1/-1}.promiseGrid{grid-template-columns:repeat(2,1fr)}.about,.contactGrid,.areaFaq{grid-template-columns:1fr}}
        @media(max-width:650px){.wrap{width:min(100% - 28px,1180px)}.nav{height:62px}.navPhone{display:none}.navCta{padding:10px 12px}.heroCopy{padding:45px 0 35px}.hero h1{font-size:48px}.heroPhoto{min-height:420px}.proofBar{grid-template-columns:1fr 1fr}.proofIntro{grid-column:1/-1;padding-left:0}.section{padding:62px 0}.sectionHead h2{font-size:38px}.situations{grid-template-columns:1fr}.serviceGrid,.promiseGrid{grid-template-columns:1fr}.projects{grid-template-columns:1fr}.project:first-child{grid-column:1}.aboutPhoto{min-height:380px}.aboutCopy{padding:34px 24px}.facts{grid-template-columns:1fr}.steps{grid-template-columns:1fr}.form{grid-template-columns:1fr}.field,.field.wide,.form .btn,.formNote{grid-column:1}.footerInner{flex-direction:column}}
      `}</style>
      <div className="demoBar">Ukázkový koncept SpustWeb.cz · nejde o skutečnou firmu · <a href="/">zpět na SpustWeb.cz</a></div>
      <div className="wrap"><nav className="nav"><a className="brand" href="#top"><span className="brandDrop"/><span>NOVÁK<small>VODA & TOPENÍ</small></span></a><div className="navLinks"><a href="#sluzby">Služby</a><a href="#realizace">Realizace</a><a href="#o-nas">O nás</a><a href="#faq">Časté dotazy</a></div><div className="navRight"><a className="navPhone" href="tel:+420777000000">777 000 000</a><a className="navCta" href="#kontakt">Poslat poptávku</a></div></nav></div>
      <header className="hero" id="top"><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow">Instalatér a topenář · České Budějovice a okolí</div><h1>Voda a topení pro domy a byty v Českých Budějovicích a okolí.</h1><p className="heroLead">Opravy, nové rozvody, koupelny a topné systémy. Akutní závady řešíme telefonicky, plánované práce můžete jednoduše poptat online.</p><div className="heroActions"><a className="btn btnSignal" href="tel:+420777000000"><Phone size={15}/> Potřebuji rychlou pomoc</a><a className="btn btnLight" href="#kontakt">Plánuji zakázku <ArrowRight size={15}/></a></div><div className="heroHint"><Camera size={15}/><span><strong>Pošlete fotografii závady.</strong> Často podle ní poznáme, co bude potřeba.</span></div></div><div className="heroPhoto"><img src="https://www.shk-profi.de/imgs/2/3/0/4/2/7/8/Baumgart_Bild1-0546af6053abd05d.jpg" alt="Topenář pracující na potrubí v technické místnosti"/><div className="heroPhotoText"><div><strong>Voda · topení · koupelny · odpady</strong><span>Menší opravy i celé realizace</span></div><div className="heroPhotoIcon"><Wrench size={18}/></div></div></div></div><div className="wrap proofBar"><div className="proofIntro">Co chcete vědět ještě před prvním telefonátem:</div><div className="proof">15 let praxe<span>voda a topení</span></div><div className="proof">Cena předem<span>ne až po práci</span></div><div className="proof">Pojištění<span>odpovědnost za škodu</span></div><div className="proof">30 km<span>běžná oblast výjezdu</span></div></div></header>
      <section className="section"><div className="wrap"><div className="sectionHead"><div className="kicker">Podle situace</div><div><h2>Jiný postup, když teče voda. Jiný, když plánujete koupelnu.</h2><p>Na webu nemusíte hledat, pod jakou službu problém patří. Stačí začít podle toho, co právě potřebujete.</p></div></div><div className="situations"><article className="situation hot"><div className="situationTop"><span className="situationLabel">Akutní závada</span><div className="situationIcon"><Phone size={20}/></div></div><h3>Něco nefunguje?</h3><div className="tags"><span>prasklá voda</span><span>únik vody</span><span>topení netopí</span><span>bojler</span><span>ucpaný odpad</span></div><a className="btn btnSignal" href="tel:+420777000000">Zavolat 777 000 000</a></article><article className="situation plan"><div className="situationTop"><span className="situationLabel">Plánovaná práce</span><div className="situationIcon"><Camera size={20}/></div></div><h3>Chystáte rekonstrukci nebo novou instalaci?</h3><div className="tags"><span>nové rozvody</span><span>koupelna</span><span>podlahové topení</span><span>technická místnost</span></div><a className="btn btnDark" href="#kontakt">Poslat poptávku a fotografie <ArrowRight size={15}/></a></article></div></div></section>
      <section className="section" id="sluzby"><div className="wrap"><div className="sectionHead"><div className="kicker">Služby</div><div><h2>Co pro vás můžeme udělat.</h2><p>Konkrétní práce rozdělené tak, aby návštěvník během pár sekund poznal, jestli řešíme právě jeho zakázku.</p></div></div><div className="serviceGrid">{services.map(({icon:Icon,title,text})=><article className="service" key={title}><div className="serviceIcon"><Icon size={21}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="section work" id="realizace"><div className="wrap"><div className="sectionHead"><div className="kicker">Realizace</div><div><h2>Práci je lepší ukázat než o ní mluvit.</h2><p>Na ostrém webu by tu byly fotografie přímo ze zakázek, ne katalogové obrázky.</p></div></div><div className="projects"><article className="project"><img src="https://www.isecursos.com/multimedia/estudios/img_78913_instalaciones_sanitarias.jpg" alt="Instalatér při opravě rozvodu pod umyvadlem"/><div className="projectText"><small>České Budějovice · rekonstrukce</small><h3>Nové rozvody vody v rodinném domě</h3></div></article><article className="project"><img src="https://www.shk-profi.de/imgs/2/3/0/4/2/7/8/Baumgart_Bild1-0546af6053abd05d.jpg" alt="Práce v technické místnosti"/><div className="projectText"><small>Rudolfov · voda + topení</small><h3>Technická místnost rodinného domu</h3></div></article><article className="project"><img src="https://vytapeni.tzb-info.cz/docu/clanky/0150/015069o7.jpg" alt="Servis topného systému v technické místnosti"/><div className="projectText"><small>Hluboká nad Vltavou · topení</small><h3>Úprava topného systému</h3></div></article></div><div className="demoNote"><span><strong>Ukázkový obsah.</strong> Firma ani uvedené realizace nejsou skutečné.</span><span>Fotografie jsou zde pouze pro předvedení struktury konceptu.</span></div></div></section>
      <section className="section"><div className="wrap"><div className="sectionHead"><div className="kicker">Co můžete čekat</div><div><h2>Ne sliby. Konkrétní pravidla spolupráce.</h2></div></div><div className="promiseGrid"><article className="promise"><span className="promiseNum">01</span><strong>Cena před zahájením práce</strong><p>U běžných oprav cenu nebo způsob účtování domluvíme předem. U větší realizace připravíme nabídku.</p></article><article className="promise"><span className="promiseNum">02</span><strong>Domluvený termín platí</strong><p>Pokud se něco změní, dáme vědět. Bez celodenního čekání na neurčitý příjezd.</p></article><article className="promise"><span className="promiseNum">03</span><strong>Po práci uklidíme</strong><p>Místo předáme tak, aby po nás nezůstala zbytečná práce navíc.</p></article><article className="promise"><span className="promiseNum">04</span><strong>Oprávnění a pojištění</strong><p>Na skutečném webu zde patří konkrétní oprávnění, pojištění a záruka na provedenou práci.</p></article></div></div></section>
      <section className="section" id="o-nas"><div className="wrap about"><div className="aboutPhoto"><img src="https://www.shk-profi.de/imgs/2/3/0/4/2/7/8/Baumgart_Bild1-0546af6053abd05d.jpg" alt="Topenář při práci v technické místnosti"/></div><div className="aboutCopy"><div className="kicker">Kdo přijede</div><h2>Jan Novák</h2><p>Instalatér a topenář z Českých Budějovic. Menší opravy řeší osobně, na větší realizace jezdí ve dvou. Tato část má zákazníkovi ukázat konkrétního člověka místo anonymní firmy bez tváře.</p><div className="facts"><div className="fact">15 let<span>praxe v oboru</span></div><div className="fact"><ShieldCheck size={15}/> Pojištění<span>odpovědnosti</span></div><div className="fact"><MapPin size={15}/> Budějovice<span>a okolí</span></div></div></div></div></section>
      <section className="section"><div className="wrap"><div className="sectionHead"><div className="kicker">Postup</div><div><h2>Jak zakázka probíhá.</h2></div></div><div className="steps"><article className="step"><div className="stepNo">1</div><h3>Ozvete se</h3><p>Telefonicky nebo formulářem. U plánované práce můžete rovnou přiložit fotografie.</p></article><article className="step"><div className="stepNo">2</div><h3>Domluvíme rozsah</h3><p>U větší zakázky proběhne obhlídka a nabídka. U malé opravy domluvíme postup rovnou.</p></article><article className="step"><div className="stepNo">3</div><h3>Přijedeme a provedeme práci</h3><p>Domluvený rozsah, termín a následné předání bez zbytečných mezikroků.</p></article></div></div></section>
      <section className="section" id="faq"><div className="wrap areaFaq"><div className="areaBox"><h3>Kde působíme</h3><p>Běžně vyjíždíme přibližně do 30 km od Českých Budějovic. Větší realizace řešíme po dohodě i dále.</p><div className="towns"><span>České Budějovice</span><span>Rudolfov</span><span>Hluboká nad Vltavou</span><span>Lišov</span><span>Borovany</span><span>Třeboň</span></div><div className="areaRule"/><div className="areaDistance"><MapPin size={16}/> České Budějovice + okolí do 30 km</div></div><div><div className="kicker" style={{marginBottom:18}}>Časté dotazy</div><div className="faq">{faqs.map(([q,a])=><article className="faqItem" key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></div></div></section>
      <section className="contact" id="kontakt"><div className="wrap contactGrid"><div><div className="kicker" style={{color:'#aaa',marginBottom:18}}>Kontakt</div><h2>Je to akutní? Zavolejte. Plánujete práci? Napište.</h2><p>Dvě jasné cesty podle situace. Telefon pro akutní problém a krátká poptávka pro plánovanou zakázku.</p><div className="contactActions"><a className="btn btnSignal" href="tel:+420777000000"><Phone size={15}/> 777 000 000</a><a className="btn btnLight" href="mailto:ukazka@spustweb.cz">ukazka@spustweb.cz</a></div></div><div className="form"><div className="field">Jméno</div><div className="field">Telefon</div><div className="field wide">Obec</div><div className="field wide big">Co potřebujete?</div><div className="field wide"><Camera size={13}/> &nbsp; Přiložit fotografie</div><div className="btn btnDark">Odeslat poptávku <ArrowRight size={14}/></div><div className="formNote">Ukázkový formulář není aktivní. Stránka představuje možnou podobu webu pro instalatéra.</div></div></div></section>
      <footer className="demoFooter"><div className="wrap footerInner"><div><strong>NOVÁK VODA & TOPENÍ</strong><br/>Fiktivní firma vytvořená pouze jako ukázkový koncept.</div><div>Tento koncept vytvořil <a href="/">SpustWeb.cz</a> · <a href="/#kontakt">Chci web pro své podnikání</a></div></div></footer>
    </div>
  )
}
