import type { Metadata } from 'next'
import { ArrowRight, CalendarDays, Clock3, MapPin, Phone } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro manikúru a pedikúru | SpustWeb.cz',
  description: 'Ukázka webu pro manikúru a pedikúru: ceník, hotové práce, hygiena, studio a rezervace.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/manikura-pedikura/' },
  robots: { index: true, follow: true },
}

const manicure = [
  ['Manikúra', '590 Kč', 'Úprava nehtů a kůžičky, závěrečná péče.'],
  ['Manikúra + gel lak', '890 Kč', 'Kompletní manikúra a gel lak v jedné barvě.'],
  ['Zpevnění přírodních nehtů', '1 090 Kč', 'Zpevnění přírodních nehtů gelem nebo builder bází.'],
  ['Nová gelová modeláž', '1 290 Kč', 'Modeláž a barevná úprava podle zvolené délky a tvaru.'],
  ['Doplnění gelové modeláže', '990 Kč', 'Doplnění odrostu, úprava tvaru a nová barva.'],
]

const pedicure = [
  ['Přístrojová pedikúra', '990 Kč', 'Úprava nehtů a chodidel, ošetření ztvrdlé kůže a závěrečná péče.'],
  ['Pedikúra + gel lak', '1 390 Kč', 'Přístrojová pedikúra a gel lak na nehtech.'],
  ['Odstranění gel laku', '250 Kč', 'Odstranění materiálu a základní úprava nehtů.'],
]

const work = [
  ['https://images.pexels.com/photos/13038494/pexels-photo-13038494.jpeg?auto=compress&cs=tinysrgb&w=1500', 'Hotová francouzská manikúra s jemným nude základem'],
  ['https://images.pexels.com/photos/5871311/pexels-photo-5871311.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Hotová barevná manikúra v teplých odstínech'],
  ['https://images.pexels.com/photos/5871817/pexels-photo-5871817.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Hotový barevný nail art'],
  ['https://images.pexels.com/photos/5083710/pexels-photo-5083710.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Hotová oranžová manikúra'],
]

export default function NailShowcase() {
  return (
    <div className="n4" id="top">
      <style>{`
        body:has(.n4) > .verno-nav-shell,body:has(.n4) > .footer{display:none!important}
        body:has(.n4) main{padding:0!important;margin:0!important}
        body:has(.n4){background:#fff!important}
        .n4{--ink:#101010;--paper:#fff;--pink:#ff6680;--lime:#d9ff69;--blue:#ccecf2;--cream:#f6f2eb;--line:#d7d7d2;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--paper)}
        .n4 *{box-sizing:border-box}.n4 a{color:inherit;text-decoration:none}.n4 img{display:block;width:100%}.n4Wrap{width:min(1240px,calc(100% - 56px));margin:0 auto}
        .n4Demo{min-height:24px;padding:5px 12px;background:#111;color:#ddd;text-align:center;font-size:9px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.n4Demo a{color:#fff!important;text-decoration:underline;text-underline-offset:3px;margin-left:8px}
        .n4Nav{background:#fff;border-bottom:1px solid #111}.n4NavInner{height:52px;display:flex;align-items:center;justify-content:space-between;gap:24px}.n4Brand{font-size:18px;font-weight:900;letter-spacing:-.05em}.n4NavLinks{display:flex;align-items:center;gap:24px;font-size:10px;font-weight:800}.n4Book{background:#111;color:#fff!important;padding:9px 12px;display:inline-flex;align-items:center;gap:7px}
        .n4Hero{background:var(--cream);overflow:hidden}.n4HeroGrid{height:calc(100svh - 76px);min-height:620px;max-height:820px;position:relative;display:grid;grid-template-columns:repeat(12,1fr);grid-template-rows:1fr 1fr;gap:12px;padding:22px 0 26px}.n4HeroWord{position:absolute;left:0;top:50%;transform:translateY(-54%);z-index:5;font-size:clamp(78px,12.2vw,176px);line-height:.72;letter-spacing:-.095em;font-weight:600;pointer-events:none;max-width:860px}.n4HeroWord span{display:block}.n4HeroWord .n4Pink{color:var(--pink)}.n4HeroMeta{position:absolute;left:0;top:42px;z-index:6;font-size:10px;font-weight:900;letter-spacing:.14em;text-transform:uppercase}.n4HeroA{grid-column:7/13;grid-row:1/3;margin:0;overflow:hidden;background:#ddd}.n4HeroA img{height:100%;object-fit:cover;object-position:center 48%}.n4HeroB{grid-column:5/8;grid-row:2;margin:0 0 12px;overflow:hidden;z-index:6;border:9px solid var(--cream);align-self:end;height:250px}.n4HeroB img{height:100%;object-fit:cover;object-position:center}.n4HeroCopy{position:absolute;left:0;bottom:34px;z-index:7;width:360px;font-size:14px;line-height:1.55}.n4HeroCopy p{margin:0 0 14px}.n4HeroCopy a{font-size:11px;font-weight:900;border-bottom:1px solid #111;padding-bottom:3px}.n4HeroTag{position:absolute;right:18px;bottom:18px;background:var(--lime);z-index:7;padding:13px 16px;font-size:9px;line-height:1.25;font-weight:900;text-align:center;transform:rotate(-2deg)}
        .n4Facts{border-top:1px solid #111;border-bottom:1px solid #111}.n4FactsInner{min-height:58px;display:flex;align-items:center;justify-content:space-between;gap:26px;flex-wrap:wrap;font-size:11px}.n4FactsInner span{display:flex;align-items:center;gap:7px}
        .n4Menu{padding:78px 0 92px}.n4MenuTop{display:grid;grid-template-columns:.7fr 1.3fr;gap:80px;align-items:end;margin-bottom:44px}.n4MenuTop h2{font-size:clamp(54px,6vw,82px);line-height:.84;letter-spacing:-.075em;font-weight:500;margin:0}.n4MenuTop p{max-width:500px;font-size:14px;line-height:1.6;color:#555;margin:0}.n4MenuGrid{display:grid;grid-template-columns:1fr 1fr;gap:64px}.n4MenuCol{border-top:3px solid #111}.n4MenuCol h3{font-size:25px;margin:16px 0 10px}.n4Price{display:grid;grid-template-columns:1fr auto;gap:8px 22px;padding:17px 0;border-top:1px solid var(--line)}.n4Price strong{font-size:15px}.n4Price b{font-size:14px}.n4Price p{grid-column:1/-1;margin:0;font-size:12px;line-height:1.5;color:#666}.n4MenuNote{margin-top:24px;font-size:11px;color:#666}
        .n4Work{padding:4px 0 96px}.n4WorkHead{display:flex;justify-content:space-between;align-items:end;gap:40px;margin-bottom:32px}.n4WorkHead h2{font-size:clamp(60px,7.8vw,108px);line-height:.8;letter-spacing:-.085em;font-weight:500;margin:0}.n4WorkHead p{max-width:420px;font-size:13px;line-height:1.6;color:#666;margin:0}.n4Portfolio{display:grid;grid-template-columns:1.32fr .88fr .88fr;grid-template-rows:300px 250px;gap:10px}.n4Portfolio figure{margin:0;overflow:hidden;background:#eee;position:relative}.n4Portfolio figure:nth-child(1){grid-column:1;grid-row:1/3}.n4Portfolio figure:nth-child(2){grid-column:2;grid-row:1}.n4Portfolio figure:nth-child(3){grid-column:3;grid-row:1/3}.n4Portfolio figure:nth-child(4){grid-column:2;grid-row:2}.n4Portfolio img{height:100%;object-fit:cover}.n4Portfolio figure:nth-child(1) img{object-position:center}.n4Portfolio figcaption{position:absolute;left:10px;bottom:10px;background:#fff;padding:6px 8px;font-size:9px;font-weight:900}.n4WorkFoot{display:flex;justify-content:space-between;gap:30px;margin-top:16px;font-size:10px;color:#777}.n4WorkFoot strong{color:#111}
        .n4Hygiene{background:var(--lime);border-top:1px solid #111;border-bottom:1px solid #111}.n4HygieneInner{min-height:78px;display:grid;grid-template-columns:140px 1fr 1fr;gap:28px;align-items:center;font-size:11px;line-height:1.45}.n4HygieneInner strong{font-size:14px}.n4HygieneInner span+span{border-left:1px solid rgba(0,0,0,.28);padding-left:28px}
        .n4Studio{padding:86px 0;background:var(--blue)}.n4StudioTitle{display:flex;align-items:end;justify-content:space-between;gap:40px;margin-bottom:26px}.n4StudioTitle h2{font-size:clamp(54px,6.5vw,88px);line-height:.84;letter-spacing:-.075em;font-weight:500;margin:0}.n4StudioTitle p{max-width:430px;font-size:13px;line-height:1.6;margin:0}.n4StudioPhoto{height:560px;overflow:hidden;background:#ddd}.n4StudioPhoto img{height:100%;object-fit:cover;object-position:center}.n4StudioData{display:grid;grid-template-columns:1.3fr 1fr 1fr 1fr;gap:24px;border-top:1px solid #111;margin-top:18px;padding-top:15px;font-size:11px}.n4StudioData strong{font-size:11px}
        .n4Booking{padding:74px 0 78px;background:#fff;overflow:hidden}.n4BookingInner{position:relative}.n4BookingGhost{position:absolute;right:-16px;top:-44px;font-size:clamp(100px,16vw,230px);font-weight:800;letter-spacing:-.1em;color:#f5c0c9;line-height:.75;z-index:0;pointer-events:none}.n4BookingHead{position:relative;z-index:2;display:flex;justify-content:space-between;align-items:end;gap:50px;margin-bottom:28px}.n4BookingHead h2{font-size:clamp(52px,6.3vw,86px);font-weight:500;letter-spacing:-.075em;line-height:.84;margin:0}.n4BookingHead p{max-width:400px;font-size:13px;line-height:1.55;margin:0}.n4BookFlow{position:relative;z-index:2;background:#fff;border-top:2px solid #111;border-bottom:2px solid #111;display:grid;grid-template-columns:1.2fr .9fr .8fr auto}.n4BookCell{padding:18px 20px;border-right:1px solid #111;min-height:82px}.n4BookCell small{display:block;font-size:8px;text-transform:uppercase;letter-spacing:.11em;color:#666;margin-bottom:9px}.n4BookCell strong{font-size:14px}.n4BookButton{border:0;background:#111;color:#fff;padding:0 25px;font-size:10px;font-weight:900;display:flex;align-items:center;justify-content:center;gap:8px}.n4BookHint{position:relative;z-index:2;margin-top:10px;font-size:9px;color:#777}
        .n4Footer{background:#111;color:#fff;padding:38px 0}.n4FooterGrid{display:grid;grid-template-columns:1.2fr 1fr auto;gap:48px;align-items:center}.n4FooterName{font-size:28px;font-weight:800;letter-spacing:-.05em}.n4FooterText{font-size:10px;line-height:1.6;color:#aaa}.n4FooterText strong{color:#fff}.n4FooterCta{background:var(--lime);color:#111!important;padding:11px 13px;font-size:10px;font-weight:900;white-space:nowrap}
        @media(max-width:980px){.n4HeroGrid{height:auto;min-height:700px}.n4HeroWord{font-size:clamp(76px,14vw,132px)}.n4HeroA{grid-column:6/13}.n4HeroB{grid-column:4/8}.n4MenuTop{grid-template-columns:1fr;gap:24px}.n4MenuGrid{grid-template-columns:1fr}.n4Portfolio{grid-template-columns:1fr 1fr;grid-template-rows:360px 300px 300px}.n4Portfolio figure:nth-child(1){grid-column:1/2;grid-row:1/3}.n4Portfolio figure:nth-child(2){grid-column:2;grid-row:1}.n4Portfolio figure:nth-child(3){grid-column:2;grid-row:2}.n4Portfolio figure:nth-child(4){grid-column:1/-1;grid-row:3}.n4HygieneInner{grid-template-columns:1fr 1fr}.n4HygieneInner strong{grid-column:1/-1}.n4HygieneInner span+span{border-left:0;padding-left:0}.n4StudioData{grid-template-columns:1fr 1fr}.n4BookFlow{grid-template-columns:1fr 1fr}.n4BookCell:nth-child(2){border-right:0}.n4BookCell{border-bottom:1px solid #111}.n4BookButton{grid-column:1/-1;min-height:54px}.n4FooterGrid{grid-template-columns:1fr 1fr}.n4FooterCta{grid-column:1/-1;justify-self:start}}
        @media(max-width:680px){.n4Wrap{width:min(100% - 28px,1240px)}.n4Demo{font-size:7.5px}.n4NavInner{height:50px}.n4NavLinks>a:not(.n4Book){display:none}.n4HeroGrid{min-height:660px;padding-top:18px}.n4HeroMeta{top:22px}.n4HeroWord{top:37%;font-size:clamp(70px,22vw,98px)}.n4HeroA{grid-column:3/13;grid-row:1/3}.n4HeroB{grid-column:1/6;grid-row:2;height:180px}.n4HeroCopy{width:85%;bottom:22px;font-size:13px}.n4HeroTag{right:8px;bottom:8px}.n4FactsInner{padding:12px 0;justify-content:flex-start}.n4Menu{padding:60px 0 70px}.n4Work{padding-bottom:68px}.n4WorkHead,.n4StudioTitle,.n4BookingHead{display:block}.n4WorkHead p,.n4StudioTitle p,.n4BookingHead p{margin-top:18px}.n4Portfolio{grid-template-columns:1fr 1fr;grid-template-rows:auto}.n4Portfolio figure:nth-child(n){grid-column:auto;grid-row:auto;height:230px}.n4Portfolio figure:nth-child(1){grid-column:1/-1;height:360px}.n4WorkFoot{display:block}.n4WorkFoot span{display:block;margin-top:6px}.n4HygieneInner{grid-template-columns:1fr;padding:18px 0;gap:10px}.n4HygieneInner strong{grid-column:auto}.n4Studio{padding:62px 0}.n4StudioPhoto{height:430px}.n4StudioData{grid-template-columns:1fr;padding-bottom:0}.n4Booking{padding:58px 0}.n4BookingGhost{top:-16px;font-size:120px}.n4BookFlow{grid-template-columns:1fr}.n4BookCell{border-right:0}.n4FooterGrid{grid-template-columns:1fr;gap:18px}}
      `}</style>

      <div className="n4Demo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <nav className="n4Nav" aria-label="Navigace ukázkového studia"><div className="n4Wrap n4NavInner"><a className="n4Brand" href="#top">STUDIO LÍNA</a><div className="n4NavLinks"><a href="#cenik">Ceník</a><a href="#prace">Práce</a><a href="#studio">Studio</a><a className="n4Book" href="#rezervace">Rezervace <CalendarDays size={12}/></a></div></div></nav>
      <header className="n4Hero"><div className="n4Wrap n4HeroGrid"><div className="n4HeroMeta">MANIKÚRA / PEDIKÚRA · ČESKÉ BUDĚJOVICE</div><div className="n4HeroWord"><span>STUDIO</span><span className="n4Pink">LÍNA</span></div><figure className="n4HeroA"><img src="https://images.pexels.com/photos/13038494/pexels-photo-13038494.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Hotová francouzská manikúra"/></figure><figure className="n4HeroB"><img src="https://images.pexels.com/photos/4677856/pexels-photo-4677856.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Manikérka pracuje s klientkou"/></figure><div className="n4HeroCopy"><p>Manikúra, gel lak, gelová modeláž a přístrojová pedikúra. Návštěvy pouze na objednání.</p><a href="#rezervace">Vybrat termín →</a></div><div className="n4HeroTag">ONLINE REZERVACE<br/>24 / 7</div></div></header>
      <div className="n4Facts"><div className="n4Wrap n4FactsInner"><span><MapPin size={14}/> centrum Českých Budějovic</span><span><Clock3 size={14}/> Po–Pá 9:00–19:00</span><span>pouze na objednání</span><span><Phone size={14}/> 777 000 000</span></div></div>
      <section className="n4Menu" id="cenik"><div className="n4Wrap"><div className="n4MenuTop"><h2>Ceník.</h2><p>Cena je známá předem. Zdobení, oprava jednotlivého nehtu nebo nestandardní délka se připočítává podle rozsahu.</p></div><div className="n4MenuGrid"><div className="n4MenuCol"><h3>Manikúra</h3>{manicure.map(([name,price,text])=><div className="n4Price" key={name}><strong>{name}</strong><b>{price}</b><p>{text}</p></div>)}</div><div className="n4MenuCol"><h3>Pedikúra</h3>{pedicure.map(([name,price,text])=><div className="n4Price" key={name}><strong>{name}</strong><b>{price}</b><p>{text}</p></div>)}</div></div><div className="n4MenuNote">Nail art od 50 Kč / nehet podle náročnosti. Ceny jsou součástí fiktivního konceptu.</div></div></section>
      <section className="n4Work" id="prace"><div className="n4Wrap"><div className="n4WorkHead"><h2>Hotové práce.</h2><p>Ukázky různých délek, tvarů a barevných úprav.</p></div><div className="n4Portfolio">{work.map(([src,alt],i)=><figure key={src}><img src={src} alt={alt}/><figcaption>0{i+1}</figcaption></figure>)}</div><div className="n4WorkFoot"><strong>Barva, tvar a zdobení se domlouvají podle zvolené služby.</strong><span>Ilustrační fotografie z Pexels · nejde o realizace skutečného studia.</span></div></div></section>
      <section className="n4Hygiene"><div className="n4Wrap n4HygieneInner"><strong>Hygiena</strong><span>Kovové nástroje se po použití čistí, dezinfikují a sterilizují.</span><span>Jednorázové pilníky a pomůcky se mezi klientkami nepoužívají opakovaně.</span></div></section>
      <section className="n4Studio" id="studio"><div className="n4Wrap"><div className="n4StudioTitle"><h2>Studio Lína.</h2><p>Jedno pracovní místo pro manikúru a samostatné křeslo pro pedikúru. Studio funguje pouze na objednání.</p></div><div className="n4StudioPhoto"><img src="https://images.pexels.com/photos/36328527/pexels-photo-36328527.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="Interiér menšího nehtového studia"/></div><div className="n4StudioData"><div><strong>České Budějovice</strong><br/>centrum</div><div><strong>Po–Pá</strong><br/>9:00–19:00</div><div><strong>Telefon</strong><br/>777 000 000</div><div><strong>Provoz</strong><br/>pouze na objednání</div></div></div></section>
      <section className="n4Booking" id="rezervace"><div className="n4Wrap n4BookingInner"><div className="n4BookingGhost">TERMÍN</div><div className="n4BookingHead"><h2>Rezervace.</h2><p>Vyberte službu, den a volný čas. Ukázkové rozhraní není aktivní.</p></div><div className="n4BookFlow"><div className="n4BookCell"><small>Služba</small><strong>Manikúra + gel lak · cca 75 min</strong></div><div className="n4BookCell"><small>Den</small><strong>Úterý 25. 8.</strong></div><div className="n4BookCell"><small>Čas</small><strong>13:00</strong></div><button className="n4BookButton" type="button">Pokračovat <ArrowRight size={13}/></button></div><div className="n4BookHint">Fiktivní studio · rezervaci nelze skutečně odeslat.</div></div></section>
      <footer className="n4Footer"><div className="n4Wrap n4FooterGrid"><div className="n4FooterName">STUDIO LÍNA</div><div className="n4FooterText"><strong>Manikúra · pedikúra</strong><br/>České Budějovice · Po–Pá 9:00–19:00<br/>Fiktivní ukázkový koncept.</div><a className="n4FooterCta" href="/#kontakt">Podobný web pro moje podnikání</a></div></footer>
    </div>
  )
}
