import type { Metadata } from 'next'
import { ArrowRight, CalendarDays, Check, Clock3, MapPin, Phone, ShieldCheck, Sparkles } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro manikúru a pedikúru | SpustWeb.cz',
  description: 'Ukázka webu pro manikúru a pedikúru: ceník, ukázky práce, hygiena, studio, provozovna a online rezervace.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/manikura-pedikura/' },
  robots: { index: true, follow: true },
}

const services = [
  ['Manikúra', '45 min', '590 Kč', 'Úprava tvaru nehtů, kůžičky a závěrečná péče.'],
  ['Manikúra + gel lak', '75 min', '890 Kč', 'Kompletní manikúra a gel lak v jedné barvě.'],
  ['Zpevnění přírodních nehtů', '90 min', '1 090 Kč', 'Zpevnění gelem nebo builder bází podle stavu nehtů.'],
  ['Pedikúra', '60 min', '990 Kč', 'Úprava nehtů a chodidel, ošetření ztvrdlé kůže a závěrečná péče.'],
  ['Pedikúra + gel lak', '90 min', '1 390 Kč', 'Kompletní pedikúra a gel lak na nehtech.'],
  ['Odstranění gel laku', '20 min', '250 Kč', 'Šetrné odstranění materiálu a základní úprava nehtů.'],
]

const gallery = [
  ['https://images.pexels.com/photos/5484948/pexels-photo-5484948.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Detail upravených nehtů během profesionální manikúry'],
  ['https://images.pexels.com/photos/4677852/pexels-photo-4677852.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Detail práce nehtové specialistky při manikúře'],
  ['https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Vzorník barev gel laků v nehtovém studiu'],
  ['https://images.pexels.com/photos/17056222/pexels-photo-17056222.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Detail lakování nehtů při pedikúře'],
  ['https://images.pexels.com/photos/6135675/pexels-photo-6135675.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Precizní úprava nehtů při manikúře'],
]

export default function NailShowcase() {
  return (
    <div className="npPage" id="top">
      <style>{`
        body:has(.npPage) > .verno-nav-shell,body:has(.npPage) > .footer{display:none!important}
        body:has(.npPage) main{padding:0!important;margin:0!important}
        body:has(.npPage){background:#fff!important}
        .npPage{--ink:#121212;--paper:#fff;--soft:#f5f5f1;--pink:#ff6b81;--red:#ef3f58;--blue:#c8e9f1;--lime:#d8ff72;--line:#d9d9d4;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--paper)}
        .npPage *{box-sizing:border-box}.npPage a{color:inherit;text-decoration:none}.npPage img{display:block;width:100%}.npWrap{width:min(1280px,calc(100% - 48px));margin:0 auto}
        .npDemo{height:24px;background:#111;color:#e7e7e4;display:flex;align-items:center;justify-content:center;font-size:8.5px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.npDemo a{margin-left:8px;color:#fff!important;text-decoration:underline;text-underline-offset:3px}
        .npShell{display:grid;grid-template-columns:84px 1fr;min-height:100vh}.npRail{position:sticky;top:0;height:100vh;background:#111;color:#fff;border-right:1px solid #2a2a2a;display:flex;flex-direction:column;align-items:center;justify-content:space-between;padding:26px 0;z-index:110}.npRailBrand{font-size:15px;font-weight:900;letter-spacing:-.04em;writing-mode:vertical-rl;transform:rotate(180deg)}.npRailNav{display:grid;gap:22px;justify-items:center}.npRailNav a{font-size:8.5px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;writing-mode:vertical-rl;transform:rotate(180deg);opacity:.68}.npRailNav a:hover{opacity:1}.npRailBook{width:46px;height:46px;border-radius:50%;background:var(--lime);color:#111!important;display:grid;place-items:center}
        .npMain{min-width:0}.npTop{position:sticky;top:24px;z-index:105;background:rgba(255,255,255,.95);backdrop-filter:blur(12px);border-bottom:1px solid var(--line)}.npTopInner{height:58px;display:flex;justify-content:space-between;align-items:center;gap:20px}.npTop strong{font-size:12px}.npTop span{font-size:9px;color:#666}.npTopCta{display:inline-flex;align-items:center;gap:7px;background:#111;color:#fff!important;padding:11px 14px;font-size:9.5px;font-weight:900}
        .npHero{min-height:calc(100svh - 24px);display:grid;grid-template-columns:1.02fr .98fr;background:#fff}.npHeroCopy{padding:76px 52px 54px 4vw;display:flex;flex-direction:column;justify-content:space-between}.npHeroEyebrow{font-size:9px;font-weight:900;letter-spacing:.15em;text-transform:uppercase}.npHero h1{font-size:clamp(64px,8.8vw,130px);line-height:.78;letter-spacing:-.075em;font-weight:500;margin:30px 0 24px;max-width:820px}.npHeroLead{font-size:14px;line-height:1.55;max-width:540px;margin:0}.npHeroActions{display:flex;gap:10px;flex-wrap:wrap;margin-top:28px}.npBtn{min-height:44px;padding:0 17px;display:inline-flex;align-items:center;justify-content:center;gap:8px;border:1px solid #111;font-size:10px;font-weight:900}.npBtnPink{background:var(--pink);border-color:var(--pink)}.npBtnWhite{background:#fff}.npHeroBottom{display:flex;gap:24px;flex-wrap:wrap;padding-top:30px;font-size:9.5px}.npHeroBottom span{display:flex;align-items:center;gap:6px}.npHeroVisual{position:relative;display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1.05fr .95fr;gap:8px;background:#111;padding:8px}.npHeroVisual figure{margin:0;overflow:hidden;position:relative}.npHeroVisual figure:first-child{grid-row:1/3}.npHeroVisual img{height:100%;object-fit:cover}.npHeroVisual figure:nth-child(1) img{object-position:center}.npHeroVisual figure:nth-child(2) img{object-position:center}.npHeroVisual figure:nth-child(3){background:var(--blue);display:flex;align-items:flex-end;padding:28px}.npHeroVisual figure:nth-child(3) strong{font-size:34px;line-height:.9;letter-spacing:-.05em;font-weight:500}.npHeroStamp{position:absolute;right:24px;bottom:24px;width:92px;height:92px;border-radius:50%;background:var(--lime);display:grid;place-items:center;text-align:center;font-size:9px;font-weight:900;line-height:1.25;transform:rotate(8deg)}
        .npTicker{background:var(--red);color:#fff;overflow:hidden;border-top:1px solid #111;border-bottom:1px solid #111}.npTickerInner{display:flex;gap:38px;white-space:nowrap;padding:13px 0;font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.npTickerInner span:after{content:'✦';margin-left:38px}
        .npServices{padding:74px 0 82px}.npSectionHead{display:flex;justify-content:space-between;align-items:end;gap:40px;margin-bottom:34px}.npSectionHead h2{font-size:clamp(48px,6.4vw,88px);line-height:.86;letter-spacing:-.065em;font-weight:500;margin:0}.npSectionHead p{max-width:430px;font-size:12px;line-height:1.6;color:#555;margin:0 0 6px}.npServiceList{border-top:2px solid #111}.npService{display:grid;grid-template-columns:1.2fr .35fr .35fr 1fr;gap:26px;align-items:center;padding:20px 0;border-bottom:1px solid var(--line)}.npService strong{font-size:18px}.npService span{font-size:10px}.npService p{font-size:10.5px;line-height:1.45;color:#666;margin:0}.npService:hover{background:var(--blue)}
        .npLookbook{background:#111;color:#fff;padding:72px 0 86px;overflow:hidden}.npLookTop{display:flex;align-items:end;justify-content:space-between;gap:30px;margin-bottom:30px}.npLookTop h2{font-size:clamp(54px,8vw,112px);line-height:.8;letter-spacing:-.07em;font-weight:500;margin:0}.npLookTop p{max-width:390px;font-size:11px;line-height:1.55;color:#bbb}.npGallery{display:grid;grid-template-columns:repeat(12,1fr);grid-auto-rows:120px;gap:9px}.npGallery figure{margin:0;overflow:hidden;position:relative}.npGallery img{height:100%;object-fit:cover}.npGallery figure:nth-child(1){grid-column:1/6;grid-row:1/5}.npGallery figure:nth-child(2){grid-column:6/10;grid-row:1/4}.npGallery figure:nth-child(3){grid-column:10/13;grid-row:1/3}.npGallery figure:nth-child(4){grid-column:8/13;grid-row:4/7}.npGallery figure:nth-child(5){grid-column:2/8;grid-row:5/8}.npGalleryLabel{position:absolute;left:10px;bottom:10px;background:#111;color:#fff;padding:6px 8px;font-size:8px;font-weight:800}.npGalleryNote{margin-top:24px;font-size:9px;color:#999}
        .npHygiene{background:var(--lime);padding:58px 0}.npHygieneGrid{display:grid;grid-template-columns:.9fr 1.1fr;gap:80px}.npHygiene h2{font-size:clamp(42px,5.2vw,72px);line-height:.88;letter-spacing:-.06em;margin:0;font-weight:500}.npHygieneList{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid rgba(0,0,0,.3)}.npHygieneItem{padding:18px 18px 18px 0;border-bottom:1px solid rgba(0,0,0,.3);display:flex;gap:10px}.npHygieneItem:nth-child(even){padding-left:18px;border-left:1px solid rgba(0,0,0,.3)}.npHygieneItem strong{display:block;font-size:12px;margin-bottom:5px}.npHygieneItem p{font-size:10px;line-height:1.45;margin:0;color:#3f4930}
        .npPedi{display:grid;grid-template-columns:1.12fr .88fr;min-height:560px}.npPediPhoto{overflow:hidden}.npPediPhoto img{height:100%;object-fit:cover}.npPediCopy{background:var(--blue);padding:56px;display:flex;flex-direction:column;justify-content:center}.npPediCopy h2{font-size:clamp(46px,5.5vw,78px);line-height:.86;letter-spacing:-.06em;font-weight:500;margin:0 0 20px}.npPediCopy p{font-size:12px;line-height:1.6;max-width:470px}.npPediFacts{display:grid;grid-template-columns:1fr 1fr;margin-top:28px;border-top:1px solid rgba(0,0,0,.24)}.npPediFact{padding:14px 16px 0 0;font-size:10px}.npPediFact strong{display:block;font-size:12px;margin-bottom:4px}
        .npStudio{padding:80px 0}.npStudioGrid{display:grid;grid-template-columns:.78fr 1.22fr;gap:54px;align-items:center}.npStudioText h2{font-size:clamp(46px,5.8vw,78px);line-height:.88;letter-spacing:-.06em;font-weight:500;margin:0 0 18px}.npStudioText p{font-size:12px;line-height:1.65;color:#555;max-width:460px}.npStudioFacts{display:grid;gap:10px;margin-top:24px}.npStudioFacts span{font-size:10px;display:flex;align-items:center;gap:8px}.npStudioPhoto{height:520px;overflow:hidden;background:#eee}.npStudioPhoto img{height:100%;object-fit:cover}.npStudioName{display:inline-block;margin-top:18px;padding:8px 10px;background:var(--pink);font-size:9px;font-weight:900}
        .npBooking{background:#111;color:#fff;padding:72px 0}.npBookingGrid{display:grid;grid-template-columns:.82fr 1.18fr;gap:64px;align-items:start}.npBooking h2{font-size:clamp(54px,6.8vw,94px);line-height:.82;letter-spacing:-.07em;font-weight:500;margin:0 0 20px}.npBooking p{font-size:11.5px;line-height:1.6;color:#bbb;max-width:420px}.npBookingMeta{display:grid;gap:8px;margin-top:25px;font-size:10px}.npBookingMeta span{display:flex;align-items:center;gap:8px}.npBookingPanel{background:#fff;color:#111;padding:22px}.npBookRow{display:grid;grid-template-columns:1fr auto;gap:20px;align-items:center;padding:14px 0;border-bottom:1px solid var(--line)}.npBookRow:first-child{border-top:1px solid var(--line)}.npBookRow strong{font-size:12px}.npBookRow span{font-size:9.5px;color:#666}.npBookSlots{display:flex;gap:7px;flex-wrap:wrap;margin:18px 0}.npBookSlots span{border:1px solid #bbb;padding:8px 10px;font-size:9px}.npBookSlots span:nth-child(2){background:var(--pink);border-color:var(--pink);font-weight:900}.npBookButton{width:100%;min-height:46px;border:0;background:#111;color:#fff;font-size:10px;font-weight:900;display:flex;align-items:center;justify-content:center;gap:8px}.npBookNote{font-size:8.5px;color:#777;margin-top:8px}
        .npContact{background:#fff;padding:56px 0}.npContactGrid{display:grid;grid-template-columns:1fr 1fr;gap:60px}.npContact h3{font-size:26px;margin:0 0 12px}.npContact p{font-size:10.5px;line-height:1.55;color:#666}.npContactLines{display:grid;gap:10px;font-size:10px}.npContactLines span{display:flex;gap:8px;align-items:center}.npFooter{border-top:1px solid #111;background:var(--pink)}.npFooterInner{min-height:96px;display:flex;align-items:center;justify-content:space-between;gap:24px;font-size:9px}.npFooter strong{font-size:13px}.npFooterCta{background:#111;color:#fff!important;padding:10px 12px;font-weight:900}
        @media(max-width:980px){.npShell{grid-template-columns:1fr}.npRail{display:none}.npTop{top:24px}.npHero{grid-template-columns:1fr}.npHeroCopy{min-height:560px;padding:64px 28px 38px}.npHeroVisual{min-height:600px}.npService{grid-template-columns:1fr auto auto}.npService p{grid-column:1/-1}.npHygieneGrid,.npStudioGrid,.npBookingGrid{grid-template-columns:1fr}.npPedi{grid-template-columns:1fr}.npPediPhoto{height:480px}.npStudioPhoto{order:-1}.npContactGrid{grid-template-columns:1fr}}
        @media(max-width:680px){.npWrap{width:min(100% - 26px,1280px)}.npDemo{height:auto;min-height:24px;text-align:center;line-height:1.3}.npTopInner{height:54px}.npTop span{display:none}.npHero{min-height:0}.npHeroCopy{min-height:500px;padding:44px 20px 28px}.npHero h1{font-size:clamp(58px,18vw,90px)}.npHeroVisual{min-height:520px}.npHeroVisual{grid-template-columns:1.2fr .8fr}.npHeroVisual figure:nth-child(3){padding:18px}.npHeroVisual figure:nth-child(3) strong{font-size:25px}.npHeroStamp{width:72px;height:72px;font-size:7.5px}.npServices,.npLookbook,.npStudio{padding:56px 0}.npSectionHead,.npLookTop{display:block}.npSectionHead p,.npLookTop p{margin-top:18px}.npService{grid-template-columns:1fr auto;gap:10px 18px}.npService span:nth-of-type(1){grid-column:2}.npService span:nth-of-type(2){grid-column:2}.npGallery{grid-template-columns:1fr 1fr;grid-auto-rows:180px}.npGallery figure:nth-child(n){grid-column:auto;grid-row:auto}.npGallery figure:nth-child(1){grid-column:1/-1;height:320px}.npHygieneGrid{gap:30px}.npHygieneList{grid-template-columns:1fr}.npHygieneItem:nth-child(even){padding-left:0;border-left:0}.npPediPhoto{height:380px}.npPediCopy{padding:38px 24px}.npStudioPhoto{height:380px}.npBooking{padding:56px 0}.npBookingGrid{gap:34px}.npContact{padding:44px 0}.npFooterInner{min-height:120px;align-items:flex-start;justify-content:center;flex-direction:column;padding:22px 0}}
      `}</style>

      <div className="npDemo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>

      <div className="npShell">
        <aside className="npRail" aria-label="Navigace ukázkového studia">
          <a className="npRailBrand" href="#top">STUDIO LÍNA</a>
          <nav className="npRailNav"><a href="#sluzby">Služby</a><a href="#prace">Práce</a><a href="#studio">Studio</a></nav>
          <a className="npRailBook" href="#rezervace" aria-label="Rezervovat termín"><CalendarDays size={17}/></a>
        </aside>

        <main className="npMain">
          <div className="npTop"><div className="npWrap npTopInner"><div><strong>STUDIO LÍNA</strong><br/><span>manikúra · pedikúra · České Budějovice</span></div><a className="npTopCta" href="#rezervace">Rezervovat termín <ArrowRight size={12}/></a></div></div>

          <header className="npHero">
            <div className="npHeroCopy">
              <div>
                <div className="npHeroEyebrow">MANIKÚRA · PEDIKÚRA · ČESKÉ BUDĚJOVICE</div>
                <h1>Nehty.<br/>Ruce.<br/>Chodidla.</h1>
                <p className="npHeroLead">Manikúra, gel lak, zpevnění přírodních nehtů a přístrojová pedikúra. Termín si můžete vybrat online.</p>
                <div className="npHeroActions"><a className="npBtn npBtnPink" href="#rezervace">Rezervovat termín <CalendarDays size={14}/></a><a className="npBtn npBtnWhite" href="#sluzby">Ceník a služby</a></div>
              </div>
              <div className="npHeroBottom"><span><Clock3 size={13}/> Po–Pá 9:00–19:00</span><span><MapPin size={13}/> centrum Českých Budějovic</span><span><ShieldCheck size={13}/> sterilizované nástroje</span></div>
            </div>
            <div className="npHeroVisual">
              <figure><img src="https://images.pexels.com/photos/30294773/pexels-photo-30294773.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Detail profesionální manikúry v nehtovém studiu"/></figure>
              <figure><img src="https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Výběr barev laků v nehtovém studiu"/></figure>
              <figure><strong>čistá práce<br/>bez zbytečností</strong></figure>
              <div className="npHeroStamp">ONLINE<br/>REZERVACE<br/>24/7</div>
            </div>
          </header>

          <div className="npTicker"><div className="npTickerInner"><span>MANIKÚRA</span><span>GEL LAK</span><span>ZPEVNĚNÍ</span><span>PEDIKÚRA</span><span>NAIL ART</span><span>ODSTRANĚNÍ MATERIÁLU</span></div></div>

          <section className="npServices" id="sluzby"><div className="npWrap"><div className="npSectionHead"><h2>Služby a ceny.</h2><p>U každé služby je uvedená orientační délka návštěvy. Nail art a opravy jednotlivých nehtů se účtují podle rozsahu.</p></div><div className="npServiceList">{services.map(([name,time,price,text])=><article className="npService" key={name}><strong>{name}</strong><span>{time}</span><span>{price}</span><p>{text}</p></article>)}</div></div></section>

          <section className="npLookbook" id="prace"><div className="npWrap"><div className="npLookTop"><h2>Poslední práce.</h2><p>Krátké, dlouhé, přirozené i barevné. Na skutečném webu by zde byla vlastní galerie studia pravidelně doplňovaná o nové práce.</p></div><div className="npGallery">{gallery.map(([src,alt],i)=><figure key={src}><img src={src} alt={alt}/><span className="npGalleryLabel">0{i+1}</span></figure>)}</div><div className="npGalleryNote">Fotografie jsou ilustrační a pocházejí z fotobanky Pexels. Fiktivní studio ani ukázané realizace nejsou skutečné.</div></div></section>

          <section className="npHygiene"><div className="npWrap npHygieneGrid"><h2>Čisté nástroje nejsou bonus.</h2><div className="npHygieneList"><div className="npHygieneItem"><Check size={15}/><div><strong>Nástroje po každé klientce</strong><p>Kovové nástroje po použití čistíme, dezinfikujeme a sterilizujeme.</p></div></div><div className="npHygieneItem"><Check size={15}/><div><strong>Jednorázové pomůcky</strong><p>Pilníky a další jednorázové pomůcky nepoužíváme opakovaně mezi klientkami.</p></div></div><div className="npHygieneItem"><Check size={15}/><div><strong>Pracovní plocha</strong><p>Stůl a dotykové plochy připravujeme před každou další návštěvou.</p></div></div><div className="npHygieneItem"><Check size={15}/><div><strong>Otevřeně před vámi</strong><p>Sterilní balení nástrojů se otevírá až při přípravě pracovního místa.</p></div></div></div></div></section>

          <section className="npPedi"><div className="npPediPhoto"><img src="https://images.pexels.com/photos/17056222/pexels-photo-17056222.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Profesionální pedikúra a lakování nehtů na nohou"/></div><div className="npPediCopy"><div className="npHeroEyebrow">PEDIKÚRA</div><h2>Nejen lak na nehty.</h2><p>Pedikúra zahrnuje úpravu nehtů a chodidel, ošetření běžné ztvrdlé kůže a závěrečnou péči. Gel lak lze přidat při rezervaci.</p><div className="npPediFacts"><div className="npPediFact"><strong>60 min</strong><span>samostatná pedikúra</span></div><div className="npPediFact"><strong>90 min</strong><span>pedikúra + gel lak</span></div><div className="npPediFact"><strong>990 Kč</strong><span>pedikúra</span></div><div className="npPediFact"><strong>1 390 Kč</strong><span>pedikúra + gel lak</span></div></div></div></section>

          <section className="npStudio" id="studio"><div className="npWrap npStudioGrid"><div className="npStudioText"><h2>Malé studio. Jedna specialistka.</h2><p>Studio vede Klára Novotná. Manikúře a pedikúře se věnuje od roku 2018. Pracuje pouze na objednání, takže se během návštěvy věnuje vždy jedné klientce.</p><div className="npStudioFacts"><span><Sparkles size={14}/> manikúra, gel lak a zpevnění</span><span><ShieldCheck size={14}/> manikúrní i pedikúrní nástroje sterilizované po použití</span><span><Clock3 size={14}/> návštěvy pouze na rezervovaný čas</span></div><span className="npStudioName">KLÁRA NOVOTNÁ · FIKTIVNÍ SPECIALISTKA</span></div><div className="npStudioPhoto"><img src="https://images.pexels.com/photos/11876024/pexels-photo-11876024.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Nehtová specialistka při práci s klientkou v menším studiu"/></div></div></section>

          <section className="npBooking" id="rezervace"><div className="npWrap npBookingGrid"><div><h2>Vyberte si termín.</h2><p>Nejdřív službu, potom den a čas. Rezervace níže je pouze ukázka rozhraní a není aktivní.</p><div className="npBookingMeta"><span><Phone size={14}/> 777 000 000</span><span><MapPin size={14}/> České Budějovice · centrum</span><span><Clock3 size={14}/> Po–Pá 9:00–19:00</span></div></div><div className="npBookingPanel"><div className="npBookRow"><div><strong>Manikúra + gel lak</strong><br/><span>75 min</span></div><strong>890 Kč</strong></div><div className="npBookRow"><div><strong>Úterý 25. srpna</strong><br/><span>volné časy</span></div><CalendarDays size={15}/></div><div className="npBookSlots"><span>10:30</span><span>13:00</span><span>16:30</span></div><button className="npBookButton" type="button">Pokračovat k rezervaci <ArrowRight size={13}/></button><div className="npBookNote">Ukázkové rozhraní není aktivní. Nejde o skutečné studio.</div></div></div></section>

          <section className="npContact"><div className="npWrap npContactGrid"><div><h3>Studio Lína</h3><p>Fiktivní nehtové studio vytvořené jako ukázkový koncept webu pro samostatnou manikérku a pedikérku.</p></div><div className="npContactLines"><span><MapPin size={14}/> České Budějovice · centrum</span><span><Clock3 size={14}/> Po–Pá 9:00–19:00 · pouze na objednání</span><span><Phone size={14}/> 777 000 000</span></div></div></section>

          <footer className="npFooter"><div className="npWrap npFooterInner"><div><strong>STUDIO LÍNA</strong><br/>Ukázkový koncept · nejde o skutečnou firmu.</div><div>Tento koncept vytvořil <a href="/">SpustWeb.cz</a> · <a className="npFooterCta" href="/#kontakt">Web pro moje podnikání</a></div></div></footer>
        </main>
      </div>
    </div>
  )
}
