import type { Metadata } from 'next'
import { ArrowRight, CalendarDays, Check, Clock3, MapPin, Phone, ShieldCheck } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Ukázkový web pro manikúru a pedikúru | SpustWeb.cz',
  description: 'Ukázka webu pro manikúru a pedikúru: ceník, ukázky práce, hygiena, studio, provozovna a online rezervace.',
  alternates: { canonical: 'https://spustweb.cz/ukazky/manikura-pedikura/' },
  robots: { index: true, follow: true },
}

const services = [
  ['Manikúra', '45 min', '590 Kč', 'Úprava tvaru nehtů, kůžičky a závěrečná péče.'],
  ['Manikúra + gel lak', '75 min', '890 Kč', 'Kompletní manikúra a gel lak v jedné barvě.'],
  ['Zpevnění přírodních nehtů', '90 min', '1 090 Kč', 'Zpevnění gelem nebo builder bází podle stavu nehtů.'],
  ['Pedikúra', '60 min', '990 Kč', 'Úprava nehtů a chodidel, ošetření ztvrdlé kůže a závěrečná péče.'],
  ['Pedikúra + gel lak', '90 min', '1 390 Kč', 'Kompletní pedikúra a gel lak na nehtech.'],
  ['Odstranění gel laku', '20 min', '250 Kč', 'Šetrné odstranění materiálu a základní úprava nehtů.'],
]

const gallery = [
  ['https://images.pexels.com/photos/4677856/pexels-photo-4677856.jpeg?auto=compress&cs=tinysrgb&w=1500', 'Manikérka upravuje nehty klientce u pracovního stolu'],
  ['https://images.pexels.com/photos/5484948/pexels-photo-5484948.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Detail upravených přírodních nehtů'],
  ['https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Výběr odstínů laků na nehty'],
  ['https://images.pexels.com/photos/6135670/pexels-photo-6135670.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Manikúra prováděná v rukavicích v salonu'],
  ['https://images.pexels.com/photos/9718365/pexels-photo-9718365.jpeg?auto=compress&cs=tinysrgb&w=1400', 'Nanášení laku na nehty při profesionální manikúře'],
]

export default function NailShowcase() {
  return (
    <div className="n2" id="top">
      <style>{`
        body:has(.n2) > .verno-nav-shell,body:has(.n2) > .footer{display:none!important}
        body:has(.n2) main{padding:0!important;margin:0!important}
        body:has(.n2){background:#fff!important}
        .n2{--ink:#111;--white:#fff;--cream:#f6f4ee;--pink:#ff667d;--red:#f24960;--blue:#ccecf2;--lime:#d9ff69;--line:#d8d8d2;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:#fff}
        .n2 *{box-sizing:border-box}.n2 a{color:inherit;text-decoration:none}.n2 img{display:block;width:100%}.n2Wrap{width:min(1240px,calc(100% - 56px));margin:0 auto}
        .n2Demo{min-height:24px;padding:5px 12px;background:#111;color:#ddd;display:flex;align-items:center;justify-content:center;text-align:center;font-size:9px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.n2Demo a{margin-left:8px;color:#fff!important;text-decoration:underline;text-underline-offset:3px}
        .n2Nav{position:sticky;top:0;z-index:120;background:rgba(255,255,255,.96);backdrop-filter:blur(14px);border-bottom:1px solid #111}.n2NavInner{height:62px;display:grid;grid-template-columns:1fr auto 1fr;gap:24px;align-items:center}.n2Brand{font-size:19px;font-weight:900;letter-spacing:-.045em}.n2NavCenter{display:flex;gap:26px;font-size:11px;font-weight:800}.n2NavRight{justify-self:end;display:flex;align-items:center;gap:16px}.n2NavPlace{font-size:10px;color:#666}.n2BookTop{display:inline-flex;align-items:center;gap:7px;background:var(--pink);padding:11px 14px;font-size:10px;font-weight:900}

        .n2Hero{position:relative;height:calc(100svh - 86px);min-height:640px;max-height:840px;overflow:hidden;background:var(--cream)}.n2HeroGrid{height:100%;display:grid;grid-template-columns:repeat(12,1fr);grid-template-rows:1fr auto;gap:0 18px;position:relative}.n2HeroMain{grid-column:6/13;grid-row:1/3;height:100%;overflow:hidden;background:#ddd}.n2HeroMain img{height:100%;object-fit:cover;object-position:center}.n2HeroCopy{grid-column:1/9;grid-row:1;z-index:2;padding-top:7vh;align-self:start}.n2HeroMeta{font-size:10px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;margin-bottom:24px}.n2Hero h1{font-size:clamp(72px,9.2vw,132px);font-weight:500;letter-spacing:-.085em;line-height:.76;margin:0;max-width:900px}.n2HeroLead{font-size:15px;line-height:1.6;max-width:510px;margin:28px 0 0;background:rgba(246,244,238,.9);padding:8px 10px 8px 0}.n2HeroActions{display:flex;gap:10px;margin-top:24px;flex-wrap:wrap}.n2Btn{min-height:46px;padding:0 17px;border:1px solid #111;display:inline-flex;align-items:center;justify-content:center;gap:8px;font-size:11px;font-weight:900;background:#fff}.n2BtnPrimary{background:var(--pink);border-color:var(--pink)}.n2HeroDetail{grid-column:4/7;grid-row:2;z-index:3;height:215px;overflow:hidden;margin-bottom:30px;border:8px solid var(--cream)}.n2HeroDetail img{height:100%;object-fit:cover}.n2HeroFacts{grid-column:1/4;grid-row:2;align-self:end;padding-bottom:34px;display:grid;gap:8px;font-size:11px}.n2HeroFacts span{display:flex;align-items:center;gap:8px}.n2HeroBadge{position:absolute;right:28px;bottom:28px;width:96px;height:96px;border-radius:50%;background:var(--lime);display:grid;place-items:center;text-align:center;font-size:9px;font-weight:900;line-height:1.25;transform:rotate(7deg);z-index:5}

        .n2Ticker{background:var(--red);color:#fff;border-top:1px solid #111;border-bottom:1px solid #111;overflow:hidden}.n2TickerInner{display:flex;justify-content:space-around;gap:28px;white-space:nowrap;padding:13px 24px;font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.n2TickerInner span:after{content:'✦';margin-left:28px}
        .n2Services{padding:82px 0 92px}.n2Head{display:grid;grid-template-columns:1fr 1fr;gap:70px;align-items:end;margin-bottom:38px}.n2Head h2{font-size:clamp(50px,5.8vw,78px);font-weight:500;letter-spacing:-.065em;line-height:.9;margin:0}.n2Head p{font-size:14px;line-height:1.65;color:#555;max-width:480px;margin:0}.n2ServiceList{border-top:2px solid #111}.n2Service{display:grid;grid-template-columns:1.15fr 100px 110px 1.1fr;gap:28px;align-items:center;padding:22px 8px;border-bottom:1px solid var(--line);transition:background .15s}.n2Service:hover{background:var(--blue)}.n2Service strong{font-size:18px}.n2Service span{font-size:12px;font-weight:700}.n2Service p{font-size:13px;line-height:1.5;color:#606060;margin:0}

        .n2Work{background:#111;color:#fff;padding:82px 0 96px;overflow:hidden}.n2WorkTop{display:grid;grid-template-columns:1.2fr .8fr;gap:60px;align-items:end;margin-bottom:38px}.n2Work h2{font-size:clamp(58px,7vw,96px);font-weight:500;letter-spacing:-.075em;line-height:.82;margin:0}.n2WorkTop p{font-size:14px;line-height:1.6;color:#bbb;margin:0;max-width:430px}.n2Gallery{display:grid;grid-template-columns:repeat(12,1fr);grid-template-rows:280px 160px 280px;gap:12px}.n2Gallery figure{margin:0;overflow:hidden;position:relative;background:#222}.n2Gallery img{height:100%;object-fit:cover}.n2Gallery figure:nth-child(1){grid-column:1/6;grid-row:1/3}.n2Gallery figure:nth-child(2){grid-column:6/10;grid-row:1/2}.n2Gallery figure:nth-child(3){grid-column:10/13;grid-row:1/2}.n2Gallery figure:nth-child(4){grid-column:7/13;grid-row:2/4}.n2Gallery figure:nth-child(5){grid-column:2/7;grid-row:3/4}.n2GalleryLabel{position:absolute;left:10px;bottom:10px;background:#111;padding:6px 8px;font-size:9px;font-weight:900}.n2GalleryNote{margin-top:20px;font-size:10px;line-height:1.5;color:#888}

        .n2Hygiene{background:var(--lime);padding:62px 0}.n2HygieneGrid{display:grid;grid-template-columns:.75fr 1.25fr;gap:80px}.n2Hygiene h2{font-size:clamp(44px,5vw,68px);font-weight:500;letter-spacing:-.065em;line-height:.9;margin:0}.n2HygieneList{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid rgba(0,0,0,.34)}.n2HygieneItem{display:flex;gap:11px;padding:20px 18px 20px 0;border-bottom:1px solid rgba(0,0,0,.34)}.n2HygieneItem:nth-child(even){padding-left:18px;border-left:1px solid rgba(0,0,0,.34)}.n2HygieneItem strong{font-size:13px;display:block;margin-bottom:6px}.n2HygieneItem p{font-size:12px;line-height:1.5;color:#344126;margin:0}

        .n2Pedi{display:grid;grid-template-columns:1fr 1fr;min-height:610px}.n2PediPhoto{overflow:hidden}.n2PediPhoto img{height:100%;object-fit:cover;object-position:center}.n2PediCopy{background:var(--blue);padding:70px;display:flex;flex-direction:column;justify-content:center}.n2PediCopy h2{font-size:clamp(54px,6vw,82px);font-weight:500;letter-spacing:-.07em;line-height:.88;margin:0 0 24px}.n2PediCopy>p{font-size:14px;line-height:1.65;max-width:510px;margin:0}.n2PediFacts{display:grid;grid-template-columns:1fr 1fr;gap:0;margin-top:30px;border-top:1px solid rgba(0,0,0,.3)}.n2PediFact{padding:17px 18px 0 0;font-size:11px}.n2PediFact strong{display:block;font-size:14px;margin-bottom:5px}

        .n2Studio{padding:92px 0;background:#fff}.n2StudioGrid{display:grid;grid-template-columns:1.1fr .9fr;gap:68px;align-items:center}.n2StudioPhoto{height:560px;overflow:hidden;background:#eee}.n2StudioPhoto img{height:100%;object-fit:cover;object-position:center}.n2StudioText{max-width:500px}.n2StudioText h2{font-size:clamp(50px,5.6vw,76px);font-weight:500;letter-spacing:-.065em;line-height:.9;margin:0 0 22px}.n2StudioText p{font-size:14px;line-height:1.7;color:#555;margin:0}.n2StudioFacts{margin-top:28px;border-top:1px solid #111}.n2StudioFact{display:grid;grid-template-columns:150px 1fr;gap:20px;padding:14px 0;border-bottom:1px solid var(--line);font-size:12px}.n2StudioFact strong{font-size:12px}.n2StudioDemo{display:inline-block;margin-top:18px;font-size:9px;color:#777;border:1px solid #bbb;padding:6px 8px}

        .n2Booking{background:var(--pink);padding:82px 0}.n2BookingGrid{display:grid;grid-template-columns:.85fr 1.15fr;gap:72px;align-items:start}.n2Booking h2{font-size:clamp(56px,6.6vw,90px);font-weight:500;letter-spacing:-.075em;line-height:.84;margin:0 0 22px}.n2BookingText p{font-size:14px;line-height:1.6;max-width:410px;margin:0}.n2BookingMeta{display:grid;gap:9px;margin-top:28px;font-size:12px}.n2BookingMeta span{display:flex;align-items:center;gap:8px}.n2BookingPanel{background:#fff;border:1px solid #111;padding:26px}.n2BookRow{display:grid;grid-template-columns:1fr auto;gap:20px;align-items:center;padding:16px 0;border-bottom:1px solid var(--line)}.n2BookRow:first-child{border-top:1px solid var(--line)}.n2BookRow strong{font-size:13px}.n2BookRow span{font-size:11px;color:#666}.n2BookSlots{display:flex;gap:9px;flex-wrap:wrap;margin:20px 0}.n2BookSlots span{border:1px solid #aaa;padding:9px 12px;font-size:11px}.n2BookSlots span:nth-child(2){background:var(--lime);border-color:#111;font-weight:900}.n2BookButton{width:100%;min-height:48px;background:#111;color:#fff;border:0;font-size:11px;font-weight:900;display:flex;align-items:center;justify-content:center;gap:8px}.n2BookNote{font-size:9px;color:#777;margin-top:9px}

        .n2Contact{background:#111;color:#fff;padding:56px 0 34px}.n2ContactGrid{display:grid;grid-template-columns:1fr 1fr;gap:70px;padding-bottom:42px}.n2Contact h3{font-size:34px;letter-spacing:-.04em;margin:0 0 14px}.n2Contact p{font-size:13px;line-height:1.6;color:#aaa;max-width:430px}.n2ContactLines{display:grid;gap:12px;font-size:12px;align-content:start}.n2ContactLines span{display:flex;align-items:center;gap:8px}.n2Footer{border-top:1px solid #444;padding-top:26px;display:flex;align-items:center;justify-content:space-between;gap:30px;font-size:10px;color:#aaa}.n2Footer strong{font-size:15px;color:#fff}.n2FooterCta{background:var(--lime);color:#111!important;padding:11px 13px;font-weight:900}

        @media(max-width:980px){.n2NavInner{grid-template-columns:1fr auto}.n2NavCenter{display:none}.n2Hero{height:auto;max-height:none;min-height:0}.n2HeroGrid{display:grid;grid-template-columns:1fr;grid-template-rows:auto}.n2HeroCopy{grid-column:1;grid-row:1;padding:58px 0 36px}.n2HeroMain{grid-column:1;grid-row:2;height:620px}.n2HeroDetail{display:none}.n2HeroFacts{grid-column:1;grid-row:3;padding:22px 0}.n2HeroBadge{bottom:25px}.n2Head,.n2WorkTop,.n2HygieneGrid,.n2StudioGrid,.n2BookingGrid{grid-template-columns:1fr}.n2Service{grid-template-columns:1fr 90px 100px}.n2Service p{grid-column:1/-1}.n2Pedi{grid-template-columns:1fr}.n2PediPhoto{height:520px}.n2StudioPhoto{order:1}.n2StudioText{order:2}.n2ContactGrid{grid-template-columns:1fr}}
        @media(max-width:680px){.n2Wrap{width:min(100% - 28px,1240px)}.n2Demo{font-size:7.5px}.n2NavPlace{display:none}.n2NavInner{height:56px}.n2Brand{font-size:17px}.n2HeroCopy{padding-top:42px}.n2Hero h1{font-size:clamp(64px,20vw,92px)}.n2HeroLead{font-size:14px;background:transparent;padding:0}.n2HeroMain{height:480px}.n2HeroBadge{width:76px;height:76px;font-size:7.5px}.n2Services,.n2Work,.n2Studio{padding:60px 0}.n2Head{gap:22px}.n2Service{grid-template-columns:1fr auto;gap:8px 18px;padding:18px 2px}.n2Service span:nth-of-type(1),.n2Service span:nth-of-type(2){grid-column:2}.n2Gallery{grid-template-columns:1fr 1fr;grid-template-rows:auto;gap:8px}.n2Gallery figure:nth-child(n){grid-column:auto;grid-row:auto;height:210px}.n2Gallery figure:nth-child(1){grid-column:1/-1;height:330px}.n2HygieneGrid{gap:30px}.n2HygieneList{grid-template-columns:1fr}.n2HygieneItem:nth-child(even){padding-left:0;border-left:0}.n2PediPhoto{height:420px}.n2PediCopy{padding:44px 24px}.n2StudioPhoto{height:430px}.n2StudioFact{grid-template-columns:110px 1fr}.n2Booking{padding:60px 0}.n2BookingGrid{gap:34px}.n2Contact{padding-top:44px}.n2Footer{align-items:flex-start;flex-direction:column;padding-bottom:12px}}
      `}</style>

      <div className="n2Demo">UKÁZKOVÝ KONCEPT SPUSTWEB.CZ · NEJDE O SKUTEČNOU FIRMU <a href="/">ZPĚT NA SPUSTWEB.CZ</a></div>
      <nav className="n2Nav" aria-label="Navigace ukázkového studia"><div className="n2Wrap n2NavInner"><a className="n2Brand" href="#top">STUDIO LÍNA</a><div className="n2NavCenter"><a href="#sluzby">Ceník</a><a href="#prace">Práce</a><a href="#studio">Studio</a></div><div className="n2NavRight"><span className="n2NavPlace">České Budějovice</span><a className="n2BookTop" href="#rezervace">Rezervace <CalendarDays size={13}/></a></div></div></nav>

      <header className="n2Hero"><div className="n2Wrap n2HeroGrid"><div className="n2HeroCopy"><div className="n2HeroMeta">MANIKÚRA · PEDIKÚRA · ČESKÉ BUDĚJOVICE</div><h1>Nehty.<br/>Ruce.<br/>Chodidla.</h1><p className="n2HeroLead">Manikúra, gel lak, zpevnění přírodních nehtů a přístrojová pedikúra. Pracuji pouze na objednání.</p><div className="n2HeroActions"><a className="n2Btn n2BtnPrimary" href="#rezervace">Vybrat termín <CalendarDays size={14}/></a><a className="n2Btn" href="#sluzby">Ceník</a></div></div><div className="n2HeroMain"><img src="https://images.pexels.com/photos/4783337/pexels-photo-4783337.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Manikérka pracuje s klientkou v menším nehtovém studiu"/></div><div className="n2HeroDetail"><img src="https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=900" alt="Vzorník odstínů laků na nehty"/></div><div className="n2HeroFacts"><span><Clock3 size={14}/> Po–Pá 9:00–19:00</span><span><MapPin size={14}/> centrum Českých Budějovic</span><span><ShieldCheck size={14}/> sterilizované nástroje</span></div><div className="n2HeroBadge">ONLINE<br/>REZERVACE<br/>24 / 7</div></div></header>

      <div className="n2Ticker"><div className="n2TickerInner"><span>MANIKÚRA</span><span>GEL LAK</span><span>ZPEVNĚNÍ</span><span>PEDIKÚRA</span><span>NAIL ART</span><span>ODSTRANĚNÍ MATERIÁLU</span></div></div>

      <section className="n2Services" id="sluzby"><div className="n2Wrap"><div className="n2Head"><h2>Služby a ceny.</h2><p>U každé služby je uvedený čas i cena. Nail art a opravy jednotlivých nehtů se připočítávají podle rozsahu.</p></div><div className="n2ServiceList">{services.map(([name,time,price,text])=><article className="n2Service" key={name}><strong>{name}</strong><span>{time}</span><span>{price}</span><p>{text}</p></article>)}</div></div></section>

      <section className="n2Work" id="prace"><div className="n2Wrap"><div className="n2WorkTop"><h2>Ukázky práce.</h2><p>Manikúra, gel lak, zpevnění přírodních nehtů a detailní práce při úpravě nehtů.</p></div><div className="n2Gallery">{gallery.map(([src,alt],i)=><figure key={src}><img src={src} alt={alt}/><span className="n2GalleryLabel">0{i+1}</span></figure>)}</div><div className="n2GalleryNote">Ilustrační fotografie z Pexels. Studio i realizace jsou součástí fiktivního konceptu.</div></div></section>

      <section className="n2Hygiene"><div className="n2Wrap n2HygieneGrid"><h2>Hygiena a sterilizace.</h2><div className="n2HygieneList"><div className="n2HygieneItem"><Check size={16}/><div><strong>Kovové nástroje</strong><p>Po použití se čistí, dezinfikují a sterilizují.</p></div></div><div className="n2HygieneItem"><Check size={16}/><div><strong>Jednorázové pomůcky</strong><p>Pilníky a další jednorázové materiály se mezi klientkami nepoužívají opakovaně.</p></div></div><div className="n2HygieneItem"><Check size={16}/><div><strong>Pracovní místo</strong><p>Stůl a dotykové plochy se připravují před každou návštěvou.</p></div></div><div className="n2HygieneItem"><Check size={16}/><div><strong>Sterilní balení</strong><p>Nástroje se uchovávají zabalené až do přípravy pracovního místa.</p></div></div></div></div></section>

      <section className="n2Pedi"><div className="n2PediPhoto"><img src="https://images.pexels.com/photos/17056222/pexels-photo-17056222.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Pedikérka pracuje na úpravě nehtů klientky"/></div><div className="n2PediCopy"><h2>Pedikúra.</h2><p>Úprava nehtů a chodidel, ošetření běžné ztvrdlé kůže a závěrečná péče. Gel lak lze zvolit při rezervaci termínu.</p><div className="n2PediFacts"><div className="n2PediFact"><strong>60 min</strong><span>pedikúra</span></div><div className="n2PediFact"><strong>90 min</strong><span>pedikúra + gel lak</span></div><div className="n2PediFact"><strong>990 Kč</strong><span>pedikúra</span></div><div className="n2PediFact"><strong>1 390 Kč</strong><span>pedikúra + gel lak</span></div></div></div></section>

      <section className="n2Studio" id="studio"><div className="n2Wrap n2StudioGrid"><div className="n2StudioPhoto"><img src="https://images.pexels.com/photos/4677861/pexels-photo-4677861.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Manikérka a klientka při práci v útulném nehtovém studiu"/></div><div className="n2StudioText"><h2>Studio Lína.</h2><p>Studio vede Klára Novotná. Manikúře a pedikúře se věnuje od roku 2018. Pracuje pouze na objednání a během rezervovaného času přijímá jednu klientku.</p><div className="n2StudioFacts"><div className="n2StudioFact"><strong>Zaměření</strong><span>manikúra, gel lak, zpevnění a pedikúra</span></div><div className="n2StudioFact"><strong>Provoz</strong><span>Po–Pá 9:00–19:00, pouze na objednání</span></div><div className="n2StudioFact"><strong>Místo</strong><span>centrum Českých Budějovic</span></div></div><span className="n2StudioDemo">Klára Novotná je fiktivní specialistka.</span></div></div></section>

      <section className="n2Booking" id="rezervace"><div className="n2Wrap n2BookingGrid"><div className="n2BookingText"><h2>Vyberte si termín.</h2><p>Vyberte službu, den a jeden z volných časů.</p><div className="n2BookingMeta"><span><Phone size={14}/> 777 000 000</span><span><MapPin size={14}/> České Budějovice · centrum</span><span><Clock3 size={14}/> Po–Pá 9:00–19:00</span></div></div><div className="n2BookingPanel"><div className="n2BookRow"><div><strong>Manikúra + gel lak</strong><br/><span>75 min</span></div><strong>890 Kč</strong></div><div className="n2BookRow"><div><strong>Úterý 25. srpna</strong><br/><span>volné časy</span></div><CalendarDays size={16}/></div><div className="n2BookSlots"><span>10:30</span><span>13:00</span><span>16:30</span></div><button className="n2BookButton" type="button">Pokračovat k rezervaci <ArrowRight size={13}/></button><div className="n2BookNote">Ukázkové rezervační rozhraní není aktivní.</div></div></div></section>

      <section className="n2Contact"><div className="n2Wrap"><div className="n2ContactGrid"><div><h3>Studio Lína</h3><p>Fiktivní studio vytvořené jako ukázka webu pro samostatnou manikérku a pedikérku.</p></div><div className="n2ContactLines"><span><MapPin size={14}/> České Budějovice · centrum</span><span><Clock3 size={14}/> Po–Pá 9:00–19:00 · pouze na objednání</span><span><Phone size={14}/> 777 000 000</span></div></div><footer className="n2Footer"><div><strong>STUDIO LÍNA</strong><br/>Ukázkový koncept · nejde o skutečnou firmu.</div><div>Tento koncept vytvořil <a href="/">SpustWeb.cz</a> · <a className="n2FooterCta" href="/#kontakt">Web pro moje podnikání</a></div></footer></div></section>
    </div>
  )
}
